/*
 * Chữ tiếng Việt của bài b4 — Tìm kiếm mù. NGUỒN SỰ THẬT.
 *
 * Cắt ra từ bundle Buổi 3 cũ khi buổi đó tách thành Buổi 3 · 4 · 5. Chữ dùng chung cho
 * Manim Lab và Code Lab nằm ở `features/search-lab/lab.text.vi.ts`, không lặp ở đây.
 * Bản EN khai `satisfies typeof VI` nên thiếu hay thừa một khóa là lỗi tsc.
 */
export const VI = {
  hero: {
    labCta: "▶ Chạy từng bước trong Lab",
    navMath: "TOÁN NỀN",
    nav01: "01 Tìm kiếm mù",
    navLab: "LAB",
    navCode: "02 Code",
    navQuiz: "03 Quiz",
    navHw: "04 Bài tập",
    cover: "Bìa",
    badge: "BUỔI 4",
    navTitle: "Tìm kiếm mù",
    titleA: "Tìm kiếm",
    titleB: "khi",
    titleC: "chưa biết gì",
    lead: "🔍 Đề đã viết xong ở buổi trước. Giờ máy phải tự mò, và nó mò trong bóng tối hoàn toàn — không có manh mối nào về việc đích nằm phía nào. Nghe như vô vọng, nhưng năm thuật toán trong buổi này chỉ khác nhau đúng <strong class='hl'>một câu</strong>: lấy nút nào ra khỏi frontier trước? Đổi câu trả lời là đổi luôn tính chất của cả thuật toán.",
    chipFifo: "FIFO — nông nhất trước",
    chipLifo: "LIFO — sâu nhất trước",
    chipSections: "4 mục học",
    chipHours: "≈ 2 giờ",
  },
  ch4: {
    s1: "Tìm kiếm mù",
    s2: "“Mù” không phải lời chê đâu — nó chỉ có nghĩa là ngoài đề bài ra, thuật toán không biết thêm gì cả. Nó không đoán được nút nào hứa hẹn hơn nút nào, chỉ biết đúng một chuyện: “đây có phải đích chưa?”. Năm thuật toán dưới đây mù như nhau, khác nhau duy nhất ở <em>thứ tự mở nút</em>.",
    s3: "Tìm theo chiều rộng",
    s4: "dừng khi đích SINH RA",
    s5: "Luôn mở nút <strong class='hl'>nông nhất</strong>. Nút mới đến xếp cuối hàng, nút chờ lâu nhất được gọi trước — đúng kiểu xếp hàng mua trà sữa. Cây vì thế lớn đều từng tầng một. Mẹo nhỏ: kiểm tra đích ngay lúc <em>sinh</em> nút con thay vì đợi lấy ra, bạn tiết kiệm được nguyên một tầng b nút.",
    s6: "ĐẦY ĐỦ",
    s7: "✓ khi b hữu hạn",
    s8: "TỐI ƯU",
    s9: "✓ khi mọi bước cùng giá",
    s10: "THỜI GIAN",
    s11: "BỘ NHỚ",
    s12: "O(b<sup>d</sup>) — RAM chết trước",
    s13: "độ sâu d",
    s14: "số nút",
    s15: "thời gian",
    s16: "bộ nhớ",
    s17: "1,1 giây",
    s18: "3 giờ",
    s19: "13 ngày",
    s20: "350 năm",
    s21: "b = 10, tốc độ 1 triệu nút/giây, 1 kB/nút. Nhìn cột thời gian còn thấy gắng đợi được; nhìn cột bộ nhớ thì thôi 💀 — RAM luôn chết trước đồng hồ.",
    s22: "Vụ nổ hàm mũ — vì sao O(bᵈ) đáng sợ",
    s23: "mỗi tầng nhân thêm b lần; tầng cuối chiếm gần hết",
    s24: "Chi phí đồng nhất",
    s25: "dừng khi đích LẤY RA",
    s26: "BFS tối ưu <em>số cạnh</em> — mà ít cạnh đâu có nghĩa là rẻ, đi 2 chặng máy bay vẫn đắt hơn 5 chặng xe buýt. UCS sửa đúng chỗ đó: nó mở nút có <strong class='hl-cyan'>g(n) — chi phí thật từ gốc</strong> — nhỏ nhất. Có hai chi tiết mà tôi thấy sinh viên mất điểm nhiều nhất: <strong class='hl'>(1)</strong> UCS chỉ dừng khi đích được <em>lấy ra</em> khỏi hàng đợi, chứ không phải lúc sinh ra — vì lúc sinh ra, biết đâu còn đường rẻ hơn đang xếp hàng; <strong class='hl'>(2)</strong> gặp lại một nút bằng đường rẻ hơn thì phải <em>cập nhật</em> cha và khóa của nó (decrease-key). Đừng tin lời tôi, mở Manim Lab chạy UCS trên đồ thị Lab mà xem, cả hai đều xảy ra thật.",
    s27: "ĐẦY ĐỦ",
    s28: "✓ khi chi phí bước ≥ ε",
    s29: "TỐI ƯU",
    s30: "✓ với mọi hàm chi phí",
    s31: "THỜI GIAN",
    s32: "BỘ NHỚ",
    s33: "như thời gian",
    s34: "Có lúc còn tệ hơn cả bᵈ: nó mải mê bò qua đủ thứ bước rẻ tiền trước khi chịu thử một đường thật sự có ích.",
    s35: "Tìm theo chiều sâu",
    s36: "dừng khi đích SINH RA",
    s37: "DFS là đứa liều: mở nút <strong class='hl'>sâu nhất</strong>, lao một mạch xuống đáy một nhánh, cụt đường mới chịu quay lui. Đừng mong tối ưu — nghiệm đầu tiên nó vớ được thường không phải nghiệm nông nhất. Nhưng nó có một thứ mà BFS thèm: <strong class='hl-green'>bộ nhớ</strong>. Nó chỉ giữ nhánh đang đi cùng mấy anh em chưa mở, O(bm) thôi; bản backtracking còn gọn nữa, O(m).",
    s38: "ĐẦY ĐỦ",
    s39: "✓ graph-search hữu hạn · ✗ tree-search",
    s40: "TỐI ƯU",
    s41: "THỜI GIAN",
    s42: "O(b<sup>m</sup>), m có thể ≫ d",
    s43: "BỘ NHỚ",
    s44: "O(bm) — lý do tồn tại",
    s45: "HAI CÁCH CHỐNG LẶP — ĐỀ RA CÁI NÀO, TRACE CÁI ĐÓ",
    s46: "Chỗ này tôi phải tách bạch ra, vì bài tập Q2 và Q4b hỏi trúng nó, và hai cách cho <strong class='hl'>thứ tự expand khác nhau</strong>:",
    s47: "NHỚ CẢ BẢN ĐỒ — EXPLORED SET",
    s48: "Ghé nút nào là cấm ghé lại, vĩnh viễn. Đây là bản trong code Python ở <a href='#codelab'>mục 08</a> — cái <span class='code-inline'>visited</span> chỉ có thêm, không bao giờ bớt. Đổi lại phải nhớ mọi trạng thái đã gặp.",
    s49: "CHỈ NHỚ ĐƯỜNG ĐANG ĐI — PATH CHECK",
    s50: "Chỉ cấm gặp lại nút <em>nằm trên đường từ gốc xuống tới đây</em>; quay lui thì nhả nút ra khỏi trí nhớ — đúng dòng <span class='code-inline'>del visited[child]</span> trong code DLS. Bộ nhớ chỉ O(m).",
    s51: "Bản path check vẫn chặn được chuyện lượn vòng vô hạn trong không gian hữu hạn, nhưng nó cho phép bạn tới cùng một nút hai lần qua hai nhánh khác nhau — tức là <strong class='hl-mid'>vẫn sinh đường dư thừa</strong>, thứ mà explored set dẹp sạch. Còn nếu bản thân không gian trạng thái là vô hạn thì đừng trông mong gì: cả hai bản đều chết như nhau.",
    s52: "Giới hạn độ sâu → Sâu dần từng nấc",
    s53: "DFS + trần ℓ = 0, 1, 2, …",
    s54: "<strong class='hl'>DLS</strong> chữa bệnh đi lạc mãi của DFS bằng cách đóng một cái trần: cấm đi sâu quá ℓ. Chạm trần thì trả về <em>cutoff</em> — nhớ phân biệt với <em>failure</em> là hết đường thật, hai chuyện khác nhau. Chọn ℓ bằng tri thức bài toán: Romania có 20 thành phố, hai thành phố bất kỳ cách nhau ≤ 9 bước, vậy ℓ = 9 là dư. Khổ nỗi ta thường <em>không biết trước</em> ℓ. Thế là <strong class='hl'>IDS</strong> làm cái việc nghe rất ngớ ngẩn: chạy DLS với ℓ = 0, rồi 1, rồi 2… tới khi đụng đích.<br/><br/>Phí phạm quá phải không? Tầng trên bị sinh đi sinh lại bao nhiêu lần. Nhưng đây là chỗ hàm mũ đứng về phía ta: tầng cuối cùng chiếm gần hết số nút, mấy tầng trên cộng lại chẳng đáng bao nhiêu. Cụ thể b = 10, d = 5 → IDS sinh 123.450 nút, BFS sinh 111.110, đội đúng <strong class='hl-green'>~11%</strong>. Trả 11% đó, bạn được bộ nhớ O(bd) của DFS cộng tính đầy đủ và tối ưu của BFS. Hời.",
    s55: "ĐẦY ĐỦ",
    s56: "✓ khi b hữu hạn",
    s57: "TỐI ƯU",
    s58: "✓ khi mọi bước cùng giá",
    s59: "THỜI GIAN",
    s60: "BỘ NHỚ",
    s61: "BỐN Ô TRÊN LÀ CỦA IDS — CÒN DLS ĐỨNG MỘT MÌNH THÌ SAO?",
    s62: "Đừng gán nhầm thành tích. DLS một mình <strong class='hl-red'>hỏng cả hai đầu</strong>, mà hỏng theo hai kiểu ngược nhau, tùy bạn đặt trần ở đâu so với độ sâu nghiệm d:",
    s63: "ĐẦY ĐỦ",
    s64: "TỐI ƯU",
    s65: "THỜI GIAN",
    s66: "BỘ NHỚ",
    s67: "Trần thấp hơn nghiệm (ℓ &lt; d) thì nghiệm nằm ngay dưới đáy trần mà nó không với tới — <em>trượt</em>. Trần cao hơn nghiệm (ℓ &gt; d) thì nó vẫn lao xuống sâu theo kiểu DFS, nên rất dễ vớ một nghiệm sâu trước khi kịp thấy nghiệm nông — <em>mất tối ưu</em>. Còn hai ô thời gian và bộ nhớ thì vẫn y hệt DFS, chỉ thay m bằng ℓ; nói ngược lại cũng đúng: <strong class='hl-mid'>DFS chính là DLS với ℓ = ∞</strong>.",
    s68: "Không biết chọn gì thì chọn IDS — nó là lựa chọn mặc định khi không gian lớn và bạn mù tịt về độ sâu nghiệm. Mở Lab chọn IDS rồi nhìn cái nhãn ℓ nhích dần lên ở góc canvas, sẽ thấy ngay nó làm gì.",
    s69: "Ý tưởng đơn giản mà hiệu quả kinh khủng: đào từ hai đầu, gặp nhau ở giữa. b<sup>d/2</sup> + b<sup>d/2</sup> ≪ b<sup>d</sup> — với b = 10, d = 6 thì là 2.000 nút thay vì 1.000.000. Cái giá: bạn phải biết cách đi <em>lùi</em> từ đích, và phải biết đích nằm ở đâu cho tường minh. Với đích kiểu “chiếu hết” thì chịu, biết chiếu hết ở thế cờ nào mà đào ngược.",
  },
  quiz: {
    s1: "Quiz — đo xem bạn <em class='hl-cyan'>thật sự</em> hiểu tới đâu",
    s2: "sáu câu · điều kiện tối ưu, lúc dừng, bộ nhớ, cutoff ≠ failure",
    s3: "Năm thuật toán, bốn tiêu chí, một bảng — đọc xong thấy gọn ghẽ lắm. Nhưng bảng đó chỉ dính lại khi bạn tự dựng được nó từ cơ chế, chứ không phải thuộc lòng. Sáu câu dưới đây hỏi đúng những chỗ tôi thấy người ta mất điểm nhiều nhất, và không câu nào tra bảng ra được.",
  },
  hw: {
    s1: "Bài tập về nhà — Buổi 4",
    s2: "hai câu · trace tay nhóm mù, mê cung",
    s3: "QUESTION 1 — TRACE TAY BỐN THUẬT TOÁN MÙ",
    s4: "Đồ thị S → G, chi phí ghi trên cạnh. Với BFS · UCS · DFS (nhớ nút trên đường đi) · IDS: liệt kê <em>thứ tự expand</em>, <em>đường đi tìm được</em>, <em>frontier cuối cùng</em>. Đồng hạng → mở theo alphabet; “expand” = lấy RA khỏi frontier. <strong class='hl'>(e)</strong> Thuật toán nào trả về đường rẻ nhất, thuật toán nào trả về đường ít cạnh nhất — có khi nào trùng nhau không?",
    s5: "<a href='#lab'>Luyện đúng kỹ năng này trong Manim Lab</a>",
    s6: "QUESTION 2 — MÊ CUNG s → g, PHẦN MÙ",
    s7: "Tường đậm không đi xuyên. Liệt kê các ô explored theo định dạng &lt;b₁, b₂, …&gt; với: <strong class='hl'>(a)</strong> BFS; <strong class='hl'>(b)</strong> DFS chống lặp, thứ tự toán tử up, left, right, down. <strong class='hl'>(c)</strong> Đổi thứ tự toán tử thành down, right, left, up thì (b) đổi thế nào — và điều đó nói gì về tính “xác định” của DFS?",
    s8: "<a href='#ch1'>Ôn: mục 01 — thứ tự mở nút</a>",
    s9: "Giải thích cho người khác nghe được: vì sao BFS và DFS dừng khi đích SINH RA, còn UCS phải nhịn đợi LẤY RA.",
    s10: "Trace tay BFS, UCS trên đồ thị 6 đỉnh của Lab rồi đối chiếu với Manim Lab.",
    s11: "Nói được vì sao DFS tốn O(bm) mà BFS tốn O(b^d), không cần nhìn bảng.",
    s12: "Phân biệt cutoff và failure, và nói được IDS hỏng thế nào nếu gộp hai thứ đó.",
    s13: "Cài được BFS · UCS · DFS · IDS chạy trơn trên đồ thị của Lab 1.",
    s14: "Tiếp theo: <strong class='hl'>Buổi 5 — Tìm kiếm có thông tin</strong>. Mình sẽ đưa cho máy một manh mối về hướng đích, và xem nó tiết kiệm được bao nhiêu công 🙂",
    s15: "← Về Lộ trình",
  },
};
