import type { VI } from './lesson04.text.vi';

export const EN = {
  hero: {
    labCta: "▶ Step through in the Lab",
    navMath: "MATH PRIMER",
    nav01: "01 Uninformed",
    navLab: "LAB",
    navCode: "02 Code",
    navQuiz: "03 Quiz",
    navHw: "04 Exercises",
    cover: "Cover",
    badge: "SESSION 4",
    navTitle: "Uninformed search",
    titleA: "Searching",
    titleB: "with",
    titleC: "no clues",
    lead: "🔍 The problem got stated last session. Now the machine has to grope for the answer, and it gropes in total darkness — not a single hint about which way the goal lies. Sounds hopeless, except the five algorithms here differ by exactly <strong class='hl'>one question</strong>: which node comes off the frontier first? Change that answer and you change everything about the algorithm.",
    chipFifo: "FIFO — shallowest first",
    chipLifo: "LIFO — deepest first",
    chipSections: "4 sections",
    chipHours: "≈ 2 hours",
  },
  ch4: {
    s1: "Uninformed search",
    s2: "“Blind” isn’t an insult here. It means the algorithm knows nothing beyond the problem definition. It can’t guess which node looks more promising; it can only ask whether a node is a goal. The five algorithms below are equally uninformed. What changes is their <em>expansion order</em>.",
    s3: "Breadth-first search",
    s4: "stop when goal is GENERATED",
    s5: "Always expand the <strong class='hl'>shallowest</strong> node. New arrivals join the back; whoever has waited longest goes first, just like a line at a coffee counter. The tree grows evenly, level by level. A small trick: test for the goal when you <em>generate</em> a child instead of waiting to pop it — that saves a whole level, and the last level is where the b-fold blowup lives.",
    s6: "COMPLETE",
    s7: "✓ with finite b",
    s8: "OPTIMAL",
    s9: "✓ with equal step costs",
    s10: "TIME",
    s11: "MEMORY",
    s12: "O(b<sup>d</sup>) — RAM gives out first",
    s13: "depth d",
    s14: "nodes",
    s15: "time",
    s16: "memory",
    s17: "1.1 seconds",
    s18: "3 hours",
    s19: "13 days",
    s20: "350 years",
    s21: "b = 10, speed 1 million nodes/second, 1 kB/node. The time column almost looks survivable; then you see the memory column 💀. RAM always gives out before the clock.",
    s22: "Exponential growth — why O(bᵈ) hurts",
    s23: "each level multiplies by b; the last holds almost everything",
    s24: "Uniform-cost search",
    s25: "stop when goal is REMOVED",
    s26: "BFS optimizes the <em>number of edges</em>, but fewer edges doesn’t mean cheaper: 2 flights can still cost more than 5 bus rides. UCS fixes that by expanding the node with the smallest <strong class='hl-cyan'>g(n) — actual cost from the start</strong>. I see two mistakes cost people marks over and over: <strong class='hl'>(1)</strong> UCS stops only when the goal is <em>removed</em> from the queue, not when it’s generated — a cheaper route might still be waiting; <strong class='hl'>(2)</strong> reaching a node by a cheaper route means you must <em>update</em> its parent and key (decrease-key). Don’t take my word for it: run UCS on the Lab graph in Manim Lab and watch both happen.",
    s27: "COMPLETE",
    s28: "✓ when step costs ≥ ε",
    s29: "OPTIMAL",
    s30: "✓ for any cost function",
    s31: "TIME",
    s32: "MEMORY",
    s33: "same as time",
    s34: "Sometimes worse than bᵈ: it crawls through countless cheap steps before trying a route that actually helps.",
    s35: "Depth-first search",
    s36: "stop when goal is GENERATED",
    s37: "DFS is the reckless one: expand the <strong class='hl'>deepest</strong> node, dive to the bottom of a branch, and backtrack only at a dead end. Don’t expect optimality — the first solution it grabs usually isn’t the shallowest. But it has something BFS envies: <strong class='hl-green'>low memory use</strong>. It keeps the current branch and unexpanded siblings, just O(bm); the backtracking version needs only O(m).",
    s38: "COMPLETE",
    s39: "✓ finite graph-search · ✗ tree-search",
    s40: "OPTIMAL",
    s41: "TIME",
    s42: "O(b<sup>m</sup>), m may be ≫ d",
    s43: "MEMORY",
    s44: "O(bm) — its reason to exist",
    s45: "TWO WAYS TO PREVENT LOOPS — TRACE THE ONE THE QUESTION SPECIFIES",
    s46: "I need to separate these, because homework Q2 and Q4b test exactly this distinction, and the two methods give <strong class='hl'>different expansion orders</strong>:",
    s47: "REMEMBER THE WHOLE MAP — EXPLORED SET",
    s48: "Visit a node and forbid revisiting it forever. This is the Python version in <a href='#codelab'>section 08</a>: <span class='code-inline'>visited</span> only grows, never shrinks. The price is remembering every state encountered.",
    s49: "REMEMBER ONLY THE CURRENT PATH — PATH CHECK",
    s50: "Forbid only nodes <em>on the path from the root to here</em>; forget a node when backtracking. That’s the <span class='code-inline'>del visited[child]</span> line in DLS. Memory is just O(m).",
    s51: "Path checking still prevents infinite cycling in a finite space, but lets you reach the same node through different branches. It <strong class='hl-mid'>still generates redundant paths</strong>, which an explored set eliminates. If the state space itself is infinite, though, don’t expect a rescue: either version can get lost forever.",
    s52: "Depth limits → Iterative deepening",
    s53: "DFS + a ceiling ℓ = 0, 1, 2, …",
    s54: "<strong class='hl'>DLS</strong> stops DFS wandering forever by imposing a ceiling: no deeper than ℓ. Hit the ceiling and return <em>cutoff</em> — keep that distinct from <em>failure</em>, which means there really are no paths left. Choose ℓ using problem knowledge: Romania has 20 cities, any pair is at most 9 steps apart, so ℓ = 9 is enough. Usually, though, you <em>don’t know</em> ℓ in advance. So <strong class='hl'>IDS</strong> does something that sounds ridiculous: run DLS with ℓ = 0, then 1, then 2… until it reaches the goal.<br/><br/>All those shallow levels generated again and again sound wasteful. Here’s where exponential growth helps: the last level holds almost all the nodes; the levels above barely add up to anything. With b = 10, d = 5, IDS generates 123,450 nodes versus BFS’s 111,110, just <strong class='hl-green'>~11%</strong> extra. For that 11%, you get DFS’s O(bd) memory plus BFS’s completeness and optimality. A good deal.",
    s55: "COMPLETE",
    s56: "✓ with finite b",
    s57: "OPTIMAL",
    s58: "✓ with equal step costs",
    s59: "TIME",
    s60: "MEMORY",
    s61: "THOSE FOUR BOXES DESCRIBE IDS — WHAT ABOUT DLS ALONE?",
    s62: "Don’t give it someone else’s results. DLS alone <strong class='hl-red'>can fail on both counts</strong>, in opposite ways depending on where you put the ceiling relative to solution depth d:",
    s63: "COMPLETE",
    s64: "OPTIMAL",
    s65: "TIME",
    s66: "MEMORY",
    s67: "Put the ceiling below the solution (ℓ &lt; d), and the solution is just out of reach: <em>missed</em>. Put it above the solution (ℓ &gt; d), and DLS still dives like DFS, so it may grab a deep solution before seeing a shallow one: <em>optimality lost</em>. Time and memory stay exactly as in DFS, with ℓ replacing m. Look at it the other way: <strong class='hl-mid'>DFS is DLS with ℓ = ∞</strong>.",
    s68: "If you don’t know what to pick, pick IDS: it’s the default for large spaces with unknown solution depth. Select IDS in the Lab and watch the ℓ label rise in the canvas corner; the behavior becomes obvious.",
    s69: "A simple, remarkably effective idea: search from both ends and meet in the middle. b<sup>d/2</sup> + b<sup>d/2</sup> ≪ b<sup>d</sup> — with b = 10, d = 6, that’s 2,000 nodes instead of 1,000,000. The price: you must know how to move <em>backward</em> from the goal, and the goal must be explicit. A goal such as “checkmate” won’t do: which checkmate position would you start from?",
  },
  quiz: {
    s1: "Quiz — find out what you <em class='hl-cyan'>really</em> understand",
    s2: "six questions · when it's optimal, when it stops, memory, cutoff ≠ failure",
    s3: "Five algorithms, four criteria, one table — it all looks very tidy once you've read it. But that table only sticks when you can rebuild it from the mechanism rather than recite it. These six questions go straight at the spots where I've seen people lose the most marks, and none of them can be answered by looking the table up.",
  },
  hw: {
    s1: "Homework — Session 4",
    s2: "two questions · tracing the uninformed group by hand, a maze",
    s3: "QUESTION 1 — TRACE FOUR UNINFORMED ALGORITHMS BY HAND",
    s4: "Graph S → G, costs on the edges. For BFS · UCS · DFS (remember nodes on the current path) · IDS: list the <em>expansion order</em>, the <em>path found</em>, and the <em>final frontier</em>. Break ties alphabetically; “expand” means REMOVED from the frontier. <strong class='hl'>(e)</strong> Which one returns the cheapest path and which returns the one with fewest edges — can those ever be the same?",
    s5: "<a href='#lab'>Practice exactly this in the Manim Lab</a>",
    s6: "QUESTION 2 — MAZE s → g, THE UNINFORMED HALF",
    s7: "Thick walls can't be crossed. List the explored cells in the form &lt;b₁, b₂, …&gt; for: <strong class='hl'>(a)</strong> BFS; <strong class='hl'>(b)</strong> DFS with cycle checking, operator order up, left, right, down. <strong class='hl'>(c)</strong> Switch the operator order to down, right, left, up — how does (b) change, and what does that tell you about how deterministic DFS's answer really is?",
    s8: "<a href='#ch1'>Review: section 01 — expansion order</a>",
    s9: "I can explain to someone else why BFS and DFS stop when the goal is GENERATED while UCS has to wait until it is REMOVED.",
    s10: "I can trace BFS and UCS by hand on the Lab's 6-node graph and check myself against the Manim Lab.",
    s11: "I can say why DFS costs O(bm) and BFS costs O(b^d) without looking at the table.",
    s12: "I can tell cutoff from failure, and say how IDS breaks if the two get merged.",
    s13: "I can implement BFS · UCS · DFS · IDS and run them cleanly on the Lab 1 graph.",
    s14: "Next up: <strong class='hl'>Session 5 — Informed Search</strong>. I'll hand the machine one clue about where the goal is, and you'll see how much work that saves 🙂",
    s15: "← Back to the roadmap",
  },
} satisfies typeof VI;
