import { useState } from 'react';
import { DataLesson, Lab, DataTable, TraceLoop, CodeBlock } from '../shared/DataLesson';
import { aggregateMeasure, scdRows, featureAt, FEATURES } from './consumption-engine';
import { SQL, FEAST, TRANSACTION } from './lesson11.code';
import { T } from './lesson11.text';
function AggregateLab(){const[kind,setKind]=useState(0),[method,setMethod]=useState(0);const r=aggregateMeasure(kind?'inventory':'revenue',['sum','average','last'][method]);return <Lab title={T.labs.aggregateTitle} help={T.labs.aggregateHelp} demo={T.demo}><div className="def-data-controls"><label>{T.labs.measure}<select value={kind} onChange={e=>setKind(Number(e.target.value))}>{T.labs.measures.map((v,i)=><option value={i} key={v}>{v}</option>)}</select></label><label>{T.labs.method}<select value={method} onChange={e=>setMethod(Number(e.target.value))}>{T.labs.methods.map((v,i)=><option value={i} key={v}>{v}</option>)}</select></label></div><p>{T.labs.values}: {r.values.join(' · ')}</p><div className="def-data-metrics" aria-live="polite"><div><span>{T.labs.result}</span><strong>{r.result}</strong></div></div><p className="def-data-callout">{r.appropriate?T.labs.valid:T.labs.invalid}</p></Lab>;}
function ScdLab(){const[type,setType]=useState(2),[changes,setChanges]=useState(1);return <Lab title={T.labs.scdTitle} help={T.labs.scdHelp} demo={T.demo}><div className="def-data-controls"><label>{T.labs.type}<select value={type} onChange={e=>setType(Number(e.target.value))}>{[0,1,2,3,4,6].map(n=><option key={n}>{n}</option>)}</select></label><label>{T.labs.changes}<select value={changes} onChange={e=>setChanges(Number(e.target.value))}>{T.labs.changeLabels.map((v,i)=><option value={i+1} key={v}>{v}</option>)}</select></label></div><DataTable label={T.labs.scdTitle} headers={T.labs.scdHeaders} rows={scdRows(type,changes).map(r=>[r.table,r.sk,r.currency,r.current,r.previous,r.from,r.to])}/><p className="def-data-note">{T.labs.scdNote}</p></Lab>;}
function FeatureLab(){const[mode,setMode]=useState(0),[ttl,setTtl]=useState(10);const r=featureAt(mode?'online':'historical',ttl);return <Lab title={T.labs.featureTitle} help={T.labs.featureHelp} demo={T.demo}><div className="def-data-controls"><label>{T.labs.mode}<select value={mode} onChange={e=>setMode(Number(e.target.value))}>{T.labs.modes.map((v,i)=><option key={v} value={i}>{v}</option>)}</select></label><label>{T.labs.ttl}<select disabled={mode===1} value={ttl} onChange={e=>setTtl(Number(e.target.value))}>{[2,5,10,20].map(n=><option key={n}>{n}</option>)}</select></label></div><DataTable label={T.labs.featureTitle} headers={T.labs.featureHeaders} rows={FEATURES.map(f=>[`${String(Math.floor(f.time/60)).padStart(2,'0')}:${String(f.time%60).padStart(2,'0')}`,f.value.toFixed(2),f.time>600?T.labs.future:T.labs.past])}/><div className="def-data-metrics" aria-live="polite"><div><span>{T.labs.selected}</span><strong>{r.selected?.value.toFixed(2)??T.labs.missing}</strong></div></div><p className="def-data-callout">{r.leakage?T.labs.leakage:T.labs.safe}</p>{mode===1&&<p className="def-data-note">{T.labs.latestNote}</p>}</Lab>;}
export default function Lesson11(){return <DataLesson text={T} id="b11" artwork={<><h2>FACT × DIMENSION</h2><div className="def-data-flow"><div>123456 · Peter Pan<span>GBP → USD → EUR</span></div><div>[2025-09-01, 2025-09-26)<span>customer_sk = 1 · GBP</span></div><div>[2025-09-26, 2025-10-10)<span>customer_sk = 2 · USD</span></div></div></>} extra={n=><>{n===1&&<TraceLoop title={T.labs.flowTitle} steps={T.labs.flowSteps} note={T.loopNote}/ >}{n===3&&<AggregateLab/>}{n===5&&<><ScdLab/><h3>{T.labs.sqlTitle}</h3><p className="def-data-callout">{T.labs.sqlNote}</p><CodeBlock value={SQL} language="SQL / VALUES"/></>}{n===10&&<><CodeBlock value={TRANSACTION} language="JSON"/><FeatureLab/><h3>{T.labs.feastTitle}</h3><p className="def-data-callout">{T.labs.feastNote}</p><CodeBlock value={FEAST}/></>}</>}/>;}
