import type { VI } from './storage-labs.text.vi';
export const EN = {
  common: {
    fixture: 'Teaching fixture · no live service connection',
    scenario: 'Scenario', metadata: 'Metadata', mechanism: 'Mechanism', tradeoff: 'Tradeoff',
    trace: 'Every phase explained', loop: 'Repeating illustration · each cycle is a new request',
    static: 'Static view · every phase is explained below the diagram',
    step: 'Step', action: 'Action', empty: 'No records yet', result: 'Result',
  },
  storage: {
    title: 'One order, three ways to find its bytes',
    help: 'Switch storage types and watch the address and update unit. I keep the order payload the same so you can see what changes in the access interface.',
    tabs: ['File · shared directory', 'Block · database disk', 'Object · saved export'],
    address: 'Access address', payload: 'Order payload', update: 'Update unit',
    note: 'The block cells only illustrate a disk interface. The database or filesystem above it decides where a record goes. This is not a speed benchmark.',
    cases: [
      { location: '/orders/2026/09/08/101.json', meta: 'Name, size, permissions and modification time belong to a file in a directory tree.', unit: 'An application opens a file and reads or writes byte ranges through a filesystem; NAS exposes a file interface over a network.', fit: 'Useful when applications need familiar paths and directories. Metadata, file count and protocol affect latency.', phases: ['A new access request: the application has the file path.', 'The filesystem resolves directory components and checks permissions.', 'The application receives file bytes. A path is not a physical block address.'] },
      { location: 'volume-01 · LBA 2048', meta: 'Storage knows block addresses and volume layout; it does not know order_id or filenames by itself.', unit: 'Read or write blocks by address. A database or filesystem manages schema and meaning above this interface.', fit: 'Useful for database or VM disks that need small-range access. SAN is one way to expose blocks over a network; latency still depends on the system.', phases: ['A new access request: the layer above has mapped its request to a block address.', 'The device locates blocks on the volume; this is not an order_id lookup.', 'The layer above reads bytes and interprets them as a database page or file content.'] },
      { location: 'orders-bucket / exports/101.json', meta: 'A key identifies an object in a bucket; metadata accompanies its payload. A / in the key does not require a directory.', unit: 'PUT a new object or replace its content through an API; do not assume in-place byte updates like a disk.', fit: 'Useful for raw data, images and large exports. It scales well, but request, network and retrieval costs still matter.', phases: ['A new access request: the application has a bucket and an object key.', 'The API accepts GET by key; metadata describes the object without turning its payload into a table.', 'The application receives the object payload. A new PUT can replace the object according to the service’s semantics.'] },
    ],
  },
  hdfs: {
    title: 'NameNode gives directions; DataNode supplies bytes',
    help: 'Follow metadata first, then data. When replica A cannot be read, the client tries replica B; bytes do not take a detour through NameNode.',
    tabs: ['Normal read', 'Replica A cannot be read'],
    client: 'Client', namenode: 'NameNode · metadata', datanode: 'DataNode',
    block: 'Block', rack: 'Rack', received: 'Bytes received', waiting: 'No bytes received yet', unavailable: 'Cannot read',
    metadataPath: 'Path → block ID + replica locations', bytePath: 'DataNode → client: block bytes',
    stored: 'Stored replica', permission: 'Access permissions',
    routes: {
      idle: 'Start a new read request for /orders/day.parquet. The replicas already exist.',
      'metadata-request': 'The client asks NameNode to open the path, obtain metadata and check permissions.',
      'metadata-response': 'NameNode returns the block ID and replica locations A/B. The client still has no data bytes.',
      'data-request': 'The client requests the block directly from DataNode A.',
      unavailable: 'Replica A cannot be read. This is a DataNode read failure, not missing metadata.',
      'replica-request': 'The client chooses replica B from the location list and sends a read request.',
      'data-response': 'The working DataNode sends bytes directly to the client.',
      complete: 'The block read is complete. The diagram holds the result before starting a new illustrative request; it does not delete replicas.',
    },
    note: 'The diagram reduces the system to one block and two replicas across two racks to show fallback; it does not describe the default replication factor. DataNodes send heartbeats to report availability and block reports to list their blocks. NameNode uses this metadata to manage replica locations.',
  },
  modeling: {
    title: 'The same revenue, different join paths',
    help: 'The fact grain here is one order line. You want revenue by product category: look at which table owns the category attribute.',
    tabs: ['Star · wide dimensions', 'Snowflake · normalized dimensions'],
    fact: 'Fact · one order line', product: 'Product dimension', category: 'Category dimension', customer: 'Customer dimension', date: 'Date dimension',
    star: 'In a star, category_name lives in dim_product. Revenue by category needs one join from fact to product; the category name can repeat across products.',
    snowflake: 'In a snowflake, dim_product holds category_id pointing to dim_category. The same question needs an extra join; the category name is managed in its own table.',
    join: 'Foreign key → primary key',
    note: 'Fewer joins do not guarantee faster queries on every system. You still need to measure with your data, query engine and physical layout. Week 11 goes deeper into grain and dimension design.',
  },
  governance: {
    title: 'Fix the specific failure in your lake',
    help: 'Enable each measure and inspect its issue rows. I deliberately leave a stale snapshot: a complete catalog cannot produce new data by itself.',
    policy: 'Measures in this simulation',
    controls: { catalog: 'Catalog', owner: 'Owner', validation: 'Validation', lineage: 'Lineage', retention: 'Retention' },
    effects: {
      catalog: 'Register the dataset, schema, tags and description so it can be found. Does not fix invalid values or refresh a snapshot.',
      owner: 'Assign the Orders team as owner and incident contact. Does not automatically repair schema or content.',
      validation: 'Run amount, unique-key and freshness rules: quarantine invalid values, remove retries from outputs and flag stale data. Does not create the missing batch.',
      lineage: 'Record source → transformation → report links for this dataset. Does not repair jobs or backfill data.',
      retention: 'Apply a sample policy that retains raw data for 90 days: remove a 120-day-old raw copy from active storage. Does not decide legal requirements for real data.',
    },
    statuses: { open: 'Still broken', fixed: 'Handled in the simulation', detected: 'Detected · still broken' },
    dataset: 'Dataset', issue: 'Specific failure', status: 'Status', evidence: 'What changed / what is missing',
    issues: {
      discovery: { label: 'Missing catalog and schema documentation', dataset: 'orders-current', open: 'No orders tag, schema or description helps an analyst find and understand the dataset.', fixed: 'Registered the orders tag, amount:number schema and revenue description. Record contents still need validation.', detected: '' },
      accountability: { label: 'No owner', dataset: 'orders-current', open: 'There is an issue, but nobody is assigned to resolve it.', fixed: 'Owner = Orders. A contact now exists; that does not make data errors disappear.', detected: '' },
      badAmount: { label: 'amount contains the string invalid', dataset: 'orders-current / B04', open: 'The invalid value remains in the unchecked output.', fixed: 'B04 goes to quarantine; the invalid string contributes nothing to revenue.', detected: '' },
      duplicate: { label: 'Order 101 retry counted twice', dataset: 'orders-current / B02', open: 'B02 exactly repeats order 101 from B01; the output has no deduplication yet.', fixed: 'B02 is logged as a duplicate and excluded from valid output. Raw still preserves the retry evidence.', detected: '' },
      stale: { label: 'Snapshot is 48 hours behind', dataset: 'orders-snapshot', open: 'No freshness alert exists; the snapshot still lacks 48 hours of data.', fixed: '', detected: 'A freshness alert is active; 48 hours of data are still missing. The owner must repair ingestion and backfill.' },
      lineage: { label: 'Report source is unknown', dataset: 'revenue-report', open: 'revenue-report cannot be traced back to its job and source dataset.', fixed: 'Recorded orders-current → clean-orders → revenue-report. An upstream failure still needs its own repair.', detected: '' },
      expired: { label: '120-day-old raw exceeds the 90-day limit', dataset: 'orders-raw-archive', open: 'Raw beyond the sample retention limit still occupies active storage.', fixed: 'Removed the 120-day-old raw copy under the sample 90-day policy. The organization must define the real policy.', detected: '' },
    },
    conclusion: 'All five measures still leave a stale snapshot. Governance helps you find data, assign responsibility, stop errors from spreading and trace their path; missing data still has to be ingested again.',
  },
  medallion: {
    title: 'Five raw rows, two trustworthy orders',
    help: 'Process one row at a time to see its destination, or finish the run and replay Bronze. Watch order 101: the retry stays available for audit without adding its amount again.',
    next: 'Process next step', run: 'Run the whole pipeline', replay: 'Replay Bronze', reset: 'Restart experiment',
    bronze: 'Bronze · original payloads', silver: 'Silver · valid unique orders', quarantine: 'Quarantine · needs repair', duplicate: 'Deduplication log', gold: 'Gold · revenue',
    rawId: 'Raw row', orderId: 'Order ID', amount: 'Amount (VND)', reason: 'Reason', original: 'Original row', processed: 'Processed rows', ledger: 'Processing ledger',
    ready: 'Bronze already contains all five rows; derived layers have not run yet.',
    replayReady: 'Replay reads the same five stored Bronze rows. The processing ledger and previous outputs remain in place.',
    actions: {
      ready: 'Ready to process Bronze.', accepted: 'Valid and not yet present: insert into Silver.', duplicate: 'Same order ID and amount: log the retry without adding it to Silver.',
      amount: 'amount is not a finite nonnegative number: send it to quarantine.', key: 'Missing a valid order ID: send it to quarantine.',
      conflict: 'Same order ID but different amount: quarantine the conflict; do not guess which version is newer.',
      replayed: 'raw_id is already in the processing ledger: preserve the outputs without adding again.', aggregate: 'Recompute Gold from Silver amounts; replace the aggregate instead of adding this run to it.',
    },
    reasons: { amount: 'Invalid amount type or value', key: 'Missing a valid key', conflict: 'Conflicting order ID' },
    invariant: 'Expected result: 5 Bronze = 2 Silver + 2 quarantine + 1 duplicate; Gold = 200,000 VND.',
    boundary: 'This is a teaching pipeline, not a running Delta Lake service. Bronze keeps the source payload with load_time and process_id. Retry B02 matches B01’s payload but has its own ingestion metadata. Replay here reads stored raw data without ingesting extra Bronze copies.',
    idempotency: 'Idempotency comes from the processed raw_id ledger, the order_id business key and replacing the Gold total. Bronze/Silver/Gold names do not deduplicate anything by themselves. In a real system, the ledger and output writes need a consistent commit; updates and CDC also need version and merge rules.',
    replayCount: 'Replay count', completed: 'Complete', aggregatePending: 'Aggregation has not run yet',
  },
} satisfies typeof VI;
