export const VI = {
  common: {
    fixture: 'Mô phỏng với dữ liệu mẫu · không kết nối dịch vụ thật',
    scenario: 'Tình huống', metadata: 'Metadata', mechanism: 'Cơ chế', tradeoff: 'Đánh đổi',
    trace: 'Lời giải từng pha', loop: 'Minh họa tự lặp · mỗi vòng là một yêu cầu mới',
    static: 'Bản tĩnh · toàn bộ các pha nằm ngay dưới hình',
    step: 'Bước', action: 'Hành động', empty: 'Chưa có bản ghi', result: 'Kết quả',
  },
  storage: {
    title: 'Một đơn hàng, ba cách tìm byte',
    help: 'Đổi cách lưu rồi nhìn vào địa chỉ và đơn vị cập nhật. Tôi giữ cùng nội dung đơn hàng để bạn thấy khác biệt nằm ở giao diện truy cập.',
    tabs: ['File · thư mục dùng chung', 'Block · đĩa cho database', 'Object · lưu bản xuất'],
    address: 'Địa chỉ truy cập', payload: 'Nội dung đơn hàng', update: 'Đơn vị cập nhật',
    note: 'Các ô block ở đây chỉ minh họa giao diện đĩa. Database hoặc filesystem phía trên quyết định bản ghi nằm ở đâu. Đây không phải benchmark tốc độ.',
    cases: [
      { location: '/orders/2026/09/08/101.json', meta: 'Tên, kích thước, quyền và thời gian sửa gắn với file trong cây thư mục.', unit: 'Ứng dụng mở file, đọc/ghi vùng byte qua filesystem; NAS cung cấp giao diện file qua mạng.', fit: 'Hợp khi nhiều ứng dụng cần path và cây thư mục quen thuộc. Metadata, số lượng file và giao thức ảnh hưởng độ trễ.', phases: ['Một lần truy cập mới: ứng dụng có path tới file.', 'Filesystem phân giải các thành phần thư mục và kiểm tra quyền.', 'Ứng dụng nhận byte của file. Path không phải địa chỉ block vật lý.'] },
      { location: 'volume-01 · LBA 2048', meta: 'Storage biết địa chỉ block và bố trí volume; không tự biết order_id hay tên file.', unit: 'Đọc/ghi block theo địa chỉ. Database hoặc filesystem quản lý schema và ý nghĩa bên trên.', fit: 'Hợp với đĩa database/VM cần truy cập vùng nhỏ. SAN là một cách cung cấp block qua mạng; độ trễ còn tùy hệ thống.', phases: ['Một lần truy cập mới: tầng trên đã ánh xạ yêu cầu sang địa chỉ block.', 'Thiết bị tìm các block trên volume; đây không phải lookup theo order_id.', 'Tầng trên đọc byte rồi diễn giải lại thành trang database hoặc nội dung file.'] },
      { location: 'orders-bucket / exports/101.json', meta: 'Key định danh object trong bucket; metadata đi cùng payload. Dấu / trong key không bắt buộc là thư mục.', unit: 'PUT một object mới hoặc thay nội dung object theo API; không mặc định sửa byte tại chỗ như đĩa.', fit: 'Hợp với dữ liệu raw, ảnh và bản xuất lớn. Mở rộng thuận lợi, nhưng chi phí request, mạng và truy xuất vẫn cần tính.', phases: ['Một lần truy cập mới: ứng dụng có bucket và object key.', 'API nhận GET theo key; metadata mô tả object, không tự biến payload thành bảng.', 'Ứng dụng nhận payload của object. Một PUT mới có thể thay object theo ngữ nghĩa của dịch vụ.'] },
    ],
  },
  hdfs: {
    title: 'NameNode chỉ đường, DataNode đưa byte',
    help: 'Theo đường metadata trước, đường dữ liệu sau. Khi bản sao A không đọc được, client thử bản sao B; byte không đi vòng qua NameNode.',
    tabs: ['Đọc bình thường', 'Bản sao A không đọc được'],
    client: 'Client', namenode: 'NameNode · metadata', datanode: 'DataNode',
    block: 'Block', rack: 'Rack', received: 'Đã nhận byte', waiting: 'Chưa nhận byte', unavailable: 'Không đọc được',
    metadataPath: 'Path → block ID + vị trí replica', bytePath: 'DataNode → client: byte của block',
    stored: 'Bản sao đã lưu', permission: 'Quyền truy cập',
    routes: {
      idle: 'Bắt đầu một yêu cầu đọc mới cho /orders/day.parquet. Các replica đã tồn tại từ trước.',
      'metadata-request': 'Client gửi yêu cầu mở path tới NameNode để lấy metadata và kiểm tra quyền.',
      'metadata-response': 'NameNode trả block ID và vị trí các replica A/B. Client vẫn chưa nhận byte dữ liệu.',
      'data-request': 'Client yêu cầu đọc block trực tiếp từ DataNode A.',
      unavailable: 'Không đọc được replica A. Đây là lỗi đọc tại DataNode, không phải mất metadata.',
      'replica-request': 'Client chọn replica B từ danh sách vị trí và gửi yêu cầu đọc.',
      'data-response': 'DataNode đang hoạt động trả byte trực tiếp về client.',
      complete: 'Đọc xong block. Hình giữ kết quả rồi bắt đầu một yêu cầu minh họa mới; không xóa replica.',
    },
    note: 'Hình rút gọn còn một block, hai replica trên hai rack để thấy fallback; không mô tả replication factor mặc định. DataNode gửi heartbeat báo còn hoạt động và block report báo các block đang giữ. NameNode dùng metadata đó để quản lý vị trí replica.',
  },
  modeling: {
    title: 'Cùng doanh thu, khác số đường join',
    help: 'Đơn vị của fact ở đây là một dòng hàng trong đơn. Bạn muốn doanh thu theo danh mục sản phẩm: xem thuộc tính category nằm ở bảng nào.',
    tabs: ['Star · dimension rộng', 'Snowflake · dimension chuẩn hóa'],
    fact: 'Fact · một dòng hàng', product: 'Dimension sản phẩm', category: 'Dimension danh mục', customer: 'Dimension khách hàng', date: 'Dimension ngày',
    star: 'Trong star, category_name nằm ngay trong dim_product. Truy vấn doanh thu theo danh mục đi từ fact tới product qua một join; tên danh mục có thể lặp giữa nhiều sản phẩm.',
    snowflake: 'Trong snowflake, dim_product giữ category_id trỏ tới dim_category. Cùng câu hỏi cần thêm một join; tên danh mục được quản lý ở bảng riêng.',
    join: 'Khóa ngoại → khóa chính',
    note: 'Ít join không tự bảo đảm nhanh hơn trên mọi hệ thống. Bạn còn phải đo trên dữ liệu, query engine và cách bố trí thực tế. Week 11 sẽ đào sâu việc chọn grain và dimension.',
  },
  governance: {
    title: 'Sửa đúng lỗi của hồ dữ liệu',
    help: 'Bật từng biện pháp rồi nhìn hàng lỗi tương ứng. Tôi cố ý giữ một snapshot cũ: catalog đầy đủ không thể tự tạo dữ liệu mới.',
    policy: 'Biện pháp trong mô phỏng',
    controls: { catalog: 'Catalog', owner: 'Owner', validation: 'Validation', lineage: 'Lineage', retention: 'Retention' },
    effects: {
      catalog: 'Đăng ký dataset, schema, tag và mô tả để tìm được. Không sửa giá trị sai hoặc làm mới snapshot.',
      owner: 'Gán đội Orders làm owner và đầu mối xử lý. Không tự sửa schema hay nội dung.',
      validation: 'Chạy quy tắc amount, khóa duy nhất và freshness: cách ly giá trị sai, loại retry khỏi đầu ra, cảnh báo dữ liệu cũ. Không sinh batch còn thiếu.',
      lineage: 'Ghi đường nguồn → biến đổi → báo cáo cho dataset này. Không tự sửa job hoặc backfill dữ liệu.',
      retention: 'Áp chính sách mẫu giữ raw 90 ngày: loại bản raw 120 ngày tuổi khỏi vùng hoạt động. Không tự quyết định quy tắc pháp lý cho dữ liệu thật.',
    },
    statuses: { open: 'Còn lỗi', fixed: 'Đã xử lý trong mô phỏng', detected: 'Đã phát hiện · còn lỗi' },
    dataset: 'Dataset', issue: 'Lỗi cụ thể', status: 'Trạng thái', evidence: 'Điều thay đổi / còn thiếu',
    issues: {
      discovery: { label: 'Thiếu catalog và tài liệu schema', dataset: 'orders-current', open: 'Không có tag orders, schema hoặc mô tả để analyst tìm và hiểu dataset.', fixed: 'Đã đăng ký tag orders, schema amount:number và mô tả doanh thu. Nội dung bản ghi vẫn cần validation.', detected: '' },
      accountability: { label: 'Không có owner', dataset: 'orders-current', open: 'Có lỗi nhưng chưa biết ai chịu trách nhiệm xử lý.', fixed: 'Owner = Orders. Đã có đầu mối; chưa đồng nghĩa lỗi dữ liệu tự biến mất.', detected: '' },
      badAmount: { label: 'amount chứa chuỗi invalid', dataset: 'orders-current / B04', open: 'Giá trị invalid vẫn nằm trong đầu ra chưa kiểm tra.', fixed: 'B04 vào quarantine; chuỗi invalid không được cộng vào doanh thu.', detected: '' },
      duplicate: { label: 'Retry đơn 101 bị tính hai lần', dataset: 'orders-current / B02', open: 'B02 lặp đúng đơn 101 từ B01; đầu ra chưa chống trùng.', fixed: 'B02 được ghi vào log duplicate và loại khỏi đầu ra hợp lệ. Raw vẫn giữ dấu vết retry.', detected: '' },
      stale: { label: 'Snapshot trễ 48 giờ', dataset: 'orders-snapshot', open: 'Chưa có cảnh báo freshness; snapshot vẫn thiếu 48 giờ dữ liệu.', fixed: '', detected: 'Cảnh báo freshness đã bật; vẫn thiếu 48 giờ dữ liệu. Owner cần sửa ingest và backfill.' },
      lineage: { label: 'Không rõ nguồn của báo cáo', dataset: 'revenue-report', open: 'Không lần ngược được revenue-report tới job và dataset nguồn.', fixed: 'Đã ghi orders-current → clean-orders → revenue-report. Chưa sửa được upstream nếu upstream đang lỗi.', detected: '' },
      expired: { label: 'Raw 120 ngày vượt hạn 90 ngày', dataset: 'orders-raw-archive', open: 'Bản raw quá hạn chính sách mẫu vẫn chiếm vùng lưu trữ hoạt động.', fixed: 'Bản raw 120 ngày đã được loại theo chính sách mẫu 90 ngày. Chính sách phải do tổ chức xác định.', detected: '' },
    },
    conclusion: 'Bật cả năm biện pháp vẫn còn snapshot cũ. Governance giúp tìm, giao trách nhiệm, ngăn lỗi đi tiếp và theo dấu; dữ liệu còn thiếu phải được nạp lại.',
  },
  medallion: {
    title: 'Năm dòng raw, hai đơn đáng tin',
    help: 'Xử lý từng dòng để nhìn nơi nó đến, hoặc chạy hết rồi replay Bronze. Theo dõi đơn 101: bản retry được giữ để audit nhưng không được cộng tiền lần nữa.',
    next: 'Xử lý bước tiếp', run: 'Chạy hết pipeline', replay: 'Replay Bronze', reset: 'Làm lại thí nghiệm',
    bronze: 'Bronze · nguyên bản', silver: 'Silver · hợp lệ duy nhất', quarantine: 'Quarantine · cần sửa', duplicate: 'Log chống trùng', gold: 'Gold · doanh thu',
    rawId: 'Dòng raw', orderId: 'Mã đơn', amount: 'Số tiền (VND)', reason: 'Lý do', original: 'Dòng gốc', processed: 'Dòng đã xử lý', ledger: 'Sổ xử lý',
    ready: 'Bronze đã có đủ năm dòng; chưa chạy các tầng dẫn xuất.',
    replayReady: 'Replay đọc lại đúng năm dòng Bronze đang có. Sổ xử lý và đầu ra trước đó được giữ nguyên.',
    actions: {
      ready: 'Sẵn sàng xử lý Bronze.', accepted: 'Hợp lệ và chưa có khóa này: đưa vào Silver.', duplicate: 'Cùng mã đơn và cùng amount: ghi retry, không thêm vào Silver.',
      amount: 'amount không phải số hữu hạn không âm: đưa vào quarantine.', key: 'Thiếu mã đơn hợp lệ: đưa vào quarantine.',
      conflict: 'Cùng mã đơn nhưng khác amount: cách ly để xử lý xung đột; không đoán bản nào mới hơn.',
      replayed: 'raw_id đã có trong sổ xử lý: giữ nguyên đầu ra, không cộng thêm.', aggregate: 'Tính lại Gold bằng tổng amount của Silver; thay kết quả tổng, không cộng dồn lượt chạy.',
    },
    reasons: { amount: 'amount sai kiểu hoặc giá trị', key: 'Thiếu khóa hợp lệ', conflict: 'Xung đột cùng mã đơn' },
    invariant: 'Kết quả cần giữ: 5 Bronze = 2 Silver + 2 quarantine + 1 duplicate; Gold = 200.000 VND.',
    boundary: 'Đây là pipeline minh họa, không phải Delta Lake đang chạy. Bronze giữ payload nguồn cùng load_time và process_id. Retry B02 giống payload B01 nhưng có metadata nạp riêng. Replay ở đây đọc lại raw đã lưu, không ingest thêm bản Bronze.',
    idempotency: 'Idempotency đến từ sổ raw_id đã xử lý, khóa nghiệp vụ order_id và việc thay tổng Gold. Tên Bronze/Silver/Gold tự nó không chống trùng. Trong hệ thống thật, sổ xử lý và ghi đầu ra cần được commit nhất quán; update/CDC còn cần quy tắc version và merge.',
    replayCount: 'Số lượt replay', completed: 'Đã hoàn tất', aggregatePending: 'Chưa chạy bước tổng hợp',
  },
};
