import type { QuizQ } from '@/components/SessionQuiz';

export const VI = {
  badge: 'BUỔI 12', title: 'Orchestration & chất lượng dữ liệu', cover: 'Bìa',
  eyebrow: 'DATA ENGINEERING FOUNDATION / PHẦN IV / 12',
  hero: 'Đúng giờ.<br/>Chưa chắc <em class="hl-cyan">đúng dữ liệu.</em>',
  intro: '02:00, pipeline bắt đầu lấy đơn hàng. 03:00, bước biến đổi chạy đúng lịch. Nhưng tệp cuối cùng đến lúc 03:20. Mọi chiếc đồng hồ đều giữ lời; báo cáo doanh thu thì sai. Tôi sẽ tua lại ca trực này để bạn thấy lúc nào nên chạy, lúc nào phải đợi và lúc nào cần chặn dữ liệu.',
  meta: '10 chương · 3 phòng thí nghiệm · 10 câu tự kiểm kiến thức',
  start: 'Bắt đầu ca trực', jump: 'Thử cổng chất lượng',
  premise: 'Tình huống bán lẻ và các lab là mô phỏng để học; không kết nối database hay chạy Airflow thật. Ví dụ API dùng mốc Airflow 3.1.0; kiến trúc cũ được ghi rõ.',
  readyTitle: '🧭 Trước khi vào phòng điều phối', readyLead: 'Bạn không cần toán đồ thị nâng cao. Giữ sáu ý này trong đầu để phân biệt một sơ đồ với một lần chạy thật.',
  terms: [
    ['Directed graph · Đồ thị có hướng', 'A → B nghĩa là B phụ thuộc A. Mũi tên ở DAG chỉ điều kiện thực thi, không có nghĩa dữ liệu tự chảy qua đó.'],
    ['Acyclic · Không chu trình', 'A → B → C hợp lệ; thêm C → A tạo vòng đợi. DAG không có chu trình; retry cùng một task không tạo thêm cạnh quay ngược.'],
    ['Task state · Trạng thái', 'queued, running, success, failed mô tả một task instance. Bạn cần nó để biết bước sau có đủ điều kiện chạy không.'],
    ['Retry · Thử lại', 'Một lần thử mới sau lỗi của cùng task instance. Chỉ hợp lý khi lỗi có thể hết; thử lại không tự sửa dữ liệu sai.'],
    ['Data interval · Khoảng dữ liệu', 'Khoảng [bắt đầu, kết thúc) mà một run xử lý. Bao gồm đầu, không gồm cuối; tránh đếm hai lần bản ghi đúng ranh giới.'],
    ['Validation rule · Quy tắc kiểm', 'Một điều kiện có thể kiểm bằng máy, như order_id không rỗng. Quy tắc cần ngưỡng, bằng chứng và hành động khi không đạt.'],
  ],
  chapters: [
    {
      title: 'Ba đồng hồ đúng, một báo cáo sai',
      lead: 'Bước transform không biết extract còn đang chạy. Một lịch hẹn không cung cấp thông tin đó.',
      body: [
        'Pipeline thường đi từ <strong class="hl-cyan">extract → transform → load</strong>: lấy dữ liệu nguồn, làm sạch theo nghiệp vụ, đưa kết quả vào warehouse rồi refresh dashboard hoặc phục vụ ML. Lịch 02:00 / 03:00 / 04:00 ngầm giả định nguồn luôn sẵn, bước trước luôn thành công và luôn hoàn tất đúng giờ.',
        'Extract kéo dài tới 03:20 nhưng transform bắt đầu lúc 03:00: nó đọc một phần dữ liệu. Load lúc 04:00 vẫn có thể trả mã thành công và ghi một báo cáo thiếu đơn hàng. <strong>Thành công của lệnh không chứng minh đầy đủ của đầu vào.</strong>',
        '<strong class="hl-cyan">Orchestration</strong> điều phối, lên lịch và quản lý việc thực thi: giải dependency, theo dõi trạng thái bằng metadata, áp dụng retry và thông báo lỗi. Phần tính toán nặng vẫn do Python, SQL, Spark hoặc hệ xử lý thực hiện.',
        'Tôi đặt extract_orders và extract_customers song song vì chúng độc lập. Transform chỉ đủ điều kiện khi cả hai thành công; load chờ transform; dashboard chờ load. Điều phối vừa chặn đúng chỗ, vừa cho chạy song song đúng chỗ. Bạn thử hai tình huống dưới đây: thời điểm 03:00 giống nhau, quyết định khác nhau.',
      ],
      headers: ['Trách nhiệm', 'Quyết định của orchestrator'],
      rows: [['Dependency', 'Bước nào phải xong trước; bước nào độc lập?'], ['Scheduling', 'Tạo run theo lịch hoặc tín hiệu nào?'], ['State', 'Task của run này đang ở trạng thái nào?'], ['Fault tolerance', 'Thử lại, chặn downstream và báo cho ai?']],
    },
    {
      title: 'Một lần chạy cần trí nhớ', lead: 'Sáng hôm sau, bạn cần biết bước nào hỏng và lần thử nào đã ghi dữ liệu. Log rời rạc không đủ để tái dựng cả workflow.',
      body: [
        'Run có thể bắt đầu theo thời gian, do bạn bấm chạy, khi dữ liệu sẵn sàng hoặc khi nhận sự kiện bên ngoài. Ví dụ: chạy hằng ngày lúc 02:00; chạy lại pipeline hôm qua; đợi object trên S3; nhận thông báo một batch mới đã được tải lên. <strong>Lên lịch tạo run; điều phối quyết định các task của run được chạy thế nào.</strong>',
        'Một task đủ dependency được scheduler xem xét, đưa vào hàng đợi rồi worker thực thi. Thành công mở đường cho downstream; lỗi tạm thời có thể dẫn tới retry sau thời gian chờ. Airflow gọi trạng thái chờ thử lại là <code>up_for_retry</code>. Hết lượt thử thì failed; downstream dùng all_success bị chặn và có thể thành upstream_failed.',
        'Skipped là chủ động bỏ qua một nhánh, không đồng nghĩa failed hoặc success. Tôi luôn giữ task ID, run ID, khoảng dữ liệu, số lần thử và log cùng nhau. Khi lỗi vẫn còn: báo owner, giữ bằng chứng và cho phép chạy lại sau khi sửa.',
        'Retry có giới hạn, thời gian chờ và backoff giúp tránh dồn tải khi nguồn đang yếu. Một mật khẩu sai hay schema bị đổi cần sửa cấu hình/contract, không cần 100 lần thử mù. Ngay cả 100 task thành công cùng query một database cũng có thể làm cả hệ chậm; chương 06 sẽ đặt giới hạn cho chúng.',
      ],
      headers: ['Trạng thái', 'Ý nghĩa và bước kế tiếp'],
      rows: [['queued', 'Đã giao executor, chờ worker.'], ['running', 'Worker đang thực thi.'], ['success', 'Lần thực thi hoàn thành; còn phải xét điều kiện downstream.'], ['up_for_retry', 'Chờ một lần thử mới theo chính sách.'], ['failed / upstream_failed', 'Task lỗi / dependency upstream làm task không chạy được.'], ['skipped', 'Nhánh không được chọn hoặc task chủ động bỏ qua.']],
    },
    {
      title: 'Timer không biết dữ liệu đã sẵn', lead: 'Lùi lịch transform một giờ chỉ chuyển rủi ro sang hôm extract chậm thêm một giờ nữa.',
      body: [
        'Cron chạy script theo biểu thức thời gian; <code>0 2 * * *</code> là mỗi ngày lúc 02:00 theo múi giờ của lịch. Cron hợp với một việc độc lập chỉ cần timer. Nó không có sẵn DAG, dependency, metadata run tập trung hay cơ chế retry của cả workflow. Script có thể tự nối lệnh, kiểm lỗi và ghi log, nhưng lúc đó bạn đang tự xây lớp điều phối.',
        'Một dòng crontab thông dụng có 5 trường thời gian rồi đến command: phút 0–59, giờ 0–23, ngày trong tháng 1–31, tháng 1–12, thứ trong tuần 0–7 (Chủ nhật là 0 hoặc 7 trong cron Unix thông dụng). Dấu * nhận mọi giá trị của trường; vì vậy 0 2 * * * chọn phút 0, giờ 2, mọi ngày. Một số hệ dùng dialect khác, nên kiểm scheduler trước khi chuyển biểu thức.',
        '<strong class="hl-purple">Bổ sung cho các chủ đề chỉ nêu ở agenda:</strong> idempotency, backfill và dynamic pipelines cần một ví dụ cụ thể. Idempotency nghĩa là chạy lại với cùng đầu vào và cùng khoảng dữ liệu không tạo thêm tác động ngoài ý muốn. INSERT nối thêm dễ nhân đôi; upsert theo khóa hoặc thay thế partition trong transaction có thể an toàn nếu thiết kế đúng.',
        'Retry thử lại task lỗi. Rerun chạy lại task/run đã có. Backfill tạo xử lý cho các khoảng lịch sử được chọn. Run của khoảng [2026-05-15, 2026-05-16) phải đọc đúng khoảng đó dù thực thi ngày khác. Với lịch theo data interval, run thường được lên lịch sau khi khoảng kết thúc; logical date không phải thời điểm worker bắt đầu.',
        'Dynamic DAG generation tạo cấu trúc từ cấu hình; dynamic task mapping tạo task instance theo danh sách đầu vào lúc chạy. Ví dụ danh sách 3 partition tạo 3 task xử lý, không phải một vòng lặp vô hạn trong DAG. Giữ ID và thứ tự ổn định, hạn chế gọi API/database ở lúc parse file, rồi dùng pool để giới hạn tải.',
        'Trong lab, hãy xuất cùng khoảng hai lần. Tôi dùng phép thay thế partition với fixture cố định: tổng số dòng vẫn là 3. Điều đó minh họa idempotency; một hệ thật còn cần giao dịch, khóa ghi và quy tắc khi đầu vào lịch sử đổi.',
      ], headers: ['Tình huống', 'Hành động có chủ đích'], rows: [['API timeout tạm thời', 'Retry task, giữ nguyên khoảng dữ liệu.'], ['Sửa logic cho các ngày trước', 'Backfill phạm vi cụ thể, kiểm tải và đối soát lại.'], ['Nhận danh sách tệp thay đổi', 'Task mapping theo danh sách hữu hạn.'], ['Chạy lại cùng batch', 'Ghi idempotent theo partition/khóa; không append mù.']],
    },
    {
      title: 'DAG là bản kế hoạch; run là sự kiện', lead: 'Cùng extract_orders xuất hiện mỗi ngày. Tên task không đủ để chỉ đúng một lần thực thi.',
      body: [
        'Airflow biểu diễn workflow bằng DAG: các task cùng cạnh phụ thuộc có hướng, không có chu trình. DAG <code>daily_sales_pipeline</code> là định nghĩa; DAG Run cho 2026-05-15 là một lần chạy; task <code>extract_orders</code> là một bước; task instance là bước đó trong run cụ thể (và chỉ số map nếu được mapping). Retry tạo lần thử mới của instance này.',
        'Airflow giúp viết workflow bằng code, lên lịch, quan sát trạng thái, lịch sử và retry. Nó <strong>không phải database, warehouse, message queue hay streaming engine</strong>. Task có thể chạy Python hoặc gửi job Spark/dbt/Docker; Airflow không tự trở thành engine tính toán phân tán hay nơi cất dataset.',
        'Trong sơ đồ Airflow đời cũ, DAG files được đọc để tạo kế hoạch; scheduler xét task đủ điều kiện; executor chọn cơ chế thực thi; workers chạy code; metadata database lưu run/state/retry và cấu hình; webserver/UI hiển thị trạng thái, log và thao tác thủ công. Sơ đồ đó vẽ các thành phần trao đổi trực tiếp qua database.',
        '<strong class="hl-yellow">Mốc Airflow 3.1.0:</strong> DAG processor parse và serialize định nghĩa; scheduler dùng kế hoạch để điều phối qua executor. Task code giao tiếp qua Task SDK và Execution API do API server phục vụ, thay vì truy cập trực tiếp metadata database. UI cũng được API server phục vụ. Với task deferrable, triggerer theo dõi điều kiện chờ và đánh thức task; nó không chạy toàn bộ phép biến đổi.',
        'Sơ đồ dưới đây là đường điều khiển và trạng thái. Dữ liệu đơn hàng nằm trong hệ lưu trữ bên ngoài; nó không đi qua metadata database chỉ vì trên hình có mũi tên.',
      ], headers: ['Khái niệm', 'Ví dụ'], rows: [['DAG', 'daily_sales_pipeline'], ['DAG Run', 'Run cho khoảng 2026-05-15'], ['Task', 'extract_orders'], ['Task Instance', 'extract_orders thuộc run 2026-05-15']],
    },
    {
      title: 'Truyền địa chỉ, đừng chuyền cả kho', lead: 'Hai task có thể chạy trên hai máy khác nhau. Biến Python và tệp /tmp của task trước không tự xuất hiện ở task sau.',
      body: [
        'Operator là khuôn công việc; khi khởi tạo trong DAG nó tạo task. <code>PythonOperator</code> gọi hàm Python, còn <code>@task</code> là cách khai báo TaskFlow thuận tiện hơn: gọi hàm đã decorate lúc dựng DAG tạo dependency/XCom reference, không phải chạy hàm xử lý ngay trên máy scheduler.',
        'Sensor là operator chờ điều kiện: file/S3 object có mặt, table được cập nhật, API sẵn sàng hoặc workflow khác hoàn thành. <code>FileSensor</code> mặc định chờ sự hiện diện của đường dẫn, không chờ file biến mất. File xuất hiện chưa chắc đã ghi xong; tốt hơn là dùng marker hoàn tất hoặc cơ chế commit của nguồn. Đường dẫn phải nhìn thấy từ worker; chế độ reschedule nhả worker slot giữa các lần kiểm tra, còn deferral cần operator hỗ trợ và triggerer.',
        '<strong class="hl-cyan">XCom</strong> cho task push/pull giá trị nhỏ: đường dẫn object, row count, ID hoặc URI model. Backend mặc định lưu giá trị trong metadata database; không gửi DataFrame lớn. Backend object storage có thể đổi nơi lưu payload, nhưng bạn vẫn cần quản lý kích thước, truy cập và vòng đời dữ liệu.',
        'Ví dụ training push <code>model_path</code> bằng <code>xcom_push</code>, evaluation pull cùng key và task ID. Nếu giá trị là /models/v2 thì đó phải là đường dẫn dùng chung hoặc URI truy cập được, không phải một thư mục local tình cờ cùng tên. TaskFlow tự tạo XCom cho return value; dependency không tự chuyển dataset giữa máy.',
        'Tôi dựng lại các ví dụ Bash, TaskFlow, FileSensor và Docker bên dưới thành code đọc được. Các đoạn là mẫu khai báo trong DAG, không phải hệ Airflow đã triển khai. Docker cần image tồn tại, daemon/connection hợp lệ và mount trên máy daemon; provider quyết định chữ ký tham số.',
      ], headers: ['Operator / API', 'Công việc'], rows: [['PythonOperator / @task', 'Chạy hàm Python / khai báo TaskFlow.'], ['BashOperator', 'Chạy shell, CLI hoặc lệnh dbt.'], ['SQLExecuteQueryOperator', 'Chạy SQL qua connection; dùng thay tên PostgresOperator của tài liệu cũ.'], ['S3KeySensor / FileSensor', 'Chờ object / đường dẫn sẵn sàng.'], ['DockerOperator', 'Chạy tác vụ trong container.'], ['HttpOperator', 'Gọi HTTP API hoặc webhook.'], ['EmailOperator', 'Gửi email thông báo khi đã cấu hình provider/connection.']],
    },
    {
      title: 'Đừng để scheduler làm nghẹt database', lead: '200 task có thể đều đúng mà vẫn cùng làm một PostgreSQL quá tải.',
      body: [
        'Variables giữ cấu hình như tên bucket, khoảng ngày hoặc feature flag. Connections giữ endpoint và thông tin xác thực cho database/API/cloud; task dùng connection ID, không chép mật khẩu vào DAG. UI, biến môi trường và secrets backend là cách cung cấp giá trị; quyền truy cập, encryption và che log vẫn phải được cấu hình. Tôi không xem việc chuyển mật khẩu khỏi code là đã hoàn tất bảo mật.',
        'Executor quyết định cách chạy: LocalExecutor dùng process trên một máy; CeleryExecutor phân phối lên worker qua broker; KubernetesExecutor tạo pod cho task. SequentialExecutor chạy một task mỗi lần là ví dụ cũ, đã bị bỏ từ Airflow 3.0; không chọn nó cho 3.1.0. Mỗi lựa chọn đổi chi phí vận hành, cách ly và năng lực mở rộng.',
        '<code>parallelism=64</code> giới hạn task instance chạy đồng thời theo scheduler trong cấu hình Airflow 3.1.0; ví dụ này giả định một scheduler. Không diễn giải 64 thành trần tuyệt đối cho mọi deployment nhiều scheduler. Worker capacity, executor và giới hạn DAG có thể làm số thực tế thấp hơn.',
        '<code>max_active_runs=1</code> hạn chế số run hoạt động của cùng DAG, không ép các task trong run chạy tuần tự và không khóa các DAG khác. Tên đúng là max_active_runs, không phải max_activate_runs. <code>max_active_tasks</code> là giới hạn task riêng ở cấp DAG.',
        '<code>postgres_pool</code> có 5 slot thì nhiều nhất 5 task một-slot dùng pool cùng chạy. Task nặng có thể xin nhiều slot qua pool_slots. Với 200 task database sẵn sàng, trần 64 và pool 5, nút thắt là 5: tăng 64 không mở rộng database. Pool là hạn mức logic, không tự tạo thêm worker hoặc kết nối.',
        'Bạn thử tăng số run trong lab rồi hạ pool. Theo dõi các hàng chờ, không chỉ tổng số task. Trong vận hành, dùng Grid/Graph và log để tìm instance lỗi; alert email/Slack kèm ngữ cảnh; Grafana/Datadog theo dõi queue depth, thời gian chạy, retry và độ trễ dữ liệu theo thời gian. Task xanh vẫn chưa đủ: chương tiếp theo kiểm chính dữ liệu.',
      ], headers: ['Executor', 'Cơ chế / đánh đổi'], rows: [['SequentialExecutor · cũ', 'Một task mỗi lần; bị bỏ từ Airflow 3.0.'], ['LocalExecutor', 'Nhiều process local; bị giới hạn bởi tài nguyên máy.'], ['CeleryExecutor', 'Cụm worker và broker; cần vận hành hạ tầng phân phối.'], ['KubernetesExecutor', 'Pod theo task; cách ly tốt, có overhead khởi tạo và vận hành cluster.']],
    },
    {
      title: 'Task xanh vẫn có thể chở dữ liệu sai', lead: 'Một cột price có toàn số nguyên hợp lệ vẫn có thể chứa giá bán của hôm qua.',
      body: [
        'Dữ liệu tốt là dữ liệu <strong class="hl-cyan">phù hợp mục đích sử dụng</strong>. Thiếu giá trị bắt buộc, sai kiểu, sai format, trùng record, dữ liệu cũ, lệch giữa hệ thống và schema đổi bất ngờ đều có thể làm quyết định sai. Đúng cú pháp không chứng minh đúng thực tế.',
        'Một sự cố thật: năm 2020, Public Health England xác nhận 15,841 ca bị chậm đưa vào báo cáo hằng ngày và chuyển sang hệ truy vết; người được xét nghiệm vẫn nhận kết quả bình thường. Đây không phải mất vĩnh viễn 16,000 kết quả. Tôi giữ khác biệt đó vì timeliness và mất dữ liệu là hai lỗi khác nhau.',
        'Các con số $11.8M gán cho Gartner và $5B vốn hóa Unity trong tài liệu gốc chưa có đủ nguồn sơ cấp/ngữ cảnh để dùng như chi phí trực tiếp đã xác nhận. Bài học không lấy chúng làm số liệu chuẩn. Vốn hóa giảm cũng không tự chứng minh toàn bộ mức giảm do một lỗi dữ liệu.',
        'Biến dimension thành rule: customer_id không NULL; order_id duy nhất; email đúng format; price > 0; event_time không ở tương lai; row count ngày giảm không quá 30% so với baseline phù hợp. Đây là contract ví dụ: đơn miễn phí có thể hợp lệ, timestamp có thể chịu clock skew, và ngày nghỉ cần baseline riêng. Tôi muốn bạn chọn quy tắc theo nghiệp vụ, không sao chép ngưỡng vì thấy đẹp.',
      ], headers: ['Dimension', 'Câu kiểm cụ thể', 'Giới hạn'], rows: [['Accuracy · Độ chính xác', 'Giá 100 khớp giá thực 100.', 'Cần nguồn đối soát đáng tin.'], ['Completeness · Đầy đủ', 'Không thiếu email nếu contract bắt buộc.', 'Không đồng nghĩa email đúng.'], ['Consistency · Nhất quán', 'Cùng user ID khớp giữa các hệ.', 'Các hệ có thể cùng chứa một lỗi.'], ['Timeliness · Kịp thời', 'Dữ liệu sẵn trong chu kỳ 5 phút.', 'Ngưỡng theo nhu cầu sử dụng.'], ['Validity · Hợp lệ', 'Điện thoại đúng format 10 chữ số của thị trường đã chọn.', 'Format đúng chưa chắc liên hệ được.'], ['Uniqueness · Duy nhất', 'Không trùng user_id ở grain mỗi khách một dòng.', 'Order line có thể lặp order_id hợp lệ.']],
    },
    {
      title: 'Chất lượng là một vòng phản hồi', lead: 'Bạn sửa một tệp CRM hôm nay; ngày mai biểu mẫu nhập liệu vẫn tạo đúng lỗi đó.',
      body: [
        'Bắt đầu từ mục đích: công ty bán lẻ cần liên hệ khách. Profile dữ liệu rồi mới định nghĩa quy tắc, giám sát và sửa tận nguồn. Trong ví dụ, 15% record thiếu email, 10% có format không hợp lệ; còn có trùng khách và số điện thoại khác cách viết. Các tỷ lệ phải ghi rõ mẫu số, không cộng khi chưa biết các nhóm có giao nhau không.',
        'Contract liên hệ yêu cầu ít nhất một email hoặc điện thoại hợp lệ. Chuẩn hóa điện thoại theo mã quốc gia và quy tắc thị trường; +84-555-1234 và 05551234 minh họa khác format, không đủ để khẳng định hai số là cùng một người hoặc hợp lệ. Email regex chỉ sàng format, còn khả năng nhận thư cần xác minh riêng.',
        'ID khách phải duy nhất; tên + ngày sinh là heuristic gắn cờ trùng, không đủ để tự động nhập hai người thành một. Tôi giữ bước xét duyệt và mapping ID cũ khi deduplicate. Khi email không hợp lệ vượt 5%, alert owner; dashboard theo dõi tỷ lệ vi phạm từng rule mỗi tuần. Sửa dữ liệu, chuẩn hóa số, xác minh email và hướng dẫn đội sales/marketing nhập đúng giúp vòng sau ít lỗi hơn.',
        'Một hệ giám sát cần bốn việc: phủ cấp table/row/column; báo đúng người với rule, expected/observed, run và khoảng dữ liệu; có đường xử lý nhanh và owner chịu trách nhiệm; mở rộng ra nhiều dataset bằng rule và metadata tái dùng. Đừng ghi dữ liệu cá nhân thô vào alert nếu chỉ cần ID bằng chứng.',
      ], headers: ['Cách phát hiện', 'Điểm mạnh / giới hạn'], rows: [['Thủ công', 'Người dùng tình cờ thấy sai; khó phủ toàn hệ.'], ['Rule-based', 'Null, unique, range có giải thích rõ; chỉ bắt điều đã mô tả.'], ['Metric monitoring', 'Theo dõi row count, freshness, phân phối; cần baseline và mùa vụ.'], ['Machine learning', 'Phát hiện thay đổi phức tạp; có false positive, cần hiệu chỉnh và người điều tra.']],
    },
    {
      title: 'Kiểm tra phải thay đổi đường chạy', lead: 'In “validation failed” rồi return bình thường khiến task vẫn xanh. Một lời cảnh báo không tự chặn load.',
      body: [
        'Đường nguy hiểm là ingest → validation báo lỗi → transform → load → dashboard/ML. Dữ liệu xấu được xuất bản trước khi ai đọc log. <strong class="hl-red">Validation gate phải biến kết quả kiểm thành điều kiện thực thi.</strong>',
        'Cách đơn giản: validation raise lỗi nếu dữ liệu không đạt; transform và load phụ thuộc nó với trigger rule all_success. Task cảnh báo chạy qua callback hoặc nhánh one_failed phù hợp. Đừng đặt all_done lên task publish vì nó có thể chạy dù upstream thất bại. Một task cleanup all_done thành công ở cuối cũng có thể làm trạng thái DAG Run trông thành công; cần theo dõi task gate và điều kiện xuất bản riêng.',
        'Cách phân nhánh: dùng BranchPythonOperator hoặc TaskFlow @task.branch. Validation hoàn tất và trả về kết quả nhỏ, branch chọn transform hoặc alert/quarantine. Nhánh còn lại skipped. Branch thành công chỉ có nghĩa đã chọn được đường đi; không có nghĩa dữ liệu đạt. Nếu nối nhánh, chọn trigger rule phù hợp nhưng vẫn để publish nằm sau nhánh đã được kiểm đạt.',
        'Tôi gọi đây là circuit breaker cho dữ liệu: lỗi thì cắt đường xuất bản, giữ bằng chứng và báo owner. Không nhất thiết có đầy đủ state closed/open/half-open như circuit breaker cho dịch vụ mạng. Quarantine giữ batch lỗi tách biệt; dashboard tiếp tục dùng bản đã xác nhận gần nhất kèm thông tin độ mới.',
        'Bạn chọn một lỗi trong lab, xem rule nào thất bại và consumer nào bị chặn. Sau khi sửa đầu vào, chạy kiểm lại cùng khoảng; chỉ khi đạt mới publish. Thử lại nguyên batch sai không chữa được null key hay rename schema.',
      ], headers: ['Bộ phận', 'Quyết định'], rows: [['Validation task', 'Đánh giá rule; lưu expected, observed, run, batch và vị trí bằng chứng.'], ['Fail / branch', 'Chặn all_success hoặc chọn nhánh an toàn.'], ['Alert / quarantine', 'Báo owner; giữ batch để điều tra.'], ['Transform → load → consumers', 'Chỉ dùng output đã được xác nhận cho đúng khoảng dữ liệu.']],
    },
    {
      title: 'Biến thỏa thuận thành thứ kiểm được', lead: 'Upstream đổi user_id thành userId. Không ai sửa SQL downstream vì không ai biết có một giao diện vừa đổi.',
      body: [
        '<strong class="hl-cyan">Data contract</strong> là thỏa thuận giữa producer và consumer: tên/kiểu cột, nullability, range/format, freshness, uniqueness và trách nhiệm khi thay đổi. Rename user_id làm query lỗi; bỏ purchase_date làm feature pipeline hỏng; đổi type làm phép tính hoặc model sai; cho NULL vào field bắt buộc khiến dashboard thiếu dữ liệu.',
        'Contract ví dụ quy định user_id là INTEGER, purchase_date bắt buộc, age từ 0 đến 120, dữ liệu mới trong 24 giờ và transaction_id duy nhất. Lưu dạng machine-readable, version hóa, kiểm ở ranh giới giữa hai đội và báo cả hai khi vi phạm. Thỏa thuận không ngăn mọi thay đổi: cần quy trình tương thích, chuyển version và migration.',
        'GX gọi một rule là Expectation; Expectation Suite gom các rule. Các tên expect_column_values_to_not_be_null, expect_column_values_to_be_unique, expect_column_values_to_be_between và expect_column_values_to_match_regex mô tả bốn nhóm kiểm. GX Core mới dùng các lớp Expectation tương ứng; đừng trộn cú pháp cũ với API mới. Có backend cho dữ liệu file qua engine phù hợp, SQL/warehouse và Spark; kiểu dữ liệu/expectation được hỗ trợ tùy backend.',
        'Luồng GX trong Airflow: load dữ liệu → chạy validation → đọc success → fail hoặc branch → transform hay alert. Một kết quả success=false phải được task chuyển thành quyết định chặn; chỉ ghi báo cáo GX chưa đủ. Suite mã hóa phần rule của contract, không tự chứa đầy đủ owner, freshness SLA hay chính sách tương thích.',
        'Deequ chạy trên Spark: profiling tìm đặc trưng dataset, analyzers tính size/completeness/uniqueness/type/distinct, VerificationSuite kiểm constraint. Ví dụ <strong>completeness > 99%</strong> là điều kiện nghiêm: 99/100 không đạt, 100/100 đạt. Anomaly detection so metric qua các batch; incremental metric computation tái dùng state phù hợp để tránh tính lại toàn bộ, không phải mọi metric đều cộng tùy ý được.',
        'DataHub quản lý metadata dataset, schema, owner, pipeline, lineage và kết quả chất lượng. Khi orders lỗi, lineage chỉ ra sales_daily, dashboard và feature/model bị ảnh hưởng. Catalog không thay GX/Deequ để tự kiểm mọi dòng; việc chặn Airflow vẫn phải được nối rõ. Tôi dùng validation để biết điều gì sai, lineage để biết ai bị ảnh hưởng.',
      ], headers: ['Công cụ', 'Vai trò chính'], rows: [['Great Expectations', 'Expectation suites và validation trên backend dữ liệu được hỗ trợ.'], ['Deequ', 'Profiling, metrics, constraints trên Spark; anomaly và incremental state.'], ['dbt tests', 'Kiểm model SQL: not_null, unique, relationships, accepted_values.'], ['Soda Core', 'Quy tắc chất lượng khai báo; chạy scan trên nguồn được hỗ trợ.'], ['DataHub', 'Catalog, ownership, lineage và hiển thị thông tin chất lượng.']],
    },
  ],
  architecture: { title: 'Đường điều phối · Airflow 3.1.0', plan: 'DAG files → DAG processor → kế hoạch đã serialize', dispatch: 'Scheduler → Executor → Worker / Task SDK', state: 'Task SDK ↔ Execution API ↔ Metadata DB', ui: 'UI ↔ API server ↔ Metadata DB', data: 'Worker ↔ Object storage / Warehouse', note: '→ hướng điều khiển; ↔ trao đổi trạng thái hoặc dữ liệu theo nhãn. Nhánh storage mới mang dataset; metadata giữ trạng thái và giá trị nhỏ.' },
  code: { title: '⌨ Từ hình sang code', lead: 'Ví dụ khai báo: Python 3.11, Airflow 3.1.0, standard provider 1.9.0; Docker minh họa provider 4.4.4. Đọc các đoạn trong ngữ cảnh một DAG; connection, tệp và image phải được chuẩn bị ở môi trường thật.', operatorNote: 'Bash in 1; @task khai báo một task; FileSensor chờ file xuất hiện. Timeout chặn chờ vô hạn. Docker map thư mục host vào /training/code và /training/data, rồi chạy train.py trong container. docker_url chọn daemon local qua Unix socket; docker_conn_id là connection đăng nhập registry, không phải địa chỉ daemon. auto_remove="success" dùng dạng chuỗi của provider đã chọn, khác True ở ví dụ cũ.', gateTitle: 'Một gate nhỏ, kết quả rõ ràng', gateLead: 'Ví dụ TaskFlow hoàn chỉnh về dependency dùng fixture rất nhỏ trong XCom để học; production lưu batch ở storage và truyền URI. Không có side effect ghi warehouse. null key làm validate thất bại và publish bị chặn; đổi None thành 102 rồi chạy lại sẽ trả count=2, total=200000.', contractTitle: 'Một contract minh họa, không phải schema cấu hình của DataHub', xcomTitle: 'XCom chỉ giữ tham chiếu', xcomNote: 'Hai hàm thuộc hai task khác nhau. Shared URI phải truy cập được từ worker của evaluation; key và task_ids chọn đúng giá trị trong cùng run.' },
  labs: {
    demo: 'MÔ PHỎNG / KHÔNG CHẠY AIRFLOW',
    schedulerTitle: '⏱ Đồng hồ hay dependency?', schedulerHelp: 'Đổi tình huống, theo dõi hàng transform lúc 03:00. Bảng giữ toàn bộ câu chuyện ngay cả khi bạn tắt chuyển động.', modes: ['Chỉ theo cron', 'Theo dependency'],
    timelineHeaders: ['Thời điểm', 'Extract', 'Transform / kết quả'],
    timeline: [
      ['Lượt minh họa mới', 'Chưa chạy', 'Chưa chạy'],
      ['02:00', 'Đang chạy', 'Đang đợi'],
      ['03:00', 'Chưa xong', 'Đọc đầu vào thiếu'],
      ['03:20', 'Thành công', 'Kết quả đã thiếu dữ liệu'],
      ['04:00', 'Thành công', 'Xuất báo cáo sai'],
    ],
    safeTimeline: [
      ['Lượt minh họa mới', 'Chưa chạy', 'Chưa chạy'],
      ['02:00', 'Đang chạy', 'Đang đợi'],
      ['03:00', 'Chưa xong', 'Chặn: extract chưa thành công'],
      ['03:20', 'Thành công', 'Đủ dependency → bắt đầu transform'],
      ['04:00', 'Thành công', 'Xuất bản sau transform thành công'],
    ], timelineNote: 'Giả định transform an toàn mất 20 phút, load 20 phút; các bước đều thành công. Mô hình phụ thuộc không tự bảo đảm deadline hay chất lượng.',
    interval: 'Khoảng dữ liệu', publish: 'Xuất / chạy lại khoảng', rows: 'Dòng đã xuất', attempts: 'Số lần xuất', idempotent: 'Mỗi khoảng có 3 dòng; chạy lại thay thế đúng partition. Chọn khoảng khác để mô phỏng backfill.',
    poolTitle: '🎛 Phòng điều phối tài nguyên', poolHelp: '2 run × 100 task độc lập cùng query database; mỗi task chiếm 1 slot, hoàn thành sau 1 nhịp. Giả định một scheduler, worker đủ sức, không có giới hạn DAG task khác.',
    capacity: 'parallelism', runs: 'max_active_runs', slots: 'postgres_pool · slots', tick: 'Hoàn tất nhóm đang chạy', reset: 'Đặt lại thí nghiệm', running: 'Đang chạy', waiting: 'Chờ tài nguyên', blocked: 'Chờ run được mở', done: 'Hoàn tất', poolNote: 'Đổi giới hạn sẽ đặt lại thí nghiệm. Slot là hạn mức logic; ô tô màu là task đang giữ slot, không phải worker vật lý.', run: 'Run', poolEvidence: 'Task chạy trong pool',
    gateTitle: '🛑 Chặn lỗi trước khi xuất bản', gateHelp: 'Chọn lỗi, kiểm batch rồi sửa và kiểm lại. Cùng snapshot của batch phải được kiểm đạt trước khi publish.',
    faults: ['Batch hợp lệ', 'customer_id rỗng', 'order_id trùng', 'amount âm', 'Dataset cũ', 'Đổi tên schema', 'Row count giảm', 'Timestamp tương lai'],
    check: 'Kiểm tra batch', fix: 'Sửa đầu vào & kiểm lại', export: 'Xuất bản batch đã đạt', unchecked: 'Chưa kiểm', pass: 'Đạt', fail: 'Không đạt · dừng & báo owner', published: 'Đã xuất bản', quarantined: 'Cách ly batch · giữ bản tốt trước đó', pending: 'Chờ kiểm batch hiện tại', consumerBlocked: 'Consumer bị chặn', consumerReady: 'Consumer sẵn sàng',
    rules: ['Schema bắt buộc', 'customer_id không rỗng', 'order_id duy nhất', 'amount > 0', 'Freshness ≤ 24 giờ', 'Row count giảm ≤ 30%', 'event_time ≤ thời điểm kiểm'],
    ruleHeaders: ['Quy tắc', 'Quan sát', 'Kết quả'], evidence: 'Bằng chứng', expected: 'Ngưỡng theo contract ví dụ',
    lineage: ['orders / producer: retail', 'sales_daily / owner: analytics', 'dashboard / owner: BI', 'features / owner: ML'],
    gateNote: 'Quy tắc ở lab là JavaScript minh họa, không phải GX/Deequ. Snapshot và thời điểm kiểm cố định để kết quả lặp lại được. Không tự sửa bằng cách xóa mọi dòng lỗi trong production.',
  },
  summaryTitle: '📌 Tấm bản đồ cuối ca trực',
  summary: ['Lịch tạo run; dependency, trạng thái và tài nguyên quyết định task được chạy.', 'Task instance gắn với một run; retry không thay đổi khoảng dữ liệu cần xử lý.', 'Rerun/backfill cần ghi idempotent; XCom truyền metadata nhỏ và URI truy cập được.', 'parallelism, max_active_runs và pool giới hạn ba thứ khác nhau.', 'Chất lượng theo mục đích sử dụng; validity chưa chứng minh accuracy.', 'Validation gate chặn publish; contract xác định kỳ vọng; lineage chỉ ra tác động.'],
  checkTitle: '✓ Tự kiểm trước khi rời bài',
  checks: ['Tôi giải thích được vì sao lịch 02:00 / 03:00 / 04:00 có thể xuất dữ liệu sai.', 'Tôi phân biệt DAG, DAG Run, Task, Task Instance và lần thử.', 'Tôi thiết kế được rerun/backfill theo khoảng dữ liệu mà không nhân đôi kết quả.', 'Tôi giải thích được pool 5 chặn tải database dù parallelism là 64.', 'Tôi chỉ ra rule, bằng chứng, owner và consumer bị ảnh hưởng khi gate thất bại.', 'Tôi phân biệt vai trò GX, Deequ và DataHub; không coi task xanh là dữ liệu đúng.'],
  quizTitle: 'Kiểm tra cuối buổi',
  topicLabels: { 'def12.dependencies': 'Dependency và trạng thái', 'def12.reruns': 'Retry và backfill', 'def12.airflow': 'Airflow và XCom', 'def12.resources': 'Concurrency và pool', 'def12.quality': 'Chất lượng và contract', 'def12.gates': 'Validation gate và lineage' },
  quiz: [
    { topicId: 'def12.dependencies', q: 'Extract kết thúc 03:20. Transform đặt cron 03:00. Sửa nào giải quyết nguyên nhân?', opts: ['Tăng số worker', 'Cho transform phụ thuộc extract thành công', 'Dời cron thêm 5 phút', 'Tắt log'], a: 1, ex: 'Dependency theo kết quả thực thi; một khoảng đệm cố định không chứng minh đầu vào sẵn sàng.' },
    { topicId: 'def12.dependencies', q: 'extract_orders trong run ngày 2026-05-15 là gì?', opts: ['Một DAG mới', 'Một executor', 'Một task instance', 'Một connection'], a: 2, ex: 'Task là định nghĩa; instance gắn task với một run (và map index nếu có).' },
    { topicId: 'def12.reruns', q: 'Chạy lại cùng partition cần tính chất nào để tránh nhân đôi dữ liệu?', opts: ['Idempotency', 'Append mọi lần', 'Đổi logical date theo giờ hiện tại', 'Tăng retry vô hạn'], a: 0, ex: 'Upsert hoặc thay thế partition có giao dịch phù hợp giúp cùng đầu vào không tạo thêm tác động ngoài ý muốn.' },
    { topicId: 'def12.airflow', q: 'Payload phù hợp với XCom mặc định là gì?', opts: ['DataFrame rất lớn', 'Toàn bộ tệp video', 'Toàn bộ bảng warehouse', 'URI object và row count'], a: 3, ex: 'Dùng XCom cho metadata nhỏ. Dataset nằm trong storage mà các worker truy cập được.' },
    { topicId: 'def12.resources', q: '200 task một-slot sẵn sàng, một scheduler parallelism=64, pool=5, worker đủ. Tối đa bao nhiêu task dùng pool chạy cùng lúc?', opts: ['64', '200', '5', '1'], a: 2, ex: 'Pool 5 là giới hạn chặt nhất trong giả định đã cho; task đang chờ không chiếm thêm slot.' },
    { topicId: 'def12.resources', q: 'max_active_runs=1 bảo đảm điều gì?', opts: ['Mọi task trong run chạy tuần tự', 'Cùng DAG chỉ có tối đa một run hoạt động theo giới hạn này', 'Mọi DAG chia sẻ một khóa database', 'Chỉ có một worker'], a: 1, ex: 'Giới hạn run không đồng nghĩa giới hạn task; task độc lập trong run vẫn có thể chạy song song.' },
    { topicId: 'def12.quality', q: 'Email đúng regex nhưng không thuộc khách hàng đó. Điều gì vẫn có thể sai?', opts: ['Accuracy', 'Tên DAG', 'Số slot', 'Acyclicity'], a: 0, ex: 'Validity kiểm format/rule; accuracy cần đối chiếu thực tế. Regex không chứng minh danh tính hoặc khả năng nhận thư.' },
    { topicId: 'def12.gates', q: 'Validation in lỗi ra log rồi return bình thường. Publish all_success vẫn chạy. Sửa đúng là gì?', opts: ['Ẩn log', 'Đổi publish sang all_done', 'Chỉ gửi email', 'Raise lỗi hoặc branch có đường publish chỉ khi đạt'], a: 3, ex: 'Kết quả rule phải đổi điều kiện thực thi. Alert không tự chặn downstream.' },
    { topicId: 'def12.quality', q: 'Deequ rule completeness > 99%. 99 giá trị có mặt trên 100 dòng có đạt không?', opts: ['Có, vì làm tròn thành 100%', 'Không, vì bằng 99% chứ chưa lớn hơn', 'Có nếu task xanh', 'Không thể tính tỷ lệ'], a: 1, ex: 'Dấu > là điều kiện nghiêm. 99/100 = 99%, không lớn hơn 99%.' },
    { topicId: 'def12.gates', q: 'Orders vi phạm contract. Lineage giúp thêm điều gì?', opts: ['Tự sửa mọi giá trị sai', 'Tự triển khai Airflow', 'Xác định dashboard/model và owner bị ảnh hưởng', 'Bỏ qua validation'], a: 2, ex: 'Validation cho biết lỗi; lineage cho biết nguồn và tác động. Hành động chặn/sửa vẫn cần workflow và owner.' },
  ] satisfies QuizQ[],
  practiceTitle: '🔧 Bài tập: bàn giao một pipeline đáng tin',
  practice: ['Vẽ DAG extract_orders + extract_customers → validate → transform → publish → dashboard. Ghi rõ cạnh phụ thuộc và nơi dataset thật được lưu.', 'Chọn khoảng [2026-05-15, 2026-05-16), giải thích retry và backfill. Chứng minh chạy cùng partition hai lần không tăng số dòng.', 'Với 200 task database, chọn parallelism=64, max_active_runs=1, pool=5. Ghi số task chạy, task chờ tài nguyên và run bị giữ lại.', 'Viết contract cho schema, null, unique, amount và freshness. Đưa vào một batch lỗi rồi ghi rule, expected/observed, owner, quarantine URI và consumer bị chặn.', 'Sửa đầu vào, kiểm lại, publish và đối soát. Ghi lại sự khác nhau giữa task thành công, dữ liệu đạt và dataset đã được xuất bản.'],
  practiceAnswer: 'Mở tiêu chí đối chiếu',
  practiceGuide: 'Hai extract độc lập; validate phải đợi cả hai. Gate lỗi thì publish không chạy, dashboard giữ bản tốt cũ. Dùng URI batch bất biến và ghi theo partition/khóa trong transaction. Với mô hình lab ban đầu: 5 task chạy, 95 chờ tài nguyên, 100 chờ run thứ hai; sau rerun cùng khoảng số dòng không đổi. Contract phải có owner và quy trình đổi version; bằng chứng kiểm phải gắn đúng snapshot đã publish.',
  next: 'Bạn đã đi tới lớp điều phối của nền tảng dữ liệu. Đầu ra của bài là một bản thiết kế có thể giải thích cách nó chờ, thất bại, phục hồi và giữ dữ liệu xấu khỏi người dùng.',
};
