import type { VI } from './lesson03.text.vi';

export const EN = {
  fn: {
    stepOf: (t: number, n: number) => `STEP ${t} / ${n}`,
    explored: (n: number) => `EXPLORED — EXPANDED (${n})`,
    goalPath: (path: string, cost: number | null, opened: number) =>
      `Path: ${path} · cost ${cost} · ${opened} nodes expanded`,
  },
  hero: {
    s1: "▶ Step through in the Lab",
    s2: "MATH PRIMER",
    s3: "02 Problem",
    s4: "04 Uninformed",
    s5: "06 Hill climbing",
    s6: "07 Summary",
    s7: "10 Exercises",
    s8: "Cover",
    s9: "SESSION 3",
    s10: "Search",
    s11: "Solving problems",
    s12: "with",
    s13: "Search",
    s14: "🧭 You need to reach a goal, but the world has millions of forks in the road. This session starts from 0: turn a messy problem into a tidy state graph, then build all 7 search algorithms for Lab 1 yourself, run them, and measure time and memory. That sounds like a lot, but trust me: those seven algorithms are really ONE loop with different machinery inside.",
    s15: "g — cost so far",
    s16: "h — estimated cost remaining",
    s17: "9 sections",
    s18: "≈ 3.5 hours",
  },
  ch1: {
    s1: "Problem-solving agents",
    s2: "Session 2 left you with reflex agents: see something, look it up, act. Now you’re in Arad and need to reach Bucharest in time for a flight. The right move <em>today</em> depends on a whole sequence of moves <em>tomorrow</em> — good luck squeezing that into a lookup table. The agent has to <strong class='hl'>think ahead</strong>: try action sequences in its model and choose one that reaches the goal. That’s a problem-solving agent, and its tool is <strong class='hl-cyan'>search</strong>.",
    s3: "STEP 1 · GOAL FORMULATION",
    s4: "Choose a goal",
    s5: "Decide which state you want the world to reach: <span class='code-inline'>In(Bucharest)</span>. Once you have a goal, countless irrelevant choices fall away. That’s what a goal is for.",
    s6: "STEP 2 · PROBLEM FORMULATION",
    s7: "Build a model",
    s8: "Describe states and actions with enough detail to make a solution <em>possible</em>, and enough abstraction to make finding it <em>manageable</em>. The weather, the song playing, your travel companion — leave them out; they’re irrelevant here.",
    s9: "STEP 3 · SEARCH",
    s10: "Search",
    s11: "This is the machine’s job: try action sequences in the <em>model</em> until one reaches the goal. That sequence is a <strong class='hl-mid'>solution</strong>.",
    s12: "STEP 4 · EXECUTION",
    s13: "Execute",
    s14: "Carry out the solution, one action at a time. This is <em>open-loop</em> execution: you can follow the plan without checking again, because the whole route has already been worked out.",
    s15: "ASSUMPTIONS FOR THIS SESSION",
    s16: "Fully observable",
    s17: "Discrete",
    s18: "Known model",
    s19: "Deterministic",
    s20: "→ these four assumptions let the solution be a <em>fixed</em> action sequence. Messier worlds come later.",
  },
  ch2: {
    s1: "A search problem has exactly 5 components",
    s2: "Good news: every problem — maps, sliding puzzles, vacuum robots, n queens — fits the same set of 5 components. Write those 5 down and you’re halfway there; the rest is choosing an algorithm. Q1 of Quiz 03 tests exactly this skill, so don’t skim it.",
    s3: "The starting state.",
    s4: "The actions available at s.",
    s5: "RESULT(s, a): the state reached by doing a at s.",
    s6: "Checks whether a state is a goal — explicitly, or by a property (checkmate!).",
    s7: "The sum of step costs c(s, a, s′) ≥ 0 along the path.",
    s8: "total kilometers traveled",
    s9: "A few names to keep handy: a <strong class='hl'>solution</strong> is a path from the initial state to a goal; an <strong class='hl-green'>optimal solution</strong> is the cheapest such path; the <em>state space</em> is the graph of all states connected by actions.",
    s10: "STATE-SPACE SIZE — A FEW NUMBERS",
    s11: "8-puzzle: 9!/2 = 181,440 states",
    s12: "Look at these numbers before taking my word for it: a naive model of 8 queens gives 64·63···57 ≈ 1.8×10¹⁴ sequences. A slightly smarter model — place a queen in the leftmost empty column, allowing no attacks — leaves <strong class='hl-green'>2,057</strong>. Same problem, 11 orders of magnitude apart. <em>Your model determines whether you can solve the problem at all.</em>",
    s13: "STATE SPACE ≠ SEARCH TREE",
    s14: "This distinction deserves a pause: Romania has exactly 20 cities, but its search tree can be <strong class='hl-red'>infinite</strong>, because nothing stops you going Arad → Sibiu → Arad → Sibiu → … forever. One state can occur in many different tree nodes. Handling those loops is precisely the boundary between tree-search and graph-search in section <a href='#ch3'>03</a>.",
  },
  ch3: {
    s1: "One framework, seven algorithms",
    s2: "This is my favorite section: seven impressive-sounding algorithms become one idea. They all use <em>the same loop</em>, changing just one decision: <strong class='hl-yellow'>which frontier node comes out first?</strong> A FIFO queue → BFS. A LIFO stack of plates → DFS. Cheapest g → UCS. Closest-looking h → GBFS. Balance both with f → A*. Remember that decision and you’ve got the backbone of the session.",
    s3: "TREE-SEARCH — may loop forever",
    s4: "<pre class='codeblock' style='background:transparent'>frontier ← {root node}\n  loop:\n    if frontier is empty: return <span style='color:#FC6255'>failure</span>\n    node ← POP(frontier)  <span style='color:#7A8399;font-style:italic'>▷ strategy = how this node is chosen</span>\n    if GOAL-TEST(node): return <span style='color:#83C167'>SOLUTION(node)</span>\n    add the children of node to frontier</pre>",
    s5: "GRAPH-SEARCH — remembers expanded states",
    s6: "<pre class='codeblock' style='background:transparent'>frontier ← {root node}; <span style='color:#F4D345'>explored ← ∅</span>\n  loop:\n    if frontier is empty: return <span style='color:#FC6255'>failure</span>\n    node ← POP(frontier)\n    if GOAL-TEST(node): return <span style='color:#83C167'>SOLUTION(node)</span>\n    <span style='color:#F4D345'>add node.STATE to explored</span>\n    add children to frontier <span style='color:#F4D345'>if their state\n    is not in explored ∪ frontier</span> <span style='color:#7A8399;font-style:italic'>▷ prevent loops</span></pre>",
    s7: "NODE ≠ STATE",
    s8: "They sound interchangeable, but they aren’t: several <em>nodes</em> can hold the same <em>state</em> — reaching Sibiu by three routes gives three nodes. That innocent-looking <strong class='hl-mid'>PARENT</strong> pointer is what lets you <em>trace back</em> the path. That’s the <span class='code-inline'>reconstruct()</span> function you’ll write in the Lab.",
    s9: "AN OIL SLICK",
    s10: "Picture graph-search as oil spreading across water 🌊. It divides space into 3 regions: <span style='color:var(--muted-2)'>explored (already covered)</span> · <span class='hl-cyan'>frontier (the advancing edge)</span> · untouched space. Every path from the start to the outside <em>must</em> cross that edge. Choosing which edge node to take next determines everything.",
    s11: "“An algorithm that forgets its history is doomed to repeat it.”",
    s12: "EVALUATION FRAMEWORK — FOR THE NEXT 4 SESSIONS",
    s13: "Complete?",
    s14: "If a solution exists, will it definitely find one?",
    s15: "Optimal?",
    s16: "Is the returned solution the cheapest?",
    s17: "Time",
    s18: "How many nodes does it generate?",
    s19: "Memory",
    s20: "How many nodes must it hold in RAM at once?",
    s21: "b — maximum branching factor",
    s22: "d — depth of the shallowest solution",
    s23: "m — maximum depth of the space",
  },
  ch4: {
    s1: "Uninformed search",
    s2: "“Blind” isn’t an insult here. It means the algorithm knows nothing beyond the problem definition. It can’t guess which node looks more promising; it can only ask whether a node is a goal. The five algorithms below are equally uninformed. What changes is their <em>expansion order</em>.",
    s3: "Breadth-first search",
    s4: "stop when goal is GENERATED",
    s5: "Always expand the <strong class='hl'>shallowest</strong> node. New arrivals join the back; whoever has waited longest goes first, just like a line at a coffee counter. The tree grows evenly, level by level. A small trick: test for the goal when you <em>generate</em> a child instead of waiting to pop it — that saves a whole level, and the last level is where the b-fold blowup lives.",
    s6: "COMPLETE",
    s7: "✓ with finite b",
    s8: "OPTIMAL",
    s9: "✓ with equal step costs",
    s10: "TIME",
    s11: "MEMORY",
    s12: "O(b<sup>d</sup>) — RAM gives out first",
    s13: "depth d",
    s14: "nodes",
    s15: "time",
    s16: "memory",
    s17: "1.1 seconds",
    s18: "3 hours",
    s19: "13 days",
    s20: "350 years",
    s21: "b = 10, speed 1 million nodes/second, 1 kB/node. The time column almost looks survivable; then you see the memory column 💀. RAM always gives out before the clock.",
    s22: "Exponential growth — why O(bᵈ) hurts",
    s23: "each level multiplies by b; the last holds almost everything",
    s24: "Uniform-cost search",
    s25: "stop when goal is REMOVED",
    s26: "BFS optimizes the <em>number of edges</em>, but fewer edges doesn’t mean cheaper: 2 flights can still cost more than 5 bus rides. UCS fixes that by expanding the node with the smallest <strong class='hl-cyan'>g(n) — actual cost from the start</strong>. I see two mistakes cost people marks over and over: <strong class='hl'>(1)</strong> UCS stops only when the goal is <em>removed</em> from the queue, not when it’s generated — a cheaper route might still be waiting; <strong class='hl'>(2)</strong> reaching a node by a cheaper route means you must <em>update</em> its parent and key (decrease-key). Don’t take my word for it: run UCS on the Lab graph in Manim Lab and watch both happen.",
    s27: "COMPLETE",
    s28: "✓ when step costs ≥ ε",
    s29: "OPTIMAL",
    s30: "✓ for any cost function",
    s31: "TIME",
    s32: "MEMORY",
    s33: "same as time",
    s34: "Sometimes worse than bᵈ: it crawls through countless cheap steps before trying a route that actually helps.",
    s35: "Depth-first search",
    s36: "stop when goal is GENERATED",
    s37: "DFS is the reckless one: expand the <strong class='hl'>deepest</strong> node, dive to the bottom of a branch, and backtrack only at a dead end. Don’t expect optimality — the first solution it grabs usually isn’t the shallowest. But it has something BFS envies: <strong class='hl-green'>low memory use</strong>. It keeps the current branch and unexpanded siblings, just O(bm); the backtracking version needs only O(m).",
    s38: "COMPLETE",
    s39: "✓ finite graph-search · ✗ tree-search",
    s40: "OPTIMAL",
    s41: "TIME",
    s42: "O(b<sup>m</sup>), m may be ≫ d",
    s43: "MEMORY",
    s44: "O(bm) — its reason to exist",
    s45: "TWO WAYS TO PREVENT LOOPS — TRACE THE ONE THE QUESTION SPECIFIES",
    s46: "I need to separate these, because homework Q2 and Q4b test exactly this distinction, and the two methods give <strong class='hl'>different expansion orders</strong>:",
    s47: "REMEMBER THE WHOLE MAP — EXPLORED SET",
    s48: "Visit a node and forbid revisiting it forever. This is the Python version in <a href='#codelab'>section 08</a>: <span class='code-inline'>visited</span> only grows, never shrinks. The price is remembering every state encountered.",
    s49: "REMEMBER ONLY THE CURRENT PATH — PATH CHECK",
    s50: "Forbid only nodes <em>on the path from the root to here</em>; forget a node when backtracking. That’s the <span class='code-inline'>del visited[child]</span> line in DLS. Memory is just O(m).",
    s51: "Path checking still prevents infinite cycling in a finite space, but lets you reach the same node through different branches. It <strong class='hl-mid'>still generates redundant paths</strong>, which an explored set eliminates. If the state space itself is infinite, though, don’t expect a rescue: either version can get lost forever.",
    s52: "Depth limits → Iterative deepening",
    s53: "DFS + a ceiling ℓ = 0, 1, 2, …",
    s54: "<strong class='hl'>DLS</strong> stops DFS wandering forever by imposing a ceiling: no deeper than ℓ. Hit the ceiling and return <em>cutoff</em> — keep that distinct from <em>failure</em>, which means there really are no paths left. Choose ℓ using problem knowledge: Romania has 20 cities, any pair is at most 9 steps apart, so ℓ = 9 is enough. Usually, though, you <em>don’t know</em> ℓ in advance. So <strong class='hl'>IDS</strong> does something that sounds ridiculous: run DLS with ℓ = 0, then 1, then 2… until it reaches the goal.<br/><br/>All those shallow levels generated again and again sound wasteful. Here’s where exponential growth helps: the last level holds almost all the nodes; the levels above barely add up to anything. With b = 10, d = 5, IDS generates 123,450 nodes versus BFS’s 111,110, just <strong class='hl-green'>~11%</strong> extra. For that 11%, you get DFS’s O(bd) memory plus BFS’s completeness and optimality. A good deal.",
    s55: "COMPLETE",
    s56: "✓ with finite b",
    s57: "OPTIMAL",
    s58: "✓ with equal step costs",
    s59: "TIME",
    s60: "MEMORY",
    s61: "THOSE FOUR BOXES DESCRIBE IDS — WHAT ABOUT DLS ALONE?",
    s62: "Don’t give it someone else’s results. DLS alone <strong class='hl-red'>can fail on both counts</strong>, in opposite ways depending on where you put the ceiling relative to solution depth d:",
    s63: "COMPLETE",
    s64: "OPTIMAL",
    s65: "TIME",
    s66: "MEMORY",
    s67: "Put the ceiling below the solution (ℓ &lt; d), and the solution is just out of reach: <em>missed</em>. Put it above the solution (ℓ &gt; d), and DLS still dives like DFS, so it may grab a deep solution before seeing a shallow one: <em>optimality lost</em>. Time and memory stay exactly as in DFS, with ℓ replacing m. Look at it the other way: <strong class='hl-mid'>DFS is DLS with ℓ = ∞</strong>.",
    s68: "If you don’t know what to pick, pick IDS: it’s the default for large spaces with unknown solution depth. Select IDS in the Lab and watch the ℓ label rise in the canvas corner; the behavior becomes obvious.",
    s69: "A simple, remarkably effective idea: search from both ends and meet in the middle. b<sup>d/2</sup> + b<sup>d/2</sup> ≪ b<sup>d</sup> — with b = 10, d = 6, that’s 2,000 nodes instead of 1,000,000. The price: you must know how to move <em>backward</em> from the goal, and the goal must be explicit. A goal such as “checkmate” won’t do: which checkmate position would you start from?",
  },
  lab: {
    s1: "Manim Lab — watch 7 algorithms step by step",
    s2: "Watching one run beats reading ten times. Pick an algorithm and press <strong class='hl'>Run</strong>, or use <strong class='hl'>Next / Back</strong> to inspect each step. Colors follow the convention used throughout the page: <span class='hl-cyan'>blue — frontier</span> · <span class='hl-yellow'>yellow — expanding</span> · <span style='color:var(--muted-2)'>gray — explored</span> · <span class='hl-green'>green — path</span> · <span class='hl-purple'>purple — a cheaper route just found</span>.",
    s3: "Here are three experiments I want you to try now: (1) on Romania, run GBFS and then A* — greedy gives 450 km, A* gives 418 km; work out where those 32 km went; (2) run HC on the same preset and watch it get stuck in Timișoara; (3) switch to the Lab graph and compare BFS (cost 9) with UCS (cost 8) to see “shallowest ≠ cheapest” for yourself.",
  },
  ch5: {
    s1: "Informed search",
    s2: "So far, the algorithms have been feeling their way through the dark. Now I’ll give them a compass 🎯: one number for <em>each node</em>, <strong class='hl-yellow'>h(n), the estimated cost from n to the goal</strong>. That number isn’t part of the problem definition; it comes from <em>outside</em> knowledge about the problem. On a map, it can be straight-line distance (SLD). Keep one convention in mind: h(goal) = 0.",
    s3: "h(Făgăraș) = 176",
    s4: "stop when goal is GENERATED",
    s5: "A compass in hand, just head toward the goal — that’s GBFS’s thinking. It always expands the node that <strong class='hl'>looks closest</strong>. And it is fast: Arad → Sibiu → Făgăraș → București, just 3 nodes expanded. But that route is 450 km, while the optimal route through Râmnicu–Pitești is only <strong class='hl-green'>418 km</strong>. GBFS sees only the future (h), forgetting the past (g), so it rushes down a route that <em>looks</em> close but takes a long way to <em>travel</em>. Worse, tree-search can bounce forever between two cities (Iași ↔ Neamț), perfectly unembarrassed.",
    s6: "COMPLETE",
    s7: "✗ tree · ✓ finite graph",
    s8: "OPTIMAL",
    s9: "TIME",
    s10: "MEMORY",
    s11: "O(b<sup>m</sup>) — good h cuts sharply",
    s12: "Balancing past and future",
    s13: "stop when goal is REMOVED",
    s14: "UCS remembers the past; GBFS guesses the future. Each is missing half the picture. A* adds the halves together:<br/><br/><span style='font-family:var(--font-serif);font-style:italic;font-size:1.35em'><span class='hl-text'>f(n)</span> = <span class='hl-cyan'>g(n)</span> + <span class='hl-yellow'>h(n)</span></span> — the estimated cost of the cheapest solution THROUGH n.<br/><br/>The implementation is almost a copy of UCS: the same priority queue, decrease-key, and “stop only when the goal is removed” rule. Just change the sorting key from g to f. But A* depends on the quality of h, and h must meet a condition:",
    s15: "COMPLETE",
    s16: "OPTIMAL",
    s17: "TIME",
    s18: "exponential in the error of h",
    s19: "MEMORY",
    s20: "O(b<sup>d</sup>) — the weak spot",
    s21: "ADMISSIBLE — never overestimates",
    s22: "h(n) ≤ h*(n) — the true cost",
    s23: "A well-behaved heuristic never exaggerates. Optimism is allowed; pessimism isn’t. SLD is admissible because no route can be shorter than the straight line. Just ONE node overestimating removes the guarantee. → A* <strong class='hl-mid'>tree-search is optimal</strong>.",
    s24: "CONSISTENT — the triangle inequality",
    s25: "A stronger condition: the estimate at a node can’t exceed the cost of one step plus the estimate from the next node. The lovely consequence is that f never decreases along a path, so a node’s first removal already gives its optimal cost; no need to revisit it. → A* <strong class='hl-mid'>graph-search is optimal</strong>. Consistent ⇒ admissible, but not the reverse.",
    s26: "Which nodes A* expands — f-contours",
    s27: "a sharper h focuses the spread toward the goal",
    s28: "circles around S, spreading evenly in every direction",
    s29: "A* — sharp h",
    s30: "contours stretch toward G, hugging the optimal path",
    s31: "Because f never decreases along a path, A* expands nodes in increasing f order, filling one <strong class='hl-yellow'>f-contour</strong> after another like rising water. Call the optimal solution cost C*. Two consequences I find especially useful: A* <strong class='hl'>expands every node with f(n) &lt; C*</strong> and <strong class='hl'>never expands a node with f(n) &gt; C*</strong>. Those nodes are cut away while the solution stays optimal. Nodes exactly on f(n) = C* depend on tie-breaking. This is your tool for <a href='#hw'>exercise 3</a>: to find whether a path could be returned, calculate f instead of guessing.<br/><br/>Back to Romania: draw contours at <strong class='hl-mid'>380 · 400 · 420</strong> around Arad, and the 420 contour just reaches București. Of course it does: the optimal solution costs <strong class='hl-green'>418</strong>. A* doesn’t touch any city beyond that contour.<br/><br/>This is where h becomes speed. With h = 0, f = g, so the contours are concentric circles around S: A* becomes UCS, spreading in every direction, including away from the goal. As h approaches the true cost, the contours stretch toward G and hug the optimal path, enclosing fewer nodes. Run UCS and A* on Romania in the Lab and count their gray nodes. That difference is what the picture shows.",
    s32: "Another title for A*: it’s <strong style='color:var(--text-2)'>optimally efficient</strong> — with the same consistent h, no optimal algorithm expands fewer nodes. Sounds perfect, but RAM remains its Achilles’ heel. When memory runs out, look toward IDA*, RBFS, and SMA*. Those are beyond this session.",
    s33: "HEURISTIC DOMINANCE — MEASURING SHARPNESS WITH b*",
    s34: "A rule for choosing a heuristic: if h₂(n) ≥ h₁(n) for every n, and both are admissible, h₂ <em>dominates</em> h₁, and A*(h₂) never needs to expand more nodes. Get as close to the true cost as you can without going over. Try the 8-puzzle: h₁ counts misplaced tiles; h₂ sums Manhattan distances.",
    s35: "But <em>how much</em> fewer? Raw node counts don’t compare problems of different depths: 227 nodes at d = 12 versus 39,135 at d = 24 — which is better? The comparison uses one number: the <strong class='hl-yellow'>effective branching factor b*</strong>. A* expands N nodes and finds a solution at depth d. Now ask: if a <em>uniform</em> tree of depth d held exactly N + 1 nodes, how many children would each node have?",
    s36: "For example, A* finds a depth-5 solution using just 52 nodes → <strong class='hl'>b* = 1.92</strong>. It slips toward the goal as if each node had fewer than 2 branches, even though the real tree is much bushier. b* varies between instances, but stays fairly stable on sufficiently difficult problems, making it useful for grading heuristics. The rule fits in a sentence: <strong class='hl-green'>the closer b* is to 1, the better</strong>. b* = 1 means going straight to the solution without expanding spare nodes. A heuristic that pushes b* close to 1 makes large problems affordable.",
    s37: "NODES GENERATED",
    s38: "Averages over 100 instances of the 8-puzzle at each depth d. “–” means the original table leaves IDS blank from d = 14 onward; there’s no measurement, and I won’t invent one for you. The 3.6 million at d = 12 is frightening enough to extrapolate from.",
    s39: "WHERE DO HEURISTICS COME FROM?",
    s40: "<strong class='hl-yellow'>1 · Relax the problem.</strong> My favorite trick: drop some rules. In the 8-puzzle, let tiles fly straight to their destinations → h₁; let tiles slide through each other → h₂. An easier problem can’t have a more expensive solution, so these heuristics are <em>automatically</em> admissible and consistent. No separate proof needed.",
    s41: "<strong class='hl-yellow'>2 · Take the max.</strong> Several admissible heuristics and no obvious winner? Use them all: h = max(h₁, …, hₖ). The maximum of well-behaved heuristics still behaves itself.",
    s42: "<strong class='hl-yellow'>3 · Pattern database.</strong> Solve subproblems beforehand — just the 4 corner tiles, for example — and store exact costs for lookup. Trade memory for a sharper h.",
    s43: "<strong class='hl-yellow'>4 · Learn from experience.</strong> Solve many instances, record the results, and fit h from state features using regression. Yes: machine learning can build heuristics for search. See you in Session 10.",
  },
  ch6: {
    s1: "Hill climbing — the Lab’s outsider",
    s2: "⛰️ Lab 1 includes an algorithm unlike the rest: hill climbing. No queue, no backtracking, no history — it holds exactly <strong class='hl'>one</strong> current node and moves to a neighbor with a smaller h. The <strong class='hl'>first-choice</strong> version is even lazier: take the first improvement without checking the rest. O(1) memory, lightning fast, and oblivious to local optima.",
    s3: "Why hill climbing gets stuck — the state-space landscape",
    s4: "the ball can climb, but never agrees to descend",
    s5: "THREE WAYS TO GET STUCK",
    s6: "local optimum",
    s7: "flat plateau",
    s8: "ridge",
    s9: "— watch it happen by running <strong class='hl-mid'>HC on Romania</strong> in the <a href='#lab'>Lab</a>: it happily climbs Arad → Timișoara as h drops from 366 to 329, then stands there with nowhere uphill to go. Output: -1.",
    s10: "Don’t dismiss it yet. Session 4 (Local Search) tackles exactly this problem with random restarts, simulated annealing, local beam search, and genetic algorithms. Hill climbing is the starting point of a powerful family.",
  },
  ch7: {
    s1: "Seven algorithms on one sheet",
    s2: "ALGORITHM",
    s3: "COMPLETE",
    s4: "OPTIMAL",
    s5: "TIME",
    s6: "MEMORY",
    s7: "USE WHEN",
    s8: "shallow solution, equal costs, plenty of RAM",
    s9: "tight RAM, deep finite space",
    s10: "same as time",
    s11: "unequal step costs, optimality required",
    s12: "repeated DLS, ℓ↑",
    s13: "default for unknown d and large spaces",
    s14: "speed matters more than optimality",
    s15: "exponential in h error",
    s16: "optimality required, good h available",
    s17: "none",
    s18: "depends on the landscape",
    s19: "huge space, a “good enough” solution will do",
    s20: "¹ finite b (UCS also needs step costs ≥ ε &gt; 0) · ² equal step costs · ³ graph-search in a finite space · ⁴ admissible h (tree) / consistent h (graph)",
  },
  codelab: {
    s1: "Code Lab — implement all 7 algorithms",
    s2: "⌨️ The fun part: writing code. The assignment asks for Python and <em>your own search implementations</em>. Helper libraries are fine; a library that solves the search for you isn’t. Read <span class='code-inline'>input.txt</span>, write <span class='code-inline'>output.txt</span>, and measure runtime and peak memory for each algorithm. This is an <strong class='hl'>individual</strong> assignment over about 3 weeks. Marks: 7 algorithms × 10% · ≥ 5 test cases 10% · report 20%. I’ve put the code framework below; you fill in the core.",
    s3: "THREE CONVENTIONS THAT CHANGE THE OUTPUT — PLEASE READ THESE",
    s4: "BFS · DFS · GBFS stop when the goal is <strong class='hl-cyan'>GENERATED</strong>",
    s5: "UCS · A* stop when the goal is <strong class='hl-yellow'>REMOVED</strong>",
    s6: "HC stuck → no path → print <strong class='hl-red'>-1</strong>",
    s7: "INPUT.TXT — the graph may be DIRECTED or undirected",
    s8: "line 1: node count · line 2: start goal · next: adjacency matrix (weights, 0 = no edge) · last line: heuristic for each node",
    s9: "OUTPUT.TXT — path or -1, with time and memory",
    s10: "this is the “Lab 1 · 6 nodes” preset from Manim Lab above — compare your code’s output step by step",
    s11: "SHARED BY ALL 7 — TRACE PARENT POINTERS BACK",
    s12: "MAIN.PY — READ INPUT, RUN 7 ALGORITHMS, MEASURE TIME + MEMORY",
    s13: "time.perf_counter() + tracemalloc — exactly the two requirements: “high-resolution timer” and “peak memory”",
    s14: "5 TEST CASE IDEAS WITH DIFFERENT PROPERTIES — MARKS WORTH PICKING UP",
    s15: "<strong class='hl-mid'>1 ·</strong> The sample 6-node graph above: Manim Lab provides reference results to catch your first bugs.",
    s16: "<strong class='hl-mid'>2 ·</strong> No solution: isolate the goal. All 7 must print -1 and exit cleanly. Any that hang have a loop bug.",
    s17: "<strong class='hl-mid'>3 ·</strong> A DIRECTED graph (asymmetric matrix): exposes neighbor-traversal bugs immediately, especially scanning a column instead of a row.",
    s18: "<strong class='hl-mid'>4 ·</strong> Deliberately supply a NON-admissible heuristic so A* returns a suboptimal path. That isn’t a bug; it matches the theory. Explaining it in your report earns useful marks.",
    s19: "<strong class='hl-mid'>5 ·</strong> A large random graph (n ≥ 500). Every algorithm finishes a 6-node graph in 0.0001 seconds; increase the size until time and memory differences show up.",
  },
  quiz: {
    s1: "Quiz — find out what you <em class='hl-cyan'>really</em> understand",
    s2: "eight questions · problem formulation, frontier, heuristics, A*",
    s3: "Reading straight through and feeling you understood everything is wonderfully familiar — and wonderfully misleading. These eight questions aren’t here to judge you. They expose what you merely <em>recognize</em> without understanding. If you get one wrong, read the explanation right away. Finish these before moving to the exercises.",
  },
  hw: {
    s1: "Homework — Session 3",
    s2: "four questions · formulation, hand traces, admissible &amp; consistent, maze",
    s3: "QUESTION 1 — TWO FRIENDS ON THE ROMANIA MAP",
    s4: "On each turn, both friends move <em>simultaneously</em> to adjacent cities. A turn takes the longer traveler’s d(i, j); the earlier arrival waits. The goal is to meet as soon as possible. <strong class='hl'>(a)</strong> Give the full formulation (state, actions, transition, goal test, cost). <strong class='hl'>(b)</strong> D(i, j) is the straight-line distance between them. Which heuristic is admissible: D(i, j) · 2·D(i, j) · D(i, j)/2? <strong class='hl'>(c)</strong> Can a fully connected map have no solution? <strong class='hl'>(d)</strong> Is there a map on which every solution forces one friend to revisit a city?",
    s5: "<a href='#ch2'>Review: section 02 — 5 components</a> · <a href='#ch5'>section 05 — admissible</a>",
    s6: "QUESTION 2 — HAND-TRACE 6 ALGORITHMS",
    s7: "A graph from S → G, with h under node names and costs on edges. For BFS (example provided) · UCS · DFS (remembering nodes on the current path) · IDS · GBFS · A*, list the <em>expansion order</em>, <em>solution path</em>, and <em>final frontier</em>. Break ties alphabetically; “expand” means remove FROM the frontier. <strong class='hl'>(g)</strong> Is h admissible? <strong class='hl'>(h)</strong> Is it consistent?",
    s8: "<a href='#lab'>Practice this exact skill in Manim Lab</a>",
    s9: "QUESTION 3 — WHICH PATHS COULD BE RETURNED?",
    s10: "A is the start, G the goal; h₁ is consistent, h₂ isn’t. <strong class='hl'>(1)</strong> For DFS · BFS · UCS · A*(h₁) · A*(h₂), mark the paths that <em>could</em> be returned under some tie-breaking order: A-B-D-G, A-C-D-G, A-B-C-D-F-G. <strong class='hl'>(2)</strong> The h₃ table is fixed except for h₃(B). Find the values making h₃ admissible; making h₃ consistent; and making A* expand exactly A, C, B, D.",
    s11: "<a href='#ch5'>Review: section 05 — admissible vs consistent</a>",
    s12: "QUESTION 4 — MAZE s → g",
    s13: "Solid walls cannot be crossed. List explored cells as &lt;b₁, b₂, …&gt; for: <strong class='hl'>(a)</strong> BFS; <strong class='hl'>(b)</strong> DFS with loop prevention and operator order up, left, right, down; <strong class='hl'>(c)</strong> GBFS using Manhattan distance (|Δx| + |Δy|); <strong class='hl'>(d)</strong> A* with the same heuristic.",
    s14: "<a href='#ch4'>Review: section 04 — expansion order</a>",
    s15: "I can write the 5 components of a problem — try Q1, the two friends on the map, now.",
    s16: "I can distinguish node ↔ state, frontier ↔ explored, and tree-search ↔ graph-search.",
    s17: "I can explain why BFS/DFS/GBFS stop on goal GENERATION, while UCS/A* wait for REMOVAL.",
    s18: "I can hand-trace BFS, UCS, and A* on the Lab’s 6-node graph and compare with Manim Lab.",
    s19: "I can prove that a heuristic is admissible / consistent (Q2g–h, Q3).",
    s20: "I can implement all 7 algorithms, run input.txt → output.txt, and measure time and memory.",
    s21: "I can create ≥ 5 test cases with different properties: no solution, directed graph, stuck HC, large graph…",
    s22: "Next: <strong class='hl'>Session 4 — Local Search</strong>, where simulated annealing, local beam search, and genetic algorithms tackle hill climbing’s tendency to get stuck. You’ll also see why “good enough” sometimes matters more than “optimal” 🙂",
    s23: "← Back to Roadmap",
  },
  searchlab: {
    s1: "hill climbing",
    s2: "FRONTIER — FIFO queue (left = next out)",
    s3: "FRONTIER — stack (right = top, next out)",
    s4: "FRONTIER — priority queue by g (sorted)",
    s5: "CURRENT PATH (DLS backtracking)",
    s6: "FRONTIER — priority queue by h",
    s7: "FRONTIER — priority queue by f = g + h",
    s8: "FRONTIER — none (one current node only)",
    s9: "Lab 1 · 6 nodes",
    s10: "Romania · 10 nodes",
    s11: "Stuck at a local optimum → output: -1",
    s12: "No solution → output: -1",
    s13: "⟲ Reset",
    s14: "◀ Back",
    s15: "❚❚ Pause",
    s16: "▶ Run",
    s17: "Next ▶",
    s18: "STUCK",
  },
  f_codelab: {
    s1: "WORKBENCH — PICK AN ALGORITHM, READ THE PSEUDOCODE, THEN INSPECT PYTHON",
    pythonHeading: "PYTHON — LAB 1 FRAMEWORK",
  },
  scenes: {
    s1: " nodes",
    s2: "b = 10, d = 12 → 10¹² nodes",
    s3: "≈ 13 days at 1 million nodes/second · ≈ 1 petabyte of memory",
    s4: "state space →",
    s5: "↑ objective value (−h)",
    s6: "global optimum",
    s7: "STUCK — local optimum",
    s8: "reaching the higher peak means accepting a DOWNHILL step",
  },
} satisfies typeof VI;
