import type { VI } from './lesson03.text.vi';

export const EN = {
  hero: {
    navMath: "MATH PRIMER",
    nav01: "01 Agent",
    nav02: "02 Five components",
    nav03: "03 The frame",
    navQuiz: "04 Quiz",
    navHw: "05 Exercises",
    cover: "Cover",
    badge: "SESSION 3",
    navTitle: "Problem formulation",
    titleA: "Stating",
    titleB: "a search",
    titleC: "problem",
    lead: "🧭 Before a machine can find anything, you have to tell it what it's looking for — and that's the hard part. Same 8-queens puzzle: state it naively and you get 1.8×10¹⁴ sequences to try; state it a little more cleverly and you get <strong class='hl-green'>2,057</strong>. Same algorithm, same machine, different wording of the problem. This session is about writing that wording.",
    chipState: "state — how the world stands",
    chipAction: "actions — where you can go",
    chipSections: "5 sections",
    chipHours: "≈ 2 hours",
  },
  ch1: {
    s1: "Problem-solving agents",
    s2: "Session 2 left you with reflex agents: see something, look it up, act. Now you’re in Arad and need to reach Bucharest in time for a flight. The right move <em>today</em> depends on a whole sequence of moves <em>tomorrow</em> — good luck squeezing that into a lookup table. The agent has to <strong class='hl'>think ahead</strong>: try action sequences in its model and choose one that reaches the goal. That’s a problem-solving agent, and its tool is <strong class='hl-cyan'>search</strong>.",
    s3: "STEP 1 · GOAL FORMULATION",
    s4: "Choose a goal",
    s5: "Decide which state you want the world to reach: <span class='code-inline'>In(Bucharest)</span>. Once you have a goal, countless irrelevant choices fall away. That’s what a goal is for.",
    s6: "STEP 2 · PROBLEM FORMULATION",
    s7: "Build a model",
    s8: "Describe states and actions with enough detail to make a solution <em>possible</em>, and enough abstraction to make finding it <em>manageable</em>. The weather, the song playing, your travel companion — leave them out; they’re irrelevant here.",
    s9: "STEP 3 · SEARCH",
    s10: "Search",
    s11: "This is the machine’s job: try action sequences in the <em>model</em> until one reaches the goal. That sequence is a <strong class='hl-mid'>solution</strong>.",
    s12: "STEP 4 · EXECUTION",
    s13: "Execute",
    s14: "Carry out the solution, one action at a time. This is <em>open-loop</em> execution: you can follow the plan without checking again, because the whole route has already been worked out.",
    s15: "ASSUMPTIONS FOR THIS SESSION",
    s16: "Fully observable",
    s17: "Discrete",
    s18: "Known model",
    s19: "Deterministic",
    s20: "→ these four assumptions let the solution be a <em>fixed</em> action sequence. Messier worlds come later.",
  },
  ch2: {
    s1: "A search problem has exactly 5 components",
    s2: "Good news: every problem — maps, sliding puzzles, vacuum robots, n queens — fits the same set of 5 components. Write those 5 down and you’re halfway there; the rest is choosing an algorithm. Q1 of Quiz 03 tests exactly this skill, so don’t skim it.",
    s3: "The starting state.",
    s4: "The actions available at s.",
    s5: "RESULT(s, a): the state reached by doing a at s.",
    s6: "Checks whether a state is a goal — explicitly, or by a property (checkmate!).",
    s7: "The sum of step costs c(s, a, s′) ≥ 0 along the path.",
    s8: "total kilometers traveled",
    s9: "A few names to keep handy: a <strong class='hl'>solution</strong> is a path from the initial state to a goal; an <strong class='hl-green'>optimal solution</strong> is the cheapest such path; the <em>state space</em> is the graph of all states connected by actions.",
    s10: "STATE-SPACE SIZE — A FEW NUMBERS",
    s11: "8-puzzle: 9!/2 = 181,440 states",
    s12: "Look at these numbers before taking my word for it: a naive model of 8 queens gives 64·63···57 ≈ 1.8×10¹⁴ sequences. A slightly smarter model — place a queen in the leftmost empty column, allowing no attacks — leaves <strong class='hl-green'>2,057</strong>. Same problem, 11 orders of magnitude apart. <em>Your model determines whether you can solve the problem at all.</em>",
    s13: "STATE SPACE ≠ SEARCH TREE",
    s14: "This distinction deserves a pause: Romania has exactly 20 cities, but its search tree can be <strong class='hl-red'>infinite</strong>, because nothing stops you going Arad → Sibiu → Arad → Sibiu → … forever. One state can occur in many different tree nodes. Handling those loops is precisely the boundary between tree-search and graph-search in section <a href='#ch3'>03</a>.",
  },
  ch3: {
    s1: "One framework, seven algorithms",
    s2: "This is my favorite section: seven impressive-sounding algorithms become one idea. They all use <em>the same loop</em>, changing just one decision: <strong class='hl-yellow'>which frontier node comes out first?</strong> A FIFO queue → BFS. A LIFO stack of plates → DFS. Cheapest g → UCS. Closest-looking h → GBFS. Balance both with f → A*. Remember that decision and you’ve got the backbone of the session.",
    s3: "TREE-SEARCH — may loop forever",
    s4: "<pre class='codeblock' style='background:transparent'>frontier ← {root node}\n  loop:\n    if frontier is empty: return <span style='color:#FC6255'>failure</span>\n    node ← POP(frontier)  <span style='color:#7A8399;font-style:italic'>▷ strategy = how this node is chosen</span>\n    if GOAL-TEST(node): return <span style='color:#83C167'>SOLUTION(node)</span>\n    add the children of node to frontier</pre>",
    s5: "GRAPH-SEARCH — remembers expanded states",
    s6: "<pre class='codeblock' style='background:transparent'>frontier ← {root node}; <span style='color:#F4D345'>explored ← ∅</span>\n  loop:\n    if frontier is empty: return <span style='color:#FC6255'>failure</span>\n    node ← POP(frontier)\n    if GOAL-TEST(node): return <span style='color:#83C167'>SOLUTION(node)</span>\n    <span style='color:#F4D345'>add node.STATE to explored</span>\n    add children to frontier <span style='color:#F4D345'>if their state\n    is not in explored ∪ frontier</span> <span style='color:#7A8399;font-style:italic'>▷ prevent loops</span></pre>",
    s7: "NODE ≠ STATE",
    s8: "They sound interchangeable, but they aren’t: several <em>nodes</em> can hold the same <em>state</em> — reaching Sibiu by three routes gives three nodes. That innocent-looking <strong class='hl-mid'>PARENT</strong> pointer is what lets you <em>trace back</em> the path. That’s the <span class='code-inline'>reconstruct()</span> function you’ll write in the Lab.",
    s9: "AN OIL SLICK",
    s10: "Picture graph-search as oil spreading across water 🌊. It divides space into 3 regions: <span style='color:var(--muted-2)'>explored (already covered)</span> · <span class='hl-cyan'>frontier (the advancing edge)</span> · untouched space. Every path from the start to the outside <em>must</em> cross that edge. Choosing which edge node to take next determines everything.",
    s11: "“An algorithm that forgets its history is doomed to repeat it.”",
    s12: "EVALUATION FRAMEWORK — FOR THE NEXT 4 SESSIONS",
    s13: "Complete?",
    s14: "If a solution exists, will it definitely find one?",
    s15: "Optimal?",
    s16: "Is the returned solution the cheapest?",
    s17: "Time",
    s18: "How many nodes does it generate?",
    s19: "Memory",
    s20: "How many nodes must it hold in RAM at once?",
    s21: "b — maximum branching factor",
    s22: "d — depth of the shallowest solution",
    s23: "m — maximum depth of the space",
  },
  quiz: {
    s1: "Quiz — find out what you <em class='hl-cyan'>really</em> understand",
    s2: "five questions · abstraction, the five components, node ≠ state, redundant paths",
    s3: "Sections 01 to 03 read very smoothly, because there's hardly a formula in them. That's exactly where it's easy to fool yourself: understanding a definition and being able to use it are two different things. These five questions aren't here to judge you — they expose where you merely <em>recognize</em> something. Get one wrong, read the explanation right there — don't save it for later.",
  },
  hw: {
    s1: "Homework — Session 3",
    s2: "two questions · a full formulation, two ways to state a problem",
    s3: "QUESTION 1 — TWO FRIENDS ON THE ROMANIA MAP",
    s4: "Each turn both friends move <em>simultaneously</em> to an adjacent city; the turn takes d(i, j) of whoever travels longer — whoever arrives first has to wait. Goal: meet as fast as possible. <strong class='hl'>(a)</strong> Write the full formulation (state, actions, transition, goal test, cost). <strong class='hl'>(b)</strong> Can a fully connected map still have no solution? <strong class='hl'>(c)</strong> Is there a map where every solution forces one of them to revisit a city?",
    s5: "<a href='#ch2'>Review: section 02 — the 5 components</a>",
    s6: "QUESTION 2 — ONE PUZZLE, TWO WAYS TO STATE IT",
    s7: "Take 8-queens. <strong class='hl'>(a)</strong> Write the <em>incremental</em> formulation: empty board, each action places one more queen. <strong class='hl'>(b)</strong> Write the <em>complete-state</em> formulation: all 8 queens already on the board, each action moves one. <strong class='hl'>(c)</strong> In (b), does path cost mean anything — and why? <strong class='hl'>(d)</strong> Forbidding a queen on an attacked square shrinks the space from 1.8×10¹⁴ to 2,057. Which of the five components changed?",
    s8: "<a href='#ch2'>Review: section 02 — state-space size</a>",
    s9: "I can write the 5 components of any problem handed to me — try it right now on Q1, the two friends.",
    s10: "I can tell a node from a state, and say why two nodes holding the same state have different g(n).",
    s11: "I can explain why the Romania search tree is infinite when there are only 20 cities.",
    s12: "I can say what a sound abstraction is, versus one that drops something the action needs to be doable.",
    s13: "Next up: <strong class='hl'>Session 4 — Uninformed Search</strong>. The problem is stated, now the machine gets to run — and you'll see all five algorithms turn out to be one loop with different machinery inside.",
    s14: "← Back to the roadmap",
  },
} satisfies typeof VI;
