/*
 * Chữ tiếng Việt của bài b3 — Phát biểu bài toán tìm kiếm. NGUỒN SỰ THẬT.
 *
 * Cắt ra từ bundle Buổi 3 cũ khi buổi đó tách thành Buổi 3 · 4 · 5. Chữ dùng chung cho
 * Manim Lab và Code Lab nằm ở `features/search-lab/lab.text.vi.ts`, không lặp ở đây.
 * Bản EN khai `satisfies typeof VI` nên thiếu hay thừa một khóa là lỗi tsc.
 */
export const VI = {
  hero: {
    navMath: "TOÁN NỀN",
    nav01: "01 Agent",
    nav02: "02 Năm thành phần",
    nav03: "03 Khung",
    navQuiz: "04 Quiz",
    navHw: "05 Bài tập",
    cover: "Bìa",
    badge: "BUỔI 3",
    navTitle: "Phát biểu bài toán",
    titleA: "Phát biểu",
    titleB: "bài toán",
    titleC: "tìm kiếm",
    lead: "🧭 Trước khi máy tìm được gì, bạn phải nói cho nó biết đang tìm cái gì — và phần đó mới khó. Cùng bài 8 quân hậu: mô hình kiểu ngây thơ ra 1,8×10¹⁴ chuỗi phải thử, mô hình khôn hơn một chút còn <strong class='hl-green'>2.057</strong>. Không đổi thuật toán, không đổi máy, chỉ đổi cách viết đề. Buổi này mình học cách viết cái đề đó.",
    chipState: "trạng thái — thế giới đang thế nào",
    chipAction: "hành động — đi được những đâu",
    chipSections: "5 mục học",
    chipHours: "≈ 2 giờ",
  },
  ch1: {
    s1: "Agent giải quyết vấn đề",
    s2: "Buổi 2 mình dừng ở agent phản xạ: thấy gì làm nấy, tra bảng là xong. Nhưng thử tình huống này xem — bạn đang ở Arad, phải có mặt ở Bucharest cho kịp chuyến bay. Nước đi đúng của <em>hôm nay</em> phụ thuộc vào cả chuỗi bước <em>ngày mai</em>, tra bảng kiểu gì cho nổi? Agent buộc phải <strong class='hl'>nghĩ trước</strong>: thử các chuỗi hành động trong đầu, chọn chuỗi nào dẫn tới đích. Nó có tên là problem-solving agent, và món võ của nó là <strong class='hl-cyan'>tìm kiếm</strong>.",
    s3: "BƯỚC 1 · GOAL FORMULATION",
    s4: "Chốt mục tiêu",
    s5: "Chốt xem bạn muốn thế giới ở trạng thái nào: <span class='code-inline'>In(Bucharest)</span>. Có mục tiêu rồi thì vô số lựa chọn vô nghĩa tự động rụng hết — đó chính là công dụng của nó.",
    s6: "BƯỚC 2 · PROBLEM FORMULATION",
    s7: "Mô hình hóa",
    s8: "Chọn cách mô tả trạng thái và hành động sao cho đủ chi tiết để giải <em>được</em>, mà đủ trừu tượng để giải <em>nổi</em>. Thời tiết, bài hát đang bật, bạn đi cùng là ai — bỏ hết, không liên quan.",
    s9: "BƯỚC 3 · SEARCH",
    s10: "Tìm kiếm",
    s11: "Đây là phần máy làm: thử các chuỗi hành động trên <em>mô hình</em> cho tới khi vớ được chuỗi chạm đích. Chuỗi đó gọi là <strong class='hl-mid'>nghiệm (solution)</strong>.",
    s12: "BƯỚC 4 · EXECUTION",
    s13: "Thực thi",
    s14: "Cầm nghiệm đi thi hành, từng hành động một. Kiểu <em>vòng hở</em> (open-loop) — nhắm mắt đi cũng tới, vì đường đã tính sẵn hết rồi.",
    s15: "GIẢ ĐỊNH CỦA BUỔI NÀY",
    s16: "Quan sát đầy đủ",
    s17: "Rời rạc",
    s18: "Biết trước mô hình",
    s19: "Tất định",
    s20: "→ nhờ bốn giả định này mà nghiệm chỉ là một chuỗi hành động <em>cố định</em>. Thế giới lầy lội hơn thì để dành các buổi sau.",
  },
  ch2: {
    s1: "Một bài toán tìm kiếm gồm đúng 5 thứ",
    s2: "Tin vui: mọi đề bài — bản đồ, trò xếp hình, robot hút bụi, n quân hậu — đều nén được về đúng cùng một bộ 5 thứ. Viết ra được 5 thứ này là bạn giải xong một nửa bài rồi, phần còn lại chỉ là chọn thuật toán. Q1 của Quiz 03 kiểm tra đúng kỹ năng này, nên đừng đọc lướt.",
    s3: "Trạng thái xuất phát.",
    s4: "Các hành động khả dụng tại s.",
    s5: "RESULT(s, a): làm a tại s thì ra trạng thái nào.",
    s6: "Kiểm tra một trạng thái có phải đích — tường minh, hoặc theo thuộc tính (chiếu hết!).",
    s7: "Tổng chi phí bước c(s, a, s′) ≥ 0 dọc đường đi.",
    s8: "tổng km đã lăn bánh",
    s9: "Gọi tên cho gọn: <strong class='hl'>nghiệm</strong> là một đường đi từ trạng thái đầu tới đích; <strong class='hl-green'>nghiệm tối ưu</strong> là cái rẻ nhất trong đám đó; còn <em>không gian trạng thái</em> là đồ thị gồm mọi trạng thái nối với nhau bằng hành động.",
    s10: "KÍCH THƯỚC KHÔNG GIAN — VÀI CON SỐ",
    s11: "8-puzzle: 9!/2 = 181.440 trạng thái",
    s12: "Nhìn con số này rồi hãy tin tôi: 8 quân hậu mô hình kiểu ngây thơ ra 64·63···57 ≈ 1,8×10¹⁴ chuỗi. Mô hình khôn hơn một chút (đặt hậu vào cột trái nhất còn trống, không cho ăn nhau) — còn <strong class='hl-green'>2.057</strong>. Cùng một bài toán, khác nhau 11 chữ số. <em>Bạn mô hình hóa thế nào quyết định bài có giải nổi hay không.</em>",
    s13: "KHÔNG GIAN TRẠNG THÁI ≠ CÂY TÌM KIẾM",
    s14: "Chỗ này dễ nhầm nên nói kỹ: Romania có đúng 20 thành phố, nhưng cây tìm kiếm của nó có thể <strong class='hl-red'>vô hạn</strong> — vì chẳng có gì cấm bạn đi Arad → Sibiu → Arad → Sibiu → … tới già. Một trạng thái có thể nằm ở rất nhiều nút khác nhau trên cây. Cách xử lý mấy vòng lặp đó chính là ranh giới giữa tree-search và graph-search ở mục <a href='#ch3'>03</a>.",
  },
  ch3: {
    s1: "Một khung, bảy thuật toán",
    s2: "Đây là mục tôi thích nhất, vì nó biến bảy thuật toán nghe rất kêu thành một chuyện duy nhất. Tất cả chúng là <em>cùng một vòng lặp</em>, khác đúng một câu: <strong class='hl-yellow'>lấy nút nào ra khỏi frontier trước?</strong> Xếp hàng FIFO → BFS. Chồng đĩa LIFO → DFS. Rẻ nhất theo g → UCS. Trông gần đích nhất theo h → GBFS. Cân cả hai theo f → A*. Nhớ được câu hỏi này là bạn nhớ cả buổi.",
    s3: "TREE-SEARCH — có thể lặp vô hạn",
    s4: "<pre class='codeblock' style='background:transparent'>frontier ← {nút gốc}\n  loop:\n    if frontier rỗng: return <span style='color:#FC6255'>failure</span>\n    node ← POP(frontier)  <span style='color:#7A8399;font-style:italic'>▷ chiến lược = cách chọn nút này</span>\n    if GOAL-TEST(node): return <span style='color:#83C167'>SOLUTION(node)</span>\n    thêm các con của node vào frontier</pre>",
    s5: "GRAPH-SEARCH — nhớ những gì đã mở",
    s6: "<pre class='codeblock' style='background:transparent'>frontier ← {nút gốc}; <span style='color:#F4D345'>explored ← ∅</span>\n  loop:\n    if frontier rỗng: return <span style='color:#FC6255'>failure</span>\n    node ← POP(frontier)\n    if GOAL-TEST(node): return <span style='color:#83C167'>SOLUTION(node)</span>\n    <span style='color:#F4D345'>thêm node.STATE vào explored</span>\n    thêm các con vào frontier <span style='color:#F4D345'>nếu state\n    chưa nằm trong explored ∪ frontier</span> <span style='color:#7A8399;font-style:italic'>▷ chặn lặp</span></pre>",
    s7: "NÚT ≠ TRẠNG THÁI",
    s8: "Hai thứ này nghe giống nhau nhưng khác hẳn: nhiều <em>nút</em> có thể cùng chứa một <em>trạng thái</em> (tới Sibiu bằng ba đường là ba nút). Cái con trỏ <strong class='hl-mid'>PARENT</strong> trông vô hại kia mới là thứ giúp bạn <em>lần ngược</em> ra đường đi — chính là hàm <span class='code-inline'>reconstruct()</span> bạn sắp viết trong Lab.",
    s9: "VẾT DẦU LOANG",
    s10: "Hình dung graph-search như vết dầu loang trên mặt nước 🌊 — nó chia không gian làm 3: <span style='color:var(--muted-2)'>explored (đã loang qua)</span> · <span class='hl-cyan'>frontier (mép sóng đang lan)</span> · phần chưa chạm tới. Điểm mấu chốt: mọi đường từ gốc muốn ra ngoài <em>bắt buộc</em> phải xuyên qua mép sóng. Nên bạn chọn lấy nút nào ở mép ra trước là bạn quyết định tất cả.",
    s11: "“Thuật toán nào quên lịch sử của mình sẽ phải lặp lại nó.”",
    s12: "KHUNG ĐÁNH GIÁ — DÙNG SUỐT 4 BUỔI TỚI",
    s13: "Đầy đủ — complete?",
    s14: "Có nghiệm thì có chắc chắn tìm ra?",
    s15: "Tối ưu — optimal?",
    s16: "Nghiệm trả về có rẻ nhất không?",
    s17: "Thời gian",
    s18: "Sinh ra bao nhiêu nút?",
    s19: "Bộ nhớ",
    s20: "Giữ bao nhiêu nút trong RAM cùng lúc?",
    s21: "b — hệ số phân nhánh tối đa",
    s22: "d — độ sâu của nghiệm nông nhất",
    s23: "m — độ sâu tối đa của không gian",
  },
  quiz: {
    s1: "Quiz — đo xem bạn <em class='hl-cyan'>thật sự</em> hiểu tới đâu",
    s2: "năm câu · trừu tượng hóa, năm thành phần, node ≠ state, đường dư thừa",
    s3: "Mục 01 tới 03 đọc trôi lắm, vì chúng gần như không có công thức nào. Đúng chỗ đó mới dễ lừa mình: hiểu một định nghĩa và dùng được nó là hai chuyện khác nhau. Năm câu dưới đây không chấm bạn, chúng chỉ lộ ra chỗ bạn mới <em>thấy quen mặt</em>. Sai câu nào đọc giải thích ngay dưới đó, đừng để dành.",
  },
  hw: {
    s1: "Bài tập về nhà — Buổi 3",
    s2: "hai câu · formulation đầy đủ, hai kiểu phát biểu",
    s3: "QUESTION 1 — HAI NGƯỜI BẠN TRÊN BẢN ĐỒ ROMANIA",
    s4: "Mỗi lượt cả hai <em>cùng</em> di chuyển sang thành phố kề; thời gian một lượt = d(i, j) của người đi lâu hơn — người tới trước phải đứng đợi. Mục tiêu: gặp nhau nhanh nhất. <strong class='hl'>(a)</strong> Viết formulation đầy đủ (state, actions, transition, goal test, cost). <strong class='hl'>(b)</strong> Có bản đồ liên thông hoàn toàn mà vô nghiệm không? <strong class='hl'>(c)</strong> Có bản đồ mà mọi nghiệm bắt một người thăm lại thành phố cũ?",
    s5: "<a href='#ch2'>Ôn: mục 02 — 5 thành phần</a>",
    s6: "QUESTION 2 — CÙNG MỘT BÀI, HAI CÁCH VIẾT ĐỀ",
    s7: "Lấy bài 8 quân hậu. <strong class='hl'>(a)</strong> Viết phát biểu <em>incremental</em>: bàn cờ trống, mỗi hành động đặt thêm một hậu. <strong class='hl'>(b)</strong> Viết phát biểu <em>complete-state</em>: 8 hậu có sẵn trên bàn, mỗi hành động dịch một quân. <strong class='hl'>(c)</strong> Ở bản (b), path cost có ý nghĩa gì không — vì sao? <strong class='hl'>(d)</strong> Cấm đặt hậu vào ô đang bị chiếu thì không gian rụt từ 1,8×10¹⁴ xuống 2.057. Chỗ nào trong năm thành phần đã đổi?",
    s8: "<a href='#ch2'>Ôn: mục 02 — kích thước không gian</a>",
    s9: "Đưa đề nào cũng viết được 5 thành phần của nó — thử ngay với Q1, hai người bạn trên bản đồ.",
    s10: "Phân biệt được node ↔ state, và nói được vì sao hai nút cùng trạng thái lại khác g(n).",
    s11: "Giải thích được vì sao cây tìm kiếm của Romania vô hạn dù chỉ có 20 thành phố.",
    s12: "Nói được đâu là trừu tượng hóa đúng, đâu là bỏ mất thứ làm hành động không thực hiện nổi.",
    s13: "Tiếp theo: <strong class='hl'>Buổi 4 — Tìm kiếm mù</strong>. Đề đã viết xong, giờ tới lượt máy chạy — và bạn sẽ thấy cả năm thuật toán hóa ra là một vòng lặp thay ruột.",
    s14: "← Về Lộ trình",
  },
};
