
/*
 * Chữ tiếng Việt của bài b3 — NGUỒN SỰ THẬT.
 *
 * Rút bằng .claude/scripts/extract_lesson.py, gom theo mục và giữ đúng thứ tự đọc.
 * Bản EN (`*.text.en.ts`) khai `satisfies typeof VI` nên thiếu hay thừa một khóa là lỗi tsc.
 */
export const VI = {
  fn: {
    stepOf: (t: number, n: number) => `BƯỚC ${t} / ${n}`,
    explored: (n: number) => `EXPLORED — ĐÃ MỞ (${n})`,
    // Chuỗi có chèn giá trị -> HÀM.
    goalPath: (path: string, cost: number | null, opened: number) =>
      `Đường đi: ${path} · chi phí ${cost} · đã mở ${opened} nút`,
  },
  hero: {
    s1: "▶ Chạy từng bước trong Lab",
    s2: "TOÁN NỀN",
    s3: "02 Bài toán",
    s4: "04 Mù",
    s5: "06 Leo đồi",
    s6: "07 Tổng kết",
    s7: "10 Bài tập",
    s8: "Bìa",
    s9: "BUỔI 3",
    s10: "Tìm kiếm",
    s11: "Giải bài toán",
    s12: "bằng",
    s13: "Tìm kiếm",
    s14: "🧭 Bạn cần tới đích, mà thế giới thì có hàng triệu ngã rẽ. Làm sao? Buổi này mình đi từ số 0 — biến một đề bài lộn xộn thành đồ thị trạng thái gọn gàng — rồi leo lên tới mức tự tay cài cả 7 thuật toán tìm kiếm của Lab 1, chạy được, đo được time lẫn memory. Nghe hơi nhiều, nhưng tin tôi đi: bảy thuật toán này thật ra chỉ là MỘT vòng lặp thay ruột.",
    s15: "g — chi phí đã đi",
    s16: "h — ước lượng còn lại",
    s17: "9 mục học",
    s18: "≈ 3,5 giờ",
  },
  ch1: {
    s1: "Agent giải quyết vấn đề",
    s2: "Buổi 2 mình dừng ở agent phản xạ: thấy gì làm nấy, tra bảng là xong. Nhưng thử tình huống này xem — bạn đang ở Arad, phải có mặt ở Bucharest cho kịp chuyến bay. Nước đi đúng của <em>hôm nay</em> phụ thuộc vào cả chuỗi bước <em>ngày mai</em>, tra bảng kiểu gì cho nổi? Agent buộc phải <strong class='hl'>nghĩ trước</strong>: thử các chuỗi hành động trong đầu, chọn chuỗi nào dẫn tới đích. Nó có tên là problem-solving agent, và món võ của nó là <strong class='hl-cyan'>tìm kiếm</strong>.",
    s3: "BƯỚC 1 · GOAL FORMULATION",
    s4: "Chốt mục tiêu",
    s5: "Chốt xem bạn muốn thế giới ở trạng thái nào: <span class='code-inline'>In(Bucharest)</span>. Có mục tiêu rồi thì vô số lựa chọn vô nghĩa tự động rụng hết — đó chính là công dụng của nó.",
    s6: "BƯỚC 2 · PROBLEM FORMULATION",
    s7: "Mô hình hóa",
    s8: "Chọn cách mô tả trạng thái và hành động sao cho đủ chi tiết để giải <em>được</em>, mà đủ trừu tượng để giải <em>nổi</em>. Thời tiết, bài hát đang bật, bạn đi cùng là ai — bỏ hết, không liên quan.",
    s9: "BƯỚC 3 · SEARCH",
    s10: "Tìm kiếm",
    s11: "Đây là phần máy làm: thử các chuỗi hành động trên <em>mô hình</em> cho tới khi vớ được chuỗi chạm đích. Chuỗi đó gọi là <strong class='hl-mid'>nghiệm (solution)</strong>.",
    s12: "BƯỚC 4 · EXECUTION",
    s13: "Thực thi",
    s14: "Cầm nghiệm đi thi hành, từng hành động một. Kiểu <em>vòng hở</em> (open-loop) — nhắm mắt đi cũng tới, vì đường đã tính sẵn hết rồi.",
    s15: "GIẢ ĐỊNH CỦA BUỔI NÀY",
    s16: "Quan sát đầy đủ",
    s17: "Rời rạc",
    s18: "Biết trước mô hình",
    s19: "Tất định",
    s20: "→ nhờ bốn giả định này mà nghiệm chỉ là một chuỗi hành động <em>cố định</em>. Thế giới lầy lội hơn thì để dành các buổi sau.",
  },
  ch2: {
    s1: "Một bài toán tìm kiếm gồm đúng 5 thứ",
    s2: "Tin vui: mọi đề bài — bản đồ, trò xếp hình, robot hút bụi, n quân hậu — đều nén được về đúng cùng một bộ 5 thứ. Viết ra được 5 thứ này là bạn giải xong một nửa bài rồi, phần còn lại chỉ là chọn thuật toán. Q1 của Quiz 03 kiểm tra đúng kỹ năng này, nên đừng đọc lướt.",
    s3: "Trạng thái xuất phát.",
    s4: "Các hành động khả dụng tại s.",
    s5: "RESULT(s, a): làm a tại s thì ra trạng thái nào.",
    s6: "Kiểm tra một trạng thái có phải đích — tường minh, hoặc theo thuộc tính (chiếu hết!).",
    s7: "Tổng chi phí bước c(s, a, s′) ≥ 0 dọc đường đi.",
    s8: "tổng km đã lăn bánh",
    s9: "Gọi tên cho gọn: <strong class='hl'>nghiệm</strong> là một đường đi từ trạng thái đầu tới đích; <strong class='hl-green'>nghiệm tối ưu</strong> là cái rẻ nhất trong đám đó; còn <em>không gian trạng thái</em> là đồ thị gồm mọi trạng thái nối với nhau bằng hành động.",
    s10: "KÍCH THƯỚC KHÔNG GIAN — VÀI CON SỐ",
    s11: "8-puzzle: 9!/2 = 181.440 trạng thái",
    s12: "Nhìn con số này rồi hãy tin tôi: 8 quân hậu mô hình kiểu ngây thơ ra 64·63···57 ≈ 1,8×10¹⁴ chuỗi. Mô hình khôn hơn một chút (đặt hậu vào cột trái nhất còn trống, không cho ăn nhau) — còn <strong class='hl-green'>2.057</strong>. Cùng một bài toán, khác nhau 11 chữ số. <em>Bạn mô hình hóa thế nào quyết định bài có giải nổi hay không.</em>",
    s13: "KHÔNG GIAN TRẠNG THÁI ≠ CÂY TÌM KIẾM",
    s14: "Chỗ này dễ nhầm nên nói kỹ: Romania có đúng 20 thành phố, nhưng cây tìm kiếm của nó có thể <strong class='hl-red'>vô hạn</strong> — vì chẳng có gì cấm bạn đi Arad → Sibiu → Arad → Sibiu → … tới già. Một trạng thái có thể nằm ở rất nhiều nút khác nhau trên cây. Cách xử lý mấy vòng lặp đó chính là ranh giới giữa tree-search và graph-search ở mục <a href='#ch3'>03</a>.",
  },
  ch3: {
    s1: "Một khung, bảy thuật toán",
    s2: "Đây là mục tôi thích nhất, vì nó biến bảy thuật toán nghe rất kêu thành một chuyện duy nhất. Tất cả chúng là <em>cùng một vòng lặp</em>, khác đúng một câu: <strong class='hl-yellow'>lấy nút nào ra khỏi frontier trước?</strong> Xếp hàng FIFO → BFS. Chồng đĩa LIFO → DFS. Rẻ nhất theo g → UCS. Trông gần đích nhất theo h → GBFS. Cân cả hai theo f → A*. Nhớ được câu hỏi này là bạn nhớ cả buổi.",
    s3: "TREE-SEARCH — có thể lặp vô hạn",
    s4: "<pre class='codeblock' style='background:transparent'>frontier ← {nút gốc}\n  loop:\n    if frontier rỗng: return <span style='color:#FC6255'>failure</span>\n    node ← POP(frontier)  <span style='color:#7A8399;font-style:italic'>▷ chiến lược = cách chọn nút này</span>\n    if GOAL-TEST(node): return <span style='color:#83C167'>SOLUTION(node)</span>\n    thêm các con của node vào frontier</pre>",
    s5: "GRAPH-SEARCH — nhớ những gì đã mở",
    s6: "<pre class='codeblock' style='background:transparent'>frontier ← {nút gốc}; <span style='color:#F4D345'>explored ← ∅</span>\n  loop:\n    if frontier rỗng: return <span style='color:#FC6255'>failure</span>\n    node ← POP(frontier)\n    if GOAL-TEST(node): return <span style='color:#83C167'>SOLUTION(node)</span>\n    <span style='color:#F4D345'>thêm node.STATE vào explored</span>\n    thêm các con vào frontier <span style='color:#F4D345'>nếu state\n    chưa nằm trong explored ∪ frontier</span> <span style='color:#7A8399;font-style:italic'>▷ chặn lặp</span></pre>",
    s7: "NÚT ≠ TRẠNG THÁI",
    s8: "Hai thứ này nghe giống nhau nhưng khác hẳn: nhiều <em>nút</em> có thể cùng chứa một <em>trạng thái</em> (tới Sibiu bằng ba đường là ba nút). Cái con trỏ <strong class='hl-mid'>PARENT</strong> trông vô hại kia mới là thứ giúp bạn <em>lần ngược</em> ra đường đi — chính là hàm <span class='code-inline'>reconstruct()</span> bạn sắp viết trong Lab.",
    s9: "VẾT DẦU LOANG",
    s10: "Hình dung graph-search như vết dầu loang trên mặt nước 🌊 — nó chia không gian làm 3: <span style='color:var(--muted-2)'>explored (đã loang qua)</span> · <span class='hl-cyan'>frontier (mép sóng đang lan)</span> · phần chưa chạm tới. Điểm mấu chốt: mọi đường từ gốc muốn ra ngoài <em>bắt buộc</em> phải xuyên qua mép sóng. Nên bạn chọn lấy nút nào ở mép ra trước là bạn quyết định tất cả.",
    s11: "“Thuật toán nào quên lịch sử của mình sẽ phải lặp lại nó.”",
    s12: "KHUNG ĐÁNH GIÁ — DÙNG SUỐT 4 BUỔI TỚI",
    s13: "Đầy đủ — complete?",
    s14: "Có nghiệm thì có chắc chắn tìm ra?",
    s15: "Tối ưu — optimal?",
    s16: "Nghiệm trả về có rẻ nhất không?",
    s17: "Thời gian",
    s18: "Sinh ra bao nhiêu nút?",
    s19: "Bộ nhớ",
    s20: "Giữ bao nhiêu nút trong RAM cùng lúc?",
    s21: "b — hệ số phân nhánh tối đa",
    s22: "d — độ sâu của nghiệm nông nhất",
    s23: "m — độ sâu tối đa của không gian",
  },
  ch4: {
    s1: "Tìm kiếm mù",
    s2: "“Mù” không phải lời chê đâu — nó chỉ có nghĩa là ngoài đề bài ra, thuật toán không biết thêm gì cả. Nó không đoán được nút nào hứa hẹn hơn nút nào, chỉ biết đúng một chuyện: “đây có phải đích chưa?”. Năm thuật toán dưới đây mù như nhau, khác nhau duy nhất ở <em>thứ tự mở nút</em>.",
    s3: "Tìm theo chiều rộng",
    s4: "dừng khi đích SINH RA",
    s5: "Luôn mở nút <strong class='hl'>nông nhất</strong>. Nút mới đến xếp cuối hàng, nút chờ lâu nhất được gọi trước — đúng kiểu xếp hàng mua trà sữa. Cây vì thế lớn đều từng tầng một. Mẹo nhỏ: kiểm tra đích ngay lúc <em>sinh</em> nút con thay vì đợi lấy ra, bạn tiết kiệm được nguyên một tầng b nút.",
    s6: "ĐẦY ĐỦ",
    s7: "✓ khi b hữu hạn",
    s8: "TỐI ƯU",
    s9: "✓ khi mọi bước cùng giá",
    s10: "THỜI GIAN",
    s11: "BỘ NHỚ",
    s12: "O(b<sup>d</sup>) — RAM chết trước",
    s13: "độ sâu d",
    s14: "số nút",
    s15: "thời gian",
    s16: "bộ nhớ",
    s17: "1,1 giây",
    s18: "3 giờ",
    s19: "13 ngày",
    s20: "350 năm",
    s21: "b = 10, tốc độ 1 triệu nút/giây, 1 kB/nút. Nhìn cột thời gian còn thấy gắng đợi được; nhìn cột bộ nhớ thì thôi 💀 — RAM luôn chết trước đồng hồ.",
    s22: "Vụ nổ hàm mũ — vì sao O(bᵈ) đáng sợ",
    s23: "mỗi tầng nhân thêm b lần; tầng cuối chiếm gần hết",
    s24: "Chi phí đồng nhất",
    s25: "dừng khi đích LẤY RA",
    s26: "BFS tối ưu <em>số cạnh</em> — mà ít cạnh đâu có nghĩa là rẻ, đi 2 chặng máy bay vẫn đắt hơn 5 chặng xe buýt. UCS sửa đúng chỗ đó: nó mở nút có <strong class='hl-cyan'>g(n) — chi phí thật từ gốc</strong> — nhỏ nhất. Có hai chi tiết mà tôi thấy sinh viên mất điểm nhiều nhất: <strong class='hl'>(1)</strong> UCS chỉ dừng khi đích được <em>lấy ra</em> khỏi hàng đợi, chứ không phải lúc sinh ra — vì lúc sinh ra, biết đâu còn đường rẻ hơn đang xếp hàng; <strong class='hl'>(2)</strong> gặp lại một nút bằng đường rẻ hơn thì phải <em>cập nhật</em> cha và khóa của nó (decrease-key). Đừng tin lời tôi, mở Manim Lab chạy UCS trên đồ thị Lab mà xem, cả hai đều xảy ra thật.",
    s27: "ĐẦY ĐỦ",
    s28: "✓ khi chi phí bước ≥ ε",
    s29: "TỐI ƯU",
    s30: "✓ với mọi hàm chi phí",
    s31: "THỜI GIAN",
    s32: "BỘ NHỚ",
    s33: "như thời gian",
    s34: "Có lúc còn tệ hơn cả bᵈ: nó mải mê bò qua đủ thứ bước rẻ tiền trước khi chịu thử một đường thật sự có ích.",
    s35: "Tìm theo chiều sâu",
    s36: "dừng khi đích SINH RA",
    s37: "DFS là đứa liều: mở nút <strong class='hl'>sâu nhất</strong>, lao một mạch xuống đáy một nhánh, cụt đường mới chịu quay lui. Đừng mong tối ưu — nghiệm đầu tiên nó vớ được thường không phải nghiệm nông nhất. Nhưng nó có một thứ mà BFS thèm: <strong class='hl-green'>bộ nhớ</strong>. Nó chỉ giữ nhánh đang đi cùng mấy anh em chưa mở, O(bm) thôi; bản backtracking còn gọn nữa, O(m).",
    s38: "ĐẦY ĐỦ",
    s39: "✓ graph-search hữu hạn · ✗ tree-search",
    s40: "TỐI ƯU",
    s41: "THỜI GIAN",
    s42: "O(b<sup>m</sup>), m có thể ≫ d",
    s43: "BỘ NHỚ",
    s44: "O(bm) — lý do tồn tại",
    s45: "HAI CÁCH CHỐNG LẶP — ĐỀ RA CÁI NÀO, TRACE CÁI ĐÓ",
    s46: "Chỗ này tôi phải tách bạch ra, vì bài tập Q2 và Q4b hỏi trúng nó, và hai cách cho <strong class='hl'>thứ tự expand khác nhau</strong>:",
    s47: "NHỚ CẢ BẢN ĐỒ — EXPLORED SET",
    s48: "Ghé nút nào là cấm ghé lại, vĩnh viễn. Đây là bản trong code Python ở <a href='#codelab'>mục 08</a> — cái <span class='code-inline'>visited</span> chỉ có thêm, không bao giờ bớt. Đổi lại phải nhớ mọi trạng thái đã gặp.",
    s49: "CHỈ NHỚ ĐƯỜNG ĐANG ĐI — PATH CHECK",
    s50: "Chỉ cấm gặp lại nút <em>nằm trên đường từ gốc xuống tới đây</em>; quay lui thì nhả nút ra khỏi trí nhớ — đúng dòng <span class='code-inline'>del visited[child]</span> trong code DLS. Bộ nhớ chỉ O(m).",
    s51: "Bản path check vẫn chặn được chuyện lượn vòng vô hạn trong không gian hữu hạn, nhưng nó cho phép bạn tới cùng một nút hai lần qua hai nhánh khác nhau — tức là <strong class='hl-mid'>vẫn sinh đường dư thừa</strong>, thứ mà explored set dẹp sạch. Còn nếu bản thân không gian trạng thái là vô hạn thì đừng trông mong gì: cả hai bản đều chết như nhau.",
    s52: "Giới hạn độ sâu → Sâu dần từng nấc",
    s53: "DFS + trần ℓ = 0, 1, 2, …",
    s54: "<strong class='hl'>DLS</strong> chữa bệnh đi lạc mãi của DFS bằng cách đóng một cái trần: cấm đi sâu quá ℓ. Chạm trần thì trả về <em>cutoff</em> — nhớ phân biệt với <em>failure</em> là hết đường thật, hai chuyện khác nhau. Chọn ℓ bằng tri thức bài toán: Romania có 20 thành phố, hai thành phố bất kỳ cách nhau ≤ 9 bước, vậy ℓ = 9 là dư. Khổ nỗi ta thường <em>không biết trước</em> ℓ. Thế là <strong class='hl'>IDS</strong> làm cái việc nghe rất ngớ ngẩn: chạy DLS với ℓ = 0, rồi 1, rồi 2… tới khi đụng đích.<br/><br/>Phí phạm quá phải không? Tầng trên bị sinh đi sinh lại bao nhiêu lần. Nhưng đây là chỗ hàm mũ đứng về phía ta: tầng cuối cùng chiếm gần hết số nút, mấy tầng trên cộng lại chẳng đáng bao nhiêu. Cụ thể b = 10, d = 5 → IDS sinh 123.450 nút, BFS sinh 111.110, đội đúng <strong class='hl-green'>~11%</strong>. Trả 11% đó, bạn được bộ nhớ O(bd) của DFS cộng tính đầy đủ và tối ưu của BFS. Hời.",
    s55: "ĐẦY ĐỦ",
    s56: "✓ khi b hữu hạn",
    s57: "TỐI ƯU",
    s58: "✓ khi mọi bước cùng giá",
    s59: "THỜI GIAN",
    s60: "BỘ NHỚ",
    s61: "BỐN Ô TRÊN LÀ CỦA IDS — CÒN DLS ĐỨNG MỘT MÌNH THÌ SAO?",
    s62: "Đừng gán nhầm thành tích. DLS một mình <strong class='hl-red'>hỏng cả hai đầu</strong>, mà hỏng theo hai kiểu ngược nhau, tùy bạn đặt trần ở đâu so với độ sâu nghiệm d:",
    s63: "ĐẦY ĐỦ",
    s64: "TỐI ƯU",
    s65: "THỜI GIAN",
    s66: "BỘ NHỚ",
    s67: "Trần thấp hơn nghiệm (ℓ &lt; d) thì nghiệm nằm ngay dưới đáy trần mà nó không với tới — <em>trượt</em>. Trần cao hơn nghiệm (ℓ &gt; d) thì nó vẫn lao xuống sâu theo kiểu DFS, nên rất dễ vớ một nghiệm sâu trước khi kịp thấy nghiệm nông — <em>mất tối ưu</em>. Còn hai ô thời gian và bộ nhớ thì vẫn y hệt DFS, chỉ thay m bằng ℓ; nói ngược lại cũng đúng: <strong class='hl-mid'>DFS chính là DLS với ℓ = ∞</strong>.",
    s68: "Không biết chọn gì thì chọn IDS — nó là lựa chọn mặc định khi không gian lớn và bạn mù tịt về độ sâu nghiệm. Mở Lab chọn IDS rồi nhìn cái nhãn ℓ nhích dần lên ở góc canvas, sẽ thấy ngay nó làm gì.",
    s69: "Ý tưởng đơn giản mà hiệu quả kinh khủng: đào từ hai đầu, gặp nhau ở giữa. b<sup>d/2</sup> + b<sup>d/2</sup> ≪ b<sup>d</sup> — với b = 10, d = 6 thì là 2.000 nút thay vì 1.000.000. Cái giá: bạn phải biết cách đi <em>lùi</em> từ đích, và phải biết đích nằm ở đâu cho tường minh. Với đích kiểu “chiếu hết” thì chịu, biết chiếu hết ở thế cờ nào mà đào ngược.",
  },
  lab: {
    s1: "Manim Lab — xem 7 thuật toán chạy từng bước",
    s2: "Đọc mười lần không bằng xem chạy một lần. Chọn thuật toán, bấm <strong class='hl'>Chạy</strong>, hoặc bước từng nhịp bằng <strong class='hl'>Tiến / Lùi</strong> để soi cho kỹ. Màu vẫn theo quy ước dùng chung cả trang: <span class='hl-cyan'>xanh dương — frontier</span> · <span class='hl-yellow'>vàng — đang mở</span> · <span style='color:var(--muted-2)'>xám — explored</span> · <span class='hl-green'>xanh lá — đường đi</span> · <span class='hl-purple'>tím — vừa tìm ra đường rẻ hơn</span>.",
    s3: "Ba thí nghiệm tôi muốn bạn tự làm ngay bây giờ: (1) preset Romania, chạy GBFS rồi A* — tham lam ra 450 km, A* ra 418 km, tự hỏi 32 km đó đi đâu mất; (2) chạy HC trên cùng preset và xem nó kẹt cứng ở Timișoara; (3) đổi sang đồ thị Lab, so BFS (chi phí 9) với UCS (chi phí 8) để tận mắt thấy “nông nhất ≠ rẻ nhất”.",
  },
  ch5: {
    s1: "Tìm kiếm có thông tin",
    s2: "Nãy giờ thuật toán của mình mò trong bóng tối. Giờ tôi cho nó một cái la bàn 🎯 — đúng một con số cho <em>mỗi nút</em>: <strong class='hl-yellow'>h(n), chi phí ước lượng từ n về tới đích</strong>. Con số này không có trong đề bài, nó đến từ hiểu biết <em>bên ngoài</em> về bài toán. Trên bản đồ thì nó là khoảng cách đường chim bay (SLD). Chỉ có đúng một quy ước phải nhớ: h(đích) = 0.",
    s3: "h(Făgăraș) = 176",
    s4: "dừng khi đích SINH RA",
    s5: "Có la bàn rồi thì cứ nhắm hướng đích mà chạy thôi, đúng không? GBFS nghĩ y như vậy: luôn mở nút <strong class='hl'>trông gần đích nhất</strong>. Và nó nhanh thật — Arad → Sibiu → Făgăraș → București, mở đúng 3 nút. Có điều đường đó dài 450 km, còn đường tối ưu vòng qua Râmnicu–Pitești chỉ <strong class='hl-green'>418 km</strong>. Sai ở đâu? GBFS chỉ nhìn tương lai (h) mà quên sạch quá khứ (g), nên nó cắm đầu vào lối <em>trông</em> thì gần mà <em>đi</em> thì xa. Tệ hơn nữa, bản tree-search có thể lắc qua lắc lại vô hạn giữa hai thành phố (Iași ↔ Neamț) mà không biết ngượng.",
    s6: "ĐẦY ĐỦ",
    s7: "✗ tree · ✓ graph hữu hạn",
    s8: "TỐI ƯU",
    s9: "THỜI GIAN",
    s10: "BỘ NHỚ",
    s11: "O(b<sup>m</sup>) — h tốt cắt mạnh",
    s12: "Cân bằng quá khứ và tương lai",
    s13: "dừng khi đích LẤY RA",
    s14: "UCS nhớ quá khứ, GBFS đoán tương lai, mỗi đứa thiếu một nửa. A* làm cái việc hiển nhiên là cộng hai nửa lại:<br/><br/><span style='font-family:var(--font-serif);font-style:italic;font-size:1.35em'><span class='hl-text'>f(n)</span> = <span class='hl-cyan'>g(n)</span> + <span class='hl-yellow'>h(n)</span></span> — chi phí ước lượng của nghiệm rẻ nhất đi QUA n.<br/><br/>Cài đặt thì gần như copy UCS: cùng hàng đợi ưu tiên, cùng decrease-key, cùng luật “chỉ dừng khi đích được lấy ra”. Bạn chỉ đổi khóa sắp xếp từ g sang f, thế thôi. Nhưng A* giỏi hay dở thì phụ thuộc hoàn toàn vào h, và h phải thỏa điều kiện:",
    s15: "ĐẦY ĐỦ",
    s16: "TỐI ƯU",
    s17: "THỜI GIAN",
    s18: "mũ theo sai số của h",
    s19: "BỘ NHỚ",
    s20: "O(b<sup>d</sup>) — điểm chết",
    s21: "ADMISSIBLE — không ước lượng lố",
    s22: "h(n) ≤ h*(n) — chi phí thật",
    s23: "Heuristic biết điều: không bao giờ nói quá. Nó được phép lạc quan, cấm bi quan. SLD admissible vì đường chim bay thì không đường nào ngắn hơn được. Chỉ cần MỘT node nói phóng lên là mất sạch bảo đảm. → A* <strong class='hl-mid'>tree-search tối ưu</strong>.",
    s24: "CONSISTENT — bất đẳng thức tam giác",
    s25: "Điều kiện chặt hơn một bậc: không có “lối tắt” nào rẻ hơn việc đi một bước rồi ước lượng tiếp. Hệ quả rất đẹp — f không bao giờ giảm dọc một đường đi, nên nút vừa được lấy ra lần đầu là đã tối ưu, khỏi cần xét lại. → A* <strong class='hl-mid'>graph-search tối ưu</strong>. Và consistent ⇒ admissible, chứ không ngược lại.",
    s26: "A* mở những nút nào — đường viền f",
    s27: "h càng sắc, vùng loang càng bó về phía đích",
    s28: "viền tròn quanh S, loang đều mọi hướng",
    s29: "A* — h sắc",
    s30: "viền kéo dài về G, bó quanh đường tối ưu",
    s31: "Vì f không giảm dọc đường đi, A* mở nút theo thứ tự f tăng dần — nó lấp lần lượt từng <strong class='hl-yellow'>đường viền f</strong> một, y như nước dâng lên từng vạch. Gọi C* là chi phí của nghiệm tối ưu, bạn suy ra được ngay hai điều mà tôi thấy rất đáng nhớ: A* <strong class='hl'>mở mọi nút có f(n) &lt; C*</strong>, và <strong class='hl'>không bao giờ mở nút có f(n) &gt; C*</strong> — đám đó bị cắt sạch mà nghiệm vẫn tối ưu. Riêng mấy nút nằm đúng trên viền f(n) = C* thì hên xui, tùy cách phá đồng hạng. Đây chính là công cụ để làm <a href='#hw'>câu 3 của bài tập</a>: muốn biết một đường có thể được trả về hay không, bạn đi tính f chứ đừng đoán.<br/><br/>Quay lại bản đồ Romania cho dễ hình dung. Vẽ các viền <strong class='hl-mid'>380 · 400 · 420</strong> quanh Arad thì viền 420 vừa vặn trùm tới được București — tất nhiên rồi, vì nghiệm tối ưu là <strong class='hl-green'>418</strong>. Mọi thành phố nằm ngoài cái viền ấy, A* không thèm đụng tới một cái nào.<br/><br/>Và đó cũng là chỗ h biến thành tốc độ. h = 0 thì f = g, viền là những vòng tròn đồng tâm quanh S — A* thoái hóa đúng thành UCS, loang đều ra mọi phía kể cả hướng ngược với đích. h càng sát chi phí thật, viền càng bị kéo dài về phía G và bó sát đường tối ưu, số nút lọt vào trong viền càng ít. Mở Lab chạy UCS rồi A* trên preset Romania, đếm số nút xám của hai bên — chênh lệch đó chính là cái hình trên.",
    s32: "Một danh hiệu nữa cho A*: nó <strong style='color:var(--text-2)'>optimally efficient</strong> — với cùng một h consistent, không thuật toán tối ưu nào mở được ít nút hơn nó. Nghe hoàn hảo, nhưng gót chân Achilles vẫn là RAM. Khi máy không chứa nổi thì tìm tới IDA*, RBFS, SMA* — ngoài phạm vi buổi này, để dành.",
    s33: "HEURISTIC TRỘI HƠN — VÀ ĐO ĐỘ SẮC BẰNG b*",
    s34: "Quy tắc chọn heuristic: nếu h₂(n) ≥ h₁(n) tại mọi n (cả hai vẫn admissible) thì h₂ <em>trội</em> h₁, và A*(h₂) không bao giờ phải mở nhiều nút hơn. Nói cách khác: ước lượng càng sát chi phí thật càng tốt, miễn đừng vượt. Thử với 8-puzzle — h₁ = số ô nằm sai chỗ, h₂ = tổng khoảng cách Manhattan.",
    s35: "Nhưng “mở ít nút hơn” thì ít hơn <em>bao nhiêu</em>? Đếm nút trần trụi không so được giữa hai bài khác độ sâu — 227 nút ở d = 12 với 39.135 nút ở d = 24, cái nào giỏi hơn? Nên người ta quy hết về một con số duy nhất: <strong class='hl-yellow'>hệ số phân nhánh hiệu dụng b*</strong>. A* mở N nút rồi tìm ra nghiệm ở độ sâu d; giờ hỏi ngược: một cây <em>đều</em> sâu d mà chứa đúng N + 1 nút thì mỗi nút phải đẻ mấy con?",
    s36: "Ví dụ A* tìm ra nghiệm ở độ sâu 5 mà chỉ tốn 52 nút → <strong class='hl'>b* = 1,92</strong>: nó len tới đích gọn như thể mỗi nút chỉ có chưa tới 2 nhánh, dù cây thật thì rậm hơn nhiều. b* đổi theo từng đề, nhưng với bài đủ khó thì khá ổn định, nên dùng nó chấm điểm heuristic được. Thước đo gói lại đúng một câu: <strong class='hl-green'>b* càng gần 1 càng ngon</strong> — b* = 1 nghĩa là đi một mạch tới nghiệm, không mở thừa nút nào. Heuristic nào ép được b* xuống sát 1 là heuristic cho bạn giải nổi bài lớn với cái giá chịu được.",
    s37: "SỐ NÚT SINH RA",
    s38: "Trung bình trên 100 thể hiện 8-puzzle cho mỗi độ sâu d. Ô “–”: từ d = 14 trở lên bảng gốc bỏ trống dòng IDS, không có số đo — và tôi không bịa cho bạn một con số. Cứ nhìn 3,6 triệu ở d = 12 rồi tự nhân tiếp là đủ sợ.",
    s39: "CHẾ HEURISTIC Ở ĐÂU RA?",
    s40: "<strong class='hl-yellow'>1 · Nới lỏng bài toán.</strong> Đây là mẹo tôi thích nhất: bỏ bớt luật đi. 8-puzzle cho ô bay tự do tới đích → ra h₁; cho ô trượt đè lên nhau → ra h₂. Vì bài dễ hơn thì nghiệm không thể đắt hơn bài gốc, mấy h kiểu này <em>tự động</em> admissible và consistent. Khỏi chứng minh.",
    s41: "<strong class='hl-yellow'>2 · Lấy max.</strong> Có nhiều h admissible mà không biết chọn cái nào? Lấy hết: h = max(h₁, …, hₖ). Max của các heuristic biết điều thì vẫn biết điều.",
    s42: "<strong class='hl-yellow'>3 · Pattern database.</strong> Giải trước vài bài con (ví dụ chỉ 4 ô góc), ghi chi phí chính xác vào bảng, lúc chạy thì tra. Đổi bộ nhớ lấy độ sắc của h.",
    s43: "<strong class='hl-yellow'>4 · Học từ kinh nghiệm.</strong> Giải nhiều lần, ghi lại, rồi hồi quy h từ các đặc trưng của trạng thái. Vâng — dùng học máy để chế heuristic cho tìm kiếm. Hẹn bạn ở Buổi 10.",
  },
  ch6: {
    s1: "Leo đồi — kẻ ngoại đạo trong Lab",
    s2: "⛰️ Lab 1 bắt cài thêm một đứa chẳng giống ai trong đám trên: leo đồi. Không hàng đợi, không quay lui, không nhớ gì hết — nó giữ đúng <strong class='hl'>một</strong> nút hiện tại rồi bước sang láng giềng nào có h nhỏ hơn. Bản <strong class='hl'>first-choice</strong> còn lười hơn: thấy láng giềng tốt hơn đầu tiên là leo luôn, khỏi so tiếp. Bộ nhớ O(1), nhanh như chớp — và mù tịt trước cực trị địa phương.",
    s3: "Vì sao leo đồi kẹt — phong cảnh trạng thái",
    s4: "quả bóng chỉ biết leo lên, không bao giờ chịu xuống",
    s5: "BA KIỂU CHẾT",
    s6: "cực trị địa phương",
    s7: "cao nguyên phẳng (plateau)",
    s8: "sống núi (ridge)",
    s9: "— muốn thấy nó chết tận mắt thì chạy <strong class='hl-mid'>HC trên preset Romania</strong> trong <a href='#lab'>Lab</a>: nó hí hửng leo Arad → Timișoara vì h giảm từ 366 xuống 329, rồi đứng đó, hết đường lên. Output: -1.",
    s10: "Đừng vội chê nó — Buổi 4 (Local Search) dành nguyên buổi để chữa đúng căn bệnh này: random restart, simulated annealing, local beam, thuật toán di truyền. Leo đồi là điểm xuất phát của cả một họ thuật toán rất mạnh.",
  },
  ch7: {
    s1: "Bảy thuật toán trên một trang giấy",
    s2: "THUẬT TOÁN",
    s3: "ĐẦY ĐỦ",
    s4: "TỐI ƯU",
    s5: "THỜI GIAN",
    s6: "BỘ NHỚ",
    s7: "DÙNG KHI",
    s8: "nghiệm nông, bước cùng giá, RAM dư",
    s9: "RAM chật, không gian sâu hữu hạn",
    s10: "như thời gian",
    s11: "chi phí bước khác nhau, cần tối ưu",
    s12: "DLS lặp, ℓ↑",
    s13: "mặc định khi d chưa biết, KG lớn",
    s14: "cần nhanh, chấp nhận lệch tối ưu",
    s15: "mũ theo sai số h",
    s16: "cần tối ưu và có h tốt",
    s17: "không có",
    s18: "tùy địa hình",
    s19: "KG khổng lồ, cần nghiệm “đủ tốt”",
    s20: "¹ b hữu hạn (UCS: thêm chi phí bước ≥ ε &gt; 0) · ² khi mọi bước cùng chi phí · ³ graph-search trên không gian hữu hạn · ⁴ h admissible (tree) / consistent (graph)",
  },
  codelab: {
    s1: "Code Lab — cài cả 7 thuật toán",
    s2: "⌨️ Tới phần vui nhất: gõ code. Đề bài yêu cầu viết Python và <em>tự cài phần lõi tìm kiếm</em> — thư viện phụ trợ thì thoải mái, nhưng đừng gọi thư viện giải hộ. Đọc <span class='code-inline'>input.txt</span>, ghi <span class='code-inline'>output.txt</span>, đo runtime và peak memory cho từng thuật toán. Bài <strong class='hl'>cá nhân</strong>, khoảng 3 tuần. Thang điểm: 7 thuật toán × 10% · ≥ 5 test case 10% · báo cáo 20%. Dưới đây tôi để sẵn khung code, bạn điền phần lõi.",
    s3: "BA QUY ƯỚC MÀ SAI LÀ LỆCH OUTPUT — ĐỌC KỸ GIÙM TÔI",
    s4: "BFS · DFS · GBFS dừng khi đích được <strong class='hl-cyan'>SINH RA</strong>",
    s5: "UCS · A* dừng khi đích được <strong class='hl-yellow'>LẤY RA</strong>",
    s6: "HC kẹt → không có đường → in <strong class='hl-red'>-1</strong>",
    s7: "INPUT.TXT — đồ thị có thể CÓ HƯỚNG hoặc vô hướng",
    s8: "dòng 1: số nút · dòng 2: start goal · tiếp theo: ma trận kề (trọng số, 0 = không có cạnh) · dòng cuối: heuristic từng nút",
    s9: "OUTPUT.TXT — path hoặc -1, kèm time và memory",
    s10: "đồ thị này chính là preset “Lab 1 · 6 đỉnh” trong Manim Lab ở trên — code bạn chạy ra gì, đối chiếu từng bước được luôn",
    s11: "DÙNG CHUNG CHO CẢ 7 — LẦN NGƯỢC CON TRỎ CHA",
    s12: "MAIN.PY — ĐỌC INPUT, CHẠY 7 THUẬT TOÁN, ĐO TIME + MEMORY",
    s13: "time.perf_counter() + tracemalloc — đúng hai thứ đề đòi: “high-resolution timer” và “peak memory”",
    s14: "GỢI Ý 5 TEST CASE “KHÁC TÍNH CHẤT” — CHỖ NÀY DỄ ĂN ĐIỂM",
    s15: "<strong class='hl-mid'>1 ·</strong> Đồ thị mẫu 6 đỉnh ở trên — có đáp án đối chiếu sẵn trong Manim Lab, dùng để bắt bug đầu tiên.",
    s16: "<strong class='hl-mid'>2 ·</strong> Vô nghiệm: cô lập cái đích ra. Cả 7 phải in -1 và thoát êm, đứa nào treo là đứa đó có bug vòng lặp.",
    s17: "<strong class='hl-mid'>3 ·</strong> Đồ thị CÓ HƯỚNG (ma trận bất đối xứng) — test này lộ ngay bug duyệt kề, kinh điển nhất là quét nhầm cột thành hàng.",
    s18: "<strong class='hl-mid'>4 ·</strong> Cố tình cho một heuristic KHÔNG admissible → A* sẽ trả đường lệch tối ưu. Không phải bug đâu, đúng lý thuyết đấy — và giải thích được chuyện này trong báo cáo thì rất ăn điểm.",
    s19: "<strong class='hl-mid'>5 ·</strong> Đồ thị lớn sinh ngẫu nhiên (n ≥ 500). Đồ thị 6 đỉnh thì thuật toán nào cũng xong trong 0,0001 giây; phải to lên thì khác biệt time/memory mới chịu hiện ra.",
  },
  quiz: {
    s1: "Quiz — đo xem bạn <em class='hl-cyan'>thật sự</em> hiểu tới đâu",
    s2: "tám câu · phát biểu bài toán, frontier, heuristic, A*",
    s3: "Đọc một mạch rồi thấy hiểu hết là cảm giác quen thuộc nhất trên đời — và cũng là cảm giác dễ lừa mình nhất. Tám câu dưới đây không phải để chấm bạn; chúng để lộ ra chỗ nào bạn mới chỉ <em>thấy quen mặt</em> chứ chưa hiểu. Sai câu nào thì đọc phần giải thích ngay dưới đó, đừng để dành. Làm xong hẵng qua bài tập.",
  },
  hw: {
    s1: "Bài tập về nhà — Buổi 3",
    s2: "bốn câu · formulation, trace tay, admissible &amp; consistent, mê cung",
    s3: "QUESTION 1 — HAI NGƯỜI BẠN TRÊN BẢN ĐỒ ROMANIA",
    s4: "Mỗi lượt cả hai <em>cùng</em> di chuyển sang thành phố kề; thời gian một lượt = d(i, j) của người đi lâu hơn — người tới trước phải đứng đợi. Mục tiêu: gặp nhau nhanh nhất. <strong class='hl'>(a)</strong> Viết formulation đầy đủ (state, actions, transition, goal test, cost). <strong class='hl'>(b)</strong> D(i, j) là đường chim bay giữa hai người — heuristic nào admissible: D(i, j) · 2·D(i, j) · D(i, j)/2? <strong class='hl'>(c)</strong> Có bản đồ liên thông hoàn toàn mà vô nghiệm không? <strong class='hl'>(d)</strong> Có bản đồ mà mọi nghiệm bắt một người thăm lại thành phố cũ?",
    s5: "<a href='#ch2'>Ôn: mục 02 — 5 thành phần</a> · <a href='#ch5'>mục 05 — admissible</a>",
    s6: "QUESTION 2 — TRACE TAY 6 THUẬT TOÁN",
    s7: "Đồ thị S → G, h ghi dưới tên đỉnh, chi phí trên cạnh. Với BFS (có mẫu) · UCS · DFS (nhớ nút trên đường đi) · IDS · GBFS · A*: liệt kê <em>thứ tự expand</em>, <em>đường đi tìm được</em>, <em>frontier cuối cùng</em>. Đồng hạng → mở theo alphabet; “expand” = lấy RA khỏi frontier. <strong class='hl'>(g)</strong> h có admissible? <strong class='hl'>(h)</strong> có consistent?",
    s8: "<a href='#lab'>Luyện đúng kỹ năng này trong Manim Lab</a>",
    s9: "QUESTION 3 — ĐƯỜNG NÀO CÓ THỂ ĐƯỢC TRẢ VỀ?",
    s10: "A là start, G là goal; h₁ consistent còn h₂ thì không. <strong class='hl'>(1)</strong> Với DFS · BFS · UCS · A*(h₁) · A*(h₂), đánh dấu những đường <em>có thể</em> được trả về dưới một cách phá đồng hạng nào đó: A-B-D-G, A-C-D-G, A-B-C-D-F-G. <strong class='hl'>(2)</strong> Bảng h₃ đã cố định trừ h₃(B): tìm tập giá trị để h₃ admissible; để h₃ consistent; để A* expand đúng thứ tự A, C, B, D.",
    s11: "<a href='#ch5'>Ôn: mục 05 — admissible vs consistent</a>",
    s12: "QUESTION 4 — MÊ CUNG s → g",
    s13: "Tường đậm không đi xuyên. Liệt kê các ô explored theo định dạng &lt;b₁, b₂, …&gt; với: <strong class='hl'>(a)</strong> BFS; <strong class='hl'>(b)</strong> DFS chống lặp, thứ tự toán tử up, left, right, down; <strong class='hl'>(c)</strong> GBFS với khoảng cách Manhattan (|Δx| + |Δy|); <strong class='hl'>(d)</strong> A* cùng heuristic đó.",
    s14: "<a href='#ch4'>Ôn: mục 04 — thứ tự mở nút</a>",
    s15: "Đưa đề nào cũng viết được 5 thành phần của nó — thử ngay với Q1, hai người bạn trên bản đồ.",
    s16: "Phân biệt được node ↔ state, frontier ↔ explored, tree-search ↔ graph-search.",
    s17: "Giải thích cho người khác nghe được: vì sao BFS/DFS/GBFS dừng khi đích SINH RA, còn UCS/A* phải nhịn đợi LẤY RA.",
    s18: "Trace tay BFS, UCS, A* trên đồ thị 6 đỉnh của Lab rồi đối chiếu với Manim Lab.",
    s19: "Chứng minh được một heuristic là admissible / consistent (Q2g–h, Q3).",
    s20: "Cài đủ 7 thuật toán, chạy trơn input.txt → output.txt, đo được time và memory.",
    s21: "Tự tạo ≥ 5 test case khác tính chất: vô nghiệm, đồ thị có hướng, HC kẹt, đồ thị lớn…",
    s22: "Tiếp theo: <strong class='hl'>Buổi 4 — Local Search</strong>, nơi mình chữa bệnh kẹt của leo đồi bằng simulated annealing, local beam và thuật toán di truyền. Cũng là lúc bạn thấy đôi khi “đủ tốt” đáng giá hơn “tối ưu” 🙂",
    s23: "← Về Lộ trình",
  },
  searchlab: {
    s1: "leo đồi",
    s2: "FRONTIER — hàng đợi FIFO (trái = ra trước)",
    s3: "FRONTIER — ngăn xếp (phải = đỉnh, ra trước)",
    s4: "FRONTIER — hàng đợi ưu tiên theo g (đã sắp xếp)",
    s5: "NHÁNH ĐANG ĐI (DLS quay lui)",
    s6: "FRONTIER — hàng đợi ưu tiên theo h",
    s7: "FRONTIER — hàng đợi ưu tiên theo f = g + h",
    s8: "FRONTIER — không có (chỉ một nút hiện tại)",
    s9: "Lab 1 · 6 đỉnh",
    s10: "Romania · 10 đỉnh",
    s11: "Kẹt cực trị địa phương → output: -1",
    s12: "Vô nghiệm → output: -1",
    s13: "⟲ Về đầu",
    s14: "◀ Lùi",
    s15: "❚❚ Dừng",
    s16: "▶ Chạy",
    s17: "Tiến ▶",
    s18: "KẸT",
  },
  f_codelab: {
    s1: "BÀN LÀM VIỆC — CHỌN THUẬT TOÁN, ĐỌC PSEUDO RỒI SOI PYTHON",
    pythonHeading: "PYTHON — KHUNG LAB 1",
  },
  scenes: {
    s1: " nút",
    s2: "b = 10, d = 12 → 10¹² nút",
    s3: "≈ 13 ngày ở tốc độ 1 triệu nút/giây · ≈ 1 petabyte bộ nhớ",
    s4: "không gian trạng thái →",
    s5: "↑ giá trị mục tiêu (−h)",
    s6: "cực trị toàn cục",
    s7: "KẸT — cực trị địa phương",
    s8: "muốn sang đỉnh cao hơn phải chấp nhận ĐI XUỐNG",
  },
};
