export const VI = {
  nav: { math: 'TOÁN NỀN', optimization: '01 Tối ưu', hill: '02 Leo đồi', lab: 'LAB N-HẬU', variants: '03 Thoát kẹt', annealing: '04 Ủ mô phỏng', beam: '05 Beam', genetic: '06 Di truyền', summary: '07 So sánh', code: '08 Code', quiz: '09 Quiz', practice: '10 Bài tập' },
  hero: {
    cover: 'Bìa', badge: 'BUỔI 6', title: 'Tìm kiếm cục bộ', eyebrow: 'CSC14003 · PHẦN II — TÌM KIẾM',
    heading: 'Đôi khi, phải đi xuống', accent: 'để lên cao hơn.',
    lead: 'Ở buổi 5, viên bi leo tới một đỉnh thấp rồi đứng im. Hôm nay tôi muốn đưa nó đi tiếp: đổi chỗ xuất phát, chấp nhận một bước lùi, hoặc cho nhiều lời giải trao đổi những phần tốt của chúng. Đích đến là một cấu hình tốt — không nhất thiết là con đường đã đi qua.',
    time: '~2,5 giờ · cả thực hành', families: '4 họ thuật toán', quiz: '8 câu tự kiểm', cta: 'Thử bàn cờ N-hậu →', back: '← Buổi 5',
    map: 'MỘT ĐỊA HÌNH · NHIỀU CÁCH TÌM', current: 'Đỉnh quanh đây', global: 'Đỉnh toàn cục',
  },
  ch1: {
    title: '🎯 Khi lời giải là <em>một cấu hình</em>', en: 'Optimization problems',
    lead: 'Bạn xếp lịch thi xong, không ai chấm thứ tự bạn đã kéo các ô trên lịch. Điều cần giữ là lịch cuối cùng: đủ phòng, không trùng ca, chi phí hợp lý. Vác theo cả cây tìm kiếm lúc này có thể là phần hành lý nặng nhất.',
    body: '<strong class="hl">Tối ưu hóa</strong> tìm trạng thái tốt nhất theo một hàm mục tiêu. Với chi phí C(s), bạn muốn cực tiểu; với giá trị V(s), bạn muốn cực đại. Bài toán tối ưu thuần túy không nhất thiết có một goal test biết sẵn; riêng N-hậu thì có: <strong class="hl-green">h(s) = 0</strong> là đủ để nhận ra nghiệm.',
    cards: [
      { title: 'Trạng thái · State', body: 'Một phương án hoàn chỉnh, dù còn sai: tất cả quân hậu đã ở trên bàn; mọi công việc đã được gán lịch. “Hoàn chỉnh” không đồng nghĩa “hợp lệ”.' },
      { title: 'Láng giềng · Neighborhood', body: 'Các phương án nhận được sau một thay đổi cho phép: dời một hậu trong cột của nó, đổi ca một công việc, hoặc đổi thứ tự vài thành phố trong hành trình.' },
      { title: 'Hàm mục tiêu · Objective', body: 'Một con số để so phương án. Tôi sẽ dùng h = số cặp hậu xung đột để giảm, rồi đổi sang fitness = số cặp không xung đột để tăng ở phần di truyền.' },
    ],
    memory: 'Tìm kiếm cục bộ thường giữ một hoặc vài cấu hình và bỏ lịch sử đường đi. <strong class="hl-yellow">O(1) cấu hình không phải O(1) byte</strong>: một bàn N-hậu vẫn cần O(N) chỗ lưu. Beam và di truyền giữ cả nhóm; lab còn lưu vết để bạn bấm Lùi — đó là bộ nhớ phục vụ giảng giải.',
    examples: 'Cùng cách nghĩ này còn dùng cho hành trình người bán hàng (TSP), hành trình quân mã, định tuyến xe, bố trí nhà xưởng, thiết kế mạch và sinh chương trình. Với TSP, cả hành trình là một trạng thái; thứ tự các lần chỉnh hành trình mới là phần có thể bỏ.',
    scale: 'Ví dụ N-hậu với cỡ 200 so với 1.000.000 gợi ra lợi thế về quy mô của các cách sửa cục bộ. Bạn đừng đọc chúng thành giới hạn cứng: khả năng xử lý phụ thuộc cách biểu diễn, cách tính xung đột và thuật toán cụ thể.',
  },
  ch2: {
    title: '⛰️ Leo đồi: giỏi quanh đây, mù phía xa', en: 'Hill-climbing & state-space landscape',
    lead: 'Một ứng viên có thể thắng mọi hàng xóm mà vẫn thua xa một ứng viên ở vùng khác. Leo đồi chỉ nhìn một bước, nên nó không có dữ kiện để phân biệt hai chuyện ấy.',
    body: 'Trên <strong class="hl">địa hình không gian trạng thái</strong>, vị trí biểu diễn trạng thái, độ cao biểu diễn giá trị. Muốn tăng V thì leo lên; muốn giảm h thì đi xuống thung lũng. Hình dưới dùng V càng lớn càng tốt; bàn cờ bên dưới dùng h càng nhỏ càng tốt.',
    rule: '<strong class="hl-cyan">Steepest-ascent hill-climbing</strong> xét mọi hàng xóm, chọn cái có giá trị cao nhất, và dừng nếu nó không tốt hơn hiện tại. Với bài cực tiểu, đảo chiều so sánh. Nó không giữ cây, không nhìn xa và không quay lại các nhánh cũ.',
    traps: [
      { title: 'Đỉnh cục bộ · Local maximum', body: 'Mọi bước quanh bạn đều đi xuống, nhưng còn đỉnh cao hơn ở xa. Với chi phí, cùng cái bẫy đó mang tên cực tiểu cục bộ.' },
      { title: 'Mặt phẳng · Plateau', body: 'Nhiều hàng xóm bằng điểm nhau. Một đỉnh phẳng không có đường tăng ngay; một vai đồi (shoulder) có thể dẫn tới dốc tăng sau vài bước ngang. Dừng ngay là bỏ lỡ cái vai đồi ấy.' },
      { title: 'Sống núi · Ridge', body: 'Hướng tốt nằm chéo với những bước mà bạn được phép đi. Các điểm trên sống núi có thể thành chuỗi cực trị cục bộ rời nhau; độ khó nằm cả ở định nghĩa láng giềng.' },
    ],
    distinction: 'Tính <strong class="hl">đầy đủ</strong> hỏi có tìm ra đích khi đích tồn tại hay không; tính <strong class="hl">tối ưu</strong> hỏi có tìm cực trị toàn cục hay không. Leo đồi đơn thuần không bảo đảm cả hai. Đừng nhầm nó với GBFS ở buổi 5: GBFS vẫn giữ frontier gồm các lựa chọn khác.',
  },
  landscape: {
    title: 'CÙNG XUẤT PHÁT · KHÁC CÁCH THOÁT KẸT', tabs: ['Leo đồi', 'Khởi động lại', 'Chấp nhận bước lùi'],
    label: 'Cách đi trên địa hình', x: 'Trạng thái s', y: 'Giá trị V(s) ↑', current: 'Hiện tại', best: 'Tốt nhất từng gặp',
    captions: [
      'Leo đồi dừng ở V = 8: hai hàng xóm đều thấp hơn. Đỉnh V = 12 vẫn nằm ngoài tầm nhìn một bước.',
      'Sau khi kẹt ở V = 8, lần chạy mới bắt đầu ở vùng khác rồi leo tới V = 12. Đoạn đứt là khởi tạo lại, không phải một nước đi lân cận.',
      'Đường minh họa này chấp nhận các bước giảm 8 → 7 → 5 → 4, rồi leo tới 12. SA có thể tạo đường như vậy, nhưng mỗi bước xấu còn phải qua phép thử xác suất.',
    ],
    note: 'Đường đi được dựng để giải thích cơ chế, không phải kết quả benchmark. Hình lặp lại từ đầu sau mỗi lượt; nét liền là bước lân cận, nét đứt là khởi động lại.',
  },
  lab: {
    title: '🧩 N-hậu: tự tay chạm vào hàm h', en: 'A complete-state search lab',
    lead: 'Tôi muốn bạn nhìn thấy số xung đột thay đổi ngay dưới tay mình. Chọn bàn 8-hậu h = 1 rồi bấm Tiến: chỉ thiếu một cặp thôi mà leo đồi vẫn chịu thua.',
    model: 'Mỗi cột có đúng một hậu; chữ số là hàng tính từ trên xuống, bắt đầu ở 1. Vì vậy có <strong class="hl">N<sup>N</sup> trạng thái</strong> và <strong class="hl">N(N − 1) hàng xóm</strong>. Với 8 hậu: 8<sup>8</sup> = 16.777.216 cấu hình, nhưng mỗi bước chỉ có 56 cách dời. Không cần duyệt hết 17 triệu bàn mới chọn được một nước.',
    pairs: 'h đếm từng <strong class="hl-red">cặp</strong> cùng hàng hoặc cùng đường chéo, kể cả khi có hậu khác nằm giữa. Ba hậu cùng hàng tạo 3 cặp, không phải 3 quân bị “phạt” độc lập. Hai cột i, j xung đột nếu rᵢ = rⱼ hoặc |rᵢ − rⱼ| = |i − j|.',
    presets: ['4 hậu · đề bài', '4 hậu · cùng hàng', '8 hậu · h = 17', '8 hậu · h = 1'], presetLabel: 'Bàn xuất phát',
    algorithms: ['Leo đồi tốt nhất', 'First-choice', 'Đi ngang ≤ 20', 'Random restart'], algorithmLabel: 'Thuật toán trên bàn cờ',
    help: 'Bấm một ô để dời hậu trong cột đó và tạo vết chạy mới. Số trong ô là h nếu chọn nước ấy; ô viền là nước có h nhỏ nhất. Trên màn hình hẹp, kéo ngang riêng bàn cờ.',
    next: 'Tiến →', previous: '← Lùi', reset: 'Về đầu vết', reseed: 'Đổi seed', seed: 'Seed', step: 'Bước', run: 'Lần chạy', evaluated: 'Hàng xóm đã chấm',
    board: 'Bàn cờ N-hậu', row: 'Hàng', column: 'Cột', costAfter: 'h sau nước đi', state: 'Cấu hình', attacks: 'Các cặp xung đột (theo cột)', noAttacks: 'Không có cặp xung đột.',
    status: { start: 'Bắt đầu: chấm h của cấu hình.', improve: 'Nhận nước có h thấp hơn.', sideways: 'Nhận nước bằng h; đã dùng một bước ngang.', restart: 'Kẹt: sinh một bàn mới, bắt đầu lần chạy tiếp.', stuck: 'Dừng: không có nước cải thiện được phép.', goal: 'Tìm được nghiệm: h = 0.', limit: 'Hết ngân sách minh họa; chưa tìm được nghiệm.' },
    budget: 'Lab dùng seed cố định để Lùi/Tiến cho cùng một vết. Phá đồng hạng ngẫu nhiên; first-choice trộn thứ tự rồi nhận nước tốt đầu tiên. Giới hạn: 20 bước ngang liên tiếp, 30 lần chạy và 240 bước nhận/khởi động lại. Hết ngân sách không chứng minh vô nghiệm.',
    experiments: 'Thử tiếp: đổi sang Random restart ở bàn h = 1; rồi so số hàng xóm đã chấm của First-choice với leo đồi tốt nhất trên bàn h = 17. Hai cách đều có thể tiến bộ nhưng trả chi phí đánh giá khác nhau.',
  },
  ch3: {
    title: '🔁 Thoát kẹt có nhiều mức giá', en: 'Sideways, stochastic, first-choice & random restart',
    lead: 'Kẹt không nhất thiết có nghĩa là bỏ cả thuật toán. Bạn có thể nới quy tắc nhận nước, giảm công tìm hàng xóm, hoặc bỏ riêng điểm xuất phát đang xấu.',
    variants: [
      { title: 'Sideways moves', body: 'Cho phép bước bằng điểm để qua vai đồi. Cần giới hạn bước ngang liên tiếp để tránh vòng lặp. Nó không tự cứu được cực trị nghiêm ngặt, nơi mọi hàng xóm đều tệ hơn.' },
      { title: 'Stochastic hill-climbing', body: 'Chọn ngẫu nhiên trong các nước tốt hơn; có thể ưu tiên nước dốc hơn bằng trọng số. Thường chậm hơn steepest-ascent về số bước, nhưng có thể đến nghiệm tốt hơn trên một số bài. Nó vẫn không nhận nước xấu.' },
      { title: 'First-choice hill-climbing', body: 'Thử hàng xóm theo thứ tự ngẫu nhiên, nhận ngay nước tốt đầu tiên. Khi mỗi trạng thái có hàng nghìn hàng xóm, bạn tránh chấm hết chỉ để tìm nước tốt nhất. Nếu lấy mẫu có giới hạn, không thấy nước tốt chưa chứng minh không có.' },
      { title: 'Random-restart hill-climbing', body: 'Chạy lại từ trạng thái ngẫu nhiên mới. Mỗi lượt có thể chạy tới lúc kẹt hoặc tới hạn thời gian; tổng số lượt cũng có thể có giới hạn. Các lượt độc lập không gộp hàng xóm hay truyền nghiệm cho nhau.' },
    ],
    statsTitle: 'MỘT THÍ NGHIỆM 8-HẬU · CÁI GIÁ CỦA VIỆC ĐI NGANG',
    stats: [ ['Không đi ngang', '14%', '4 bước khi thành công · 3 khi thất bại'], ['Cho tối đa 100 bước ngang', '94%', '21 bước khi thành công · 64 khi thất bại'] ],
    caveat: 'Đây là số liệu minh họa của thí nghiệm 8-hậu trong tài liệu học: bản thường kẹt 86% lượt. Chúng phụ thuộc cách khởi tạo, phá đồng hạng và giới hạn, không phải xác suất bảo đảm của lab này. Tôi giữ chúng để bạn thấy đổi độ linh hoạt lấy thêm công tìm kiếm.',
    restart: 'Nếu mỗi lượt độc lập thành công với cùng xác suất p > 0, thì <strong class="hl">E[số lượt] = 1/p</strong>, tính cả lượt đầu. Số lần khởi động lại sau lượt đầu có kỳ vọng (1 − p)/p. Với p = 0,14: khoảng 7,14 lượt, tức 6,14 lần khởi động lại. Tôi ghi rõ cách đếm vì hai con số ấy rất dễ bị gọi chung là “restart”.',
    probability: 'Sau r lượt độc lập, xác suất thành công là 1 − (1 − p)<sup>r</sup>. Nó tiến tới 1 khi r tăng vô hạn; <strong class="hl-yellow">một ngân sách hữu hạn vẫn có thể thất bại</strong>. Lập luận này cần khả năng khởi tạo tới vùng dẫn tới nghiệm, không áp máy móc cho mọi không gian liên tục.',
  },
  ch4: {
    title: '🔥 Ủ mô phỏng: nhận bước xấu có tính toán', en: 'Simulated annealing',
    lead: 'Khi nung rồi làm nguội vật liệu, nhiệt độ cho hệ cơ hội đổi cấu hình trước khi ổn định. Thuật toán mượn ý tưởng đó: ban đầu dễ nhận bước lùi, về sau kén dần. Nhiệt độ ở đây là tham số, không phải bạn cần mua lò nung.',
    body: 'Mỗi bước, SA <strong class="hl">chọn ngẫu nhiên một hàng xóm</strong>. Với bài cực tiểu, đặt ΔC = C(next) − C(current). Bước tốt hơn hoặc bằng điểm được nhận; bước xấu (ΔC > 0) được nhận với xác suất e<sup>−ΔC/T</sup>, khi T > 0.',
    sign: 'Nếu đang cực đại hóa giá trị như hình địa hình, dùng ΔV = V(next) − V(current) và xác suất e<sup>ΔV/T</sup> cho bước xấu ΔV < 0. Hai công thức cùng một ý. Tôi thường viết chữ “chi phí tăng là xấu” cạnh code để khỏi lật dấu.',
    schedule: 'Một lịch dễ cài là T(t) = T₀α<sup>t</sup>, với 0 &lt; α &lt; 1. Nguội nhanh thì đóng băng sớm; nguội chậm thì tốn thêm lượt thử. Dừng ở T = 0 hoặc khi hết ngân sách. Code bên dưới trả cả current lẫn best: <strong class="hl-yellow">trạng thái cuối có thể tệ hơn trạng thái tốt nhất từng gặp</strong>.',
    guarantee: 'Bảo đảm hội tụ về tối ưu với xác suất tiến tới 1 cần giả thiết về không gian/truy cập trạng thái và lịch nguội đủ chậm trong giới hạn thời gian vô hạn. Lịch nhân hữu hạn trong ví dụ <strong class="hl">không có bảo đảm ấy</strong>. Đôi khi nó thoát kẹt; đôi khi nó chỉ đi chơi lâu hơn.',
    experiment: 'Thử giữ ΔC = 2 rồi hạ T từ 10 xuống 1: xác suất nhận bước xấu giảm từ khoảng 81,87% xuống 13,53%. Bạn đang thay mức sẵn lòng mạo hiểm, không thay mức xấu của nước đi.',
  },
  annealing: { title: 'BÀN ĐIỀU KHIỂN XÁC SUẤT', temperature: 'Nhiệt độ T', delta: 'Chi phí tăng ΔC', probability: 'Xác suất chấp nhận', sample: 'Số thử u = 0,30', accept: 'Nhận nếu u < P', reject: 'Với u này: từ chối', accepted: 'Với u này: chấp nhận', frozen: 'T = 0: dừng lịch, không thực hiện phép chia.', note: 'u được giữ cố định để bạn so cùng một phép thử. Đây là thí nghiệm một quyết định, không phải tần suất của nhiều lần chạy.' },
  ch5: {
    title: 'Nhiều ứng viên, một cuộc tuyển chọn', en: 'Local beam search',
    lead: 'Hai người leo hai ngọn đồi rồi mỗi người giữ đường riêng vẫn có thể cùng kẹt. Beam search cho phép cả nhóm dồn công vào vùng đang có triển vọng — và vì thế cũng dễ kéo nhau vào cùng một cái bẫy.',
    body: 'Khởi tạo k trạng thái ngẫu nhiên. Sinh tất cả hàng xóm của cả k trạng thái, kiểm tra đích nếu bài có goal test, rồi <strong class="hl-cyan">giữ k ứng viên tốt nhất từ một danh sách chung</strong>. Lặp lại. Hai suất mới có thể đều là con của cùng một cha.',
    diversity: 'Khác với k lượt restart độc lập, các nhánh ở đây chia sẻ kết quả qua tuyển chọn chung. Khi mọi ứng viên tụ vào một vùng, bạn mất đa dạng và có thể trả tiền cho một phiên leo đồi đông người.',
    stochastic: '<strong class="hl">Stochastic beam</strong> lấy mẫu k ứng viên, ưu tiên giá trị tốt thay vì luôn cắt top-k. Nó giúp duy trì cơ hội cho vùng khác, nhưng không bảo đảm luôn giữ được đa dạng. Với bài giảm chi phí, phải đổi chi phí thành trọng số ưu tiên phù hợp; không cho chi phí lớn xác suất lớn hơn.',
  },
  beam: { title: 'k = 2 · ĐIỂM V CÀNG CAO CÀNG TỐT', tabs: ['Tuyển chọn chung', 'Hai lượt độc lập'], label: 'Cách chia sẻ ứng viên', parents: 'Hai trạng thái đang giữ', pool: 'Hàng xóm được sinh', chosen: 'Hai ứng viên tiếp theo', phases: ['Giữ hai trạng thái A, B', 'Sinh và chấm toàn bộ hàng xóm', 'Tuyển hai ứng viên tiếp theo', 'Giữ kết quả để so sánh'], notes: ['Beam giữ A:9 và A:8. Cả hai suất thuộc vùng A; vùng B bị bỏ.', 'Hai lượt độc lập giữ A:9 và B:6. Mỗi lượt tự chọn, không tranh suất với lượt kia.'], note: 'Đây là một thế hệ minh họa với điểm đã cho. Mỗi vòng hình lặp lại cùng ví dụ, không giả vờ sinh thêm thế hệ.' },
  ch6: {
    title: '🧬 Thuật toán di truyền: ghép, rồi thử', en: 'Genetic algorithms',
    lead: 'Hai lịch làm việc có thể tốt ở hai nửa khác nhau. Thay vì chỉ sửa một lịch, bạn thử ghép nửa đầu của lịch này với nửa sau của lịch kia. Mấu chốt nằm ở chữ “thử”: hai bố mẹ tốt vẫn có thể sinh một phương án tệ.',
    body: 'GA gần với stochastic beam nhưng tạo ứng viên bằng <strong class="hl-purple">hai cha mẹ</strong>. Bắt đầu từ quần thể k cá thể, chấm fitness, chọn cha mẹ, lai ghép, đột biến và thay thế quần thể; dừng khi đủ tốt hoặc hết ngân sách. Một cá thể có thể được chọn nhiều lần hoặc không được chọn.',
    encoding: 'Một cá thể là chuỗi trên bảng ký hiệu hữu hạn. Với 8-hậu, dùng 8 số từ 1 đến 8, mỗi số là hàng của hậu ở cột tương ứng. Cũng có thể mã hóa mỗi hàng bằng 3 bit (ánh xạ 1…8 thành 000…111): tổng cộng <strong class="hl">24 bit</strong>. Chuỗi hàng này cho phép lặp, không phải hoán vị.',
    fitness: 'Fitness càng cao càng tốt. N-hậu có N(N − 1)/2 cặp, nên <strong class="hl-green">fitness = N(N − 1)/2 − h</strong>. Với 8 hậu, mức tối đa là 28. Quần thể 24748552, 32752411, 24415124, 32543213 có fitness 24, 23, 20, 11: xác suất chọn tương ứng 24/78, 23/78, 20/78, 11/78, xấp xỉ 31%, 29%, 26%, 14%.',
    roulette: 'Chọn theo roulette: P(i) = fitness(i) / tổng fitness. Trọng số phải không âm; nếu tất cả bằng 0 thì phép chia chưa xác định, cần quy tắc dự phòng như chọn đều. Các dải màu dưới đây rộng đúng theo xác suất, không có nghĩa mỗi thế hệ phải chọn đúng tỷ lệ đó.',
    crossover: 'Lai một điểm: lấy tiền tố cha A và hậu tố cha B. Ví dụ cắt sau gene 3: 327|52411 + 247|48552 → 32748552; con đối ứng là 24752411. Có thể nhảy sang vùng xa của không gian. Tôi dùng vị trí cắt bên trong chuỗi; cắt ở cuối chỉ chép lại một cha.',
    mutation: 'Đột biến thêm biến thiên: mỗi gene có xác suất nhỏ, độc lập, để đổi hàng. Một biến thể khác là tung một phép thử trên cả cá thể rồi chỉ đổi một gene. <strong class="hl">Hai quy tắc không cùng phân phối</strong>; code ở mục 08 dùng xác suất trên từng gene. Lab cho bạn chọn một gene để thấy hậu quả trực tiếp.',
    caveat: 'GA cần chọn kích thước quần thể, lịch dừng, phép lai, tỷ lệ đột biến và cách biểu diễn. Nếu thay toàn bộ thế hệ mà không giữ elite, nghiệm tốt nhất có thể mất. Với TSP, lai chuỗi thông thường có thể lặp/mất thành phố: cần phép lai bảo toàn hoán vị hoặc sửa con. Genetic programming còn tiến hóa cấu trúc chương trình, không chỉ một chuỗi bit.',
    conclusion: 'Lai ghép giúp khám phá vùng mà một bước cục bộ khó chạm tới, và GA có thể giải các bài khó với ít kiến thức miền được mã hóa trực tiếp. Nhưng ít kiến thức miền không có nghĩa không cần thiết kế. Tôi sẽ so với restart đơn giản cùng ngân sách trước khi kết luận GA tốt hơn; không có thứ hạng chung cho mọi bài toán.',
  },
  genetic: { title: 'XƯỞNG LAI GHÉP', population: 'Quần thể 4-hậu · tính trước, mở sau', reveal: 'Hiện fitness và xác suất', hide: 'Ẩn kết quả', individual: 'Cá thể', score: 'Fitness', chance: 'P(chọn)', parentA: 'Cha A', parentB: 'Cha B', cut: 'Cắt sau gene', child: 'Con sau lai', mutated: 'Con sau đột biến', column: 'Gene cần đổi (cột)', row: 'Hàng mới', apply: 'Áp dụng đột biến', reset: 'Bỏ đột biến',
    note: 'Đổi điểm cắt sẽ bỏ đột biến cũ. Nhãn A/B trong từng ô cho biết gene đến từ cha nào; M đánh dấu gene thực sự đã đổi. Hãy so h và fitness trước/sau, đừng mặc định con tốt hơn cha.',
    answer: 'Với 4 hậu có 6 cặp: fitness lần lượt 2, 3, 1, 0; tổng bằng 6. Xác suất là 1/3, 1/2, 1/6, 0. Cá thể 4321 không được chọn làm cha theo đúng quy tắc này, nhưng một phép đột biến về sau vẫn có thể sinh ra nó.',
  },
  ch7: {
    title: 'Chọn theo cái giá bạn trả được', en: 'A comparison you can use',
    lead: 'Câu hỏi thực dụng là bạn có bao nhiêu lượt chấm điểm, bao nhiêu bộ nhớ và chịu được mức rủi ro nào. Một tên thuật toán nghe giống sinh học không tự làm lời giải tốt hơn.',
    headers: ['Cách tìm', 'Giữ gì?', 'Thoát kẹt bằng gì?', 'Điểm cần nhớ'],
    rows: [
      ['Hill-climbing', 'Một cấu hình', 'Bản thường không thoát', 'Rẻ về số cấu hình; có thể kẹt rất sớm.'],
      ['Random restart', 'Một lượt đang chạy', 'Đổi điểm xuất phát', 'Xác suất thành công tăng qua các lượt độc lập; hữu hạn vẫn có thể trượt.'],
      ['Simulated annealing', 'Một current; có thể thêm best', 'Nhận bước xấu theo nhiệt độ', 'Lịch nguội và ngân sách quyết định nhiều; không hứa tối ưu hữu hạn.'],
      ['Local beam', 'k cấu hình + ứng viên', 'Gộp lựa chọn từ nhiều vùng', 'Có thể mất đa dạng; không phải k lần leo độc lập.'],
      ['Genetic algorithm', 'k cá thể + thế hệ mới', 'Chọn lọc, lai ghép, đột biến', 'Nhạy với biểu diễn; con và thế hệ sau có thể kém hơn.'],
    ],
    cost: 'Nếu một cấu hình có b hàng xóm và mỗi lần chấm tốn E, một bước steepest-ascent tốn khoảng O(bE). Beam sinh đủ ứng viên tốn O(kbE), và cần thêm công chọn top-k. Nói chung, các thuật toán này không có một thời gian cố định tới nghiệm. Đo số lần chấm mục tiêu cùng chất lượng nghiệm sẽ công bằng hơn chỉ đếm số vòng.',
    bridge: 'Buổi 3–5 giữ đường đi; buổi 6 sửa cấu hình. Buổi 7 thêm một đối thủ cố làm bạn thua; buổi 8 sẽ mô tả ràng buộc của N-hậu một cách có hệ thống. Cùng một bàn cờ, nhưng câu hỏi quyết định thuật toán khác nhau.',
  },
  code: {
    title: 'Từ quy tắc đến code chạy được', en: 'Python · standard library only',
    lead: 'Tôi để cùng một hàm h phục vụ ba cách tìm để bạn chỉ nhìn phần quy tắc đổi khác. Copy cả khối đang mở vào một file .py; mỗi tab đã có đủ helper và ví dụ chạy.',
    tabs: ['Hill-climbing', 'Simulated annealing', 'Genetic algorithm'], label: 'Mã Python',
    notes: [
      'Bản này giảm h, xét đủ hàng xóm và phá đồng hạng bằng thứ tự cố định. Dừng khi best ≥ current; vì thế có thể trả bàn chưa phải nghiệm. Bàn 83742516 cho kết quả h = 1.',
      'Bản này chọn một hàng xóm ngẫu nhiên, dùng exp(−delta/T), giữ riêng best và current, và dừng sau tối đa 2.000 phép thử. Nhiệt độ nhân 0,995 mỗi bước. Seed 42 giúp lặp lại trong cùng môi trường Python; kết quả khác môi trường không phải chứng minh sai thuật toán.',
      'Bản này dùng roulette (chọn đều nếu tổng fitness bằng 0), lai bên trong chuỗi, mutation độc lập 0,05 mỗi gene và tối đa 200 thế hệ. Nó giữ best bên ngoài để trả về, nhưng không đưa elite vào thế hệ mới. Vì vậy fitness của best đã thấy không giảm (h(best) không tăng), còn fitness tốt nhất trong quần thể thì có thể giảm.',
    ],
    task: 'Bài thực hành nhỏ: thêm bộ đếm số lần gọi h, rồi chạy nhiều seed với cùng ngân sách đánh giá. Ghi cả tỷ lệ tìm được h = 0 và h nhỏ nhất khi chưa tìm thấy. Một lần may mắn không đủ để xếp hạng thuật toán.',
  },
  quiz: { title: 'Tự kiểm trước khi rời bàn cờ', en: '8 questions · feedback by topic', lead: 'Tám câu ngắn về mô hình, bước đi và xác suất. Hãy chốt đáp án trước khi đọc giải thích; điểm cuối buổi được lưu vào đúng buổi 6 trong lộ trình.' },
  hw: {
    title: '✏️ Đến lượt bạn tự dựng lời giải', en: 'Practice & self-check',
    lead: 'Tôi muốn bạn tự tính trên giấy trước, rồi dùng lab để kiểm. Phần gợi ý chỉ mở khi bạn cần đối chiếu cách làm.',
    cards: [
      { title: '01 · Bốn quân hậu', body: 'Với trạng thái S = (1, 2, 1, 4), tính số trạng thái, số hàng xóm và h(S). Tìm một chuỗi bước hợp lệ tới h = 0 bằng một biến thể leo đồi; ghi h ở mỗi nút. Preset đầu của lab chính là bàn này.', hint: 'Có 4⁴ = 256 trạng thái và 4 × 3 = 12 hàng xóm. h(S) = 5: các cặp cột (1,2), (1,3), (1,4), (2,3), (2,4). Một đường giảm h là 1214 (5) → 2214 (3) → 2414 (1) → 2413 (0). Mỗi bước chỉ đổi một cột; đây là lựa chọn cải thiện, không yêu cầu luôn dốc nhất.' },
      { title: '02 · Tô màu đồ thị', body: 'Dùng đồ thị A–H trong tệp bài tập. Một trạng thái gán đỏ/xanh/vàng cho từng đỉnh; h là số cạnh hai đầu cùng màu. Định nghĩa láng giềng bằng đổi màu một đỉnh, rồi sửa cấu hình ban đầu tới h = 0.', hint: 'Hình có 8 đỉnh A–H dù dòng mô tả chỉ ghi a…g. Theo hình: 3⁸ = 6.561 trạng thái, 8 × 2 = 16 hàng xóm. Ban đầu chỉ C–G và G–H xung đột. Đổi C từ xanh sang đỏ, rồi H từ xanh sang vàng: h đi 2 → 1 → 0. G vẫn xanh; mỗi lần chỉ đổi một đỉnh.' },
      { title: '03 · Chọn lọc bằng fitness', body: 'Tự tính fitness và P(chọn) của 2341, 2132, 1232, 4321. Sau đó thử lai 2341 và 2132 ở từng điểm cắt bên trong, tính fitness các con. Bạn có tìm được một con kém cả hai cha mẹ không?', hint: 'Fitness cha mẹ là 2, 3, 1, 0; tổng 6, xác suất 1/3, 1/2, 1/6, 0. Cắt 2341 và 2132 sau gene 2 cho 2332, fitness = 2: không hơn cha tốt hơn. Cắt sau gene 1 cho 2132, fitness = 3; sau gene 3 cho 2342, fitness = 2. Với chiều lai này không có con kém cả hai cha mẹ. Nhưng lai hai nghiệm 2413 và 3142 (fitness = 6) sau gene 2 cho 2442, fitness = 2: một phản ví dụ rõ ràng cho ý nghĩ con luôn tốt hơn.' },
    ],
    graphNote: 'Ban đầu: D đỏ; B, F vàng; A, C, E, G, H xanh. Cạnh: AB, BC, AD, BD, BG, CG, DE, DF, DG, FG, GH. Nét đứt đánh dấu hai cạnh xung đột CG và GH.',
    hint: 'Mở gợi ý / đối chiếu', file: 'Mở tệp bài tập gốc ↗',
    checks: ['Tôi phân biệt cấu hình cuối với đường đi tới cấu hình.', 'Tôi đếm h theo cặp và tính được Nᴺ, N(N − 1).', 'Tôi phân biệt plateau, shoulder, ridge và cực trị cục bộ.', 'Tôi giải thích được first-choice, stochastic, sideways và restart khác nhau ở đâu.', 'Tôi viết đúng dấu của xác suất SA cho bài cực tiểu.', 'Tôi chọn k ứng viên beam từ danh sách chung.', 'Tôi tính fitness, xác suất chọn và kiểm tra tính hợp lệ sau lai.', 'Tôi không biến một lần chạy thành lời hứa tìm nghiệm tối ưu.'],
    next: 'Tiếp theo là Buổi 7 — Tìm kiếm đối kháng: lúc này, quân bên kia sẽ không đứng yên cho bạn tối ưu nữa.', roadmap: 'Về lộ trình →',
  },
};
