import type { VI } from './lesson06.text.vi';
export const EN = {
  nav: { math: 'MATH PRIMER', optimization: '01 Optimization', hill: '02 Hill-climbing', lab: 'QUEENS LAB', variants: '03 Escaping traps', annealing: '04 Annealing', beam: '05 Beam', genetic: '06 Genetics', summary: '07 Compare', code: '08 Code', quiz: '09 Quiz', practice: '10 Practice' },
  hero: {
    cover: 'Cover', badge: 'SESSION 6', title: 'Local search', eyebrow: 'CSC14003 · PART II — SEARCHING',
    heading: 'Sometimes, you go down', accent: 'to climb higher.',
    lead: 'In Session 5, the ball climbed a low peak and stopped. Today I want to get it moving again: change the starting point, accept a backward step, or let several solutions exchange their useful parts. The destination is a good configuration — the path taken need not be part of the answer.',
    time: '~2.5 hours · including practice', families: '4 algorithm families', quiz: '8 self-check questions', cta: 'Try the N-queens board →', back: '← Session 5',
    map: 'ONE LANDSCAPE · DIFFERENT SEARCHES', current: 'A nearby peak', global: 'The global peak',
  },
  ch1: {
    title: '🎯 When the answer is <em>a configuration</em>', en: 'Optimization problems',
    lead: 'Once you have an exam timetable, nobody grades the order in which you dragged its blocks around. What matters is the final schedule: enough rooms, no clashes, reasonable cost. Carrying the entire search tree can become your heaviest piece of luggage.',
    body: '<strong class="hl">Optimization</strong> seeks the best state according to an objective function. For a cost C(s), you want a minimum; for a value V(s), a maximum. Pure optimization need not have a goal test known in advance; N-queens does: <strong class="hl-green">h(s) = 0</strong> identifies a solution.',
    cards: [
      { title: 'State', body: 'A complete candidate, even if it still violates constraints: every queen is on the board; every job has a slot. “Complete” does not mean “valid”.' },
      { title: 'Neighborhood', body: 'The candidates reachable through one allowed change: moving a queen within its column, changing a job’s slot, or rearranging some cities in a tour.' },
      { title: 'Objective', body: 'A number for comparing candidates. I’ll minimize h, the number of attacking queen pairs, then switch to maximizing fitness, the number of non-attacking pairs, for genetic algorithms.' },
    ],
    memory: 'Local search usually keeps one or a few configurations and discards the path history. <strong class="hl-yellow">O(1) configurations is not O(1) bytes</strong>: an N-queens board still takes O(N) storage. Beam search and genetic algorithms keep a group; the lab also saves a trace so you can go back — that extra memory serves the explanation.',
    examples: 'The same approach applies to the traveling salesperson problem (TSP), the knight’s tour, vehicle routing, factory layouts, circuit design and program generation. In TSP, an entire tour is one state; it’s the sequence of edits to that tour that can be discarded.',
    scale: 'N-queens examples at sizes 200 versus 1,000,000 suggest the scaling advantage of local repair. Don’t read these as hard limits: capacity depends on representation, conflict evaluation and the particular algorithm.',
  },
  ch2: {
    title: '⛰️ Hill-climbing: a local view', en: 'Hill-climbing & state-space landscape',
    lead: 'A candidate can beat every neighbor and still lose badly to a candidate elsewhere. Hill-climbing sees just one step ahead, so it has no evidence to tell those situations apart.',
    body: 'On a <strong class="hl">state-space landscape</strong>, position represents state and elevation represents value. To increase V, climb uphill; to decrease h, descend into a valley. The picture below uses higher-is-better V; the chessboard below it uses lower-is-better h.',
    rule: '<strong class="hl-cyan">Steepest-ascent hill-climbing</strong> examines every neighbor, picks the highest-valued one, and stops if it is no better than the current state. Reverse the comparison for minimization. It keeps no tree, looks no further ahead and does not return to old branches.',
    traps: [
      { title: 'Local maximum', body: 'Every nearby step goes down, yet a higher peak exists elsewhere. When minimizing cost, the same trap is called a local minimum.' },
      { title: 'Plateau', body: 'Several neighbors have the same value. A flat peak offers no immediate uphill route; a shoulder can lead to rising ground after some sideways steps. Stopping immediately misses that shoulder.' },
      { title: 'Ridge', body: 'The useful direction lies diagonally to the moves you are allowed to make. Points along a ridge can form a chain of disconnected local optima; the neighborhood definition is part of the difficulty.' },
    ],
    distinction: '<strong class="hl">Completeness</strong> asks whether a goal will be found if one exists; <strong class="hl">optimality</strong> asks whether a global extremum will be found. Plain hill-climbing guarantees neither. Don’t confuse it with GBFS from Session 5: GBFS still keeps a frontier of alternatives.',
  },
  landscape: {
    title: 'SAME START · DIFFERENT WAYS OUT', tabs: ['Hill-climbing', 'Random restart', 'Accept a setback'],
    label: 'Search strategy on the landscape', x: 'State s', y: 'Value V(s) ↑', current: 'Current', best: 'Best seen',
    captions: [
      'Hill-climbing stops at V = 8: both neighbors are lower. The V = 12 peak is still beyond its one-step view.',
      'After getting stuck at V = 8, a new run starts elsewhere and climbs to V = 12. The dashed segment is reinitialization, not a neighboring move.',
      'This illustrative path accepts the drops 8 → 7 → 5 → 4, then climbs to 12. SA can produce a path like this, but each worsening move still has to pass a probability test.',
    ],
    note: 'These paths illustrate mechanisms; they are not optimizer benchmarks. The picture starts over after each cycle; solid lines mean neighboring moves and dashed lines mean a restart.',
  },
  lab: {
    title: '🧩 N-queens: put your hands on h', en: 'A complete-state search lab',
    lead: 'I want you to see the conflict count change under your fingertips. Choose the 8-queens h = 1 board and click Next: only one pair is wrong, yet hill-climbing gives up.',
    model: 'Each column contains exactly one queen; each digit is its row, counted from the top starting at 1. That gives <strong class="hl">N<sup>N</sup> states</strong> and <strong class="hl">N(N − 1) neighbors</strong>. For 8 queens: 8<sup>8</sup> = 16,777,216 configurations, but only 56 moves per step. You don’t need to inspect all 17 million boards to choose a move.',
    pairs: 'h counts each <strong class="hl-red">pair</strong> sharing a row or diagonal, even with another queen between them. Three queens in a row contribute 3 pairs, not independent penalties on 3 queens. Columns i, j conflict if rᵢ = rⱼ or |rᵢ − rⱼ| = |i − j|.',
    presets: ['4 queens · exercise', '4 queens · same row', '8 queens · h = 17', '8 queens · h = 1'], presetLabel: 'Starting board',
    algorithms: ['Steepest ascent', 'First-choice', 'Sideways ≤ 20', 'Random restart'], algorithmLabel: 'Chessboard algorithm',
    help: 'Click a square to move that column’s queen and start a new trace. Numbers show h after that move; outlined squares have the lowest resulting h. On a narrow screen, scroll the board itself horizontally.',
    next: 'Next →', previous: '← Back', reset: 'Trace start', reseed: 'Change seed', seed: 'Seed', step: 'Step', run: 'Run', evaluated: 'Neighbors evaluated',
    board: 'N-queens board', row: 'Row', column: 'Column', costAfter: 'h after move', state: 'Configuration', attacks: 'Attacking pairs (by column)', noAttacks: 'No attacking pairs.',
    status: { start: 'Start: evaluate this configuration’s h.', improve: 'Accept a move with lower h.', sideways: 'Accept equal h; use one sideways move.', restart: 'Stuck: generate a new board for the next run.', stuck: 'Stop: no permitted improving move remains.', goal: 'Solution found: h = 0.', limit: 'Illustration budget exhausted; no solution found.' },
    budget: 'The lab fixes its seed so Back/Next replay the same trace. Ties are random; first-choice shuffles candidates and accepts the first improvement. Limits: 20 consecutive sideways moves, 30 runs and 240 accepted moves/restarts. Exhausting the budget does not prove that no solution exists.',
    experiments: 'Next, try Random restart on the h = 1 board; then compare evaluated-neighbor counts for First-choice and steepest ascent on the h = 17 board. Both may improve, but they pay different evaluation costs.',
  },
  ch3: {
    title: '🔁 Different ways out, different costs', en: 'Sideways, stochastic, first-choice & random restart',
    lead: 'Getting stuck need not mean abandoning the algorithm. You can loosen the acceptance rule, spend less effort choosing a neighbor, or discard only the unlucky starting point.',
    variants: [
      { title: 'Sideways moves', body: 'Allow equal-valued moves to cross a shoulder. Cap consecutive sideways moves to avoid loops. This alone cannot escape a strict local optimum, where every neighbor is worse.' },
      { title: 'Stochastic hill-climbing', body: 'Choose randomly among improving moves; weights can favor steeper moves. It often takes more steps than steepest ascent, but can reach better solutions on some problems. It still rejects worsening moves.' },
      { title: 'First-choice hill-climbing', body: 'Try neighbors in random order and accept the first improvement. With thousands of neighbors, you avoid scoring every one just to find the best. With a sampling budget, failing to sample an improvement does not prove none exists.' },
      { title: 'Random-restart hill-climbing', body: 'Run again from a fresh random state. Each run can continue until stuck or until a time limit; the total run count can also be bounded. Independent runs do not pool neighbors or pass solutions to each other.' },
    ],
    statsTitle: 'AN 8-QUEENS EXPERIMENT · THE COST OF SIDEWAYS MOVES',
    stats: [ ['No sideways moves', '14%', '4 steps on success · 3 on failure'], ['Up to 100 sideways moves', '94%', '21 steps on success · 64 on failure'] ],
    caveat: 'These are illustrative results from the course material’s 8-queens experiment: the plain version gets stuck on 86% of runs. They depend on initialization, tie-breaking and limits, not a guaranteed success rate for this lab. I keep them here to show how flexibility costs more search effort.',
    restart: 'If independent runs each succeed with the same probability p > 0, then <strong class="hl">E[runs] = 1/p</strong>, including the first run. Expected restarts after that first run are (1 − p)/p. With p = 0.14: about 7.14 runs, or 6.14 restarts. I spell out the counting because both quantities easily get called “restarts”.',
    probability: 'After r independent runs, success probability is 1 − (1 − p)<sup>r</sup>. It approaches 1 as r grows without bound; <strong class="hl-yellow">a finite budget can still fail</strong>. This argument needs initialization to reach a region leading to a solution; it does not automatically apply to every continuous space.',
  },
  ch4: {
    title: '🔥 Annealing: accept setbacks deliberately', en: 'Simulated annealing',
    lead: 'Heating and cooling a material lets its structure rearrange before settling. The algorithm borrows that idea: accept backward steps readily at first, then become more selective. Temperature is a parameter here; you don’t need to buy a furnace.',
    body: 'At each step, SA <strong class="hl">chooses a random neighbor</strong>. For minimization, define ΔC = C(next) − C(current). Improving or equal-valued moves are accepted; a worsening move (ΔC > 0) is accepted with probability e<sup>−ΔC/T</sup>, for T > 0.',
    sign: 'If you maximize value as in the landscape picture, use ΔV = V(next) − V(current) and probability e<sup>ΔV/T</sup> for a worsening move with ΔV < 0. The formulas express the same idea. I usually write “higher cost is worse” beside the code to avoid flipping the sign.',
    schedule: 'An easy schedule to implement is T(t) = T₀α<sup>t</sup>, with 0 &lt; α &lt; 1. Fast cooling can freeze the search too soon; slow cooling costs more trials. Stop at T = 0 or when the budget runs out. The code below returns both current and best: <strong class="hl-yellow">the final state may be worse than the best state seen</strong>.',
    guarantee: 'Convergence to the optimum with probability approaching 1 requires assumptions about the space and state reachability, plus sufficiently slow cooling in the infinite-time limit. The finite geometric schedule in this example <strong class="hl">has no such guarantee</strong>. Sometimes it escapes; sometimes it just wanders longer.',
    experiment: 'Hold ΔC = 2 and lower T from 10 to 1: acceptance probability falls from about 81.87% to 13.53%. You are changing the willingness to take a risk, not how bad the move is.',
  },
  annealing: { title: 'PROBABILITY WORKBENCH', temperature: 'Temperature T', delta: 'Cost increase ΔC', probability: 'Acceptance probability', sample: 'Trial value u = 0.30', accept: 'Accept if u < P', reject: 'For this u: reject', accepted: 'For this u: accept', frozen: 'T = 0: stop the schedule; do not divide.', note: 'u is fixed so you can compare the same decision. This is one decision experiment, not a frequency measured over many runs.' },
  ch5: {
    title: 'Several candidates, one selection pool', en: 'Local beam search',
    lead: 'Two people climbing separate hills can both get stuck if each keeps their own route. Beam search lets the group concentrate on a promising region — which can also pull everyone into the same trap.',
    body: 'Initialize k random states. Generate all neighbors of all k states, check for a goal if the problem has a goal test, then <strong class="hl-cyan">keep the k best candidates from one shared list</strong>. Repeat. Both new slots may belong to children of the same parent.',
    diversity: 'Unlike k independent restarts, these branches share results through pooled selection. When every candidate crowds into the same region, diversity disappears and you may be paying for hill-climbing with a bigger crowd.',
    stochastic: '<strong class="hl">Stochastic beam</strong> samples k candidates with a preference for good values instead of always taking the top-k. This gives other regions a chance, but does not guarantee sustained diversity. For cost minimization, convert cost into suitable preference weights; don’t give higher costs higher probability.',
  },
  beam: { title: 'k = 2 · HIGHER V IS BETTER', tabs: ['Shared selection', 'Two independent runs'], label: 'How candidates are shared', parents: 'Two retained states', pool: 'Generated neighbors', chosen: 'Next two candidates', phases: ['Keep two states A, B', 'Generate and score all neighbors', 'Select two next candidates', 'Hold the result for comparison'], notes: ['Beam keeps A:9 and A:8. Both slots go to region A; region B is discarded.', 'Independent runs keep A:9 and B:6. Each makes its own choice without competing for the other’s slot.'], note: 'This is one illustrative generation with supplied scores. Each cycle repeats the same example; it does not claim to generate further generations.' },
  ch6: {
    title: '🧬 Genetic algorithms: combine, then test', en: 'Genetic algorithms',
    lead: 'Two work schedules may be good in different halves. Instead of editing only one, try joining the first half of one to the second half of the other. The key word is “try”: good parents can still produce a poor candidate.',
    body: 'GA resembles stochastic beam search but creates candidates from <strong class="hl-purple">two parents</strong>. Start with a population of k individuals, score fitness, select parents, cross over, mutate and replace the population; stop when good enough or out of budget. An individual may be selected several times or not at all.',
    encoding: 'An individual is a string over a finite alphabet. For 8-queens, use 8 numbers from 1 to 8, each giving the queen’s row in that column. You can also encode each row with 3 bits (mapping 1…8 to 000…111): <strong class="hl">24 bits</strong> in total. This row string permits repeats; it is not a permutation.',
    fitness: 'Higher fitness is better. N-queens has N(N − 1)/2 pairs, so <strong class="hl-green">fitness = N(N − 1)/2 − h</strong>. For 8 queens, the maximum is 28. The population 24748552, 32752411, 24415124, 32543213 has fitness 24, 23, 20, 11: selection probabilities are 24/78, 23/78, 20/78, 11/78, approximately 31%, 29%, 26%, 14%.',
    roulette: 'Roulette selection uses P(i) = fitness(i) / total fitness. Weights must be nonnegative; when all are 0, the division is undefined, so provide a fallback such as uniform selection. The bands below have widths proportional to probability; that does not mean each generation must select exactly those proportions.',
    crossover: 'One-point crossover takes parent A’s prefix and parent B’s suffix. Cut after gene 3: 327|52411 + 247|48552 → 32748552; the reciprocal child is 24752411. This can jump far across the space. I use cuts inside the string; cutting at the end merely copies a parent.',
    mutation: 'Mutation introduces variation: each gene has a small, independent probability of changing row. Another variant makes one probability test for the whole individual and changes just one gene. <strong class="hl">These produce different distributions</strong>; the code in section 08 uses per-gene probability. The lab lets you choose one gene to inspect the effect directly.',
    caveat: 'GA requires choices about population size, stopping, crossover, mutation rate and representation. Replacing a whole generation without elitism can lose the best solution. For TSP, ordinary string crossover can repeat or omit cities: use permutation-preserving crossover or repair the child. Genetic programming evolves program structure, not just a bit string.',
    conclusion: 'Crossover explores regions that a single local move may struggle to reach, and GA can tackle difficult problems with little domain knowledge encoded directly. But little domain knowledge does not mean no design work. I’d compare it with simple restarts under the same budget before calling it better; no ranking holds across all problems.',
  },
  genetic: { title: 'CROSSOVER WORKSHOP', population: '4-queens population · calculate before revealing', reveal: 'Reveal fitness and probabilities', hide: 'Hide answers', individual: 'Individual', score: 'Fitness', chance: 'P(selection)', parentA: 'Parent A', parentB: 'Parent B', cut: 'Cut after gene', child: 'Child after crossover', mutated: 'Child after mutation', column: 'Gene to change (column)', row: 'New row', apply: 'Apply mutation', reset: 'Remove mutation',
    note: 'Changing the cut removes the previous mutation. A/B labels show each gene’s parent; M marks a gene that actually changed. Compare h and fitness before and after; don’t assume the child improves on its parents.',
    answer: 'With 4 queens there are 6 pairs: fitness values are 2, 3, 1, 0, totaling 6. Probabilities are 1/3, 1/2, 1/6, 0. Individual 4321 cannot be selected as a parent under this rule, although a later mutation could still produce it.',
  },
  ch7: {
    title: 'Choose the cost you can afford', en: 'A comparison you can use',
    lead: 'The practical questions are how many evaluations you can afford, how much memory you have and how much risk you can tolerate. A name inspired by biology does not make an answer better by itself.',
    headers: ['Method', 'What is kept?', 'How does it escape?', 'Remember'],
    rows: [
      ['Hill-climbing', 'One configuration', 'The plain version does not', 'Few retained configurations; may get stuck early.'],
      ['Random restart', 'One active run', 'Change the starting point', 'Success probability grows across independent runs; finite runs can still fail.'],
      ['Simulated annealing', 'One current; optionally best', 'Accept setbacks by temperature', 'Cooling and budget matter greatly; no finite-time optimum promised.'],
      ['Local beam', 'k configurations + candidates', 'Pool choices from several regions', 'Can lose diversity; not k independent climbs.'],
      ['Genetic algorithm', 'k individuals + next generation', 'Selection, crossover, mutation', 'Representation matters; children and later generations may be worse.'],
    ],
    cost: 'If a configuration has b neighbors and each evaluation costs E, one steepest-ascent step costs about O(bE). Generating all beam candidates costs O(kbE), plus top-k selection. In general, these methods have no fixed time to a solution. Comparing objective evaluations alongside solution quality is fairer than counting iterations alone.',
    bridge: 'Sessions 3–5 keep paths; Session 6 repairs configurations. Session 7 adds an opponent trying to make you lose; Session 8 describes N-queens constraints systematically. The board can stay the same while the question changes the algorithm.',
  },
  code: {
    title: 'From a rule to runnable code', en: 'Python · standard library only',
    lead: 'I use the same h function for three searches so you can focus on the rule that changes. Copy the entire open block into a .py file; each tab contains its helpers and a runnable example.',
    tabs: ['Hill-climbing', 'Simulated annealing', 'Genetic algorithm'], label: 'Python code',
    notes: [
      'This version minimizes h, examines every neighbor and breaks ties by a fixed ordering. It stops when best ≥ current, so it can return an unsolved board. Board 83742516 returns h = 1.',
      'This version picks a random neighbor, uses exp(−delta/T), tracks best separately from current and stops after at most 2,000 trials. Temperature is multiplied by 0.995 each step. Seed 42 supports repeatability in the same Python environment; different results across environments do not prove the algorithm wrong.',
      'This version uses roulette selection (uniform when total fitness is 0), internal crossover, independent mutation probability 0.05 per gene and at most 200 generations. It keeps best separately for its return value but does not insert an elite into the next population. The fitness of best seen therefore never decreases (h(best) never increases), while population-best fitness can decrease.',
    ],
    task: 'A small experiment: count h calls, then try several seeds under the same evaluation budget. Record both the rate of finding h = 0 and the lowest h on unsuccessful runs. One lucky run is not enough to rank algorithms.',
  },
  quiz: { title: 'Check yourself before leaving the board', en: '8 questions · feedback by topic', lead: 'Eight short questions about models, moves and probability. Commit to your answer before reading the explanation; the final score is saved to Session 6 in the roadmap.' },
  hw: {
    title: '✏️ Your turn to build a solution', en: 'Practice & self-check',
    lead: 'I want you to calculate on paper first, then check with the lab. Open the hints only when you need to compare your approach.',
    cards: [
      { title: '01 · Four queens', body: 'For S = (1, 2, 1, 4), calculate the state count, neighbor count and h(S). Find a valid sequence to h = 0 using a hill-climbing variant; label each node with h. The first lab preset is this board.', hint: 'There are 4⁴ = 256 states and 4 × 3 = 12 neighbors. h(S) = 5: column pairs (1,2), (1,3), (1,4), (2,3), (2,4). One decreasing path is 1214 (5) → 2214 (3) → 2414 (1) → 2413 (0). Each step changes just one column; this chooses improvements without requiring the steepest one.' },
      { title: '02 · Graph coloring', body: 'Use the A–H graph in the exercise file. A state assigns red/blue/yellow to every vertex; h counts edges whose ends have the same color. Define neighbors by recoloring one vertex, then repair the initial coloring to h = 0.', hint: 'The picture has 8 vertices A–H even though the text lists a…g. Following the picture: 3⁸ = 6,561 states and 8 × 2 = 16 neighbors. Initially only C–G and G–H conflict. Change C from blue to red, then H from blue to yellow: h goes 2 → 1 → 0. G stays blue; each move changes one vertex.' },
      { title: '03 · Fitness-based selection', body: 'Calculate fitness and P(selection) for 2341, 2132, 1232, 4321. Then cross 2341 with 2132 at each internal cut and evaluate the children. Can you find a child worse than both parents?', hint: 'Population fitness values are 2, 3, 1, 0; total 6, probabilities 1/3, 1/2, 1/6, 0. Crossing 2341 with 2132 after gene 2 yields 2332, fitness = 2: no better than the stronger parent. Cutting after gene 1 gives 2132, fitness = 3; after gene 3 gives 2342, fitness = 2. In this crossover direction no child is worse than both parents. But crossing solutions 2413 and 3142 (fitness = 6) after gene 2 gives 2442, fitness = 2: a clear counterexample to the idea that children always improve.' },
    ],
    graphNote: 'Initially: D is red; B, F yellow; A, C, E, G, H blue. Edges: AB, BC, AD, BD, BG, CG, DE, DF, DG, FG, GH. Dashed lines mark conflicting edges CG and GH.',
    hint: 'Open hint / check your work', file: 'Open the original exercises ↗',
    checks: ['I distinguish the final configuration from the path to it.', 'I count h by pairs and can compute Nᴺ and N(N − 1).', 'I distinguish plateaus, shoulders, ridges and local optima.', 'I can explain first-choice, stochastic, sideways and restart variants.', 'I use the correct SA probability sign for minimization.', 'I select k beam candidates from the shared pool.', 'I compute fitness and selection probabilities and check children’s validity.', 'I don’t turn one run into a promise of an optimal solution.'],
    next: 'Next is Session 7 — Adversarial Search: the other side will no longer sit still while you optimize.', roadmap: 'Back to roadmap →',
  },
} satisfies typeof VI;
