
/*
 * Chữ tiếng Việt của bài b2 — NGUỒN SỰ THẬT.
 *
 * Rút bằng .claude/scripts/extract_lesson.py, gom theo mục và giữ đúng thứ tự đọc.
 * Bản EN (`*.text.en.ts`) khai `satisfies typeof VI` nên thiếu hay thừa một khóa là lỗi tsc.
 */
export const VI = {
  note: {
    start: "Chưa làm gì cả. Đây là sàn nhà lúc bạn vừa bật máy.",
    suckDirty: "Ô đang bẩn → hút. Sàn sạch thêm một ô.",
    suckClean: "Hút một ô vốn đã sạch — tốn công, chẳng được điểm rác nào.",
    moved: "Ô này sạch rồi → sang ô bên cạnh xem sao.",
    wall: "Đã đụng tường, không đi thêm được.",
    restAll2: "Sổ tay ghi cả hai ô đều sạch → đứng yên, khỏi tốn xăng.",
    restAll4: "Sổ tay ghi cả bốn ô đều sạch → đứng yên, khỏi tốn xăng.",
  },
  fn: {
    perceptsSeen: (n: number) => `CHUỖI TRI GIÁC ĐÃ NHẬN · ${n} tri giác`,
    labTitle: (n: number) => `Lab · thế giới hút bụi ${n} ô`,
    stepOf: (t: number, n: number) => `BƯỚC ${t} / ${n}`,
    scoreAfter: (n: number) => `ĐIỂM SAU ${n} BƯỚC`,
    level: (n: number) => `NẤC ${n}`,
    // Chuỗi có chèn giá trị -> HÀM, để trật tự vế trong câu mỗi thứ tiếng một khác vẫn đổi được.
    archAria: (n: number, name: string) => `Sơ đồ kiến trúc agent nấc ${n}: ${name}`,
    stepTitle: (t: number, action: string) => `Bước ${t}${action ? ' · ' + action : ''}`,
    roomAria: (t: number, loc: string) => `Bước ${t}: robot đang ở ô ${loc}. `,
    cellState: (c: string, dirty: boolean) => `ô ${c} ${dirty ? 'bẩn' : 'sạch'}`,
  },
  hero: {
    s1: "TOÁN NỀN",
    s2: "02 Hàm agent",
    s3: "03 Duy lý",
    s4: "04 Không toàn tri",
    s5: "06 Môi trường",
    s6: "07 Bảng tra",
    s7: "08 Năm nấc",
    s8: "09 Tổng kết",
    s9: "11 Bài tập",
    s10: "Bìa",
    s11: "BUỔI 2",
    s12: "Tác tử thông minh",
    s13: "CSC14003 · BUỔI 2 · TÁC TỬ THÔNG MINH",
    s14: "Mổ con",
    s15: "tác tử",
    s15b: "ra xem",
    s16: "Buổi trước tôi kết bài bằng một lời hứa: cả khóa này sẽ nhìn mọi thứ qua con mắt <strong class='hl'>agent</strong>. Rồi tôi bỏ đó, chưa nói agent thật ra là cái gì. Buổi này trả nợ. Hết buổi bạn sẽ viết được hàm hành vi của một agent thành ký hiệu, mô tả được bài toán bằng <strong class='hl-cyan'>PEAS</strong>, đọc được bảy chiều của môi trường, và biết một con agent có thể phức tạp tới nấc nào — từ con ếch ba luật cho tới thứ tự sửa được chính mình.",
    s17: "Agent nhận tri giác từ môi trường và trả lại hành động",
  },
  hero_ah2: {
    s1: "Môi trường",
    s2: "tri giác · percepts",
    s3: "hành động · actions",
    s4: "cảm biến",
    s5: "bộ chấp hành",
  },
  ch1: {
    s1: "Agent là gì — và vì sao định nghĩa nó <em class='hl-cyan'>rộng đến thế</em>",
    s2: "Hãy nghĩ tới một trợ lý lập trình đang chạy trên máy bạn. Nó <em>đọc</em> file trong dự án, đọc thông báo lỗi từ trình biên dịch — rồi nó <em>sửa</em> file, <em>chạy</em> lệnh trong terminal. Đọc là cảm biến, sửa và chạy là bộ chấp hành. Bỏ hết tên riêng đi thì còn lại đúng một khuôn.<br/><br/>Khuôn đó là định nghĩa của cả buổi: <strong class='hl'>agent là thứ tri giác được môi trường qua cảm biến, và tác động lên môi trường qua bộ chấp hành</strong>. Gọn tới mức nghe như chưa nói gì, và bạn có quyền hỏi “thế thì cái gì chẳng phải agent?”. Câu hỏi đúng đấy — câu trả lời chính là lý do người ta chọn định nghĩa rộng đến vậy.",
    s3: "AGENT NGƯỜI",
    s4: "mắt, tai, và mấy giác quan còn lại",
    s5: "tay, chân, dây thanh quản",
    s6: "camera, cảm biến hồng ngoại đo khoảng cách",
    s7: "cần gạt, mô-tơ",
    s8: "AGENT PHẦN MỀM",
    s9: "phím bạn gõ, nội dung file, gói tin mạng",
    s10: "màn hình, ổ đĩa, bộ định tuyến",
    s11: "SENSORS · CẢM BIẾN",
    s12: "ACTUATORS · BỘ CHẤP HÀNH",
    s13: "VÌ SAO PHẢI RỘNG NHƯ VẬY",
    s14: "Vì đây là <strong class='hl'>công cụ để mổ xẻ hệ thống</strong>, không phải nhãn dán để phân loại đồ vật. Mọi ngành kỹ thuật đều đang chế ra những thứ tương tác với thế giới; chỗ riêng của AI là những thứ có kha khá năng lực tính toán và phải ra quyết định không hề tầm thường. Định nghĩa rộng cho phép bạn dùng chung một bộ đồ nghề để soi con robot hút bụi, chương trình cờ vua, lẫn cái hệ gợi ý video — và đó chính là thứ giúp bạn khỏi phải học lại từ đầu ở mỗi buổi sau.",
  },
  ch2: {
    s1: "Từ “hành vi” mơ hồ tới một <em class='hl-yellow'>hàm</em>",
    s2: "🧹 Nói “agent cư xử thông minh” thì dễ, nhưng muốn kiểm tra thì phải viết ra được nó cư xử <em>thế nào</em>. Cách viết ấy đây: gom mọi thứ agent từng cảm nhận từ lúc bật máy tới giờ thành một chuỗi, rồi hỏi chuỗi đó dẫn tới hành động nào.",
    s3: "BA CHỮ CẦN PHÂN BIỆT",
    s4: "<strong class='hl-yellow'>Percept · tri giác</strong> — thứ cảm biến đưa vào tại <em>một khoảnh khắc</em>. Một tấm ảnh, một dòng cảm biến, một lần thôi.",
    s5: "<strong class='hl-yellow'>Percept sequence · chuỗi tri giác</strong> — toàn bộ lịch sử, từ tri giác đầu tiên tới cái vừa nhận. Không sót cái nào.",
    s6: "<strong class='hl-yellow'>Agent function · hàm agent</strong> — luật gán mỗi chuỗi tri giác cho đúng một hành động. Đây là <em>mô tả toán học</em> của hành vi, không phải code.",
    s7: "Còn <strong class='hl'>agent program · chương trình agent</strong> mới là phần chạy được. Nó khác hàm agent ở một chỗ rất thực tế: hàm nhận cả chuỗi lịch sử, còn chương trình mỗi lần chỉ được đưa cho <strong class='hl'>đúng tri giác hiện tại</strong> — muốn nhớ quá khứ thì phải tự lo lấy chỗ mà cất. Chi tiết nhỏ này sẽ quay lại cắn bạn ở mục <a href='#ch8'>08</a>.",
    s8: "THẾ GIỚI HÚT BỤI HAI Ô",
    s9: "Thế giới nhỏ nhất mà vẫn đủ dạy: <strong class='hl'>hai ô</strong> tên A và B, mỗi ô sạch hoặc bẩn, con robot đứng ở một trong hai. Tri giác là cặp <span class='code-inline'>[vị trí, tình trạng]</span>. Hành động có bốn: sang trái, sang phải, hút, đứng yên.",
    s10: "CHUỖI TRI GIÁC",
    s11: "HÀNH ĐỘNG",
    s12: "Cái dấu ⋮ ở cuối bảng mới là chỗ đáng sợ. Tri giác chỉ có <strong class='hl'>4 loại</strong> — hai ô nhân hai tình trạng, đúng tích Descartes ở thẻ toán nền. Nhưng chuỗi dài 10 bước thì số chuỗi phải liệt kê là 4 + 4² + … + 4¹⁰ = <strong class='hl-red'>1.398.100 dòng</strong>. Một thế giới có đúng hai ô, và bảng đã hơn một triệu dòng cho mười bước đầu. Lát tới lab ở mục <a href='#ch3'>03</a>, bấm sang thế giới <strong class='hl'>bốn ô</strong> rồi nghĩ lại con số này: tri giác thành 8 loại, cùng mười bước đó bảng phình lên <strong class='hl-red'>1.227.133.512 dòng</strong> — thêm hai ô thôi mà dài gấp gần 900 lần.",
    s13: "MAY LÀ KHÔNG AI VIẾT CÁI BẢNG ĐÓ — BỐN DÒNG NÀY LÀM ĐÚNG VIỆC ĐÓ",
  },
  ch3: {
    s1: "“Làm điều đúng” — nhưng <em class='hl-green'>ai chấm</em>?",
    s2: "Giả sử bạn thuê người dọn nhà và trả công theo <em>số ký rác hốt được</em>. Tuần đầu sạch bong. Tuần thứ ba, bạn bắt đầu thấy rác xuất hiện ở những chỗ trước giờ chưa từng có rác.<br/><br/>Không ai gian cả — người đó chỉ đang tối đa đúng cái bạn đo. Agent duy lý là agent làm điều đúng, nhưng “đúng” theo ai? Thứ tôi muốn bạn mang về từ mục này là: <strong class='hl'>cái thước không nằm trong agent, nó nằm ở người thiết kế</strong> — nên đặt sai thước thì agent càng giỏi càng tai hại.",
    s3: "THƯỚC ĐO HIỆU NĂNG · PERFORMANCE MEASURE",
    s4: "Nó chấm <strong class='hl'>chuỗi trạng thái của MÔI TRƯỜNG</strong>, không chấm trạng thái của agent. Chỗ này đáng gạch chân: agent có thể tự thấy mình đang làm rất tốt, tự tin ngời ngời — điểm vẫn là điểm của sàn nhà, không phải điểm của sự tự tin.",
    s5: "LUẬT ĐẶT THƯỚC",
    s6: "Đặt thước theo <strong class='hl'>thứ bạn thật sự muốn có trong môi trường</strong>, chứ đừng theo cách bạn nghĩ agent nên cư xử. Ví dụ kinh điển: chấm “hốt được bao nhiêu rác trong ca tám tiếng” nghe rất hợp lý — cho tới khi bạn nhận ra agent tối đa điểm đó bằng cách hốt rác lên rồi đổ xuống hốt lại. Cái bạn muốn là <em>sàn sạch</em>, vậy thì chấm sàn sạch.",
    s7: "ĐỊNH NGHĨA ĐẦY ĐỦ — BỐN THỨ NÓ TỰA VÀO",
    s8: "<em>Với mỗi chuỗi tri giác có thể có, một agent duy lý chọn hành động được kỳ vọng làm tối đa thước đo hiệu năng của nó, dựa trên bằng chứng mà chuỗi tri giác cung cấp và tri thức có sẵn mà agent mang trong mình.</em>",
    s9: "THƯỚC ĐO",
    s10: "định nghĩa thế nào là thành công",
    s11: "TRI THỨC CÓ SẴN",
    s12: "agent biết gì về môi trường từ trước",
    s13: "CHUỖI TRI GIÁC",
    s14: "nó đã thấy được những gì tới giờ",
    s15: "HÀNH ĐỘNG",
    s16: "nó làm được những gì",
    s17: "Đổi bất kỳ cái nào trong bốn thứ này, câu trả lời “có duy lý không” đổi theo. Lab ngay dưới cho bạn đổi cái thứ nhất và tự thấy.",
    s18: "BA THÍ NGHIỆM TÔI MUỐN BẠN TỰ LÀM NGAY BÂY GIỜ",
    s19: "<strong class='hl'>Một:</strong> chọn sàn “đã sạch bong”, rồi bấm qua lại giữa hai chương trình mà nhìn bảng điểm cuối. Thước A chấm cả hai <strong class='hl-green'>40 — 40</strong>, hòa. Thêm đúng một dòng “đi lại tốn xăng” vào thước đo thì thành <strong class='hl-red'>20 — 39</strong>. Không dòng code nào của hai chương trình thay đổi cả; chỉ cái thước đổi, và con phản xạ thuần từ chỗ hoàn hảo tụt xuống thảm hại.",
    s20: "<strong class='hl'>Hai:</strong> vẫn sàn sạch bong, chạy “phản xạ + trí nhớ” từ bước 0 và soi dòng SỔ TAY. Bước 1 nó vẫn phải đi sang B — vì nó <em>chưa nhìn thấy</em> B bao giờ, mà chưa thấy thì chưa có quyền kết luận. Nhìn thấy rồi mới dám nghỉ. Đó là bài học về thu thập thông tin ở mục <a href='#ch4'>04</a>, và là lý do phải có trí nhớ ở mục <a href='#ch8'>08</a> — bạn vừa gặp nó trước khi tôi kịp giảng.",
    s21: "<strong class='hl'>Ba:</strong> bấm nút <strong class='hl-cyan'>4 ô</strong>, vẫn để sàn sạch bong. Thước A vẫn hòa <strong class='hl-green'>80 — 80</strong>, thước B giãn ra thành <strong class='hl-red'>60 — 77</strong>. Mà chuyện hay nhất nằm ở băng hành động: con phản xạ thuần lết tới ô D rồi <strong class='hl'>ping-pong giữa C và D tới hết đời</strong> — A và B nó không bao giờ quay lại nữa. Luật “ở ô cuối thì lùi, còn lại thì tiến” nghe hợp lý ở hai ô, sang bốn ô là thành cái bẫy. Bản có trí nhớ thì tốn ba bước đi thăm dò rồi nghỉ hẳn: <em>đi tốn xăng, nhưng đi để biết mà nghỉ vẫn rẻ hơn đi mù</em>.",
  },
  ch4: {
    s1: "Duy lý <em class='hl-purple'>không phải</em> là hoàn hảo",
    s2: "Đây là chỗ tôi thấy người học hiểu sai nhiều nhất, và hiểu sai từ buổi 1. Duy lý không có nghĩa là luôn ra kết quả tốt nhất — vì kết quả còn phụ thuộc những thứ agent không có cách nào biết trước.",
    s3: "TOÀN TRI · OMNISCIENCE",
    s4: "Biết trước kết quả thật của mọi hành động, không còn khả năng nào khác xảy ra. Nghe thì sướng, nhưng ngoài đời <strong class=\"hl\">không tồn tại</strong>. Bạn sang đường lúc đường vắng hoe rồi bị cánh cửa máy bay rơi trúng — quyết định đó vẫn duy lý, chỉ là xui. Duy lý chấm <em>quyết định</em>, không chấm <em>kết quả</em>.",
    s5: "THU THẬP THÔNG TIN",
    s6: "Làm một việc chỉ để <strong class=\"hl\">sửa những gì mình sẽ thấy về sau</strong> — ngó trái ngó phải trước khi sang đường, mở nắp ra soi, đi thăm dò. Nghe như phí một nước đi, nhưng nó là một phần của tính duy lý: nhắm mắt băng qua đường thì không xui, mà là ẩu.",
    s7: "HỌC · LEARNING",
    s8: "Agent duy lý phải học được càng nhiều càng tốt từ những gì nó tri giác. Cấu hình ban đầu do người thiết kế nạp vào chỉ là điểm xuất phát, gặp trải nghiệm thì phải được sửa và bồi thêm. Có những trường hợp cực đoan mà môi trường đã biết trước hoàn toàn — khi đó khỏi cần học, nhưng đó là ngoại lệ hiếm.",
    s9: "TỰ CHỦ · AUTONOMY",
    s10: "Agent nào chỉ sống bằng tri thức người thiết kế nhét sẵn, không thèm đếm xỉa tới tri giác của chính mình, thì agent đó <strong class=\"hl\">thiếu tính tự chủ</strong>. Cái đồng hồ treo tường là ví dụ: không đầu vào, chạy đúng thuật toán đã lên dây, không học, không kinh nghiệm. Nó chỉ đúng giờ chừng nào không ai bê nó sang múi giờ khác.",
  },
  ch5: {
    s1: "PEAS — bốn câu hỏi <em class='hl-cyan'>trước khi</em> gõ dòng code đầu tiên",
    s2: "🧭 Môi trường tác vụ chính là <em>bài toán</em>, còn agent duy lý là <em>lời giải</em>. Mà chưa phát biểu xong bài toán thì lời giải nào cũng chỉ là đoán. PEAS là bốn câu hỏi bắt bạn phát biểu cho xong — và nó phải là bước đầu tiên, làm càng đầy đủ càng tốt.",
    s3: "Thước đo hiệu năng",
    s4: "Lấy gì chấm điểm agent này?",
    s5: "Môi trường",
    s6: "Nó sống giữa những gì?",
    s7: "Bộ chấp hành",
    s8: "Nó tác động ra bằng đường nào?",
    s9: "Cảm biến",
    s10: "Nó nhận thông tin vào bằng đường nào?",
    s11: "SÁU AGENT, SÁU BẢN MÔ TẢ PEAS",
    s12: "Hàng đầu là chiếc taxi tự lái, ví dụ đáng mổ kỹ nhất. Đọc lướt cả bảng một lượt rồi để ý: cột <strong class='hl'>P</strong> ngắn nhất mà lại khó viết nhất, vì nó là chỗ bạn phải quyết định thế nào là thành công — và như mục <a href='#ch3'>03</a> vừa cho thấy, viết hớ ở cột này là hỏng cả hệ thống.",
    s13: "P · THƯỚC ĐO",
    s14: "E · MÔI TRƯỜNG",
    s15: "A · BỘ CHẤP HÀNH",
    s16: "S · CẢM BIẾN",
    s17: "SOFTBOT — KHI MÔI TRƯỜNG KHÔNG PHẢI THẾ GIỚI THẬT",
    s18: "Trình mô phỏng bay, game, Internet — toàn môi trường nhân tạo, nhưng phức tạp chẳng kém gì thật. Agent sống trong đó gọi là <strong class='hl'>softbot</strong>, mọi bộ phận đều là phần mềm: cảm biến là gói tin và nội dung file, bộ chấp hành là màn hình và ổ đĩa. Đừng nhầm “nhân tạo” với “dễ”.",
    s19: "THỬ NGAY, ĐỪNG ĐỌC TIẾP VỘI",
    s20: "Viết PEAS cho hai việc này, và cố ý đặt chúng cạnh nhau: <strong class='hl'>(1) đánh một trận tennis trong giải đấu</strong> — <strong class='hl'>(2) tập tennis bằng cách đập bóng vào tường</strong>. Cùng một môn thể thao, cùng cây vợt, nhưng cột P của hai bên khác nhau hoàn toàn. Giữ lại tờ giấy đó, mục <a href='#ch6'>06</a> sẽ bắt bạn dùng lại chính hai việc này.",
  },
  ch6: {
    s1: "Bảy chiều để <em class='hl-yellow'>đo</em> một môi trường",
    s2: "🎛️ Trước khi đọc tiếp, trả lời giúp tôi một câu: <strong class='hl'>poker và backgammon khác nhau ở mấy chiều?</strong><br/><br/>Đúng một chiều. Cả hai đều có yếu tố may rủi, đều rời rạc, đều nhiều người chơi — nhưng backgammon bày hết quân ra bàn còn poker thì úp bài. Nếu lúc nãy bạn định trả lời “hai chiều, vì poker còn ngẫu nhiên nữa”, thì bạn vừa dính đúng cái bẫy mà bảng dưới đây sinh ra để gỡ: <em>nhìn thấy hết</em> và <em>đoán trước được</em> là hai chuyện độc lập.<br/><br/>Bảy cặp chiều dưới đây là bộ số đo cho biết bạn đang đối mặt với cái gì — và quan trọng hơn, chúng quyết định kiến trúc agent tối thiểu bạn buộc phải dùng. Càng nhiều chiều rơi về vế phải, bài toán càng khó.",
    s3: "CHIỀU QUAN SÁT ĐÁNG ĐƯỢC NÓI KỸ HƠN MỘT CÁI NHÃN",
    s4: "<strong class='hl'>Quan sát đầy đủ</strong> nghĩa là cảm biến đưa cho agent <em>toàn bộ</em> trạng thái của môi trường. Phần thưởng đi kèm rất cụ thể: agent khỏi cần giữ trạng thái trong, vì chẳng có gì để mà nhớ — nhìn phát nào biết hết phát đó.",
    s5: "Rơi xuống <strong class='hl'>một phần</strong> thì do một trong hai lý do, và chúng khác nhau hẳn. <strong class='hl-cyan'>Lý do một — cảm biến nhiễu hoặc thiếu chính xác:</strong> thông tin có tới, nhưng tới sai. <strong class='hl-cyan'>Lý do hai — một mảng trạng thái đơn giản là không có mặt trong dữ liệu cảm biến:</strong> con robot ở mục <a href='#ch3'>03</a> chỉ có cảm biến bẩn <em>tại chỗ nó đứng</em>, nên nó không thể biết ô bên kia thế nào — đó chính là lý do bản có trí nhớ vẫn phải lết sang B một chuyến rồi mới dám nghỉ. Bạn đã thấy tận mắt trước khi tôi kịp đặt tên cho nó.",
    s6: "Và có mức cùng cực: <strong class='hl-red'>không quan sát được · unobservable</strong> — agent không có cảm biến nào hết. Nghe như đùa, nhưng vẫn còn cửa: nó phải hành động dựa trọn vào tri thức có sẵn, kiểu nhắm mắt đi theo một lộ trình đã tính trước.",
    s7: "CHIỀU THỨ BẢY — VÀ VÌ SAO NÓ KHÔNG CÓ TRONG BẢNG TRÊN",
    s8: "<strong class='hl-yellow'>Biết vs không biết · known vs unknown</strong>. Môi trường <em>biết</em> là môi trường mà kết quả của mọi hành động đã được cho sẵn (hoặc xác suất kết quả, nếu nó ngẫu nhiên). Không biết thì agent phải tự học lấy cách nó vận hành mới ra quyết định tử tế được.",
    s9: "Tôi tách nó ra khỏi bảng khám phá vì nó <strong class='hl'>không cùng loại</strong> với sáu chiều kia: sáu chiều kia mô tả bản thân môi trường, còn chiều này mô tả <em>trạng thái hiểu biết của agent</em> về môi trường. Hai thứ độc lập nhau — bạn hoàn toàn có thể quan sát đầy đủ một trò chơi mà vẫn không biết luật, như lần đầu ngồi vào bàn cờ vây.",
    s10: "MÔI TRƯỜNG DỄ NHẤT",
    s11: "Quan sát đầy đủ · tất định · từng hồi · tĩnh · rời rạc · một agent. Gặp được bộ này thì bạn đang ở thiên đường.",
    s12: "VÀ HẦU HẾT TÌNH HUỐNG ĐỜI THỰC",
    s13: "Quan sát một phần · ngẫu nhiên · tuần tự · động · liên tục · nhiều agent. Đủ bộ vế phải. Bấm lại “Lái taxi” ở bảng trên mà xem — nó chính là hàng này.",
    s14: "HAI CHỖ HAY BỊ LẪN — VÀ MỘT CHỖ ĐÁNH DẤU SẴN CHO BUỔI 5",
    s15: "<strong class='hl'>Từng hồi ≠ tĩnh.</strong> Từng hồi nói về việc quyết định bây giờ có ảnh hưởng quyết định sau không; tĩnh nói về việc môi trường có tự đổi trong lúc bạn ngồi nghĩ không. Robot gắp linh kiện là từng hồi mà vẫn động.",
    s16: "<strong class='hl'>Ngẫu nhiên ≠ nhiều agent.</strong> Chẩn đoán y khoa đầy bất ngờ nhưng chỉ một agent — con vi khuẩn không tính toán để hạ bạn. Cứ hỏi: hành vi của thực thể kia có nhằm tối đa một thước đo phụ thuộc vào hành vi của tôi không? Có thì mới là agent.",
    s17: "Và khi đã có nhiều agent thì còn chia tiếp làm hai loại, tùy vào thước đo của họ ăn nhau thế nào. <strong class='hl-red'>Cạnh tranh</strong>: tôi được điểm nghĩa là bạn mất điểm — cờ vua, bạn thắng thì tôi thua, không có đường nào khác. <strong class='hl-green'>Hợp tác</strong>: cùng lái xe trên đường, ai cũng muốn về nhà và <em>không ai muốn đâm nhau cả</em>, nên thước đo của tôi và của bạn phần lớn cùng chiều. Nhớ chữ cạnh tranh — buổi 5 gọi tên nó thành “tìm kiếm đối kháng”, và toàn bộ minimax mọc ra từ đúng chỗ này.",
  },
  ch7: {
    s1: "Sao không nhét sẵn <em class='hl-red'>mọi đáp án</em> vào một cái bảng?",
    s2: "📇 Hàm agent đã là một bảng tra rồi mà: chuỗi tri giác nào ra hành động nấy. Vậy cứ liệt kê hết ra, tra bảng, xong. <strong class='hl'>Nó sai ở đâu?</strong><br/><br/>Thử loại trừ trước khi đọc tiếp. Chạy chậm? Không, tra bảng là thao tác nhanh nhất đời. Không nhớ được quá khứ? Cũng không, nó nhớ nguyên cả chuỗi. Không xử được môi trường ngẫu nhiên? Vẫn không phải.<br/><br/>Nó sai ở một chỗ tầm thường tới mức dễ bị bỏ qua — và đó lại chính là cửa vào chỗ hiểm nhất của cả ngành.",
    s3: "AGENT TRA BẢNG · TABLE-DRIVEN-AGENT",
    s4: "function TABLE-DRIVEN-AGENT(percept) returns an action\n      persistent: percepts, một chuỗi, ban đầu rỗng\n                  table, bảng hành động, đánh chỉ mục theo\n                         chuỗi tri giác, ban đầu đã điền đủ\n\n      nối percept vào cuối percepts\n      action ← LOOKUP(percepts, table)\n      return action",
    s5: "Nó giữ nguyên cả chuỗi tri giác trong bộ nhớ, mỗi lần có tri giác mới thì nối vào rồi tra. Gọn gàng, và <strong class='hl'>làm đúng y những gì ta muốn</strong>.",
    s6: "CON SỐ GIẾT CHẾT Ý TƯỞNG ĐÓ",
    s7: "Gọi <span class='code-inline'>P</span> là số tri giác có thể có và <span class='code-inline'>T</span> là tuổi thọ agent tính bằng số tri giác nó sẽ nhận. Kích thước bảng là tổng của <span class='code-inline'>P^t</span> với t chạy từ 1 tới T. Với cờ vua, lấy P ≈ 10 và T = 150 nước, bảng cần <strong class='hl-red'>ít nhất 10¹⁵⁰ dòng</strong>.",
    s8: "BẢNG TRA CỜ VUA",
    s9: "10¹⁵⁰ dòng",
    s10: "NGUYÊN TỬ TRONG VŨ TRỤ QUAN SÁT ĐƯỢC",
    s11: "Không phải “hơi to”. Là to hơn vũ trụ bảy mươi bậc — bạn có gom hết vật chất trong vũ trụ lại làm ổ cứng cũng không đủ chỗ ghi một phần tỉ tỉ tỉ của cái bảng đó 😅",
    s12: "VẬY THÌ THÁCH THỨC CỐT LÕI CỦA AI LÀ GÌ",
    s13: "Viết được chương trình <strong class='hl'>sinh ra hành vi duy lý từ một lượng code nhỏ, thay vì từ một lượng dòng bảng khổng lồ</strong>. Đó là một câu, nhưng nó là cả cái ngành.",
    s14: "Có một phép so sánh làm chuyện này rõ ngay: tính căn bậc hai. Bạn có thể lập bảng tra căn bậc hai cho mọi số — hoặc viết <strong class='hl-green'>năm dòng theo phương pháp Newton</strong>. Năm dòng đó thắng cái bảng ở mọi mặt: nhỏ hơn, chạy được với số chưa từng có trong bảng, và ai đọc cũng hiểu được vì sao nó đúng. Mọi buổi còn lại của khóa này — tìm kiếm, logic, học máy — đều là những cách khác nhau để đi tìm “năm dòng Newton” cho các bài toán khó hơn.",
    s15: "Nhân tiện nhắc lại công thức của mục này: <strong class='hl'>agent = kiến trúc + chương trình</strong>. Kiến trúc là cái máy có cảm biến và bộ chấp hành thật — máy tính thường, hay chiếc xe gắn đầy camera. Chương trình phải hợp với kiến trúc: chương trình bảo “đi bộ” thì kiến trúc phải có chân.",
  },
  ch8: {
    s1: "Năm nấc thang, từ <em class='hl-purple'>con ếch</em> tới thứ tự sửa được mình",
    s2: "🪜 Con ếch ngồi bên bờ ao sống được bằng đúng ba luật: vật nhỏ đang động thì đớp, vật lớn đang động thì né, còn lại thì thôi. Ba luật, không trí nhớ, không mục tiêu — vậy mà đủ nuôi sống cả một loài suốt hàng triệu năm.<br/><br/>Nó là nấc thấp nhất trong năm nấc dưới đây. Năm kiến trúc này thường được vẽ rời nhau thành năm sơ đồ, nhìn vậy dễ tưởng chúng là năm lựa chọn ngang hàng — không phải. Chúng là <strong class='hl'>một sơ đồ lớn dần</strong>, mỗi nấc thêm đúng một thứ để chữa đúng một chỗ chết của nấc dưới. Bấm 1 → 5 và nhìn hộp vàng.",
    s3: "CON ẾCH — MỘT AGENT PHẢN XẠ CÓ THẬT NGOÀI TỰ NHIÊN",
    s4: "Tri giác vào chỉ có hai thứ: <strong class='hl'>kích thước</strong> và <strong class='hl'>chuyển động</strong>. Toàn bộ bộ luật của nó gọn thế này:",
    s5: "(1) vật NHỎ đang động →",
    s6: "ĐỚP",
    s7: "(2) vật LỚN đang động →",
    s8: "NÉ",
    s9: ", và chặn phản xạ đớp",
    s10: "(3) còn lại (không động) →",
    s11: "KHÔNG LÀM GÌ",
    s12: "Luật (3) trông thừa nhưng bắt buộc phải có: bộ luật thiếu nhánh mặc định là bộ luật có lỗ, gặp tình huống ngoài dự kiến thì agent đứng hình. Còn cái giá của kiến trúc này thì cũng lộ ra ngay ở luật (1) — thả một viên bi lăn qua, con ếch vẫn đớp.",
    s13: "TRÍ NHỚ TRÔNG NHƯ THẾ NÀO KHI VIẾT RA",
    s14: "Vẫn là bảng luật, chỉ khác ở chỗ vế NẾU giờ được nhắc tới <em>quá khứ</em>. So hai dòng giữa mà xem — cùng một tri giác “thấy vật phía trước”, hai hành động khác nhau, chỉ vì phần trước đó khác:",
    s15: "NẾU",
    s16: "THÌ",
    s17: "Không thấy vật phía trước",
    s18: "Đi thẳng",
    s19: "Thấy vật phía trước",
    s20: "Rẽ ngẫu nhiên",
    s21: "Đã thấy vật, đã rẽ phải, giờ phía trước quang",
    s22: "Đi thẳng",
    s23: "Đã thấy vật, đã rẽ phải, phía trước lại có vật",
    s24: "Dừng",
    s25: "Hai dòng dưới chính là thứ agent phản xạ thuần <strong class='hl'>không thể nào viết được</strong> — nó chỉ nhận đúng tri giác hiện tại, không có chỗ nào cất câu “đã rẽ phải rồi”. Nhớ mục <a href='#ch2'>02</a> chứ? Hàm agent nhận cả chuỗi, chương trình agent chỉ nhận một tri giác. Trạng thái trong là cách chương trình vá lại khoảng cách đó.",
    s26: "THẾ CÒN “AI AGENT” MÀ AI CŨNG NÓI THÌ NẰM Ở NẤC MẤY?",
    s27: "Câu hỏi đáng hỏi, vì cái tên trùng nhau mà nội hàm thì không. Thử soi một trợ lý lập trình qua đúng năm nấc trên. Nó <strong class='hl'>có trạng thái trong</strong> — nhớ những gì đã đọc, đã sửa — nên vượt nấc 1. Nó <strong class='hl'>có mục tiêu</strong>: bạn giao việc, nó thử hành động rồi xem đã tới chưa. Đó là nấc 3, và phần lớn thứ đang được gọi là “AI agent” dừng lại ở đây.",
    s28: "Nấc 4 thì lỏng lẻo. Nó hiếm khi có một <em>thang điểm</em> tường minh để cân nhanh với an toàn, hay cân cái chắc ăn với cái đáng giá mà hên xui — thứ đó thường nằm trong đầu bạn chứ không nằm trong chương trình. Còn nấc 5 thì gần như không có: mô hình <strong class='hl-red'>không tự sửa mình sau mỗi lần bị chê</strong>. Việc học xảy ra ở một chu kỳ khác hẳn, do người khác chạy, cách nhau hàng tháng. Cái vòng phê bình → học → sinh vấn đề mà bạn vừa xem ở nấc 5 vẫn còn để trống.",
    s29: "Nói vậy không phải để dìm. Nói vậy để bạn có một cái thước: lần tới đọc quảng cáo về “agent tự chủ”, bạn hỏi được đúng câu — <em>nó đang ở nấc mấy, và ba cái hộp của nấc 5 ai đang cầm?</em>",
    s30: "MÓC NỐI — MỖI NẤC LÀ MỘT BUỔI SAU",
    s31: "Đừng đọc năm nấc này như một danh sách để thuộc lòng. Chúng là mục lục của cả khóa: <strong class='hl'>nấc 3</strong> đẻ ra buổi 3–6, nơi bạn đi tìm đường tới mục tiêu bằng tìm kiếm và ràng buộc. <strong class='hl'>Nấc 4</strong> là cái thang điểm mà buổi 5 dùng để so hai nước cờ và buổi 9 dùng để cân xác suất. <strong class='hl'>Nấc 5</strong> chính là buổi 10 và 11 — bộ học ở đó có tên riêng là ID3, là mạng nơ-ron. Còn <strong class='hl'>nấc 2</strong>, cái mô hình thế giới, là thứ buổi 7 và 8 sẽ viết ra bằng logic.",
  },
  ch9: {
    s1: "Tổng kết một trang",
    s2: "và tự kiểm trước khi qua buổi 3",
    s3: "Nếu chỉ giữ lại được một trang từ buổi này thì giữ trang này.",
    s4: "Tri giác qua cảm biến, tác động qua bộ chấp hành. Hành vi của nó là hàm <span class=\"code-inline\">f : 𝓟* → 𝓐</span> — cả chuỗi lịch sử cho ra một hành động. Chương trình agent là bản chạy được của hàm đó, và mỗi lần chỉ được đưa cho tri giác hiện tại.",
    s5: "DUY LÝ",
    s6: "Chọn hành động <em>kỳ vọng</em> tối đa thước đo hiệu năng, dựa trên chuỗi tri giác tới giờ và tri thức có sẵn. Thước đo chấm môi trường chứ không chấm agent. Duy lý không phải toàn tri, không phải hoàn hảo, và có bao gồm việc đi thăm dò lẫn việc học.",
    s7: "Bốn câu phải trả lời trước khi thiết kế: thước đo · môi trường · bộ chấp hành · cảm biến. Bảy chiều môi trường quyết định kiến trúc tối thiểu bạn buộc phải dùng — mất quan sát đầy đủ là mất luôn quyền dùng agent phản xạ thuần.",
    s8: "NĂM KIẾN TRÚC",
    s9: "Phản xạ → thêm trạng thái trong và mô hình thế giới → thêm mục tiêu → thêm hàm thỏa dụng → thêm vòng học (phê bình · bộ học · sinh vấn đề). Mỗi nấc chữa đúng một chỗ chết của nấc dưới, và bảng tra khổng lồ là lý do không nấc nào được phép liệt kê sẵn mọi câu trả lời.",
    s10: "TỰ KIỂM — TICK KHI BẠN GIẢI THÍCH ĐƯỢC RA MIỆNG, KHÔNG PHẢI KHI THẤY QUEN MẶT",
    s11: "Phân biệt được tri giác, chuỗi tri giác, hàm agent và chương trình agent — nói được chương trình khác hàm ở đúng chỗ nào.",
    s12: "Giải thích được vì sao thước đo hiệu năng chấm chuỗi trạng thái của môi trường, chứ không chấm agent.",
    s13: "Nêu được một thước đo đặt hớ và hậu quả cụ thể của nó (không dùng lại ví dụ hốt rác của tôi).",
    s14: "Nói được vì sao duy lý không đồng nghĩa với toàn tri, và vì sao đi thăm dò lại là một phần của duy lý.",
    s15: "Viết được PEAS cho một tác vụ tự chọn, bốn mục đều có nội dung thật.",
    s16: "Đọc một môi trường lạ và xếp được nó vào bảy chiều, có giải thích cho từng chiều.",
    s17: "Giải thích được vì sao agent tra bảng bất khả thi, bằng một con số chứ không bằng cảm giác.",
    s18: "Kể được năm kiến trúc theo đúng thứ tự, mỗi nấc nói rõ nó thêm gì và chữa chỗ chết nào.",
  },
  quiz: {
    s1: "Quiz — đo xem bạn <em class='hl-cyan'>thật sự</em> hiểu tới đâu",
    s2: "tám câu · hàm agent, thước đo, PEAS, bảy chiều, năm kiến trúc",
    s3: "Đọc một mạch rồi thấy hiểu hết là cảm giác quen thuộc nhất trên đời — và cũng là cảm giác dễ lừa mình nhất. Tám câu dưới đây không phải để chấm bạn; chúng để lộ ra chỗ nào bạn mới chỉ <em>thấy quen mặt</em> chứ chưa hiểu. Sai câu nào thì đọc phần giải thích ngay dưới đó, đừng để dành. Làm xong hẵng qua bài tập.",
  },
  hw: {
    s1: "Bài tập về nhà — Buổi 2",
    s2: "bốn câu · PEAS và tính chất môi trường",
    s3: "✏️ Bốn câu, hai trò chơi ngoài sân. Buổi 1 tôi có nhá qua mấy câu này rồi bảo để dành — giờ thì bạn có đủ đồ nghề để làm thật. Làm bằng giấy bút, đừng làm trong đầu: chỗ bí sẽ lộ ra ngay khi phải viết cột P xuống.",
    s4: "CÂU THỨ NĂM, KHÔNG CÓ TRONG ĐỀ NHƯNG ĐÁNG LÀM NHẤT",
    s5: "Quay lại hai việc tennis ở mục <a href='#ch5'>05</a> — đánh giải và đập bóng vào tường — rồi xếp cả hai vào bảy chiều. Bạn sẽ thấy chúng lệch nhau ở <strong class='hl'>số agent</strong> và ở chiều <strong class='hl'>từng hồi / tuần tự</strong>. Rồi tự hỏi tiếp: cái tường có phải một agent không? Trả lời được câu đó là bạn đã thật sự hiểu tiêu chí phân biệt agent với đồ vật, chứ không chỉ thuộc nó.",
    s6: "Tiếp theo: <strong class='hl'>Buổi 3 — Giải bài toán bằng Tìm kiếm</strong>. Ở đó bạn dựng đúng con agent nấc 3 của mục 08: có mục tiêu, và phải tự tìm đường tới đó.",
    s7: "← Về Lộ trình",
  },
  agentarchdiagram: {
    s1: "Môi trường",
    s2: "Thế giới đang",
    s3: "thế nào",
    s4: "Sẽ ra sao nếu",
    s5: "tôi làm A",
    s6: "Làm vậy tôi",
    s7: "sướng cỡ nào",
    s8: "Vậy giờ",
    s9: "nên làm gì",
    s10: "Trạng thái",
    s11: "Thế giới tự biến đổi ra sao",
    s12: "Hành động của tôi làm gì",
    s13: "Mục tiêu",
    s14: "Độ thỏa dụng",
    s15: "Luật điều kiện–hành động",
    s16: "Cảm biến",
    s17: "Bộ chấp hành",
    s18: "Cảm biến",
    s19: "Bộ chấp hành",
    s20: "Chuẩn hiệu năng",
    s21: "Bộ phê bình",
    s22: "Bộ học",
    s23: "Bộ thi hành",
    s24: "Bộ sinh vấn đề",
    s25: "tri giác",
    s26: "phản hồi",
    s27: "sửa đổi",
    s28: "tri thức",
    s29: "mục tiêu học",
    s30: "Năm nấc, một sơ đồ",
    s31: "bấm 1 → 5, hộp vàng là thứ nấc đó vừa thêm vào",
    s32: "CHỖ NÓ CHỊU THUA — VÀ LÀ LÝ DO CÓ NẤC SAU",
    s33: "<em>Với chiếc taxi:</em> ",
  },
  vacuumlab: {
    s1: "Suck · hút",
    s2: "Left · sang trái",
    s3: "Right · sang phải",
    s4: "NoOp · đứng yên",
    s5: "hút",
    s6: "di chuyển",
    s7: "di chuyển",
    s8: "đứng yên",
    s9: "BĂNG HÀNH ĐỘNG · BẤM ĐỂ NHẢY TỚI BƯỚC BẤT KỲ",
    s10: "hút",
    s11: "di chuyển",
    s12: "đứng yên",
    s13: "chưa có gì — máy vừa bật",
    s14: "cùng một chuỗi hành động, ba thước đo chấm song song",
    s15: "CHƯƠNG TRÌNH",
    s16: "THẾ GIỚI",
    s17: "bản gốc — A và B",
    s18: "hành lang A · B · C · D, vẫn đúng bốn hành động cũ",
    s19: "SÀN LÚC ĐẦU",
    s20: "HÀNH ĐỘNG BƯỚC NÀY",
    s21: "— chưa chạy",
    s22: "↺ Về đầu",
    s23: "← Lùi",
    s24: "Tiến →",
    s25: "Tới cuối ⇥",
    s26: "Bảng này chấm cả hai chương trình trên đúng sàn nhà bạn đang chọn, nên bạn không cần bấm đi bấm lại mới so được. Ô xanh là đứa thắng ở thước đó, ô đỏ là đứa thua — và <strong class='hl'>chú ý cột nào hòa, cột nào không</strong>.",
  },
  vacuumroom: {
    s1: "đã thấy sạch",
    s2: "sổ tay: đã thấy sạch",
    s3: "chưa biết",
    s4: "sổ tay: chưa biết",
    s5: "ĐÃ THẤY Ở ĐÂY",
    s6: "TRI GIÁC",
    s7: "chưa nhìn gì",
  },
  envexplorer: {
    s1: "Bảng khám phá · môi trường nào rơi vào vế nào",
    s2: "sáu chiều xếp được thành bảng so sánh",
  },
};
