import type { VI } from './lesson02.text.vi';

/*
 * Bản tiếng Anh của bài 2. `satisfies typeof VI` là cổng kiểm cấu trúc.
 * Giọng: .claude/skills/lesson-voice/references/english.md.
 */
export const EN = {
  note: {
    start: "Nothing done yet. This is the floor the moment you switched the machine on.",
    suckDirty: "Square is dirty → suck. One more square clean.",
    suckClean: "Sucked a square that was already clean — effort spent, no dirt points earned.",
    moved: "This square is clean → move next door and look.",
    wall: "Hit the wall, can’t go any further.",
    restAll2: "The notebook says both squares are clean → stay put, save the fuel.",
    restAll4: "The notebook says all four squares are clean → stay put, save the fuel.",
  },
  fn: {
    perceptsSeen: (n: number) => `PERCEPT SEQUENCE SO FAR · ${n} percept${n === 1 ? '' : 's'}`,
    labTitle: (n: number) => `Lab · ${n}-square vacuum world`,
    stepOf: (t: number, n: number) => `STEP ${t} / ${n}`,
    scoreAfter: (n: number) => `SCORE AFTER ${n} STEPS`,
    level: (n: number) => `LEVEL ${n}`,
    archAria: (n: number, name: string) => `Agent architecture diagram, level ${n}: ${name}`,
    stepTitle: (t: number, action: string) => `Step ${t}${action ? ' · ' + action : ''}`,
    roomAria: (t: number, loc: string) => `Step ${t}: the robot is in square ${loc}. `,
    cellState: (c: string, dirty: boolean) => `square ${c} ${dirty ? 'dirty' : 'clean'}`,
  },
  hero: {
    s1: "MATH PRIMER",
    s2: "02 Agent function",
    s3: "03 Rationality",
    s4: "04 Not omniscient",
    s5: "06 Environments",
    s6: "07 Lookup table",
    s7: "08 Five levels",
    s8: "09 Wrap-up",
    s9: "11 Homework",
    s10: "Cover",
    s11: "SESSION 2",
    s12: "Intelligent agents",
    s13: "CSC14003 · SESSION 2 · INTELLIGENT AGENTS",
    s14: "Taking the",
    s15: "agent",
    s15b: "apart",
    s16: "Last session I closed with a promise: this whole course looks at everything through the eyes of an <strong class='hl'>agent</strong>. Then I left it there without saying what an agent actually is. This session pays that off. By the end you’ll write an agent’s behavior out as a function, describe a problem with <strong class='hl-cyan'>PEAS</strong>, read the seven dimensions of an environment, and know how complex an agent can get — from a three-rule frog up to something that rewrites itself.",
    s17: "An agent takes percepts from the environment and returns actions",
  },
  hero_ah2: {
    s1: "Environment",
    s2: "percepts",
    s3: "actions",
    s4: "sensors",
    s5: "actuators",
  },
  ch1: {
    s1: "What an agent is — and why the definition is <em class='hl-cyan'>so wide</em>",
    s2: "Think about a coding assistant running on your machine. It <em>reads</em> the files in your project, reads the compiler errors — then it <em>edits</em> files and <em>runs</em> commands in the terminal. It senses by reading; it acts by editing files and running commands. Strip the proper nouns away and one shape is left.<br/><br/>That shape is the definition for the whole session: <strong class='hl'>an agent is anything that perceives its environment through sensors and acts on it through actuators</strong>. So compact it sounds like it says nothing, and you have every right to ask “then what isn’t an agent?”. Good question — and the answer is exactly why the definition was drawn that wide.",
    s3: "HUMAN AGENT",
    s4: "eyes, ears, and the rest of the senses",
    s5: "hands, legs, vocal cords",
    s6: "cameras, infrared range finders",
    s7: "levers, motors",
    s8: "SOFTWARE AGENT",
    s9: "the keys you press, file contents, network packets",
    s10: "the screen, the disk, the router",
    s11: "SENSORS",
    s12: "ACTUATORS",
    s13: "WHY IT HAS TO BE THIS WIDE",
    s14: "Because this is <strong class='hl'>a tool for taking systems apart</strong>, not a label for sorting objects. Every engineering discipline builds things that interact with the world; AI’s own corner is the things with real computing power behind them that face decisions that are anything but trivial. A wide definition lets you point the same toolkit at a robot vacuum, a chess program and a video recommender alike — and that is what saves you from relearning everything from scratch in each later session.",
  },
  ch2: {
    s1: "From vague “behavior” to an actual <em class='hl-yellow'>function</em>",
    s2: "🧹 Saying “the agent behaves intelligently” is easy, but to check it you have to write down <em>how</em> it behaves. Here is how: gather everything the agent has sensed since it was switched on into one sequence, then ask which action that sequence leads to.",
    s3: "THREE WORDS TO KEEP APART",
    s4: "<strong class='hl-yellow'>Percept</strong> — what the sensors deliver at <em>one instant</em>. One image, one sensor reading, once.",
    s5: "<strong class='hl-yellow'>Percept sequence</strong> — the entire history, from the first percept to the one that just arrived. Nothing left out.",
    s6: "<strong class='hl-yellow'>Agent function</strong> — the rule mapping every percept sequence to exactly one action. This is the <em>mathematical description</em> of the behavior, not code.",
    s7: "The <strong class='hl'>agent program</strong> is the part that runs. It differs from the agent function in one very practical way: the function takes the whole history, while the program is only ever handed <strong class='hl'>the current percept</strong> — if it wants to remember the past, it has to arrange storage itself. That small detail comes back to bite you in section <a href='#ch8'>08</a>.",
    s8: "THE TWO-SQUARE VACUUM WORLD",
    s9: "The smallest world that still teaches something: <strong class='hl'>two squares</strong> called A and B, each clean or dirty, with the robot standing in one of them. A percept is the pair <span class='code-inline'>[location, status]</span>. There are four actions: go left, go right, suck, do nothing.",
    s10: "PERCEPT SEQUENCE",
    s11: "ACTION",
    s12: "The ⋮ at the bottom of the table is the frightening part. There are only <strong class='hl'>4 kinds</strong> of percept — two squares times two statuses, the Cartesian product from the math primer. But for sequences up to 10 steps long, the number of rows to enumerate is 4 + 4² + … + 4¹⁰ = <strong class='hl-red'>1,398,100 rows</strong>. A world with exactly two squares, and the table is already over a million rows for the first ten steps. When you reach the lab in section <a href='#ch3'>03</a>, switch to the <strong class='hl'>four-square</strong> world and think about this number again: percepts become 8 kinds, and over those same ten steps the table swells to <strong class='hl-red'>1,227,133,512 rows</strong> — two extra squares, nearly 900 times longer.",
    s13: "LUCKY NOBODY WROTE THAT TABLE — THESE FOUR LINES DO THE SAME JOB",
  },
  ch3: {
    s1: "“Doing the right thing” — but <em class='hl-green'>who grades it</em>?",
    s2: "Suppose you hire a cleaner and pay by <em>the kilos of rubbish collected</em>. Week one, spotless. By week three you start noticing rubbish in places that never had any before.<br/><br/>Nobody cheated — the cleaner is maximizing exactly what you measured. A rational agent does the right thing, but right by whose measure? What I want you to take from this section is this: <strong class='hl'>the ruler lives with the designer, not inside the agent</strong> — so set the wrong ruler and the better the agent gets, the more damage it does.",
    s3: "PERFORMANCE MEASURE",
    s4: "It grades <strong class='hl'>the sequence of ENVIRONMENT states</strong>, not the agent’s state. Worth underlining: an agent can feel it is doing wonderfully, brimming with confidence — the score still belongs to the floor, not to the confidence.",
    s5: "HOW TO SET THE RULER",
    s6: "Set it by <strong class='hl'>what you actually want to be true of the environment</strong>, not by how you think the agent ought to behave. The classic: grading on “how much dirt collected in an eight-hour shift” sounds perfectly reasonable — until you notice the agent maximizing it by dumping the dirt back out and collecting it again. What you want is a <em>clean floor</em>, so grade the clean floor.",
    s7: "THE FULL DEFINITION — THE FOUR THINGS IT LEANS ON",
    s8: "<em>For each possible percept sequence, a rational agent selects the action expected to maximize its performance measure, given the evidence the percept sequence provides and whatever built-in knowledge the agent has.</em>",
    s9: "PERFORMANCE MEASURE",
    s10: "defines what success means",
    s11: "BUILT-IN KNOWLEDGE",
    s12: "what the agent knew about the environment beforehand",
    s13: "PERCEPT SEQUENCE",
    s14: "what it has managed to see so far",
    s15: "ACTIONS",
    s16: "what it is able to do",
    s17: "Change any one of these four and the answer to “is this rational” changes with it. The lab right below lets you change the first one and watch.",
    s18: "THREE EXPERIMENTS I WANT YOU TO RUN RIGHT NOW",
    s19: "<strong class='hl'>One:</strong> pick the “already spotless” floor, then flip between the two programs and watch the final scoreboard. Ruler A scores them <strong class='hl-green'>40 — 40</strong>, a tie. Add exactly one line — “moving costs fuel” — to the measure and it becomes <strong class='hl-red'>20 — 39</strong>. Not a line of either program changed; only the ruler did, and the pure reflex agent fell from perfect to dismal.",
    s20: "<strong class='hl'>Two:</strong> same spotless floor, run “reflex + memory” from step 0 and watch the NOTEBOOK row. At step 1 it still has to go across to B — because it has <em>never seen</em> B, and until it has seen it, it has no right to conclude anything. Only after looking does it dare to stop. That is the information-gathering lesson from section <a href='#ch4'>04</a>, and the reason memory is needed in section <a href='#ch8'>08</a> — you met it before I got round to teaching it.",
    s21: "<strong class='hl'>Three:</strong> hit the <strong class='hl-cyan'>4 squares</strong> button, floor still spotless. Ruler A still ties at <strong class='hl-green'>80 — 80</strong>, ruler B stretches to <strong class='hl-red'>60 — 77</strong>. The best part is in the action tape: the pure reflex agent drags itself to square D and then <strong class='hl'>ping-pongs between C and D forever</strong> — it never returns to A or B again. The rule “at the end square turn back, otherwise go forward” sounds sensible with two squares; with four it becomes a trap. The version with memory spends three steps scouting and then stops for good: <em>moving costs fuel, but moving in order to know when to stop is still cheaper than moving blind</em>.",
  },
  ch4: {
    s1: "Rational <em class='hl-purple'>is not</em> perfect",
    s2: "This is where I see learners go wrong most often, and they go wrong from session 1. Rational does not mean always producing the best outcome — because outcomes also depend on things the agent had no way of knowing in advance.",
    s3: "OMNISCIENCE",
    s4: "Knowing the actual outcome of every action in advance, with no other possibility left open. It sounds lovely, but in the real world it <strong class=\"hl\">does not exist</strong>. You cross an empty street and an aircraft door lands on you — that decision was still rational, you were just unlucky. Rationality grades the <em>decision</em>, not the <em>outcome</em>.",
    s5: "INFORMATION GATHERING",
    s6: "Doing something purely to <strong class=\"hl\">improve what you will see later</strong> — looking both ways before crossing, opening the lid to check, going out to scout. It sounds like a wasted move, but it is part of being rational: crossing with your eyes shut isn’t unlucky, it’s reckless.",
    s7: "LEARNING",
    s8: "A rational agent has to learn as much as it can from what it perceives. The initial configuration the designer loads in is only a starting point; experience has to correct and extend it. There are extreme cases where the environment is fully known in advance — then no learning is needed, but those are the rare exception.",
    s9: "AUTONOMY",
    s10: "An agent that lives entirely on knowledge its designer stuffed in, paying no attention to its own percepts, <strong class=\"hl\">lacks autonomy</strong>. A wall clock is the example: no input, running the algorithm it was wound with, no learning, no experience. It stays right exactly as long as nobody carries it into another time zone.",
  },
  ch5: {
    s1: "PEAS — four questions <em class='hl-cyan'>before</em> you type the first line of code",
    s2: "🧭 The task environment is the <em>problem</em>, and the rational agent is the <em>solution</em>. Until the problem is stated, any solution is a guess. PEAS is four questions that force you to finish stating it — and it has to come first, done as fully as you can manage.",
    s3: "Performance measure",
    s4: "What grades this agent?",
    s5: "Environment",
    s6: "What does it live among?",
    s7: "Actuators",
    s8: "By what channels does it act?",
    s9: "Sensors",
    s10: "By what channels does information reach it?",
    s11: "SIX AGENTS, SIX PEAS DESCRIPTIONS",
    s12: "The first row is the self-driving taxi, the one most worth dissecting. Skim the whole table once, then notice: the <strong class='hl'>P</strong> column is the shortest and the hardest to write, because it is where you have to decide what success means — and as section <a href='#ch3'>03</a> just showed, getting that column wrong breaks the whole system.",
    s13: "P · PERFORMANCE",
    s14: "E · ENVIRONMENT",
    s15: "A · ACTUATORS",
    s16: "S · SENSORS",
    s17: "SOFTBOTS — WHEN THE ENVIRONMENT ISN’T THE REAL WORLD",
    s18: "Flight simulators, games, the Internet — all artificial environments, and no less complex for it. An agent living in one is called a <strong class='hl'>softbot</strong>, and every part of it is software: its sensors are packets and file contents, its actuators the screen and the disk. Don’t mistake “artificial” for “easy”.",
    s19: "TRY THIS NOW, DON’T READ ON YET",
    s20: "Write PEAS for these two, and deliberately put them side by side: <strong class='hl'>(1) playing a tennis match in a tournament</strong> — <strong class='hl'>(2) practicing tennis by hitting a ball against a wall</strong>. Same sport, same racket, and the P column of each is nothing like the other. Keep that piece of paper; section <a href='#ch6'>06</a> makes you use these same two again.",
  },
  ch6: {
    s1: "Seven dimensions for <em class='hl-yellow'>measuring</em> an environment",
    s2: "🎛️ Before you read on, answer one thing for me: <strong class='hl'>how many dimensions apart are poker and backgammon?</strong><br/><br/>Exactly one. Both involve chance, both are discrete, both have several players — but backgammon lays every piece out on the board while poker keeps cards face down. If you were about to answer “two, because poker is also stochastic”, you just walked into the trap the table below exists to spring: <em>seeing everything</em> and <em>predicting what comes next</em> are two independent matters.<br/><br/>The seven pairs below are the measurements that tell you what you are facing — and more importantly, they decide the minimum agent architecture you are forced to use. The more dimensions that land on the right-hand side, the harder the problem.",
    s3: "THE OBSERVABILITY DIMENSION DESERVES MORE THAN A LABEL",
    s4: "<strong class='hl'>Fully observable</strong> means the sensors hand the agent the <em>entire</em> state of the environment. The reward is very concrete: the agent needs no internal state, because there is nothing to remember — one look tells it everything.",
    s5: "It drops to <strong class='hl'>partially</strong> observable for one of two reasons, and they are quite different. <strong class='hl-cyan'>Reason one — noisy or inaccurate sensors:</strong> the information arrives, but it arrives wrong. <strong class='hl-cyan'>Reason two — some part of the state simply isn’t in the sensor data at all:</strong> the robot in section <a href='#ch3'>03</a> only has a dirt sensor <em>for the square it is standing in</em>, so it cannot know the state of the other one — which is exactly why the version with memory still has to trudge over to B once before it dares to stop. You saw it for yourself before I had a name for it.",
    s6: "And there is an extreme: <strong class='hl-red'>unobservable</strong> — the agent has no sensors at all. It sounds like a joke, but there is still a way through: it has to act purely on built-in knowledge, following a route worked out in advance with its eyes shut.",
    s7: "THE SEVENTH DIMENSION — AND WHY IT ISN’T IN THE TABLE ABOVE",
    s8: "<strong class='hl-yellow'>Known vs unknown</strong>. A <em>known</em> environment is one where the outcome of every action is given in advance (or the probabilities of outcomes, if it is stochastic). If it is unknown, the agent has to learn how it works before it can make decent decisions.",
    s9: "I kept it out of the explorer table because it is <strong class='hl'>not the same kind of thing</strong> as the other six: those describe the environment itself, while this one describes <em>the agent’s state of knowledge</em> about the environment. The two are independent — you can perfectly well observe a whole game and still not know the rules, like your first time sitting down at a Go board.",
    s10: "THE EASIEST ENVIRONMENT",
    s11: "Fully observable · deterministic · episodic · static · discrete · single agent. Land this set and you are in paradise.",
    s12: "AND MOST REAL-WORLD SITUATIONS",
    s13: "Partially observable · stochastic · sequential · dynamic · continuous · multi-agent. The full right-hand set. Click “Taxi driving” in the table above and see — that is this row exactly.",
    s14: "TWO THINGS PEOPLE MIX UP — AND ONE MARKED FOR SESSION 5",
    s15: "<strong class='hl'>Episodic ≠ static.</strong> Episodic is about whether the decision you make now affects later decisions; static is about whether the environment changes while you sit thinking. A part-picking robot is episodic and still dynamic.",
    s16: "<strong class='hl'>Stochastic ≠ multi-agent.</strong> Medical diagnosis is full of surprises but has a single agent — the bacterium isn’t calculating how to beat you. Just ask: is the other entity’s behavior aimed at maximizing a measure that depends on my behavior? Only then is it an agent.",
    s17: "And once there are several agents, they split again by how their measures relate. <strong class='hl-red'>Competitive</strong>: my point is your lost point — chess, you win and I lose, no other arrangement. <strong class='hl-green'>Cooperative</strong>: sharing a road, everyone wants to get home and <em>nobody wants a collision</em>, so your measure and mine mostly point the same way. Hold on to the word competitive — session 5 renames it “adversarial search”, and the whole of minimax grows out of exactly this spot.",
  },
  ch7: {
    s1: "Why not just precompute <em class='hl-red'>every answer</em> into a table?",
    s2: "📇 The agent function already is a lookup table: every percept sequence maps to an action. So enumerate them all, look them up, done. <strong class='hl'>Where does that go wrong?</strong><br/><br/>Rule things out before reading on. Too slow? No — a lookup is the fastest operation there is. Can’t remember the past? Also no, it holds the entire sequence. Can’t handle a stochastic environment? Still not it.<br/><br/>It goes wrong somewhere so mundane it is easy to skip past — and that spot is the doorway into the hardest problem in the field.",
    s3: "TABLE-DRIVEN-AGENT",
    s4: "function TABLE-DRIVEN-AGENT(percept) returns an action\n      persistent: percepts, a sequence, initially empty\n                  table, a table of actions, indexed by\n                         percept sequence, initially fully specified\n\n      append percept to the end of percepts\n      action ← LOOKUP(percepts, table)\n      return action",
    s5: "It keeps the whole percept sequence in memory, appends each new percept, then looks it up. Tidy, and it <strong class='hl'>does exactly what you asked for</strong>.",
    s6: "THE NUMBER THAT KILLS THE IDEA",
    s7: "Let <span class='code-inline'>P</span> be the number of possible percepts and <span class='code-inline'>T</span> the agent’s lifetime measured in percepts received. The table size is the sum of <span class='code-inline'>P^t</span> for t from 1 to T. For chess, taking P ≈ 10 and T = 150 moves, the table needs <strong class='hl-red'>at least 10¹⁵⁰ rows</strong>.",
    s8: "CHESS LOOKUP TABLE",
    s9: "10¹⁵⁰ rows",
    s10: "ATOMS IN THE OBSERVABLE UNIVERSE",
    s11: "Not “a bit large”. Seventy orders of magnitude larger than the universe — gather every particle of matter in existence into one hard drive and you still couldn’t record a billionth of a billionth of a billionth of that table 😅",
    s12: "SO WHAT IS THE CORE CHALLENGE OF AI",
    s13: "Writing programs that <strong class='hl'>produce rational behavior from a small amount of code rather than from an enormous number of table rows</strong>. That’s one sentence, and it is the entire field.",
    s14: "One comparison makes this land immediately: square roots. You could build a lookup table of square roots for every number — or write <strong class='hl-green'>five lines of Newton’s method</strong>. Those five lines beat the table on every count: smaller, works on numbers that were never in the table, and anyone reading it can see why it is correct. Every remaining session of this course — search, logic, machine learning — is a different way of hunting for the “five lines of Newton” for harder problems.",
    s15: "One more formula before I move on: <strong class='hl'>agent = architecture + program</strong>. The architecture is the actual machine with real sensors and actuators — an ordinary computer, or a car covered in cameras. The program has to suit the architecture: if the program says “walk”, the architecture had better have legs.",
  },
  ch8: {
    s1: "Five levels, from <em class='hl-purple'>a frog</em> to something that rewrites itself",
    s2: "🪜 A frog sitting by a pond gets by on exactly three rules: small thing moving, snap at it; large thing moving, dodge; otherwise do nothing. Three rules, no memory, no goals — and enough to keep a species alive for millions of years.<br/><br/>It is the lowest of the five levels below. These five architectures are usually drawn as five separate diagrams, which makes them look like five equal-ranking options — they aren’t. They are <strong class='hl'>one diagram growing</strong>, each level adding exactly one thing to cure exactly one fatal flaw of the level beneath. Click 1 → 5 and watch the yellow box.",
    s3: "THE FROG — A REFLEX AGENT THAT ACTUALLY EXISTS IN NATURE",
    s4: "Only two things come in through its senses: <strong class='hl'>size</strong> and <strong class='hl'>movement</strong>. Its entire rule set is this short:",
    s5: "(1) SMALL thing moving →",
    s6: "SNAP",
    s7: "(2) LARGE thing moving →",
    s8: "DODGE",
    s9: ", and suppress the snap reflex",
    s10: "(3) otherwise (not moving) →",
    s11: "DO NOTHING",
    s12: "Rule (3) looks redundant but is mandatory: a rule set with no default branch is a rule set with a hole, and the agent freezes the moment something unforeseen turns up. The price of this architecture shows up right there in rule (1) too — roll a marble past and the frog snaps at it.",
    s13: "WHAT MEMORY LOOKS LIKE WRITTEN OUT",
    s14: "Still a rule table, except the IF side can now refer to <em>the past</em>. Compare the two middle rows — the same percept, “object ahead”, two different actions, purely because what came before differs:",
    s15: "IF",
    s16: "THEN",
    s17: "No object ahead",
    s18: "Go straight",
    s19: "Object ahead",
    s20: "Turn at random",
    s21: "Saw an object, turned right, now the way ahead is clear",
    s22: "Go straight",
    s23: "Saw an object, turned right, another object ahead",
    s24: "Stop",
    s25: "Those bottom two rows are what a pure reflex agent <strong class='hl'>simply cannot express</strong> — it only receives the current percept, with nowhere to keep the sentence “I already turned right”. Remember section <a href='#ch2'>02</a>? The agent function takes the whole sequence; the agent program gets one percept. Internal state is how the program patches that gap.",
    s26: "SO WHERE DO THE “AI AGENTS” EVERYONE TALKS ABOUT SIT?",
    s27: "Worth asking, because the name is the same and the substance isn’t. Put a coding assistant through those five levels. It <strong class='hl'>has internal state</strong> — it remembers what it read and edited — so it clears level 1. It <strong class='hl'>has goals</strong>: you give it a job, it tries actions and checks whether it has got there. That is level 3, and most of what gets called an “AI agent” stops here.",
    s28: "Level 4 is shaky. It rarely has an explicit <em>scale</em> for weighing speed against safety, or a sure thing against a valuable gamble — that scale usually lives in your head rather than in the program. Level 5 is nearly absent: the model <strong class='hl-red'>does not correct itself after each complaint</strong>. Learning happens on a completely different cycle, run by other people, months apart. The critic → learner → problem generator loop you just watched at level 5 is still empty.",
    s29: "None of that is to sneer. It is to give you a ruler: next time you read an advert for an “autonomous agent”, you can ask the right question — <em>which level is it on, and who is holding the three boxes of level 5?</em>",
    s30: "THE THREAD — EVERY LEVEL IS A LATER SESSION",
    s31: "Don’t read these five as a list to memorize. They are the table of contents for the course: <strong class='hl'>level 3</strong> gives you sessions 3–6, where you find a route to a goal with search and constraints. <strong class='hl'>Level 4</strong> is the scale session 5 uses to compare two chess moves and session 9 uses to weigh probabilities. <strong class='hl'>Level 5</strong> is sessions 10 and 11 — the learner there has names of its own, ID3 and neural networks. And <strong class='hl'>level 2</strong>, the world model, is what sessions 7 and 8 write out in logic.",
  },
  ch9: {
    s1: "One page of wrap-up",
    s2: "and a self-check before session 3",
    s3: "If you keep only one page from this session, keep this one.",
    s4: "Perceives through sensors, acts through actuators. Its behavior is the function <span class=\"code-inline\">f : 𝓟* → 𝓐</span> — the whole history in, one action out. The agent program is the runnable version of that function, and it is only ever handed the current percept.",
    s5: "RATIONALITY",
    s6: "Choose the action <em>expected</em> to maximize the performance measure, given the percept sequence so far and built-in knowledge. The measure grades the environment, not the agent. Rational is not omniscient, not perfect, and it does include scouting and learning.",
    s7: "Four questions to answer before designing: performance measure · environment · actuators · sensors. The seven environment dimensions decide the minimum architecture you are forced to use — lose full observability and you lose the right to use a pure reflex agent.",
    s8: "FIVE ARCHITECTURES",
    s9: "Reflex → add internal state and a world model → add goals → add a utility function → add the learning loop (critic · learner · problem generator). Each level cures exactly one fatal flaw of the one below, and the enormous lookup table is why no level is allowed to precompute every answer.",
    s10: "SELF-CHECK — TICK IT WHEN YOU CAN SAY IT OUT LOUD, NOT WHEN IT LOOKS FAMILIAR",
    s11: "Tell apart percept, percept sequence, agent function and agent program — and say exactly where the program differs from the function.",
    s12: "Explain why the performance measure grades the sequence of environment states rather than the agent.",
    s13: "Give a badly set measure and its concrete consequence (don’t reuse my rubbish-collecting one).",
    s14: "Say why rational doesn’t mean omniscient, and why scouting is part of being rational.",
    s15: "Write PEAS for a task of your choosing, with real content in all four entries.",
    s16: "Read an unfamiliar environment and place it on the seven dimensions, with a justification for each.",
    s17: "Explain why a table-driven agent is impossible, using a number rather than a feeling.",
    s18: "List the five architectures in order, saying for each what it adds and which fatal flaw it cures.",
  },
  quiz: {
    s1: "Quiz — how much did you <em class='hl-cyan'>actually</em> take in?",
    s2: "eight questions · agent function, performance measure, PEAS, the seven dimensions, the five architectures",
    s3: "Reading straight through and feeling like you got all of it is the most familiar sensation there is — and the easiest one to fool yourself with. The eight questions below aren’t here to grade you; they’re here to expose where you only <em>recognize</em> something rather than understand it. Get one wrong and read the explanation right underneath, don’t save it for later. Finish these before the homework.",
  },
  hw: {
    s1: "Homework — Session 2",
    s2: "four questions · PEAS and environment properties",
    s3: "✏️ Four questions, two games played outdoors. I hinted at these in session 1 and said they could wait — now you have the tools to do them properly. Use pen and paper, not your head: the sticking points show up the moment you have to write the P column down.",
    s4: "A FIFTH QUESTION, NOT ON THE SHEET, AND THE ONE MOST WORTH DOING",
    s5: "Go back to the two tennis tasks in section <a href='#ch5'>05</a> — playing a match and hitting a ball against a wall — and place both on the seven dimensions. You’ll find they differ on <strong class='hl'>the number of agents</strong> and on the <strong class='hl'>episodic / sequential</strong> dimension. Then ask yourself: is the wall an agent? Answering that means you have genuinely understood the criterion separating an agent from an object, rather than merely memorizing it.",
    s6: "Next up: <strong class='hl'>Session 3 — Solving Problems by Searching</strong>. There you build exactly the level-3 agent from section 08: it has a goal, and it has to find its own way there.",
    s7: "← Back to the roadmap",
  },
  agentarchdiagram: {
    s1: "Environment",
    s2: "What the world",
    s3: "is like now",
    s4: "What it will be like",
    s5: "if I do A",
    s6: "How happy that",
    s7: "will make me",
    s8: "So what should",
    s9: "I do now",
    s10: "State",
    s11: "How the world changes on its own",
    s12: "What my actions do",
    s13: "Goals",
    s14: "Utility",
    s15: "Condition–action rules",
    s16: "Sensors",
    s17: "Actuators",
    s18: "Sensors",
    s19: "Actuators",
    s20: "Performance standard",
    s21: "Critic",
    s22: "Learner",
    s23: "Performance element",
    s24: "Problem generator",
    s25: "percepts",
    s26: "feedback",
    s27: "changes",
    s28: "knowledge",
    s29: "learning goals",
    s30: "Five levels, one diagram",
    s31: "click 1 → 5; the yellow box is what that level just added",
    s32: "WHERE IT GIVES UP — AND WHY THERE IS A NEXT LEVEL",
    s33: "<em>For the taxi:</em> ",
  },
  vacuumlab: {
    s1: "Suck",
    s2: "Left",
    s3: "Right",
    s4: "NoOp",
    s5: "suck",
    s6: "move",
    s7: "move",
    s8: "stay put",
    s9: "ACTION TAPE · CLICK TO JUMP TO ANY STEP",
    s10: "suck",
    s11: "move",
    s12: "stay put",
    s13: "nothing yet — just switched on",
    s14: "one action sequence, three measures grading in parallel",
    s15: "PROGRAM",
    s16: "WORLD",
    s17: "the original — A and B",
    s18: "corridor A · B · C · D, same four actions as before",
    s19: "STARTING FLOOR",
    s20: "ACTION THIS STEP",
    s21: "— not started",
    s22: "↺ Back to start",
    s23: "← Back",
    s24: "Forward →",
    s25: "To the end ⇥",
    s26: "This table grades both programs above on whichever floor you have selected, so you don’t have to click back and forth to compare. A green cell is the winner on that measure, a red cell the loser — and <strong class='hl'>notice which columns tie and which don’t</strong>.",
  },
  vacuumroom: {
    s1: "seen clean",
    s2: "notebook: seen clean",
    s3: "not yet known",
    s4: "notebook: not yet known",
    s5: "SEEN HERE",
    s6: "PERCEPT",
    s7: "nothing seen yet",
  },
  envexplorer: {
    s1: "Explorer table · which environment lands on which side",
    s2: "six dimensions arranged into a comparison table",
  },
} satisfies typeof VI;
