import type { Course } from '../../types';

const M = `${import.meta.env.BASE_URL}materials/`;
const U = M + 'Lecture/';

export const csc14003: Course = {
  slug: 'csc14003',
  code: 'CSC14003',
  title: 'Cơ sở',
  titleAccent: 'Trí tuệ Nhân tạo',
  subtitle: 'Lộ trình tự học 11 tuần · 4 phần · dựa trên active recall & spaced repetition',
  description:
    'Đi từ câu hỏi “trí tuệ nhân tạo là gì” tới chỗ tự cài được các thuật toán tìm kiếm, viết được suy luận logic và huấn luyện được mô hình học máy đầu tiên. Bài học do mình viết lại theo cách hiểu của mình, tham khảo khóa “Các thuật toán thông minh nhân tạo” (Đại học Khoa học Tự nhiên – TP.HCM) và CS188 — Introduction to Artificial Intelligence (UC Berkeley).',
  org: 'Sổ tay tự học · CSC14003',
  weeks: 11,
  parts: [
    { id: 'foundations', no: 'PHẦN I', title: 'Nhập môn & Tác tử', en: 'Foundations & Agents', range: 'Tuần 1–2', color: 'var(--green)',
      testDesc: '8 câu · Buổi 1–2 · bốn hướng tiếp cận AI, phép thử Turing, PEAS, kiến trúc agent' },
    { id: 'searching', no: 'PHẦN II', title: 'Tìm kiếm', en: 'Searching', range: 'Tuần 3–6', color: 'var(--cyan)',
      testDesc: '8 câu · Buổi 3–6 · tìm kiếm mù, heuristic, cục bộ, đối kháng và CSP' },
    { id: 'knowledge', no: 'PHẦN III', title: 'Biểu diễn tri thức & suy luận', en: 'Knowledge & Reasoning', range: 'Tuần 7–9', color: 'var(--purple)',
      testDesc: '10 câu · Buổi 7–9 · logic mệnh đề, FOL, mạng Bayes' },
    { id: 'ml', no: 'PHẦN IV', title: 'Học máy', en: 'Machine Learning', range: 'Tuần 10–11', color: 'var(--yellow)',
      testDesc: '10 câu · Buổi 10–11 · ID3, Naïve Bayes, mạng nơ-ron' },
  ],
  sessions: [
    { id: 'b1', week: 1, part: 0, title: 'Buổi 1 · Nhập môn AI', en: 'Introduction to AI', hours: '~2h lý thuyết',
      lessonPath: '/courses/csc14003/lessons/b1',
      topics: 'AI là gì (4 hướng: think/act × human/rational) · Turing Test · lịch sử AI · ứng dụng · vì sao học theo góc nhìn agent.',
      math: 'Không cần toán — chỉ cần tư duy phản biện. Đọc trước: Rational (duy lý), Agent (tác tử).',
      links: [] },
    { id: 'b2', week: 2, part: 0, title: 'Buổi 2 · Tác tử thông minh', en: 'Intelligent Agents', hours: '~2.5h',
      lessonPath: '/courses/csc14003/lessons/b2',
      topics: 'Agent & môi trường · chuỗi tri giác · tính duy lý · mô tả PEAS · 7 chiều môi trường · 5 kiến trúc agent (reflex → learning).',
      math: 'Set (tập hợp) · Function / mapping (ánh xạ) · Cartesian product (tích Descartes).',
      links: [{ label: 'Bài tập', href: U + 'buoi1/Homework1.pdf' }] },
    { id: 'b3', week: 3, part: 1, title: 'Buổi 3 · Giải bài toán bằng Tìm kiếm', en: 'Search: Uninformed + Informed', hours: '~6h · 3 phần',
      lessonPath: '/courses/csc14003/lessons/b3', labChip: 'LAB 1 · SEARCH',
      topics: 'Phát biểu bài toán (5 thành phần) · không gian trạng thái · BFS, UCS, DFS, DLS, IDS · heuristic · GBFS, A* · admissible & consistent.',
      math: 'Graph (đồ thị) · Tree (cây), branching factor b (hệ số phân nhánh) · Stack / Queue / Priority queue · Big-O · Logarithm (logarit).',
      links: [{ label: 'Bài tập 1', href: U + 'buoi2/Homework2.pdf' }, { label: 'Bài tập 2', href: U + 'buoi3/Homework3.pdf' }, { label: 'Lab 1', href: M + 'Lab/Lab 1 - Searching/Lab 1 - Searching.pdf' }] },
    { id: 'b4', week: 4, part: 1, title: 'Buổi 4 · Tìm kiếm cục bộ', en: 'Local Search & Optimization', hours: '~2.5h',
      topics: 'Bài toán tối ưu · state-space landscape · hill-climbing + biến thể · simulated annealing · local beam · genetic algorithm.',
      math: 'Local / global extremum (cực trị địa phương / toàn cục) · Gradient (hướng dốc) — mức trực giác · Probability (xác suất cơ bản) · Permutation (hoán vị).',
      links: [{ label: 'Bài tập', href: U + 'buoi4/Homework4.pdf' }] },
    { id: 'b5', week: 5, part: 1, title: 'Buổi 5 · Tìm kiếm đối kháng', en: 'Adversarial Search / Games', hours: '~3h',
      topics: 'Game theory · cây trò chơi · minimax · cắt tỉa α-β · quyết định thời gian thực · trò chơi ngẫu nhiên (expectiminimax).',
      math: 'Game tree (cây trò chơi) · Expected value (kỳ vọng) · Recursion (đệ quy) · lập luận min / max.',
      links: [{ label: 'Bài tập', href: U + 'buoi5/Homework5.pdf' }] },
    { id: 'b6', week: 6, part: 1, title: 'Buổi 6 · Bài toán thỏa mãn ràng buộc', en: 'Constraint Satisfaction Problems', hours: '~3h + tự kiểm tra giữa kỳ',
      topics: 'X / D / C · constraint graph · node & arc consistency (AC-3) · backtracking + MRV, LCV, forward checking · min-conflicts.',
      math: 'Relation (quan hệ) · Graph coloring (tô màu đồ thị) · Backtracking recursion (đệ quy quay lui) · Domain (miền giá trị).',
      links: [] },
    { id: 'b7', week: 7, part: 2, title: 'Buổi 7 · Tác tử logic · Logic mệnh đề', en: 'Logical Agents · Propositional Logic', hours: '~4h', labChip: 'LAB 2 · LOGIC',
      topics: 'KB agent · thế giới Wumpus · cú pháp & ngữ nghĩa PL · entailment · model checking · resolution · forward / backward chaining · DPLL.',
      math: 'Proposition (mệnh đề) · Truth table (bảng chân trị) · Connectives ∧ ∨ ¬ ⇒ ⇔ (phép nối) · Tautology (hằng đúng) · Proof by contradiction (phản chứng).',
      links: [{ label: 'Bài tập', href: U + 'buoi6/Homework6.pdf' }, { label: 'Lab 2', href: M + 'Lab/Lab 2 - Logic/Lab2.ipynb' }] },
    { id: 'b8', week: 8, part: 2, title: 'Buổi 8 · Logic bậc nhất', en: 'First-Order Logic', hours: '~4.5h',
      topics: 'Objects / relations / functions · lượng từ ∀ ∃ · viết câu FOL · unification · forward / backward chaining · resolution.',
      math: 'Predicate (vị từ) · Quantifier ∀ ∃ (lượng từ) · Substitution (phép thế) · Set-builder notation (ký hiệu tập hợp).',
      links: [{ label: 'Bài tập', href: U + 'buoi7/Homework7.pdf' }] },
    { id: 'b9', week: 9, part: 2, title: 'Buổi 9 · Mạng Bayes', en: 'Bayesian Networks', hours: '~3h',
      topics: 'Phân phối đồng thời đầy đủ · độc lập có điều kiện · cấu trúc BN + CPT · suy diễn chính xác (enumeration) · xây dựng BN.',
      math: 'Conditional probability (xác suất có điều kiện) · Bayes’ rule (định lý Bayes) · Independence (độc lập) · Marginalization (biên hóa) · DAG.',
      links: [] },
    { id: 'b10', week: 10, part: 3, title: 'Buổi 10 · Học máy cơ bản · Cây quyết định ID3', en: 'Basic ML · ID3 · Naïve Bayes', hours: '~4h', labChip: 'LAB 3 · DECISION TREE',
      topics: 'ML là gì · các kiểu học · supervised learning · ID3: entropy & information gain · Naïve Bayes · train/test, accuracy.',
      math: 'Entropy (độ hỗn loạn thông tin) · log₂ · Expected value (kỳ vọng) · Conditional probability · Weighted average (trung bình có trọng số).',
      links: [{ label: 'Bài tập', href: U + 'buoi8/Homework8.pdf' }, { label: 'Lab 3', href: M + 'Lab/Lab 3 - Decision Tree/Lab3-DecisionTree.pdf' }] },
    { id: 'b11', week: 11, part: 3, title: 'Buổi 11 · Mạng nơ-ron', en: 'Neural Networks: Perceptron & MLP', hours: '~3.5h + tổng ôn',
      topics: 'Nơ-ron sinh học → nhân tạo · perceptron + luật học · khả tách tuyến tính · MLP · backpropagation · hàm kích hoạt.',
      math: 'Vector & dot product (tích vô hướng) · Matrix multiplication (nhân ma trận) · Derivative & chain rule (đạo hàm, quy tắc chuỗi) · Sigmoid · Gradient descent (hạ gradient).',
      links: [{ label: 'Bài tập', href: U + 'buoi9/Homework9.pdf' }] },
  ],
};
