import type { TestPart } from './part-tests';

/*
 * Bản tiếng Anh của bộ đề kiểm tra tổng hợp. Viết PHẲNG (không dẫn xuất) vì đây là file nhiều
 * chữ ít cấu trúc — hai bản đọc đối chiếu cạnh nhau được, và `check_i18n.py` ghép theo vị trí.
 *
 * BẤT BIẾN: `topicId`, `a` (đáp án đúng) và `tex` phải y hệt bản VI. Đổi `a` là bản EN chấm
 * khác bản VI và tiến độ người học tách đôi âm thầm — `check_i18n.py` so từng câu.
 */
export const PART_TESTS_EN: TestPart[] = [
  {
    title: 'Part I — Foundations & Agents (Sessions 1–2)', colorVar: 'var(--green)', tabLabel: 'Foundations & Agents',
    desc: 'The four approaches to AI, the Turing test, 80 years of history — then on to rational agents: PEAS, the environment dimensions, the five kinds of agent. All of it groundwork, so a gap here is a gap in the whole course.',
    qs: [
      { topicId: 'b1', q: 'A system proves mathematical theorems by formal logical deduction and pays no attention to how humans think — which of the four approaches to AI does it belong to?', opts: ['Think like humans', 'Act like humans', 'Think rationally', 'Act rationally'], a: 2, ex: 'It opens the lid and inspects the PROCESS (think), and it measures itself against logic rather than against a human reasoning trace (rationally) → the “laws of thought” box. This course takes the fourth box, act rationally, as its spine.' },
      { topicId: 'b1', q: 'Which of the four definitions of AI does the Turing test measure a machine against?', opts: ['Think like humans', 'Act like humans', 'Think rationally', 'Act rationally'], a: 1, ex: "The interrogator can’t tell which is which → the machine BEHAVES like a human, and that’s the whole test. Nobody asks what is going on inside. This course follows the fourth road instead: act rationally." },
      { topicId: 'b1', q: 'What makes the 1956 Dartmouth conference matter?', opts: ['The first successful training of a multi-layer neural network', 'It settled on the name “Artificial Intelligence” and founded the field as its own discipline', 'The first machine to pass the Turing test', 'Deep Blue beating the reigning world chess champion'], a: 1, ex: 'The McCulloch & Pitts neuron dates to 1943 and Turing’s paper to 1950 — but not until Dartmouth in 1956 did the field get a NAME and a community of its own. Deep Blue was 1997, still a long way off.' },
      { topicId: 'b1', q: 'Why is 1988–93 known as an AI Winter?', opts: ['Computers were still too slow to run search algorithms', 'The expert-systems industry collapsed: promises ran far ahead of what the tech could deliver, so funding was cut', 'Every researcher moved over to neural networks', 'There was no data to train models on'], a: 1, ex: 'Every AI winter follows the same recipe: promise too much → fail to deliver → the money dries up. What came after was 1990–2010, probability and agents — the “AI Spring”.' },
      { topicId: 'b2', q: 'In the PEAS description of a self-driving taxi, which component do “cameras, GPS, speedometer” belong to?', opts: ['Performance measure', 'Environment', 'Actuators', 'Sensors'], a: 3, ex: 'Sensors are the channel IN, actuators the channel OUT (steering, throttle, brakes). This is the pair I see mixed up most — just ask yourself “does this carry information IN, or push an effect OUT?” and it settles.' },
      { topicId: 'b2', q: 'When is an agent called rational?', opts: ['When it knows every outcome of its actions in advance (omniscient)', 'When it picks the action expected to maximize its performance measure, given its percept sequence and built-in knowledge', 'When it never makes a mistake', 'When it imitates human behavior as closely as possible'], a: 1, ex: "Rational ≠ omniscient — do me a favor and hold on to that one. Rational means doing the BEST YOU CAN with the information you actually have. The outcome may still be bad; that’s fine, as long as the decision made sense at the time." },
      { topicId: 'b2', q: 'Chess with a clock is an environment of what kind?', opts: ['Partially observable, stochastic, continuous', 'Fully observable, deterministic, multi-agent, sequential', 'Fully observable, stochastic, single-agent', 'Partially observable, deterministic, discrete'], a: 1, ex: 'Take it one dimension at a time: the board is all visible (fully observable) · a move has a defined result (deterministic) · someone is sitting opposite you (multi-agent) · earlier moves shape later ones (sequential). Add the clock and it becomes semidynamic.' },
      { topicId: 'b2', q: 'A simple reflex agent breaks down when the environment is only partially observable. Which architecture exists to cure exactly that?', opts: ['Goal-based agent — add a goal to reach', 'Model-based reflex agent — keep internal state describing the part of the world it cannot see', 'Utility-based agent — add a utility function', 'Learning agent — add a self-improving component'], a: 1, ex: "If you can’t see enough, you have to REMEMBER — that simple. A model-based agent keeps internal state and updates it from two things: how the world changes on its own, and how its own actions change the world. Goal, utility and learning solve three quite different problems: picking a goal, comparing goals, and getting better." },
    ],
  },
  {
    title: 'Part II — Searching (Sessions 3–6)', colorVar: 'var(--cyan)', tabLabel: 'Searching',
    desc: 'Turn the problem into a graph of states and go looking inside it: uninformed search, heuristics, local search, adversarial search and CSPs. The heaviest part of the course — and the one I enjoy most.',
    qs: [
      { topicId: 'b3', q: 'BFS, DFS and UCS all share the graph-search skeleton. What is the ONE thing that differs?', opts: ['How the goal test is done', 'The data structure behind the frontier', 'How successor states are generated', 'How the explored set is stored'], a: 1, ex: 'FIFO queue → BFS, LIFO stack → DFS, priority queue on g → UCS. One loop, three personalities — swap the frontier and you have swapped the algorithm.' },
      { topicId: 'b3', q: 'Given an admissible heuristic h, which statement is FALSE?', opts: ['A* tree-search returns an optimal solution', 'h(goal) = 0', 'h may exceed the true cost at a few nodes as long as it is lower on average', 'GBFS using h can still return a non-optimal solution'], a: 2, ex: 'Admissible is a constraint AT EVERY NODE: h(n) ≤ h*(n) — averaging doesn’t get you off the hook. One single node that overestimates and A* loses its optimality guarantee entirely. One bad apple.' },
      { topicId: 'b4', q: 'Where does hill-climbing typically get stuck?', opts: ['Global maximum', 'Local maximum, plateau, ridge', 'The initial state', 'An empty frontier'], a: 1, ex: 'It can only see its immediate neighbors: reach a local peak and the road ends, even though the real summit is on the next mountain over. On a flat plateau it wanders, and a ridge makes it zigzag forever without gaining height.' },
      { topicId: 'b4', q: 'By what mechanism does simulated annealing escape a local optimum?', opts: ['Doubling the number of climbing agents (local beam)', 'Occasionally accepting a DOWNHILL step, with a probability that falls as the “temperature” T drops', 'Backtracking to the initial state when stuck', 'Only ever taking the steepest uphill step'], a: 1, ex: 'Picture shaking a box with a marble in it: while it is hot you shake hard and allow downhill moves, so the marble can hop out of a shallow dip. As it cools, only good moves get through. Cool slowly enough and you approach the global optimum.' },
      { topicId: 'b4', q: 'In a genetic algorithm, what does crossover do?', opts: ['Randomly mutate a single gene', 'Splice segments from two parent individuals into a child', 'Discard the individual with the lowest fitness', 'Copy the best individual through unchanged'], a: 1, ex: 'Crossover mixes the good “building blocks” of two parents. Don’t confuse it with mutation (a random tweak) or selection (culling by fitness) — three completely different jobs.' },
      { topicId: 'b5', q: 'A minimax tree: MAX at the root has 2 options; the left branch leads to leaves [3, 12], the right to [2, 8] (MIN moves second). What is the value at the root?', opts: ['12', '3', '2', '8'], a: 1, ex: 'Work bottom-up: MIN takes the smaller value on each branch → left = min(3,12) = 3, right = min(2,8) = 2. Then MAX takes the larger of those: max(3,2) = 3.' },
      { topicId: 'b5', q: 'How does α-β pruning affect the minimax result?', opts: ['An approximate result, in exchange for speed', 'The result is IDENTICAL; it only skips branches that provably cannot change the decision', 'It is only correct on a balanced tree', 'It only works for games of chance'], a: 1, ex: 'This one gets misread a lot, so plainly: α-β is NOT an approximation. It cuts only branches already proven unable to affect the decision at the root. Order the moves well and you examine b^(m/2) nodes instead of b^m, for free.' },
      { topicId: 'b6', q: 'A map-coloring CSP: variables {WA, NT, SA}, domain {red, green, blue}, WA=red. After forward checking on the constraints SA≠WA and NT≠WA, what is left in the domains of SA and NT?', opts: ['SA and NT both keep {red, green, blue}', 'SA and NT both keep {green, blue}', 'SA keeps {green}, NT keeps {blue}', 'SA and NT are both empty'], a: 1, ex: 'Forward checking does one job: strike “red” from the domain of every variable adjacent to WA. But that’s precisely inference interleaved with search — the central idea of the whole CSP chapter.' },
    ],
  },
  {
    title: 'Part III — Knowledge & Reasoning (Sessions 7–9)', colorVar: 'var(--purple)', tabLabel: 'Knowledge & Reasoning',
    desc: 'From propositional logic through first-order logic to probabilistic reasoning with Bayesian networks. This is where the agent stops enumerating states blindly and starts to “think” over knowledge.',
    qs: [
      { topicId: 'b7', q: 'What does “KB ⊨ α” (KB entails α) mean?', opts: ['α appears verbatim inside KB', 'Every model (world) that makes KB true also makes α true', 'α follows from exactly one resolution step', 'KB and α contain the same number of sentences'], a: 1, ex: 'Entailment is a SEMANTIC relation, not a syntactic one: the truth of α is already contained in the truth of KB. Model checking just does what the definition says — enumerate every world and check.' },
      { topicId: 'b7', q: 'In the Wumpus world, square [1,1] has a Breeze. What can KB conclude?', opts: ['There is a pit at [1,2] AND at [2,1]', 'There is a pit at [1,2] OR at [2,1]', 'There is definitely a Wumpus adjacent', 'Nothing can be concluded'], a: 1, ex: 'B₁,₁ ⇔ (P₁,₂ ∨ P₂,₁). A breeze says only “at least one adjacent square has a pit”, never which one. Being able to express INCOMPLETE information like that is exactly where logic beats a handful of booleans in your code.' },
      { topicId: 'b7', q: 'What is the CNF form of the sentence A ⇒ B?', opts: ['A ∧ B', '¬A ∨ B', 'A ∨ ¬B', '¬A ∧ ¬B'], a: 1, ex: 'Implication elimination: (α ⇒ β) ≡ (¬α ∨ β). Remember this one formula if nothing else, because it’s the first move of every conversion to CNF before running resolution.' },
      { topicId: 'b7', q: 'Resolving the two clauses (A ∨ B) and (¬B ∨ C) produces what?', opts: ['A ∧ C', 'A ∨ C', 'B', 'The empty clause'], a: 1, ex: 'B and ¬B cancel, and what’s left joins up: A ∨ C. And a resolution proof always runs the same trick: add ¬α to KB and derive until you reach the empty clause — that is, a contradiction.' },
      { topicId: 'b7', q: 'How do forward chaining and backward chaining differ?', opts: ['FC goes from the goal back to the facts; BC goes from the facts to the goal', 'FC is data-driven (spreading out from facts); BC is goal-driven (working back from the question)', 'FC only works for FOL, BC only for propositional logic', 'They differ in speed, not direction'], a: 1, ex: 'FC: derive whatever follows and keep spreading until you hit the goal — complete for Horn KBs, but it derives a pile of things nobody asked about. BC: only chase what was asked, which saves work; Prolog runs exactly this way.' },
      { topicId: 'b8', q: 'What is the correct way to write “Every student studies at HCMUS”?', opts: ['∀x Student(x) ∧ StudyAt(x, hcmus)', '∀x Student(x) ⇒ StudyAt(x, hcmus)', '∃x Student(x) ⇒ StudyAt(x, hcmus)', '∀x StudyAt(x, hcmus)'], a: 1, ex: 'Remember the pairing: ∀ goes with ⇒. Because ∀ ranges over EVERY object in the universe, you have to fence it in with an implication; use ∧ and you have just declared that everything in existence is a student, chairs included.' },
      { topicId: 'b8', q: '“Some student studies at HCMUS” — why is ∃x Student(x) ⇒ StudyAt(x, hcmus) wrong?', opts: ['Because ∃ must pair with ∧: the sentence above is satisfied even by an x that is not a student (an implication is true whenever its left side is false)', 'Because it is missing an outer ∀', 'Because StudyAt must come before Student', 'It is written correctly'], a: 0, ex: 'And the other half of the pairing: ∃ goes with ∧. Write ∃ with ⇒ and the sentence is already true as soon as a single NON-student exists — it says nothing at all. The correct form is ∃x Student(x) ∧ StudyAt(x, hcmus).' },
      { topicId: 'b8', q: 'What substitution does UNIFY(Knows(John, x), Knows(y, Mary)) yield?', opts: ['{x/John, y/Mary}', '{y/John, x/Mary}', '{x/y}', 'Failure'], a: 1, ex: 'Match position by position: John matches y → y/John; x matches Mary → x/Mary. Unification is the engine underneath every FOL inference — FC, BC and resolution all run on it.' },
      { topicId: 'b9', q: 'Which is the correct statement of Bayes’ rule?', tex: 'P(A\\mid B) = \\dfrac{P(B\\mid A)\\,P(A)}{P(B)}', opts: ['Exactly as written above', 'It is missing P(A) in the denominator', 'P(A|B) = P(B|A), always equal', 'It only holds when A and B are independent'], a: 0, ex: 'What Bayes really buys you is flipping the condition around: P(symptom | disease) is what a hospital can measure easily, but P(disease | symptom) is what you actually want to know. This underpins both Bayesian networks and the Naïve Bayes classifier in Session 10.' },
      { topicId: 'b9', q: 'In a Bayesian network, what do the DAG structure and the CPTs save you compared with a full joint probability distribution (FJPD)?', opts: ['Nothing is saved, it’s only easier to look at', 'A steep drop in parameters thanks to conditional independence: each node needs only P(X | Parents(X))', 'Probability can be dropped entirely', 'It only saves anything when the network has a cycle'], a: 1, ex: 'Run the numbers and it hits you: an FJPD over n binary variables needs 2ⁿ−1 parameters, while a BN needs Σ 2^(number of parents) across its nodes. At 30 variables that is roughly 1 billion numbers against a few hundred. That’s why BNs exist.' },
    ],
  },
  {
    title: 'Part IV — Machine Learning (Sessions 10–11)', colorVar: 'var(--yellow)', tabLabel: 'Machine Learning',
    desc: 'The last leg: the agent stops waiting for you to program it and starts learning from data. ID3 decision trees with entropy & information gain, Naïve Bayes, the perceptron, and multi-layer networks.',
    qs: [
      { topicId: 'b10', q: 'What does supervised learning require of the data?', opts: ['The more dimensions the better', 'Every example carries a correct LABEL', 'The data must be noise-free', 'The data must be numeric'], a: 1, ex: 'You learn from pairs of (input → correct answer), and that’s the whole requirement. No labels and it is unsupervised (clustering); only a delayed reward or penalty and it is reinforcement learning.' },
      { topicId: 'b10', q: 'A dataset holds 8 positive and 8 negative examples. What is its entropy?', tex: 'H(S) = -\\sum_i p_i \\log_2 p_i', opts: ['0 bits', '0.5 bits', '1 bit', '8 bits'], a: 2, ex: 'p₊ = p₋ = 0.5 → H = −0.5·log₂0.5 − 0.5·log₂0.5 = 1 bit. That’s maximum disorder: you know nothing, and guessing a label is a coin flip.' },
      { topicId: 'b10', q: 'What is the entropy of a set containing only positive examples (100% one class)?', opts: ['1 bit', '0 bits', 'Undefined', 'Equal to the number of examples'], a: 1, ex: 'Once it’s pure there’s no uncertainty left: H = −1·log₂1 = 0. This is also exactly when ID3 stops splitting — that, or when it runs out of attributes to ask about.' },
      { topicId: 'b10', q: 'On what criterion does ID3 pick the attribute to split a node on?', tex: 'Gain(S,A) = H(S) - \\sum_v \\tfrac{|S_v|}{|S|} H(S_v)', opts: ['The attribute with the most values', 'The largest information gain — the biggest average drop in entropy', 'Whichever attribute comes first in the table', 'Weighted random choice'], a: 1, ex: 'Gain = parent entropy − the weighted average entropy of the children. In plain terms: pick the question that tells you the most once answered — the same tactic that wins you a game of twenty questions.' },
      { topicId: 'b10', q: 'A decision tree scores 100% on the training set but only 60% on the test set. What is this called, and how do you fix it?', opts: ['Underfitting — grow the tree deeper', 'Overfitting — cap the depth or prune, like the max_depth experiment in Lab 3', 'Data leakage — change algorithm', 'Nothing is wrong, no fix needed'], a: 1, ex: 'The tree has memorized the noise in the training set along with the signal — word-perfect recall without understanding. Lab 3 lets you watch it happen: sweep max_depth on the Breast Cancer set and past a certain depth the test accuracy falls away.' },
      { topicId: 'b10', q: 'What is the “naïve” assumption in Naïve Bayes?', opts: ['Every class has the same prior probability', 'The attributes are independent of one another GIVEN the class', 'The data has no noise', 'There are only 2 classes'], a: 1, ex: 'P(x₁,…,xₙ | C) = Π P(xᵢ | C). That assumption is almost never true in the wild, and yet the model classifies surprisingly well — spam filtering is the classic case.' },
      { topicId: 'b11', q: 'A perceptron: w = [2, −1], x = [1, 3], bias = 0, step activation (threshold 0). What is the output?', tex: 'y = step(\\mathbf{w}\\cdot\\mathbf{x} + b)', opts: ['1 (since 2·1 + (−1)·3 = −1 > −2)', '0 (since w·x = 2 − 3 = −1 < 0)', '−1', 'Undefined when bias = 0'], a: 1, ex: 'Dot product: 2·1 + (−1)·3 = −1. Negative → below threshold → output 0. The whole neuron sounds grand but does exactly three things: multiply, add, compare against a threshold.' },
      { topicId: 'b11', q: 'Which of these can a single-layer perceptron NOT learn?', opts: ['AND', 'OR', 'XOR', 'NOT'], a: 2, ex: 'A perceptron can draw exactly ONE straight dividing line (linear separability), and XOR needs two. It takes a hidden layer (an MLP) to manage it. And yes — this one tiny function is why the whole field went cold through the 1970s.' },
      { topicId: 'b11', q: 'What lets an MLP get past the perceptron’s limitation?', opts: ['A higher learning rate', 'Hidden layers plus a NON-LINEAR activation function', 'More bias terms', 'Normalized data'], a: 1, ex: 'The hidden layer handles combining features, but the non-linearity (sigmoid, ReLU) is what allows the boundary to bend. Drop the non-linearity and you can stack 100 layers and still have one linear map — worth burning into memory.' },
      { topicId: 'b11', q: 'What does backpropagation update the weights from?', tex: 'w \\leftarrow w - \\eta\\,\\dfrac{\\partial E}{\\partial w}', opts: ['The gradient of the error, propagated back from output to input by the chain rule', 'The Manhattan distance between layers', 'How often each neuron fired', 'The random order of the examples'], a: 0, ex: 'A derivative answers exactly one question: “if I turn this dial a little, how much does the error move?”. The chain rule lets you ask that question through many layers. And gradient descent is the simple part: to go down, step against the slope.' },
    ],
  },
];
