import type { TopicId } from './topics';
// Bộ câu hỏi kiểm tra tổng hợp CSC14003 — 4 phần, chấm theo buổi.
export interface TestQuestion {
  topicId: TopicId;
  q: string;
  tex?: string;
  opts: string[];
  a: number;
  ex: string;
}
export interface TestPart {
  title: string;
  colorVar: string;
  desc: string;
  tabLabel: string;
  qs: TestQuestion[];
}

export const PART_TESTS: TestPart[] = [
  {
    title: 'Phần I — Nhập môn & Tác tử (Buổi 1–2)', colorVar: 'var(--green)', tabLabel: 'Nhập môn & Tác tử',
    desc: 'Bốn hướng tiếp cận AI, phép thử Turing, 80 năm lịch sử — rồi tới tác tử duy lý: PEAS, các chiều môi trường, năm kiểu agent. Toàn khái niệm nền, hổng ở đây là hổng cả khóa.',
    qs: [
      { topicId: 'b1', q: 'Một hệ thống chứng minh định lý toán bằng suy diễn logic hình thức, không quan tâm con người nghĩ thế nào — nó nằm ở ô nào trong 4 hướng tiếp cận AI?', opts: ['Think like humans', 'Act like humans', 'Think rationally', 'Act rationally'], a: 2, ex: 'Nó mở nắp máy ra xem QUÁ TRÌNH (think), và cầm cây thước logic chứ không phải vết suy luận của người (rationally) → ô «luật của tư duy». Còn khóa này thì chọn ô thứ tư, act rationally, làm trục.' },
      { topicId: 'b1', q: 'Turing Test kiểm tra máy theo hướng tiếp cận nào trong 4 định nghĩa AI?', opts: ['Think like humans', 'Act like humans', 'Think rationally', 'Act rationally'], a: 1, ex: 'Người hỏi không phân biệt nổi ai là ai → máy HÀNH XỬ như người, hết. Không ai quan tâm bên trong nó nghĩ gì. Còn khóa này đi theo hướng thứ tư: act rationally.' },
      { topicId: 'b1', q: 'Hội nghị Dartmouth 1956 quan trọng ở điểm nào?', opts: ['Lần đầu huấn luyện được mạng nơ-ron nhiều tầng', 'Chốt cái tên «Artificial Intelligence» và khai sinh ngành như một lĩnh vực riêng', 'Lần đầu có máy vượt qua phép thử Turing', 'Deep Blue thắng kỳ thủ vô địch thế giới'], a: 1, ex: 'Mô hình nơ-ron McCulloch & Pitts có từ 1943, bài báo Turing từ 1950 — nhưng phải tới Dartmouth 1956 ngành mới có TÊN và cộng đồng riêng. Deep Blue thì mãi 1997, còn xa lắm.' },
      { topicId: 'b1', q: 'Vì sao giai đoạn 1988–93 được gọi là AI Winter?', opts: ['Máy tính chưa đủ nhanh để chạy thuật toán tìm kiếm', 'Ngành hệ chuyên gia sụp đổ: kỳ vọng vượt xa năng lực thật nên nguồn tài trợ bị cắt', 'Mọi nhà nghiên cứu chuyển hết sang mạng nơ-ron', 'Không có dữ liệu để huấn luyện mô hình'], a: 1, ex: 'Mùa đông AI nào cũng đúng một công thức: hứa quá tay → không giao nổi kết quả → nhà tài trợ rút ví. Xong rồi tới 1990–2010 với xác suất và agent — giai đoạn «AI Spring».' },
      { topicId: 'b2', q: 'Trong mô tả PEAS của taxi tự lái, «camera, GPS, cảm biến tốc độ» thuộc thành phần nào?', opts: ['Performance measure', 'Environment', 'Actuators', 'Sensors'], a: 3, ex: 'Sensors là kênh NHẬN, actuators là kênh TÁC ĐỘNG (vô-lăng, ga, phanh). Đây là cặp tôi thấy bị nhầm nhiều nhất — cứ tự hỏi «cái này đưa thông tin VÀO hay đẩy tác động RA?» là xong.' },
      { topicId: 'b2', q: 'Một agent được gọi là duy lý (rational) khi nào?', opts: ['Khi nó biết trước mọi kết quả hành động (omniscient)', 'Khi nó chọn hành động kỳ vọng tối đa hóa performance measure, dựa trên chuỗi tri giác và tri thức sẵn có', 'Khi nó không bao giờ mắc lỗi', 'Khi nó bắt chước hành vi con người chính xác nhất'], a: 1, ex: 'Duy lý ≠ toàn tri, nhớ giùm tôi chỗ này. Rational là làm điều TỐT NHẤT CÓ THỂ với thông tin đang có — kết quả có tệ cũng không sao, miễn quyết định lúc đó là hợp lý.' },
      { topicId: 'b2', q: 'Chơi cờ vua (có đồng hồ) là môi trường thuộc loại nào?', opts: ['Quan sát một phần, ngẫu nhiên, liên tục', 'Quan sát đầy đủ, tất định, đa tác tử, tuần tự', 'Quan sát đầy đủ, ngẫu nhiên, một tác tử', 'Quan sát một phần, tất định, rời rạc'], a: 1, ex: 'Soi từng chiều một: bàn cờ lộ hết (fully observable) · nước đi cho kết quả xác định (deterministic) · có người ngồi đối diện (multi-agent) · nước trước ảnh hưởng nước sau (sequential). Thêm cái đồng hồ nữa nên semidynamic.' },
      { topicId: 'b2', q: 'Agent phản xạ đơn giản (simple reflex) hỏng khi môi trường chỉ quan sát được một phần. Kiến trúc nào sinh ra để chữa đúng bệnh đó?', opts: ['Goal-based agent — thêm mục tiêu cần đạt', 'Model-based reflex agent — giữ trạng thái nội tại mô tả phần thế giới không nhìn thấy', 'Utility-based agent — thêm hàm thỏa dụng', 'Learning agent — thêm thành phần tự học'], a: 1, ex: 'Không nhìn đủ thì phải NHỚ — đơn giản vậy thôi. Model-based giữ internal state, cập nhật theo hai thứ: «thế giới tự đổi thế nào» và «hành động của mình đổi thế giới thế nào». Còn goal / utility / learning giải ba bài toán khác hẳn: chọn đích, so sánh các đích, và tự khá lên.' },
    ],
  },
  {
    title: 'Phần II — Tìm kiếm (Buổi 3–6)', colorVar: 'var(--cyan)', tabLabel: 'Tìm kiếm',
    desc: 'Biến đề bài thành đồ thị trạng thái rồi đi tìm trong đó: tìm kiếm mù, heuristic, tìm kiếm cục bộ, đối kháng và CSP. Phần nặng nhất khóa — cũng là phần tôi thấy vui nhất.',
    qs: [
      { topicId: 'b3', q: 'BFS, DFS, UCS dùng chung khung graph-search. Điểm khác nhau DUY NHẤT là gì?', opts: ['Cách kiểm tra đích', 'Cấu trúc dữ liệu của frontier', 'Cách sinh trạng thái kế', 'Cách lưu explored set'], a: 1, ex: 'FIFO queue → BFS, LIFO stack → DFS, priority queue theo g → UCS. Một vòng lặp, ba tính cách — đổi cấu trúc frontier là đổi luôn thuật toán.' },
      { topicId: 'b3', q: 'Với heuristic admissible h, phát biểu nào SAI?', opts: ['A* tree-search cho nghiệm tối ưu', 'h(đích) = 0', 'h có thể lớn hơn chi phí thật ở vài node miễn là trung bình nhỏ hơn', 'GBFS dùng h vẫn có thể trả nghiệm không tối ưu'], a: 2, ex: 'Admissible là ràng buộc TẠI MỌI NODE: h(n) ≤ h*(n), chứ không phải trung bình cho qua. Chỉ cần MỘT node nói phóng lên là A* mất sạch bảo đảm tối ưu — một con sâu làm rầu nồi canh.' },
      { topicId: 'b4', q: 'Hill-climbing hay mắc kẹt ở đâu?', opts: ['Global maximum', 'Local maximum, plateau (cao nguyên), ridge (sống núi)', 'Trạng thái đầu', 'Frontier rỗng'], a: 1, ex: 'Nó chỉ nhìn được mấy hàng xóm sát bên: leo tới đỉnh cục bộ là hết đường, dù đỉnh thật nằm ở ngọn núi kế bên. Plateau phẳng thì nó đi lang thang, ridge thì bắt nó zigzag mãi không lên nổi.' },
      { topicId: 'b4', q: 'Simulated annealing thoát khỏi cực trị cục bộ bằng cơ chế nào?', opts: ['Nhân đôi số agent leo đồi (local beam)', 'Thỉnh thoảng chấp nhận bước ĐI XUỐNG, với xác suất giảm dần theo "nhiệt độ" T', 'Quay lui về trạng thái đầu khi kẹt', 'Chỉ chọn bước lên dốc nhất'], a: 1, ex: 'Hình dung như lắc cái hộp có viên bi trong đó: lúc nóng thì lắc mạnh, chấp nhận cả bước đi xuống để bi nhảy khỏi hố nông. Nguội dần thì chỉ còn nhận bước tốt. Nguội đủ chậm → tiệm cận tối ưu toàn cục.' },
      { topicId: 'b4', q: 'Trong genetic algorithm, «crossover» (lai ghép) làm gì?', opts: ['Đột biến ngẫu nhiên một gene', 'Ghép hai đoạn của hai cá thể cha mẹ thành cá thể con', 'Loại cá thể có fitness thấp nhất', 'Sao chép nguyên vẹn cá thể tốt nhất'], a: 1, ex: 'Crossover là trộn mấy «khối xây dựng» tốt của hai cha mẹ lại với nhau. Đừng lẫn với mutation (đột biến ngẫu nhiên) và selection (loại bớt theo fitness) — ba việc hoàn toàn khác nhau.' },
      { topicId: 'b5', q: 'Cây minimax: MAX ở gốc có 2 lựa chọn; nhánh trái dẫn tới các lá [3, 12], nhánh phải dẫn tới [2, 8] (MIN đi sau). Giá trị gốc là?', opts: ['12', '3', '2', '8'], a: 1, ex: 'Tính từ dưới lên: MIN chọn nhỏ nhất ở mỗi nhánh → trái = min(3,12) = 3, phải = min(2,8) = 2. Rồi MAX chọn lớn nhất trong hai cái đó: max(3,2) = 3.' },
      { topicId: 'b5', q: 'Cắt tỉa alpha-beta (α-β pruning) ảnh hưởng thế nào tới kết quả minimax?', opts: ['Kết quả gần đúng, đổi lại nhanh hơn', 'Kết quả GIỐNG HỆT, chỉ bỏ qua các nhánh chắc chắn không ảnh hưởng quyết định', 'Chỉ đúng khi cây cân bằng', 'Chỉ dùng được cho trò chơi may rủi'], a: 1, ex: 'Chỗ này hay bị hiểu nhầm nên nói rõ: α-β KHÔNG phải xấp xỉ. Nó chỉ cắt những nhánh đã chứng minh được là không thể ảnh hưởng tới quyết định ở gốc. Duyệt đúng thứ tự → xem b^(m/2) node thay vì b^m, miễn phí.' },
      { topicId: 'b6', q: 'CSP tô màu bản đồ: biến {WA, NT, SA}, miền {đỏ, lục, lam}, WA=đỏ. Sau khi chạy forward checking trên ràng buộc SA≠WA và NT≠WA, miền của SA và NT còn lại gì?', opts: ['SA, NT đều còn {đỏ, lục, lam}', 'SA, NT đều còn {lục, lam}', 'SA còn {lục}, NT còn {lam}', 'SA, NT đều rỗng'], a: 1, ex: 'Forward checking chỉ làm một việc: gạch «đỏ» khỏi miền của mọi biến kề WA. Nhưng đó chính là suy diễn (inference) đan xen với tìm kiếm — ý tưởng trung tâm của cả CSP.' },
    ],
  },
  {
    title: 'Phần III — Biểu diễn tri thức & suy luận (Buổi 7–9)', colorVar: 'var(--purple)', tabLabel: 'Tri thức & suy luận',
    desc: 'Từ logic mệnh đề, logic bậc nhất tới suy luận xác suất bằng mạng Bayes. Đây là lúc agent thôi duyệt trạng thái mù quáng và bắt đầu biết «suy nghĩ» trên tri thức.',
    qs: [
      { topicId: 'b7', q: '«KB ⊨ α» (KB entails α) nghĩa là gì?', opts: ['α xuất hiện nguyên văn trong KB', 'Mọi model (thế giới) làm KB đúng đều làm α đúng', 'α được suy ra sau đúng một bước resolution', 'KB và α có cùng số mệnh đề'], a: 1, ex: 'Entailment là quan hệ NGỮ NGHĨA, không phải cú pháp: chân lý của α đã nằm sẵn trong chân lý của KB rồi. Model checking thì làm y hệt định nghĩa — duyệt hết mọi thế giới ra mà kiểm.' },
      { topicId: 'b7', q: 'Trong thế giới Wumpus, ô [1,1] có gió (Breeze). KB kết luận được gì?', opts: ['Có hố ở [1,2] VÀ [2,1]', 'Có hố ở [1,2] HOẶC [2,1]', 'Chắc chắn có Wumpus kề bên', 'Không kết luận được gì'], a: 1, ex: 'B₁,₁ ⇔ (P₁,₂ ∨ P₂,₁). Gió chỉ nói «ít nhất một ô kề có hố», không chỉ đích danh ô nào. Diễn đạt được thông tin KHÔNG ĐẦY ĐỦ như thế chính là chỗ logic ăn đứt mấy biến bool trong code.' },
      { topicId: 'b7', q: 'Dạng CNF (hội chuẩn) của câu A ⇒ B là gì?', opts: ['A ∧ B', '¬A ∨ B', 'A ∨ ¬B', '¬A ∧ ¬B'], a: 1, ex: 'Luật loại kéo theo: (α ⇒ β) ≡ (¬α ∨ β). Nhớ đúng một công thức này thôi cũng được, vì nó là bước đầu tiên của mọi lần đưa về CNF để chạy resolution.' },
      { topicId: 'b7', q: 'Resolution trên hai mệnh đề (A ∨ B) và (¬B ∨ C) cho ra gì?', opts: ['A ∧ C', 'A ∨ C', 'B', 'Mệnh đề rỗng'], a: 1, ex: 'B với ¬B triệt tiêu nhau, phần còn lại gộp lại: A ∨ C. Và chiêu chứng minh bằng resolution lúc nào cũng vậy: nhét ¬α vào KB rồi suy cho tới khi ra mệnh đề rỗng — tức là mâu thuẫn.' },
      { topicId: 'b7', q: 'Forward chaining và backward chaining khác nhau thế nào?', opts: ['FC đi từ đích về dữ kiện; BC đi từ dữ kiện tới đích', 'FC là data-driven (từ facts lan ra); BC là goal-driven (từ câu hỏi truy ngược)', 'FC chỉ dùng cho FOL, BC chỉ cho logic mệnh đề', 'Không khác nhau về hướng, chỉ khác tốc độ'], a: 1, ex: 'FC: có gì suy nấy, cứ lan ra tới khi chạm đích — đầy đủ với Horn KB, nhưng suy ra cả đống thứ chẳng ai hỏi. BC: hỏi gì mới truy ngược cái đó, đỡ tốn công; Prolog chạy đúng kiểu này.' },
      { topicId: 'b8', q: 'Cách viết đúng của «Mọi sinh viên đều học ở HCMUS» là gì?', opts: ['∀x Student(x) ∧ StudyAt(x, hcmus)', '∀x Student(x) ⇒ StudyAt(x, hcmus)', '∃x Student(x) ⇒ StudyAt(x, hcmus)', '∀x StudyAt(x, hcmus)'], a: 1, ex: 'Nhớ cặp bài trùng: ∀ đi với ⇒. Vì ∀ nói về MỌI vật trên đời nên phải khoanh vùng lại bằng kéo theo; xài ∧ là bạn vừa tuyên bố mọi thứ trên đời đều là sinh viên, kể cả cái ghế.' },
      { topicId: 'b8', q: '«Có một sinh viên học ở HCMUS» — vì sao KHÔNG viết ∃x Student(x) ⇒ StudyAt(x, hcmus)?', opts: ['Vì ∃ phải đi với ∧: câu trên đúng cả khi x không phải sinh viên (kéo theo đúng khi vế trái sai)', 'Vì thiếu lượng từ ∀ bên ngoài', 'Vì StudyAt phải đứng trước Student', 'Câu đó viết đúng rồi'], a: 0, ex: 'Và cặp còn lại: ∃ đi với ∧. Viết ∃ + ⇒ thì chỉ cần tồn tại một vật KHÔNG phải sinh viên là câu đã đúng rồi — chẳng nói lên điều gì. Đúng phải là ∃x Student(x) ∧ StudyAt(x, hcmus).' },
      { topicId: 'b8', q: 'UNIFY(Knows(John, x), Knows(y, Mary)) cho phép thế nào?', opts: ['{x/John, y/Mary}', '{y/John, x/Mary}', '{x/y}', 'Thất bại'], a: 1, ex: 'Khớp từng vị trí một: John khớp y → y/John; x khớp Mary → x/Mary. Unification là cái động cơ nằm dưới mọi suy diễn FOL — FC, BC, resolution đều chạy trên nó cả.' },
      { topicId: 'b9', q: 'Định lý Bayes viết đúng là?', tex: 'P(A\\mid B) = \\dfrac{P(B\\mid A)\\,P(A)}{P(B)}', opts: ['Đúng như công thức trên', 'Thiếu P(A) ở mẫu', 'P(A|B) = P(B|A) luôn bằng nhau', 'Chỉ đúng khi A, B độc lập'], a: 0, ex: 'Công dụng thật của Bayes là đảo chiều điều kiện: P(triệu chứng | bệnh) thì bệnh viện đo dễ, còn P(bệnh | triệu chứng) mới là thứ bạn cần biết. Đây là nền của cả mạng Bayes lẫn Naïve Bayes ở Buổi 10.' },
      { topicId: 'b9', q: 'Trong mạng Bayes, cấu trúc DAG + CPT giúp tiết kiệm gì so với bảng phân phối đồng thời đầy đủ (FJPD)?', opts: ['Không tiết kiệm, chỉ dễ nhìn hơn', 'Số tham số giảm mạnh nhờ tính độc lập có điều kiện: mỗi node chỉ cần P(X | Parents(X))', 'Bỏ được hoàn toàn xác suất', 'Chỉ tiết kiệm khi mạng có chu trình'], a: 1, ex: 'Làm phép tính cho thấm: FJPD của n biến nhị phân cần 2ⁿ−1 tham số, còn BN chỉ cần Σ 2^(số cha) ở mỗi node. Với 30 biến là khoảng 1 tỷ con số so với vài trăm. Đấy, đó là lý do BN tồn tại.' },
    ],
  },
  {
    title: 'Phần IV — Học máy (Buổi 10–11)', colorVar: 'var(--yellow)', tabLabel: 'Học máy',
    desc: 'Chặng cuối: agent thôi chờ bạn lập trình mà tự học từ dữ liệu. Cây quyết định ID3 với entropy & information gain, Naïve Bayes, perceptron và mạng nơ-ron nhiều tầng.',
    qs: [
      { topicId: 'b10', q: 'Supervised learning (học có giám sát) cần điều kiện gì ở dữ liệu?', opts: ['Dữ liệu càng nhiều chiều càng tốt', 'Mỗi mẫu có NHÃN (label) đúng kèm theo', 'Dữ liệu không có nhiễu', 'Phải là dữ liệu số'], a: 1, ex: 'Học từ cặp (đầu vào → đáp án đúng), thế thôi. Không có nhãn thì là unsupervised (gom cụm); chỉ có thưởng/phạt tới muộn thì là reinforcement.' },
      { topicId: 'b10', q: 'Tập dữ liệu có 8 mẫu dương + 8 mẫu âm. Entropy của tập này là?', tex: 'H(S) = -\\sum_i p_i \\log_2 p_i', opts: ['0 bit', '0,5 bit', '1 bit', '8 bit'], a: 2, ex: 'p₊ = p₋ = 0,5 → H = −0,5·log₂0,5 − 0,5·log₂0,5 = 1 bit. Đây là mức hỗn loạn tối đa: bạn mù tịt hoàn toàn, đoán nhãn nào cũng như tung đồng xu.' },
      { topicId: 'b10', q: 'Tập chỉ toàn mẫu dương (100% một lớp) có entropy bằng bao nhiêu?', opts: ['1 bit', '0 bit', 'Không xác định', 'Bằng số mẫu'], a: 1, ex: 'Thuần khiết rồi thì còn gì mà bất định nữa: H = −1·log₂1 = 0. Đây cũng chính là lúc ID3 ngừng tách nhánh — hoặc khi nó hết thuộc tính để hỏi.' },
      { topicId: 'b10', q: 'ID3 chọn thuộc tính để tách node theo tiêu chí nào?', tex: 'Gain(S,A) = H(S) - \\sum_v \\tfrac{|S_v|}{|S|} H(S_v)', opts: ['Thuộc tính có nhiều giá trị nhất', 'Information gain lớn nhất — giảm entropy trung bình nhiều nhất', 'Thuộc tính xuất hiện đầu tiên trong bảng', 'Ngẫu nhiên có trọng số'], a: 1, ex: 'Gain = entropy cha − trung bình có trọng số entropy các con. Dịch sang tiếng người: chọn câu hỏi nào mà hỏi xong biết được nhiều nhất — đúng chiến thuật chơi trò đoán đồ vật.' },
      { topicId: 'b10', q: 'Cây quyết định đạt 100% trên tập train nhưng chỉ 60% trên tập test. Hiện tượng này gọi là gì và chữa bằng cách nào?', opts: ['Underfitting — tăng độ sâu cây', 'Overfitting — giới hạn độ sâu / cắt tỉa (pruning), như thí nghiệm max_depth trong Lab 3', 'Data leakage — đổi thuật toán', 'Bình thường, không cần chữa'], a: 1, ex: 'Cây học thuộc lòng luôn cả nhiễu trong tập train — thuộc bài chứ không hiểu bài. Lab 3 cho bạn thấy tận mắt: quét max_depth trên tập Breast Cancer, sâu quá một mức là test accuracy tụt.' },
      { topicId: 'b10', q: 'Naïve Bayes «ngây thơ» ở giả định nào?', opts: ['Mọi lớp có xác suất tiên nghiệm bằng nhau', 'Các thuộc tính độc lập với nhau KHI BIẾT lớp', 'Dữ liệu không có nhiễu', 'Chỉ có 2 lớp'], a: 1, ex: 'P(x₁,…,xₙ | C) = Π P(xᵢ | C). Giả định này gần như chẳng bao giờ đúng ngoài đời, vậy mà mô hình vẫn phân loại tốt đến bất ngờ — lọc spam là ví dụ kinh điển.' },
      { topicId: 'b11', q: 'Perceptron: w = [2, −1], x = [1, 3], bias = 0, hàm bước (ngưỡng 0). Đầu ra là?', tex: 'y = step(\\mathbf{w}\\cdot\\mathbf{x} + b)', opts: ['1 (vì 2·1 + (−1)·3 = −1 > −2)', '0 (vì w·x = 2 − 3 = −1 < 0)', '−1', 'Không tính được khi bias = 0'], a: 1, ex: 'Tích vô hướng: 2·1 + (−1)·3 = −1. Âm → dưới ngưỡng → output 0. Cả cái nơ-ron nghe kêu vậy thôi chứ chỉ làm đúng ba việc: nhân, cộng, so ngưỡng.' },
      { topicId: 'b11', q: 'Perceptron một tầng KHÔNG học được hàm nào sau đây?', opts: ['AND', 'OR', 'XOR', 'NOT'], a: 2, ex: 'Perceptron chỉ vẽ được đúng MỘT đường thẳng để chia (linear separability), mà XOR thì cần hai. Phải có tầng ẩn (MLP) mới xong. Vâng — chỉ vì cái hàm XOR bé tí này mà cả ngành lạnh đi suốt thập niên 1970.' },
      { topicId: 'b11', q: 'MLP vượt qua giới hạn của perceptron nhờ điều gì?', opts: ['Tăng learning rate', 'Tầng ẩn (hidden layers) + hàm kích hoạt PHI TUYẾN', 'Nhiều bias hơn', 'Dữ liệu được chuẩn hóa'], a: 1, ex: 'Tầng ẩn lo phần tổ hợp đặc trưng, còn phi tuyến (sigmoid, ReLU) mới là thứ cho phép uốn cong đường biên. Bỏ phi tuyến đi thì bạn chồng 100 tầng cũng chỉ ra đúng một phép tuyến tính — nhớ kỹ chỗ này.' },
      { topicId: 'b11', q: 'Backpropagation cập nhật trọng số dựa trên gì?', tex: 'w \\leftarrow w - \\eta\\,\\dfrac{\\partial E}{\\partial w}', opts: ['Gradient của hàm lỗi, lan ngược từ output về input bằng quy tắc chuỗi (chain rule)', 'Khoảng cách Manhattan giữa các tầng', 'Số lần nơ-ron được kích hoạt', 'Thứ tự ngẫu nhiên của mẫu'], a: 0, ex: 'Đạo hàm chỉ đang trả lời đúng một câu: «xoay cái núm này một tí thì lỗi đổi bao nhiêu?». Chain rule cho phép hỏi câu đó xuyên qua nhiều tầng. Còn gradient descent thì đơn giản: muốn xuống thấp thì bước ngược chiều dốc.' },
    ],
  },
];
