import { useState } from 'react';
import { DataLesson, Lab, DataTable, TraceLoop, CodeBlock } from '../shared/DataLesson';
import { windowTrace, recoveryModel, queueTrace } from './stream-engine';
import { SQL, JAVA, TABLE } from './lesson10.code';
import { T } from './lesson10.text';
function WindowLab() {
  const [bound,setBound]=useState(5), [lateness,setLateness]=useState(15), [side,setSide]=useState(true);
  const rows=windowTrace(bound,lateness,side);
  const actions: Record<string,string>=T.labs.actions, states:Record<string,string>=T.labs.states;
  return <Lab title={T.labs.windowTitle} help={T.labs.windowHelp} demo={T.demo}><div className="def-data-controls"><label>{T.labs.bound}<select value={bound} onChange={e=>setBound(Number(e.target.value))}>{[0,5,10].map(n=><option key={n}>{n}</option>)}</select></label><label>{T.labs.lateness}<select value={lateness} onChange={e=>setLateness(Number(e.target.value))}>{[0,15,30].map(n=><option key={n}>{n}</option>)}</select></label><label>{T.labs.policy}<select value={side?0:1} onChange={e=>setSide(e.target.value==='0')}>{T.labs.policies.map((s,i)=><option value={i} key={s}>{s}</option>)}</select></label></div><DataTable label={T.labs.windowTitle} headers={T.labs.headers} rows={rows.map(r=>[`${r.id} · ${r.event}/${r.arrival}`,`${Number.isFinite(r.before)?r.before:'−∞'} → ${r.watermark}`,actions[r.action],r.count,states[r.state]])}/><TraceLoop title={T.labs.windowTitle} steps={rows.map(r=>[`${r.id} · W=${r.watermark}`,`${actions[r.action]} · ${states[r.state]} · count=${r.count}`])} note={T.loopNote}/></Lab>;
}
function RecoveryLab() {
  const [complete,setComplete]=useState(true),[safe,setSafe]=useState(true);const r=recoveryModel(safe,complete);
  return <Lab title={T.labs.recoveryTitle} help={T.labs.recoveryHelp} demo={T.demo}><div className="def-data-controls"><label>{T.labs.checkpoint}<select value={complete?0:1} onChange={e=>setComplete(e.target.value==='0')}>{T.labs.checkpoints.map((s,i)=><option key={s} value={i}>{s}</option>)}</select></label><label>{T.labs.sink}<select value={safe?0:1} onChange={e=>setSafe(e.target.value==='0')}>{T.labs.sinks.map((s,i)=><option key={s} value={i}>{s}</option>)}</select></label></div><div className="def-data-metrics" aria-live="polite">{[[T.labs.savedOffset,r.savedOffset],[T.labs.savedState,r.savedState],[T.labs.replayed,r.replayed],[T.labs.finalState,r.state],[T.labs.external,r.externalTotal],[T.labs.effects,r.effects]].map(([l,v])=><div key={l}><span>{l}</span><strong>{v}</strong></div>)}</div><TraceLoop title={T.labs.recoveryTitle} steps={T.labs.recoverySteps} note={T.loopNote}/></Lab>;
}
function QueueLab(){const[rate,setRate]=useState(3);return <Lab title={T.labs.queueTitle} help={T.labs.queueHelp} demo={T.demo}><div className="def-data-controls"><label>{T.labs.sinkRate}<select value={rate} onChange={e=>setRate(Number(e.target.value))}>{[3,6,8,10].map(n=><option key={n}>{n}</option>)}</select></label></div><DataTable label={T.labs.queueTitle} headers={T.labs.queueHeaders} rows={queueTrace(rate).map(r=>[r.tick,r.accepted,r.output,r.queue,r.waiting])}/></Lab>;}
export default function Lesson10(){return <DataLesson text={T} id="b10" artwork={<><div className="def-data-brand"><img src={`${import.meta.env.BASE_URL}frameworks/flink.svg`} alt=""/><h2>Apache Flink</h2></div><div className="def-data-flow"><div>00:58 − 5s<span>W = 00:53</span></div><div>01:05 − 5s<span>W = 01:00</span></div><div>[00:00, 01:00)<span>count: 3 → 4</span></div></div></>} extra={n=><>{n===4&&<WindowLab/>}{n===5&&<><h3>{T.labs.codeTitle}</h3><p className="def-data-callout">{T.labs.codeNote}</p><CodeBlock value={SQL} language="Flink SQL 1.20"/><h3>{T.labs.apiTitle}</h3><p className="def-data-callout">{T.labs.apiNote}</p><CodeBlock value={JAVA} language="Java / DataStream"/><CodeBlock value={TABLE} language="Python / Table API"/></>}{n===7&&<RecoveryLab/>}{n===9&&<QueueLab/>}</>}/>;}
