/*
 * Chữ tiếng Việt của bài b5 — Tìm kiếm có thông tin. NGUỒN SỰ THẬT.
 *
 * Cắt ra từ bundle Buổi 3 cũ khi buổi đó tách thành Buổi 3 · 4 · 5. Chữ dùng chung cho
 * Manim Lab và Code Lab nằm ở `features/search-lab/lab.text.vi.ts`, không lặp ở đây.
 * Bản EN khai `satisfies typeof VI` nên thiếu hay thừa một khóa là lỗi tsc.
 */
export const VI = {
  hero: {
    labCta: "▶ Chạy từng bước trong Lab",
    navMath: "TOÁN NỀN",
    nav01: "01 Heuristic",
    nav02: "02 Leo đồi",
    nav03: "03 Tổng kết",
    navLab: "LAB",
    navCode: "04 Code",
    navQuiz: "05 Quiz",
    navHw: "06 Bài tập",
    cover: "Bìa",
    badge: "BUỔI 5",
    navTitle: "Tìm kiếm có thông tin",
    titleA: "Tìm kiếm",
    titleB: "khi đã có",
    titleC: "manh mối",
    lead: "🎯 Buổi trước máy mò trong bóng tối. Giờ mình đưa cho nó một con số: <em>từ đây tới đích ước chừng còn bao xa</em>. Chỉ một con số thôi, mà trên bài 8-puzzle độ sâu 12 nó kéo số nút phải mở từ <strong class='hl-red'>3.644.035</strong> xuống <strong class='hl-green'>73</strong>. Buổi này mình học cách con số đó hoạt động, và điều kiện nào để nó không nói dối.",
    chipG: "g — chi phí đã đi",
    chipH: "h — ước lượng còn lại",
    chipSections: "6 mục học",
    chipHours: "≈ 2,5 giờ",
  },
  ch5: {
    s1: "Tìm kiếm có thông tin",
    s2: "Nãy giờ thuật toán của mình mò trong bóng tối. Giờ tôi cho nó một cái la bàn 🎯 — đúng một con số cho <em>mỗi nút</em>: <strong class='hl-yellow'>h(n), chi phí ước lượng từ n về tới đích</strong>. Con số này không có trong đề bài, nó đến từ hiểu biết <em>bên ngoài</em> về bài toán. Trên bản đồ thì nó là khoảng cách đường chim bay (SLD). Chỉ có đúng một quy ước phải nhớ: h(đích) = 0.",
    s3: "h(Făgăraș) = 176",
    s4: "dừng khi đích SINH RA",
    s5: "Có la bàn rồi thì cứ nhắm hướng đích mà chạy thôi, đúng không? GBFS nghĩ y như vậy: luôn mở nút <strong class='hl'>trông gần đích nhất</strong>. Và nó nhanh thật — Arad → Sibiu → Făgăraș → București, mở đúng 3 nút. Có điều đường đó dài 450 km, còn đường tối ưu vòng qua Râmnicu–Pitești chỉ <strong class='hl-green'>418 km</strong>. Sai ở đâu? GBFS chỉ nhìn tương lai (h) mà quên sạch quá khứ (g), nên nó cắm đầu vào lối <em>trông</em> thì gần mà <em>đi</em> thì xa. Tệ hơn nữa, bản tree-search có thể lắc qua lắc lại vô hạn giữa hai thành phố (Iași ↔ Neamț) mà không biết ngượng.",
    s6: "ĐẦY ĐỦ",
    s7: "✗ tree · ✓ graph hữu hạn",
    s8: "TỐI ƯU",
    s9: "THỜI GIAN",
    s10: "BỘ NHỚ",
    s11: "O(b<sup>m</sup>) — h tốt cắt mạnh",
    s12: "Cân bằng quá khứ và tương lai",
    s13: "dừng khi đích LẤY RA",
    s14: "UCS nhớ quá khứ, GBFS đoán tương lai, mỗi đứa thiếu một nửa. A* làm cái việc hiển nhiên là cộng hai nửa lại:<br/><br/><span style='font-family:var(--font-serif);font-style:italic;font-size:1.35em'><span class='hl-text'>f(n)</span> = <span class='hl-cyan'>g(n)</span> + <span class='hl-yellow'>h(n)</span></span> — chi phí ước lượng của nghiệm rẻ nhất đi QUA n.<br/><br/>Cài đặt thì gần như copy UCS: cùng hàng đợi ưu tiên, cùng decrease-key, cùng luật “chỉ dừng khi đích được lấy ra”. Bạn chỉ đổi khóa sắp xếp từ g sang f, thế thôi. Nhưng A* giỏi hay dở thì phụ thuộc hoàn toàn vào h, và h phải thỏa điều kiện:",
    s15: "ĐẦY ĐỦ",
    s16: "TỐI ƯU",
    s17: "THỜI GIAN",
    s18: "mũ theo sai số của h",
    s19: "BỘ NHỚ",
    s20: "O(b<sup>d</sup>) — điểm chết",
    s21: "ADMISSIBLE — không ước lượng lố",
    s22: "h(n) ≤ h*(n) — chi phí thật",
    s23: "Heuristic biết điều: không bao giờ nói quá. Nó được phép lạc quan, cấm bi quan. SLD admissible vì đường chim bay thì không đường nào ngắn hơn được. Chỉ cần MỘT node nói phóng lên là mất sạch bảo đảm. → A* <strong class='hl-mid'>tree-search tối ưu</strong>.",
    s24: "CONSISTENT — bất đẳng thức tam giác",
    s25: "Điều kiện chặt hơn một bậc: không có “lối tắt” nào rẻ hơn việc đi một bước rồi ước lượng tiếp. Hệ quả rất đẹp — f không bao giờ giảm dọc một đường đi, nên nút vừa được lấy ra lần đầu là đã tối ưu, khỏi cần xét lại. → A* <strong class='hl-mid'>graph-search tối ưu</strong>. Và consistent ⇒ admissible, chứ không ngược lại.",
    s26: "A* mở những nút nào — đường viền f",
    s27: "h càng sắc, vùng loang càng bó về phía đích",
    s28: "viền tròn quanh S, loang đều mọi hướng",
    s29: "A* — h sắc",
    s30: "viền kéo dài về G, bó quanh đường tối ưu",
    s31: "Vì f không giảm dọc đường đi, A* mở nút theo thứ tự f tăng dần — nó lấp lần lượt từng <strong class='hl-yellow'>đường viền f</strong> một, y như nước dâng lên từng vạch. Gọi C* là chi phí của nghiệm tối ưu, bạn suy ra được ngay hai điều mà tôi thấy rất đáng nhớ: A* <strong class='hl'>mở mọi nút có f(n) &lt; C*</strong>, và <strong class='hl'>không bao giờ mở nút có f(n) &gt; C*</strong> — đám đó bị cắt sạch mà nghiệm vẫn tối ưu. Riêng mấy nút nằm đúng trên viền f(n) = C* thì hên xui, tùy cách phá đồng hạng. Đây chính là công cụ để làm <a href='#hw'>câu 2 của bài tập</a>: muốn biết một đường có thể được trả về hay không, bạn đi tính f chứ đừng đoán.<br/><br/>Quay lại bản đồ Romania cho dễ hình dung. Vẽ các viền <strong class='hl-mid'>380 · 400 · 420</strong> quanh Arad thì viền 420 vừa vặn trùm tới được București — tất nhiên rồi, vì nghiệm tối ưu là <strong class='hl-green'>418</strong>. Mọi thành phố nằm ngoài cái viền ấy, A* không thèm đụng tới một cái nào.<br/><br/>Và đó cũng là chỗ h biến thành tốc độ. h = 0 thì f = g, viền là những vòng tròn đồng tâm quanh S — A* thoái hóa đúng thành UCS, loang đều ra mọi phía kể cả hướng ngược với đích. h càng sát chi phí thật, viền càng bị kéo dài về phía G và bó sát đường tối ưu, số nút lọt vào trong viền càng ít. Mở Lab chạy UCS rồi A* trên preset Romania, đếm số nút xám của hai bên — chênh lệch đó chính là cái hình trên.",
    s32: "Một danh hiệu nữa cho A*: nó <strong style='color:var(--text-2)'>optimally efficient</strong> — với cùng một h consistent, không thuật toán tối ưu nào mở được ít nút hơn nó. Nghe hoàn hảo, nhưng gót chân Achilles vẫn là RAM. Khi máy không chứa nổi thì tìm tới IDA*, RBFS, SMA* — ngoài phạm vi buổi này, để dành.",
    s33: "HEURISTIC TRỘI HƠN — VÀ ĐO ĐỘ SẮC BẰNG b*",
    s34: "Quy tắc chọn heuristic: nếu h₂(n) ≥ h₁(n) tại mọi n (cả hai vẫn admissible) thì h₂ <em>trội</em> h₁, và A*(h₂) không bao giờ phải mở nhiều nút hơn. Nói cách khác: ước lượng càng sát chi phí thật càng tốt, miễn đừng vượt. Thử với 8-puzzle — h₁ = số ô nằm sai chỗ, h₂ = tổng khoảng cách Manhattan.",
    s35: "Nhưng “mở ít nút hơn” thì ít hơn <em>bao nhiêu</em>? Đếm nút trần trụi không so được giữa hai bài khác độ sâu — 227 nút ở d = 12 với 39.135 nút ở d = 24, cái nào giỏi hơn? Nên người ta quy hết về một con số duy nhất: <strong class='hl-yellow'>hệ số phân nhánh hiệu dụng b*</strong>. A* mở N nút rồi tìm ra nghiệm ở độ sâu d; giờ hỏi ngược: một cây <em>đều</em> sâu d mà chứa đúng N + 1 nút thì mỗi nút phải đẻ mấy con?",
    s36: "Ví dụ A* tìm ra nghiệm ở độ sâu 5 mà chỉ tốn 52 nút → <strong class='hl'>b* = 1,92</strong>: nó len tới đích gọn như thể mỗi nút chỉ có chưa tới 2 nhánh, dù cây thật thì rậm hơn nhiều. b* đổi theo từng đề, nhưng với bài đủ khó thì khá ổn định, nên dùng nó chấm điểm heuristic được. Thước đo gói lại đúng một câu: <strong class='hl-green'>b* càng gần 1 càng ngon</strong> — b* = 1 nghĩa là đi một mạch tới nghiệm, không mở thừa nút nào. Heuristic nào ép được b* xuống sát 1 là heuristic cho bạn giải nổi bài lớn với cái giá chịu được.",
    s37: "SỐ NÚT SINH RA",
    s38: "Trung bình trên 100 thể hiện 8-puzzle cho mỗi độ sâu d. Ô “–”: từ d = 14 trở lên bảng gốc bỏ trống dòng IDS, không có số đo — và tôi không bịa cho bạn một con số. Cứ nhìn 3,6 triệu ở d = 12 rồi tự nhân tiếp là đủ sợ.",
    s39: "CHẾ HEURISTIC Ở ĐÂU RA?",
    s40: "<strong class='hl-yellow'>1 · Nới lỏng bài toán.</strong> Đây là mẹo tôi thích nhất: bỏ bớt luật đi. 8-puzzle cho ô bay tự do tới đích → ra h₁; cho ô trượt đè lên nhau → ra h₂. Vì bài dễ hơn thì nghiệm không thể đắt hơn bài gốc, mấy h kiểu này <em>tự động</em> admissible và consistent. Khỏi chứng minh.",
    s41: "<strong class='hl-yellow'>2 · Lấy max.</strong> Có nhiều h admissible mà không biết chọn cái nào? Lấy hết: h = max(h₁, …, hₖ). Max của các heuristic biết điều thì vẫn biết điều.",
    s42: "<strong class='hl-yellow'>3 · Pattern database.</strong> Giải trước vài bài con (ví dụ chỉ 4 ô góc), ghi chi phí chính xác vào bảng, lúc chạy thì tra. Đổi bộ nhớ lấy độ sắc của h.",
    s43: "<strong class='hl-yellow'>4 · Học từ kinh nghiệm.</strong> Giải nhiều lần, ghi lại, rồi hồi quy h từ các đặc trưng của trạng thái. Vâng — dùng học máy để chế heuristic cho tìm kiếm. Hẹn bạn ở Buổi 12.",
    s44: "✓ b hữu hạn, bước ≥ ε",
  },
  ch6: {
    s1: "Leo đồi — kẻ ngoại đạo trong Lab",
    s2: "⛰️ Lab 1 bắt cài thêm một đứa chẳng giống ai trong đám trên: leo đồi. Không hàng đợi, không quay lui, không nhớ gì hết — nó giữ đúng <strong class='hl'>một</strong> nút hiện tại rồi bước sang láng giềng nào có h nhỏ hơn. Bản <strong class='hl'>first-choice</strong> còn lười hơn: thấy láng giềng tốt hơn đầu tiên là leo luôn, khỏi so tiếp. Bộ nhớ O(1), nhanh như chớp — và mù tịt trước cực trị địa phương.",
    s3: "Vì sao leo đồi kẹt — phong cảnh trạng thái",
    s4: "quả bóng chỉ biết leo lên, không bao giờ chịu xuống",
    s5: "BA KIỂU CHẾT",
    s6: "cực trị địa phương",
    s7: "cao nguyên phẳng (plateau)",
    s8: "sống núi (ridge)",
    s9: "— muốn thấy nó chết tận mắt thì chạy <strong class='hl-mid'>HC trên preset Romania</strong> trong <a href='#lab'>Lab</a>: nó hí hửng leo Arad → Timișoara vì h giảm từ 366 xuống 329, rồi đứng đó, hết đường lên. Output: -1.",
    s10: "Đừng vội chê nó — Buổi 6 (Local Search) dành nguyên buổi để chữa đúng căn bệnh này: random restart, simulated annealing, local beam, thuật toán di truyền. Leo đồi là điểm xuất phát của cả một họ thuật toán rất mạnh.",
  },
  ch7: {
    s1: "Bảy thuật toán trên một trang giấy",
    s2: "THUẬT TOÁN",
    s3: "ĐẦY ĐỦ",
    s4: "TỐI ƯU",
    s5: "THỜI GIAN",
    s6: "BỘ NHỚ",
    s7: "DÙNG KHI",
    s8: "nghiệm nông, bước cùng giá, RAM dư",
    s9: "RAM chật, không gian sâu hữu hạn",
    s10: "như thời gian",
    s11: "chi phí bước khác nhau, cần tối ưu",
    s12: "DLS lặp, ℓ↑",
    s13: "mặc định khi d chưa biết, KG lớn",
    s14: "cần nhanh, chấp nhận lệch tối ưu",
    s15: "mũ theo sai số h",
    s16: "cần tối ưu và có h tốt",
    s17: "không có",
    s18: "tùy địa hình",
    s19: "KG khổng lồ, cần nghiệm “đủ tốt”",
    s20: "¹ b hữu hạn (UCS và A*: thêm chi phí bước ≥ ε > 0) · ² khi mọi bước cùng chi phí · ³ graph-search trên không gian hữu hạn · ⁴ h admissible (tree) / consistent (graph)",
  },
  quiz: {
    s1: "Quiz — đo xem bạn <em class='hl-cyan'>thật sự</em> hiểu tới đâu",
    s2: "sáu câu · vì sao tham lam hụt, admissible vs consistent, điều kiện của A*",
    s3: "Buổi này có hai định nghĩa rất dễ đọc lướt qua — admissible và consistent — và gần như mọi lỗi tôi từng mắc với A* đều bắt nguồn từ việc lẫn hai cái đó. Sáu câu dưới đây đi thẳng vào chỗ ấy. Sai câu nào thì đọc giải thích ngay, đừng để dành tới lúc làm bài tập.",
  },
  hw: {
    s1: "Bài tập về nhà — Buổi 5",
    s2: "ba câu · trace tay nhóm có thông tin, đường nào trả về được, mê cung",
    s3: "QUESTION 1 — TRACE TAY GBFS VÀ A*",
    s4: "Vẫn đồ thị S → G của buổi trước, giờ thêm h ghi dưới tên đỉnh. Với GBFS · A*: liệt kê <em>thứ tự expand</em>, <em>đường đi tìm được</em>, <em>frontier cuối cùng</em>. Đồng hạng → mở theo alphabet. <strong class='hl'>(c)</strong> h có admissible không? <strong class='hl'>(d)</strong> có consistent không? <strong class='hl'>(e)</strong> So với BFS/UCS ở buổi 4, A* mở ít hơn bao nhiêu nút?",
    s5: "<a href='#lab'>Luyện đúng kỹ năng này trong Manim Lab</a>",
    s6: "QUESTION 2 — ĐƯỜNG NÀO CÓ THỂ ĐƯỢC TRẢ VỀ?",
    s7: "A là start, G là goal; h₁ consistent còn h₂ thì không. <strong class='hl'>(1)</strong> Với DFS · BFS · UCS · A*(h₁) · A*(h₂), đánh dấu những đường <em>có thể</em> được trả về dưới một cách phá đồng hạng nào đó: A-B-D-G, A-C-D-G, A-B-C-D-F-G. <strong class='hl'>(2)</strong> Bảng h₃ đã cố định trừ h₃(B): tìm tập giá trị để h₃ admissible; để h₃ consistent; để A* expand đúng thứ tự A, C, B, D.",
    s8: "<a href='#ch1'>Ôn: mục 01 — admissible vs consistent</a>",
    s9: "QUESTION 3 — MÊ CUNG s → g, PHẦN CÓ THÔNG TIN",
    s10: "Vẫn mê cung của buổi 4. Liệt kê các ô explored với: <strong class='hl'>(a)</strong> GBFS dùng khoảng cách Manhattan (|Δx| + |Δy|); <strong class='hl'>(b)</strong> A* cùng heuristic đó. <strong class='hl'>(c)</strong> Manhattan trên lưới có đi xuyên tường được không — vậy nó còn admissible không?",
    s11: "<a href='#ch1'>Ôn: mục 01 — heuristic từ bài nới lỏng</a>",
    s12: "Chứng minh được một heuristic là admissible / consistent, và nói được cái nào mạnh hơn cái nào.",
    s13: "Giải thích được vì sao GBFS ra 450 km còn A* ra 418 km trên cùng một bản đồ.",
    s14: "Nói được A* cần điều kiện gì để ĐẦY ĐỦ, ngoài chuyện heuristic admissible.",
    s15: "Trace tay A* trên đồ thị 6 đỉnh của Lab rồi đối chiếu với Manim Lab.",
    s16: "Cài được GBFS và A* chạy trơn, và bắt được lỗi khi heuristic không admissible.",
    s17: "Tiếp theo: <strong class='hl'>Buổi 6 — Tìm kiếm cục bộ</strong>, nơi mình chữa bệnh kẹt của leo đồi bằng simulated annealing, local beam và thuật toán di truyền. Cũng là lúc bạn thấy đôi khi “đủ tốt” đáng giá hơn “tối ưu” 🙂",
    s18: "← Về Lộ trình",
  },
};
