import type { VI } from './lesson05.text.vi';

export const EN = {
  hero: {
    labCta: "▶ Step through in the Lab",
    navMath: "MATH PRIMER",
    nav01: "01 Heuristics",
    nav02: "02 Hill climbing",
    nav03: "03 Summary",
    navLab: "LAB",
    navCode: "04 Code",
    navQuiz: "05 Quiz",
    navHw: "06 Exercises",
    cover: "Cover",
    badge: "SESSION 5",
    navTitle: "Informed search",
    titleA: "Searching",
    titleB: "once you have",
    titleC: "a clue",
    lead: "🎯 Last session the machine groped in the dark. Now I hand it one number: <em>roughly how far is the goal from here</em>. One number — and on 8-puzzle at depth 12 it drops the nodes expanded from <strong class='hl-red'>3,644,035</strong> to <strong class='hl-green'>73</strong>. This session is about how that number works, and what has to be true for it not to lie.",
    chipG: "g — cost so far",
    chipH: "h — estimated cost remaining",
    chipSections: "6 sections",
    chipHours: "≈ 2.5 hours",
  },
  ch5: {
    s1: "Informed search",
    s2: "So far, the algorithms have been feeling their way through the dark. Now I’ll give them a compass 🎯: one number for <em>each node</em>, <strong class='hl-yellow'>h(n), the estimated cost from n to the goal</strong>. That number isn’t part of the problem definition; it comes from <em>outside</em> knowledge about the problem. On a map, it can be straight-line distance (SLD). Keep one convention in mind: h(goal) = 0.",
    s3: "h(Făgăraș) = 176",
    s4: "stop when goal is GENERATED",
    s5: "A compass in hand, just head toward the goal — that’s GBFS’s thinking. It always expands the node that <strong class='hl'>looks closest</strong>. And it is fast: Arad → Sibiu → Făgăraș → București, just 3 nodes expanded. But that route is 450 km, while the optimal route through Râmnicu–Pitești is only <strong class='hl-green'>418 km</strong>. GBFS sees only the future (h), forgetting the past (g), so it rushes down a route that <em>looks</em> close but takes a long way to <em>travel</em>. Worse, tree-search can bounce forever between two cities (Iași ↔ Neamț), perfectly unembarrassed.",
    s6: "COMPLETE",
    s7: "✗ tree · ✓ finite graph",
    s8: "OPTIMAL",
    s9: "TIME",
    s10: "MEMORY",
    s11: "O(b<sup>m</sup>) — good h cuts sharply",
    s12: "Balancing past and future",
    s13: "stop when goal is REMOVED",
    s14: "UCS remembers the past; GBFS guesses the future. Each is missing half the picture. A* adds the halves together:<br/><br/><span style='font-family:var(--font-serif);font-style:italic;font-size:1.35em'><span class='hl-text'>f(n)</span> = <span class='hl-cyan'>g(n)</span> + <span class='hl-yellow'>h(n)</span></span> — the estimated cost of the cheapest solution THROUGH n.<br/><br/>The implementation is almost a copy of UCS: the same priority queue, decrease-key, and “stop only when the goal is removed” rule. You just swap the sort key from g to f. That's it. But whether A* is any good rides entirely on h, and h has to meet a condition:",
    s15: "COMPLETE",
    s16: "OPTIMAL",
    s17: "TIME",
    s18: "exponential in the error of h",
    s19: "MEMORY",
    s20: "O(b<sup>d</sup>) — the weak spot",
    s21: "ADMISSIBLE — never overestimates",
    s22: "h(n) ≤ h*(n) — the true cost",
    s23: "A well-behaved heuristic never exaggerates. Optimism is allowed; pessimism isn’t. SLD is admissible because no route can be shorter than the straight line. Just ONE node overestimating removes the guarantee. → A* <strong class='hl-mid'>tree-search is optimal</strong>.",
    s24: "CONSISTENT — the triangle inequality",
    s25: "A stronger condition: the estimate at a node can’t exceed the cost of one step plus the estimate from the next node. The lovely consequence is that f never decreases along a path, so a node’s first removal already gives its optimal cost; no need to revisit it. → A* <strong class='hl-mid'>graph-search is optimal</strong>. Consistent ⇒ admissible, but not the reverse.",
    s26: "Which nodes A* expands — f-contours",
    s27: "a sharper h focuses the spread toward the goal",
    s28: "circles around S, spreading evenly in every direction",
    s29: "A* — sharp h",
    s30: "contours stretch toward G, hugging the optimal path",
    s31: "Because f never decreases along a path, A* expands nodes in increasing f order, filling one <strong class='hl-yellow'>f-contour</strong> after another like rising water. Call the optimal solution cost C*. Two consequences you can read straight off, and I think both are worth remembering: A* <strong class='hl'>expands every node with f(n) &lt; C*</strong> and <strong class='hl'>never expands a node with f(n) &gt; C*</strong>. Those nodes are cut away while the solution stays optimal. Nodes exactly on f(n) = C* depend on tie-breaking. This is your tool for <a href='#hw'>exercise 2</a>: to find whether a path could be returned, calculate f instead of guessing.<br/><br/>Back to Romania: draw contours at <strong class='hl-mid'>380 · 400 · 420</strong> around Arad, and the 420 contour just reaches București. Of course it does: the optimal solution costs <strong class='hl-green'>418</strong>. A* doesn’t touch any city beyond that contour.<br/><br/>This is where h becomes speed. With h = 0, f = g, so the contours are concentric circles around S: A* becomes UCS, spreading in every direction, including away from the goal. As h approaches the true cost, the contours stretch toward G and hug the optimal path, enclosing fewer nodes. Run UCS and A* on Romania in the Lab and count their gray nodes. That difference is what the picture shows.",
    s32: "Another title for A*: it’s <strong style='color:var(--text-2)'>optimally efficient</strong> — with the same consistent h, no optimal algorithm expands fewer nodes. Sounds perfect, but RAM remains its Achilles’ heel. When memory runs out, look toward IDA*, RBFS, and SMA*. Those are beyond this session.",
    s33: "HEURISTIC DOMINANCE — MEASURING SHARPNESS WITH b*",
    s34: "A rule for choosing a heuristic: if h₂(n) ≥ h₁(n) for every n, and both are admissible, h₂ <em>dominates</em> h₁, and A*(h₂) never needs to expand more nodes. Get as close to the true cost as you can without going over. Try the 8-puzzle: h₁ counts misplaced tiles; h₂ sums Manhattan distances.",
    s35: "But <em>how much</em> fewer? Raw node counts don’t compare problems of different depths: 227 nodes at d = 12 versus 39,135 at d = 24 — which is better? The comparison uses one number: the <strong class='hl-yellow'>effective branching factor b*</strong>. A* expands N nodes and finds a solution at depth d. Now ask: if a <em>uniform</em> tree of depth d held exactly N + 1 nodes, how many children would each node have?",
    s36: "For example, A* finds a depth-5 solution using just 52 nodes → <strong class='hl'>b* = 1.92</strong>. It slips toward the goal as if each node had fewer than 2 branches, even though the real tree is much bushier. b* varies between instances, but stays fairly stable on sufficiently difficult problems, making it useful for grading heuristics. The rule fits in a sentence: <strong class='hl-green'>the closer b* is to 1, the better</strong>. b* = 1 means going straight to the solution without expanding spare nodes. A heuristic that pushes b* close to 1 makes large problems affordable.",
    s37: "NODES GENERATED",
    s38: "Averages over 100 instances of the 8-puzzle at each depth d. “–” means the original table leaves IDS blank from d = 14 onward; there’s no measurement, and I won’t invent one for you. The 3.6 million at d = 12 is frightening enough to extrapolate from.",
    s39: "WHERE DO HEURISTICS COME FROM?",
    s40: "<strong class='hl-yellow'>1 · Relax the problem.</strong> My favorite trick: drop some rules. In the 8-puzzle, let tiles fly straight to their destinations → h₁; let tiles slide through each other → h₂. An easier problem can’t have a more expensive solution, so these heuristics are <em>automatically</em> admissible and consistent. No separate proof needed.",
    s41: "<strong class='hl-yellow'>2 · Take the max.</strong> Several admissible heuristics and no obvious winner? Use them all: h = max(h₁, …, hₖ). The maximum of well-behaved heuristics still behaves itself.",
    s42: "<strong class='hl-yellow'>3 · Pattern database.</strong> Solve subproblems beforehand — just the 4 corner tiles, for example — and store exact costs for lookup. Trade memory for a sharper h.",
    s43: "<strong class='hl-yellow'>4 · Learn from experience.</strong> Solve many instances, record the results, and fit h from state features using regression. Yes: machine learning can build heuristics for search. See you in Session 12.",
    s44: "✓ finite b, steps ≥ ε",
  },
  ch6: {
    s1: "Hill climbing — the Lab’s outsider",
    s2: "⛰️ Lab 1 includes an algorithm unlike the rest: hill climbing. No queue, no backtracking, no history — it holds exactly <strong class='hl'>one</strong> current node and moves to a neighbor with a smaller h. The <strong class='hl'>first-choice</strong> version is even lazier: take the first improvement without checking the rest. O(1) memory, lightning fast, and oblivious to local optima.",
    s3: "Why hill climbing gets stuck — the state-space landscape",
    s4: "the ball can climb, but never agrees to descend",
    s5: "THREE WAYS TO GET STUCK",
    s6: "local optimum",
    s7: "flat plateau",
    s8: "ridge",
    s9: "— watch it happen by running <strong class='hl-mid'>HC on Romania</strong> in the <a href='#lab'>Lab</a>: it happily climbs Arad → Timișoara as h drops from 366 to 329, then stands there with nowhere uphill to go. Output: -1.",
    s10: "Don’t dismiss it yet. Session 6 (Local Search) tackles exactly this problem with random restarts, simulated annealing, local beam search, and genetic algorithms. Hill climbing is the starting point of a powerful family.",
  },
  ch7: {
    s1: "Seven algorithms on one sheet",
    s2: "ALGORITHM",
    s3: "COMPLETE",
    s4: "OPTIMAL",
    s5: "TIME",
    s6: "MEMORY",
    s7: "USE WHEN",
    s8: "shallow solution, equal costs, plenty of RAM",
    s9: "tight RAM, deep finite space",
    s10: "same as time",
    s11: "unequal step costs, optimality required",
    s12: "repeated DLS, ℓ↑",
    s13: "default for unknown d and large spaces",
    s14: "speed matters more than optimality",
    s15: "exponential in h error",
    s16: "optimality required, good h available",
    s17: "none",
    s18: "depends on the landscape",
    s19: "huge space, a “good enough” solution will do",
    s20: "¹ finite b (UCS and A* also need step costs ≥ ε > 0) · ² equal step costs · ³ graph-search in a finite space · ⁴ admissible h (tree) / consistent h (graph)",
  },
  quiz: {
    s1: "Quiz — find out what you <em class='hl-cyan'>really</em> understand",
    s2: "six questions · why greedy falls short, admissible vs consistent, what A* needs",
    s3: "This session has two definitions that are very easy to skim — admissible and consistent — and nearly every mistake I've made with A* traces back to blurring them together. These six questions go straight there. Get one wrong and read the explanation immediately, rather than saving it for the exercises.",
  },
  hw: {
    s1: "Homework — Session 5",
    s2: "three questions · tracing the informed group, which paths can come back, a maze",
    s3: "QUESTION 1 — TRACE GBFS AND A* BY HAND",
    s4: "Same S → G graph as last session, now with h written under each vertex. For GBFS · A*: list the <em>expansion order</em>, the <em>path found</em>, and the <em>final frontier</em>. Break ties alphabetically. <strong class='hl'>(c)</strong> Is h admissible? <strong class='hl'>(d)</strong> Is it consistent? <strong class='hl'>(e)</strong> Compared with BFS/UCS in session 4, how many fewer nodes does A* expand?",
    s5: "<a href='#lab'>Practise exactly this in the Manim Lab</a>",
    s6: "QUESTION 2 — WHICH PATHS CAN COME BACK?",
    s7: "A is the start, G the goal; h₁ is consistent and h₂ is not. <strong class='hl'>(1)</strong> For DFS · BFS · UCS · A*(h₁) · A*(h₂), mark the paths that <em>could</em> be returned under some tie-breaking rule: A-B-D-G, A-C-D-G, A-B-C-D-F-G. <strong class='hl'>(2)</strong> The h₃ table is fixed except for h₃(B): find the values that make h₃ admissible; that make it consistent; that make A* expand exactly in the order A, C, B, D.",
    s8: "<a href='#ch1'>Review: section 01 — admissible vs consistent</a>",
    s9: "QUESTION 3 — MAZE s → g, THE INFORMED HALF",
    s10: "Same maze as session 4. List the explored cells for: <strong class='hl'>(a)</strong> GBFS with Manhattan distance (|Δx| + |Δy|); <strong class='hl'>(b)</strong> A* with the same heuristic. <strong class='hl'>(c)</strong> Does Manhattan distance on a grid walk straight through walls — and if so, is it still admissible?",
    s11: "<a href='#ch1'>Review: section 01 — heuristics from relaxed problems</a>",
    s12: "I can prove a heuristic admissible or consistent, and say which of the two is the stronger claim.",
    s13: "I can explain why GBFS returns 450 km and A* returns 418 km on the same map.",
    s14: "I can say what A* needs to be COMPLETE, beyond the heuristic being admissible.",
    s15: "I can trace A* by hand on the Lab's 6-node graph and check myself against the Manim Lab.",
    s16: "I can implement GBFS and A*, and spot the failure when a heuristic isn't admissible.",
    s17: "Next up: <strong class='hl'>Session 6 — Local Search</strong>, where you'll cure hill climbing's habit of getting stuck with simulated annealing, local beam and genetic algorithms. It's also where you'll see that “good enough” sometimes beats “optimal” 🙂",
    s18: "← Back to the roadmap",
  },
} satisfies typeof VI;
