
/*
 * Chữ tiếng Việt của bài b1 — NGUỒN SỰ THẬT.
 *
 * Rút bằng .claude/scripts/extract_lesson.py, gom theo mục và giữ đúng thứ tự đọc.
 * Bản EN (`*.text.en.ts`) khai `satisfies typeof VI` nên thiếu hay thừa một khóa là lỗi tsc.
 */
export const VI = {
  // Nhãn mục lục + nhãn từng mục ở chế độ trình chiếu, khóa theo anchor id. Cấu trúc
  // (href, hot) ở lại trong trang; chỉ CHỮ nằm đây, nên kiểm anchor↔id của
  // check_lesson.py không đổi gì.
  nav: {
    hero: "Bìa",
    toan: "TOÁN NỀN",
    ch1: "01 AI là gì",
    ch2: "02 Bốn ô",
    ch3: "03 Turing",
    ch4: "04 Suy nghĩ",
    ch5: "05 Duy lý",
    ch6: "06 Nền tảng",
    ch7: "07 Lịch sử",
    ch8: "08 Ứng dụng",
    ch9: "09 Tổng kết",
    quiz: "10 Quiz",
    hw: "11 Qua buổi 2",
  },
  hero: {
    s12: "BUỔI 1",
    s13: "Nhập môn AI",
    s14: "CSC14003 · BUỔI 1 · ZERO → HERO",
    s15: "Trí tuệ",
    s16: "nhân tạo",
    s17: "là gì?",
    s18: "🤔 Nghe hàn lâm dễ sợ nhỉ? Tôi cũng tưởng thế. Hóa ra cả môn này chỉ là bốn phe cãi nhau xem “thông minh” nghĩa là gì — và cãi suốt 70 năm chưa xong. Buổi 1 mình đi từ số 0: hết buổi, bạn đưa tôi hệ thống nào cũng được, bạn xếp được nó vào đúng ô, đọc trôi 80 năm lịch sử ngành, và làm xong bài tập.",
    s19: "𝓟 — chuỗi tri giác",
    s20: "𝓐 — hành động",
    s21: "10 mục học",
    s22: "Quiz phân loại 8 câu",
    s23: "Bài tập — PEAS",
    s24: "≈ 2 giờ",
    s25: "NHƯ NGƯỜI",
    s26: "DUY LÝ",
    s27: "SUY NGHĨ",
    s28: "Suy nghĩ như người",
    s29: "Suy nghĩ duy lý",
    s30: "HÀNH ĐỘNG",
    s31: "Hành động như người",
    s32: "Hành động duy lý",
  },
  ch1: {
    s1: "Không chỉ hiểu, mà còn xây",
    s2: "Năm 1988, lúc Richard Feynman mất, trên tấm bảng trong phòng làm việc của ông còn một dòng chưa kịp xóa: <em>cái gì tôi không tạo ra được thì tôi chưa hiểu nó</em>.<br/><br/>Tâm lý học và thần kinh học đã mổ xẻ trí thông minh hàng trăm năm với mục tiêu <em>hiểu</em> nó. AI nhận lấy đúng vế còn lại của câu đó: hiểu chưa đủ, phải <strong class='hl'>xây thử ra một cái xem sao</strong>. Nghe na ná nhau, nhưng đúng một chữ ấy là lý do AI ngồi ở khoa máy tính chứ không ngồi ở khoa tâm lý.",
    s3: "INTELLIGENCE — TRÍ THÔNG MINH",
    s4: "Bao gồm năng lực <em>logic, hiểu, học, lập luận, sáng tạo, giải quyết vấn đề</em>, v.v.",
    s5: "Không chỉ cố <em>hiểu</em>, mà còn cố <strong class='hl'>xây dựng các thực thể thông minh</strong>.",
    s6: "MỘT NGÀNH RẤT MỚI",
    s7: "AI trẻ hơn bạn tưởng nhiều. Người ta bắt tay làm nghiêm túc ngay sau Thế chiến II, còn cái tên <strong class='hl'>“Artificial Intelligence”</strong> thì mãi tới hội nghị ở Đại học Dartmouth năm <strong class='hl-yellow'>1956</strong> mới có — nghĩa là ngành này còn chưa tới 70 tuổi. Mấy người ngồi trong phòng hôm đó:",
    s8: "MÔ PHỎNG NGƯỜI Ở BỐN MẶT",
    s9: "<strong class='hl-cyan'>Suy nghĩ</strong> — học, lập kế hoạch, tinh chỉnh tri thức.",
    s10: "<strong class='hl-cyan'>Tri giác</strong> — thấy, nghe, cảm nhận.",
    s11: "<strong class='hl-cyan'>Thao tác</strong> — cầm nắm và di chuyển vật thể.",
    s12: "<strong class='hl-cyan'>Giao tiếp</strong> — bằng ngôn ngữ tự nhiên.",
    s13: "Nhớ bốn mặt này giùm tôi: về sau chúng lớn lên thành bốn nhóm bài toán riêng — học máy, thị giác/tiếng nói, robot, xử lý ngôn ngữ.",
  },
  ch2: {
    s1: "Bốn định nghĩa, hai trục",
    s2: "“AI là gì” không có một câu trả lời — nó có <strong class='hl'>bốn</strong>, và bốn câu ấy chỉ khác nhau ở hai chỗ. Một: bạn mở nắp máy ra xem nó <em>nghĩ</em>, hay đứng ngoài xem nó <em>làm</em>? Hai: lấy <em>con người</em> làm thước, hay lấy <em>tính duy lý</em> làm thước?<br/><br/>Hai câu hỏi, hai trục, bốn ô. Nắm được bảng này rồi bạn sẽ hiểu vì sao hai bài báo AI cãi nhau chan chát mà vẫn đúng cả hai — chúng đang đứng ở hai ô khác nhau.",
    s3: "Bốn ô trên hai trục",
    s4: "cột: chuẩn là người hay là tính duy lý · dòng: đo suy nghĩ hay đo hành vi",
    s5: "CÁCH ĐỌC HAI TRỤC",
    s6: "dòng trên — thought processes and reasoning",
    s7: "dòng dưới — behavior",
    s8: "cột trái — chuẩn: con người",
    s9: "cột phải — chuẩn: tính duy lý",
    s10: "→ bốn mục tới tôi dẫn bạn đi từng ô một, cuối cùng thả bạn vào ô tương tác để tự xếp.",
  },
  ch3: {
    s1: "Hành động như người — phép thử Turing",
    s2: "Tháng 10 năm 1950, trên tạp chí <em>Mind</em>, Alan Turing mở bài bằng đúng câu hỏi ai cũng muốn hỏi: máy có nghĩ được không? Rồi vài dòng sau, ông gạt nó đi — câu đó vô nghĩa tới mức không đáng đem ra bàn.<br/><br/>Thứ ông đặt vào chỗ trống là một câu <em>đo được</em>: bạn ngồi gõ chữ hỏi vài câu; nếu không nói nổi bên kia là người hay máy, thì máy <strong class='hl'>vượt phép thử</strong>. Toàn bộ tiêu chí nằm ở hành vi — chẳng ai mở nắp máy ra soi xem bên trong nó nghĩ kiểu gì.",
    s3: "Bố cục phép thử",
    s4: "sơ đồ — chỉ trao đổi bằng chữ viết, người hỏi không thấy ai ở bên kia",
    s5: "HAI BIẾN THỂ",
    s6: "<strong class='hl-yellow'>Reverse Turing Test</strong> — đảo vai: máy ra đề, người phải chứng minh mình là người. Bạn thi cái này gần như mỗi ngày mà không để ý, tên nó là <span class='code-inline'>CAPTCHA</span> 🤖",
    s7: "<strong class='hl-yellow'>Total Turing Test</strong> — bản khó: bắt máy thi thêm phần nhìn (thị giác máy tính) và phần cầm nắm đồ vật (robot), không cho trốn sau màn hình chữ nữa.",
    s8: "VÌ SAO ÍT AI THEO ĐUỔI PHÉP THỬ NÀY",
    s9: "Anh em nhà Wright không chế ra máy bay bằng cách gắn lông vũ lên cánh. Họ bỏ con chim sang một bên và đi tìm nguyên lý nâng — và <em>chính vì</em> bỏ con chim đi mà họ bay được. Ngành AI đi theo đúng lối ấy, nên phép thử nổi tiếng nhất trong lịch sử của chính nó thì gần như không phòng thí nghiệm nào thèm theo đuổi: <strong class='hl'>hiểu nguyên lý đáng giá hơn sao chép một mẫu vật</strong>.",
    s10: "Đó mới là lý do thực dụng. Lý do thứ hai sâu hơn, và tôi muốn bạn tự tìm ra. Hai câu — trả lời trong đầu trước rồi hẵng đọc tiếp.<br/><br/><strong class='hl'>Một: vượt được phép thử Turing thì có chắc là thông minh không?</strong> Chưa chắc. Muốn qua bài, máy phải bắt chước cả những chỗ rất người mà chẳng thông minh gì — gõ sai chính tả, nhẩm 17×24 mất mười giây.<br/><br/><strong class='hl'>Hai: trượt phép thử thì có nghĩa là không thông minh không?</strong> Cũng không. Đưa một dãy triệu số bảo tìm quy luật, máy tìm ra trong một nốt nhạc — và chính vì làm được nên nó rớt, lộ ngay không phải người.<br/><br/>Ghép hai câu trả lời lại là ra kết luận: cái thước này đo <strong class='hl'>hành vi người</strong>, không đo hành vi thông minh. Hai tập ấy chỉ chồng lên nhau một phần — nên nó vừa quá chặt vừa quá lỏng.",
    s11: "Mà nhân nói chuyện máy “nhìn”: theo bạn đây là con cừu, hay cái giẻ lau? 🐑",
  },
  ch4: {
    s1: "Hai lối đo <em class='hl-cyan'>suy nghĩ</em>",
    s2: "Năm 1961, Newell và Simon làm một chuyện nghe rất lạ: họ bắt người thật ngồi giải đố và <strong class='hl'>nói to ra mọi thứ đang nghĩ trong đầu</strong>, rồi chép lại từng câu. Không phải để nghiên cứu tâm lý — để đem so với từng bước của chương trình họ vừa viết.<br/><br/>Đó là một trong hai cách đo <em>suy nghĩ</em>. Cách còn lại chẳng cần tới con người nào cả: so với luật logic. Cùng một chương trình, hai cây thước ấy chấm ra hai điểm khác nhau.",
    s3: "SUY NGHĨ NHƯ NGƯỜI · THINKING HUMANLY",
    s4: "General Problem Solver — Newell và Simon, 1961",
    s5: "Cái hay của GPS không nằm ở chỗ nó giải đúng bài. Mà ở chỗ hai tác giả bắt người thật ngồi giải cùng bài, ghi lại từng bước nghĩ, rồi <strong class='hl'>đem so với từng bước của chương trình</strong>. Ra đúng đáp án chưa được tính điểm — phải đi đúng cả đường trong đầu nữa cơ.",
    s6: "KHOA HỌC TRI NHẬN — COGNITIVE SCIENCE",
    s7: "Mô hình máy tính của AI <span style='color:var(--faint)'>+</span> thí nghiệm của tâm lý học <span style='color:var(--faint)'>→</span> lý thuyết <strong class='hl-mid'>chính xác và kiểm chứng được</strong> về trí óc người. Giờ hai bên đã ra ở riêng: vẫn xài chung mấy lý thuyết cũ, nhưng chưa bên nào giải thích nổi thứ gì thật sự giống trí thông minh của người.",
    s8: "SUY NGHĨ DUY LÝ · THINKING RATIONALLY",
    s9: "Luật của tư duy — Aristotle (384–322 TCN)",
    s10: "“Nghĩ đúng” ở đây nghĩa là lập luận chặt tới mức không ai bác được. Aristotle để lại sẵn các khuôn tam đoạn luận: cứ nhét tiền đề đúng vào là <strong class='hl'>kết luận chắc chắn đúng</strong> — máy chạy đúng khuôn đó là đang nghĩ duy lý.",
    s11: "Mọi người đều phải chết.",
    s12: "Socrates là người.",
    s13: "Vậy Socrates phải chết.",
    s14: "HAI CHỖ VẤP CỦA ĐƯỜNG LOGICIST",
    s15: "<strong class='hl-red-soft'>1 ·</strong> Không phải hành vi thông minh nào cũng chịu đi qua logic — bạn có giải tam đoạn luận nào đâu trước khi né cú xe tạt đầu.",
    s16: "<strong class='hl-red-soft'>2 ·</strong> “Trên nguyên tắc là giải được” và “giải xong trước khi mặt trời tắt” là hai chuyện rất khác nhau.",
    s17: "Nhớ kỹ hai chỗ vấp này. Buổi 7 và 8 mình sẽ xây đúng loại hệ lập luận đó, và sẽ vấp lại đúng hai chỗ này.",
  },
  ch6: {
    s1: "AI vay gì của ai",
    s2: "AI không tự nhiên rơi từ trên trời xuống. Tám ngành khác đã hỏi sẵn những câu hay nhất và để lại đủ bộ đồ nghề; AI mượn hết về, rồi hỏi thêm đúng một câu: <em>thế làm ra cái máy như vậy được không?</em>",
    s3: "LĨNH VỰC",
    s4: "TIẾNG VIỆT",
    s5: "ĐÓNG GÓP CHO AI",
    s6: "Ba cái tên này bị dùng lẫn lộn khắp nơi, kể cả trên báo. Thật ra chúng lồng vào nhau như búp bê Nga: học sâu là một cách làm học máy, học máy là một cách làm AI. Mấy mô hình ngôn ngữ lớn bạn đang dùng hằng ngày nằm ở lớp trong cùng — và tám buổi giữa của khóa này, từ tìm kiếm tới logic, không đụng tới lớp đó lấy một lần.",
    s7: "ĐƯỢC GÌ · MẤT GÌ",
    s8: "ĐƯỢC",
    s9: "Máy tính mạnh hơn, hữu dụng hơn",
    s10: "Giao diện mới và tốt hơn",
    s11: "Giải được những bài toán mới",
    s12: "Xử lý thông tin tốt hơn",
    s13: "Giảm tình trạng ngập trong thông tin",
    s14: "Biến thông tin thành tri thức",
    s15: "MẤT",
    s16: "Chi phí tăng",
    s17: "Phát triển phần mềm khó — chậm và đắt",
    s18: "Ít lập trình viên có kinh nghiệm",
  },
  ch7: {
    s1: "Tám thập kỷ, hai mùa đông",
    s2: "Năm 1970, Marvin Minsky nói với tạp chí Life rằng chỉ ba tới tám năm nữa thôi, ta sẽ có cỗ máy thông minh ngang một người bình thường. Bốn năm sau, các cơ quan tài trợ ở Anh rồi Mỹ lần lượt cắt ngân sách. Phòng thí nghiệm đóng cửa, nghiên cứu sinh chuyển ngành.<br/><br/>Câu đáng hỏi ở đây không phải “vì sao Minsky đoán sai” — ai mà chẳng có lúc đoán sai. Câu đáng hỏi là: <strong class='hl'>chuyện đó có phải một tai nạn đơn lẻ không?</strong> Không. Nó là một vòng lặp, và bạn sắp thấy nó chạy đủ hai lượt trong tám thập kỷ.<br/><br/>Xem dòng thời gian một lượt, để ý riêng hai vùng đỏ. Rồi đọc tên bốn giai đoạn: đó là bốn câu trả lời khác nhau cho đúng câu hỏi ở mục 02.",
    s3: "Dòng thời gian 1940 → 2022",
    s4: "đầu đọc quét từ trái sang phải; vùng đỏ là các mùa đông AI",
    s5: "1940–70 · LOGIC DẪN ĐƯỜNG",
    s6: "Mạch Boole của não (1943), bài báo của Turing (1950), cờ đam của Samuel, Logic Theorist, Geometry Engine, hội nghị Dartmouth 1956, thuật toán lập luận đầy đủ của Robinson 1965.",
    s7: "1970–90 · TRI THỨC RỒI SỤP",
    s8: "Hệ dựa trên tri thức phát triển từ 1969–79, ngành hệ chuyên gia bùng nổ 1980–88, rồi sụp 1988–93 — đúng thời kỳ mang tên <strong class=\"hl-red-soft\">AI Winter</strong>.",
    s9: "1990–2010 · THỐNG KÊ VÀ AGENT",
    s10: "Xác suất trở lại, tập trung vào bất định, độ sâu kỹ thuật tăng, agent và hệ thống biết học — “AI Spring”. TD-Gammon 1992, Deep Blue 1997, Roomba 2002.",
    s11: "2010– · DỮ LIỆU LỚN, RỒI QUY MÔ",
    s12: "SIRI 2011, AlexNet 2012, Atari 2015, AlphaGo 2016, Transformer 2017, AlphaFold 2018–20, sinh ảnh 2021–22, ChatGPT 2022.",
    s13: "Mùa đông nổi tiếng nhất là 1988–93, lúc ngành hệ chuyên gia sụp cái rầm. Vùng 1974–80 ít được nhắc hơn nhưng cùng một công thức: hứa to → làm không nổi → nhà tài trợ rút ví. Công thức này lặp đủ nhiều lần để đáng nhớ — bạn thấy nó quen quen với thời bây giờ không? 👀",
  },
  quiz: {
    s1: "Quiz — đo xem bạn <em class='hl-cyan'>thật sự</em> hiểu tới đâu",
    s2: "tám câu · bốn hướng tiếp cận, Turing, lịch sử, agent duy lý",
    s3: "Đọc một mạch rồi thấy hiểu hết là cảm giác quen thuộc nhất trên đời — và cũng là cảm giác dễ lừa mình nhất. Tám câu dưới đây không phải để chấm bạn; chúng để lộ ra chỗ nào bạn mới chỉ <em>thấy quen mặt</em> chứ chưa hiểu. Sai câu nào thì đọc phần giải thích ngay dưới đó, đừng để dành. Làm xong hẵng qua bài tập.",
  },
  ch5: {
    qCount: (i: number, n: number) => `CÂU ${i}/${n}`,
    score: (c: number, n: number) => `ĐÚNG ${c}/${n}`,
    s1: "Hành động duy lý — ô mà môn này chọn",
    s2: "Đây là ô mà cả khóa sẽ sống trong đó, nên tôi muốn bạn trả lời một câu trước đã.<br/><br/><strong class='hl'>Bạn nhìn trước nhìn sau rồi sang đường lúc vắng hoe, và bị một cánh cửa máy bay rơi trúng. Quyết định sang đường lúc đó có duy lý không?</strong><br/><br/>Có. Duy lý chấm <em>quyết định</em>, không chấm <em>kết quả</em> — và đó là toàn bộ chỗ khó của chữ này. Duy lý = <strong class='hl'>làm điều đúng</strong>, mà “điều đúng” có nghĩa rất hẹp và đo được: điều mà <em>kỳ vọng</em> đưa bạn tới gần mục tiêu nhất, với đúng mớ thông tin đang có trong tay. Còn <strong class='hl-green'>agent</strong> thì đơn giản tới mức hơi hụt hẫng: thứ gì tri giác rồi hành động, hết.",
    s3: "AGENT LÀ GÌ",
    s4: "Một cái hàm, nhận tri giác vào rồi nhả hành động ra. Nhìn thì tầm thường, nhưng cả Buổi 2 dành để mổ đúng nó: PEAS, bảy chiều môi trường, năm kiểu agent.",
    s5: "RỘNG HƠN “LUẬT CỦA TƯ DUY”",
    s6: "<strong class='hl-green'>Gồm cả</strong> suy nghĩ và suy diễn — chúng chỉ là công cụ để hành động cho đúng thôi.",
    s7: "<strong class='hl-green'>Gồm thêm</strong> những hành động chẳng kịp nghĩ gì cả — phản xạ chẳng hạn.",
    s8: "<strong class='hl-green'>Và</strong> suy diễn đúng chưa phải là tất cả: có lúc chẳng chứng minh được hành động nào là đúng, mà vẫn phải làm gì đó chứ không đứng đực ra.",
    s9: "DỄ PHÁT TRIỂN KHOA HỌC HƠN",
    s10: "Lý do rất thực dụng: “duy lý” là một khái niệm toán học, rõ ràng và tổng quát, nên còn làm khoa học trên nó được. Chứ <em>hành vi người</em> hay <em>suy nghĩ người</em> thì tới giờ ta còn chưa mô tả nổi, lấy gì làm chuẩn. Nên cả khóa này tôi chọn ô đó làm trục 🎯",
    s11: "TỰ PHÂN LOẠI — ĐẶT HỆ THỐNG VÀO ĐÚNG Ô",
    s12: "↺ làm lại",
    s13: "✓ Đúng. ",
    s14: "✗ Chưa đúng — đáp án: ",
    s15: "↺ Về câu 1",
    s16: "Câu tiếp →",
    s17: "CÂU HỎI MỞ — PHẢN XẠ, THÔNG MINH, HAY DUY LÝ?",
    s18: "Không có đáp án sẵn đâu, tôi cũng không dám chắc. Bốn tình huống dưới đây: cái nào là phản xạ, cái nào phải nghĩ, và cái nào chẳng nghĩ gì mà vẫn duy lý như thường?",
    s19: "Một người đàn ông rút ngón tay khỏi bếp nóng.",
    s20: "Em bé mới sinh nắm lấy ngón tay của mẹ.",
    s21: "Hai người băng qua đường ở vạch dành cho người đi bộ.",
    s22: "Một cô gái đeo khẩu trang để không lây cúm cho người khác.",
  },
  ch8: {
    s1: "Làm được gì, chưa làm được gì",
    s2: "Ngày 8 tháng 10 năm 2024, giải Nobel Vật lý được trao cho Hopfield và Hinton vì những khám phá nền cho mạng nơ-ron nhân tạo. Đúng một ngày sau, giải Nobel Hóa học gọi tên AlphaFold. Hai giải khoa học tự nhiên trong hai ngày liên tiếp, cho cùng một họ công cụ — thứ mà ba mươi năm trước còn bị coi là ngõ cụt.<br/><br/>Dưới đây là những chỗ AI đã làm được thật. Đọc xong, giữ lại chút hoài nghi cho phần cuối mục: danh sách <em>chưa</em> làm được vẫn dài hơn bạn nghĩ.",
    s3: "LẬP KẾ HOẠCH VÀ ĐIỀU ĐỘ TỰ ĐỘNG",
    s4: "Xếp lịch quan sát cho kính viễn vọng",
    s5: "Xe tự hành thăm dò",
    s6: "Phân tích dữ liệu",
    s7: "Y HỌC",
    s8: "Phân loại trên ảnh y khoa",
    s9: "Hệ chẩn đoán — ví dụ MYCIN",
    s10: "Đã có kết quả nuôi cấy dương tính chưa?",
    s11: "BÁC SĨ:",
    s12: "Có.",
    s13: "Nhiễm khuẩn loại nào?",
    s14: "BÁC SĨ:",
    s15: "Nhiễm khuẩn huyết tiên phát.",
    s16: "→ Tôi đề nghị dùng gentamycin liều…",
    s17: "GAME VÀ GIẢI TRÍ",
    s18: "Deep Blue thắng Kasparov (1997)",
    s19: "AlphaGo thắng Lee Sedol (2016)",
    s20: "Poker: DeepStack và Libratus (2017)",
    s21: "Game là phòng thí nghiệm sạch nhất mà AI có: luật rõ ràng, thắng thua khỏi cãi. Buổi 5 mình sẽ mở nắp mấy con này ra xem bên trong — minimax và cắt tỉa α-β.",
    s22: "CÂU ĐỐ — HIỆN NAY MÁY LÀM ĐƯỢC VIỆC NÀO?",
    s23: "bấm chọn việc bạn nghĩ máy làm được — không có đáp án, đây là chỗ để tự cãi với chính mình",
    s24: "Danh sách này viết từ nhiều năm trước. Trò vui: thử đoán hồi 2015 người ta trả lời thế nào, rồi so với câu trả lời của bạn hôm nay. Chỗ nào lệch, chỗ đó là ngành vừa tiến được một bước thật.",
    s25: "GIỚI HẠN VÀ ĐẠO ĐỨC",
    s26: "Nãy giờ toàn tin vui. Giờ tới phần tôi không thích lắm nhưng vẫn phải nói: cùng đúng những năng lực đó, dùng sai thì thành rủi ro thật. Bốn chuyện nên nhớ khi bạn làm đồ án, và khi bạn đi cãi nhau về AI:",
    s27: "<strong class=\"hl-red-soft\">Vũ khí tự hành sát thương</strong> — máy tự quyết định mục tiêu.",
    s28: "<strong class=\"hl-red-soft\">Theo dõi và thuyết phục</strong> — quy mô giám sát và tác động lên dư luận. Từ khi dựng được giọng nói và khuôn mặt giả gần như thật, chi phí của một lời bịa đặt có sức thuyết phục đã rơi xuống gần bằng không.",
    s29: "<strong class=\"hl-red-soft\">Thiên lệch trong quyết định</strong> — hệ học từ dữ liệu cũ nên tái sinh định kiến cũ. Mô hình càng nuốt nhiều dữ liệu vơ từ Internet thì càng khó biết nó đang học định kiến của ai.",
    s30: "<strong class=\"hl-red-soft\">Việc làm và an toàn</strong> — tự động hóa, và những chỗ mà một lỗi là chết người. Thêm một kiểu lỗi rất mới: hệ nói sai bằng giọng chắc nịch, nghe thuyết phục hơn cả lúc nó nói đúng.",
  },
  ch9: {
    s1: "Tổng kết — và môn này sẽ đi đâu",
    s2: "🧭 Một câu tóm cả buổi, nếu bạn chỉ nhớ được một câu: AI cố xây ra thực thể thông minh, có bốn cách định nghĩa “thông minh”, và mình chọn ô <strong class='hl-green'>hành động duy lý</strong> để bám theo suốt 11 buổi. Còn đây là bản đồ chặng đường phía trước.",
    s3: "Bốn ô, không nhìn bảng",
    s4: "Kể tên bốn hướng tiếp cận AI và nói rõ mỗi hướng lấy gì làm chuẩn chấm. Kẹt ô nào thì quay lại <a href=\"#ch2\">mục 02</a> — nhưng thử nhớ trước đã, nhớ hụt rồi tra mới dính lâu.",
    s5: "Phép thử Turing sai ở đâu",
    s6: "Không phải “vì khó quá”. Nói cho được vì sao vượt phép thử không đồng nghĩa với thông minh, <em>và</em> vì sao trượt nó cũng không đồng nghĩa với không thông minh (<a href=\"#ch3\">mục 03</a>).",
    s7: "Mùa đông AI đến từ đâu",
    s8: "Mô tả cơ chế, không phải mốc thời gian: chuyện gì trong cách ngành này hứa hẹn đã dẫn tới chỗ cạn tiền (<a href=\"#ch7\">mục 07</a>)?",
  },
  hw: {
    // Chuỗi có link nội bộ nên phải là HÀM: `localeBase` khác nhau giữa hai ngôn ngữ, và
    // viết thẳng BASE_URL vào đây là rơi đúng cái bẫy ADR-0007.
    lead: (base: string) =>
      `Buổi này không có đề bài tập riêng — bộ đề của khóa bắt đầu từ nội dung buổi 2, và bốn câu PEAS mà bạn có thể đã nghe nhắc tới thì tôi để đúng chỗ của chúng: <a href='${base}courses/csc14003/lessons/b2#hw'>mục 10 của Buổi 2</a>, nơi bạn có đủ đồ nghề để làm thật. Còn ba câu dưới đây thì trả lời được ngay bây giờ, bằng đúng những gì vừa đọc.`,
    s1: "Trước khi qua <em class='hl-purple'>Buổi 2</em>",
    s2: "ba câu tự vấn · không cần giấy bút",
    s3: "Tiếp theo: <strong class='hl'>Buổi 2 — Tác tử thông minh</strong>, nơi mình mổ hàm f: 𝓟 → 𝓐 ra xem bên trong — PEAS, bảy chiều môi trường, năm kiểu agent. Đúng bộ đồ nghề mà bốn câu bài tập kia đang đòi 😉",
    s4: "← Về Lộ trình",
  },
  scenes: {
    s1: "HUMANS — CHUẨN LÀ NGƯỜI",
    s2: "RATIONALITY — CHUẨN LÀ DUY LÝ",
    s3: "suy nghĩ",
    s4: "hành động",
    s5: "Người hỏi",
    s6: "Một người",
    s7: "Một cái máy",
    s8: "MÀN NGĂN — CHỈ TRAO ĐỔI BẰNG CHỮ VIẾT",
    s9: "câu hỏi viết →",
    s10: "← trả lời viết",
    s11: "cái nào là người, cái nào là máy?",
    s12: "KHÔNG PHÂN BIỆT ĐƯỢC → MÁY VƯỢT PHÉP THỬ",
    s13: "tám thập kỷ AI — các mốc chính và bốn giai đoạn",
  },
};
