import type { VI } from './lesson01.text.vi';

/*
 * Bản tiếng Anh của bài 1. `satisfies typeof VI` là cổng kiểm cấu trúc; giá trị thì
 * `check_i18n.py` canh (thẻ HTML, số liệu, anchor, định danh code).
 *
 * Giọng: .claude/skills/lesson-voice/references/english.md — I/you, rút gọn dùng dấu ’,
 * ví von gắn văn hóa thì THAY chứ không dịch.
 */
export const EN = {
  nav: {
    hero: "Cover",
    toan: "MATH PRIMER",
    ch1: "01 What AI is",
    ch2: "02 Four boxes",
    ch3: "03 Turing",
    ch4: "04 Thinking",
    ch5: "05 Rationality",
    ch6: "06 Foundations",
    ch7: "07 History",
    ch8: "08 Applications",
    ch9: "09 Wrap-up",
    quiz: "10 Quiz",
    hw: "11 On to Session 2",
  },
  hero: {
    s12: "SESSION 1",
    s13: "Introduction to AI",
    s14: "CSC14003 · SESSION 1 · ZERO → HERO",
    s15: "What is",
    s16: "artificial",
    s17: "intelligence?",
    s18: "🤔 Sounds forbiddingly academic, doesn’t it? I thought so too. It turns out the whole subject is four camps arguing over what “intelligent” means — and they’ve been at it for 70 years without settling. Session 1 starts from zero: by the end, hand me any system you like and you’ll drop it in the right box, read 80 years of the field’s history without stalling, and finish the homework.",
    s19: "𝓟 — percept sequence",
    s20: "𝓐 — actions",
    s21: "10 sections",
    s22: "8-question sorting quiz",
    s23: "Homework — PEAS",
    s24: "≈ 2 hours",
    s25: "LIKE HUMANS",
    s26: "RATIONALLY",
    s27: "THINKING",
    s28: "Think like humans",
    s29: "Think rationally",
    s30: "ACTING",
    s31: "Act like humans",
    s32: "Act rationally",
  },
  ch1: {
    s1: "Not just understand it — build it",
    s2: "In 1988, when Richard Feynman died, one line was still up on his office blackboard, not yet wiped off: <em>what I cannot create, I do not understand</em>.<br/><br/>Psychology and neuroscience have been taking intelligence apart for centuries with the aim of <em>understanding</em> it. AI picks up the other half of that sentence: understanding isn’t enough, you have to <strong class='hl'>try building one and see</strong>. It sounds like a small difference, and that one word is the whole reason AI sits in a computer science department rather than a psychology one.",
    s3: "INTELLIGENCE",
    s4: "Covers the capacity for <em>logic, understanding, learning, reasoning, creativity, problem solving</em>, and so on.",
    s5: "Not only trying to <em>understand</em> it, but trying to <strong class='hl'>build intelligent entities</strong>.",
    s6: "A VERY YOUNG FIELD",
    s7: "AI is younger than you think. Serious work started right after World War II, and the name <strong class='hl'>“Artificial Intelligence”</strong> only arrived at the Dartmouth College conference in <strong class='hl-yellow'>1956</strong> — which makes the field not quite 70 years old. The people in that room:",
    s8: "IMITATING HUMANS ON FOUR FRONTS",
    s9: "<strong class='hl-cyan'>Thinking</strong> — learning, planning, refining what it knows.",
    s10: "<strong class='hl-cyan'>Perceiving</strong> — seeing, hearing, sensing.",
    s11: "<strong class='hl-cyan'>Manipulating</strong> — gripping and moving objects.",
    s12: "<strong class='hl-cyan'>Communicating</strong> — in natural language.",
    s13: "Keep these four in mind for me: later on they grow into four separate families of problems — machine learning, vision and speech, robotics, and language processing.",
  },
  ch2: {
    s1: "Four definitions, two axes",
    s2: "“What is AI” has no single answer — it has <strong class='hl'>four</strong>, and those four differ in only two places. One: do you open the lid and watch it <em>think</em>, or stand outside and watch it <em>act</em>? Two: do you measure it against <em>humans</em>, or against <em>rationality</em>?<br/><br/>Two questions, two axes, four boxes. Once this table is in your head you’ll see why two AI papers can contradict each other flatly and both still be right — they’re standing in different boxes.",
    s3: "Four boxes on two axes",
    s4: "columns: measured against humans or against rationality · rows: measuring thought or measuring behavior",
    s5: "HOW TO READ THE TWO AXES",
    s6: "top row — thought processes and reasoning",
    s7: "bottom row — behavior",
    s8: "left column — the standard: humans",
    s9: "right column — the standard: rationality",
    s10: "→ over the next four sections I walk you through the boxes one at a time, then drop you into an interactive one to sort systems yourself.",
  },
  ch3: {
    s1: "Acting like a human — the Turing test",
    s2: "In October 1950, in the journal <em>Mind</em>, Alan Turing opened with exactly the question everybody wants to ask: can machines think? A few lines later he threw it out — too meaningless to be worth discussing.<br/><br/>What he put in its place was a question you can <em>measure</em>: you sit and type a few questions; if you can’t tell whether the other side is a person or a machine, the machine <strong class='hl'>passes the test</strong>. The entire criterion is behavior — nobody opens the lid to inspect how it thinks in there.",
    s3: "How the test is set up",
    s4: "diagram — written exchange only, the interrogator cannot see who is on the other side",
    s5: "TWO VARIANTS",
    s6: "<strong class='hl-yellow'>Reverse Turing Test</strong> — swap the roles: the machine sets the test and the human has to prove they’re human. You sit this one almost daily without noticing; it’s called a <span class='code-inline'>CAPTCHA</span> 🤖",
    s7: "<strong class='hl-yellow'>Total Turing Test</strong> — the hard version: the machine also has to see (computer vision) and handle objects (robotics), with no hiding behind a text screen.",
    s8: "WHY ALMOST NOBODY CHASES THIS TEST",
    s9: "The Wright brothers didn’t build an airplane by gluing feathers to the wings. They set the bird aside and went looking for the principle of lift — and it was <em>because</em> they set the bird aside that they flew. AI took the same road, which is why the most famous test in its own history is one that almost no lab bothers to pursue: <strong class='hl'>understanding the principle is worth more than copying a specimen</strong>.",
    s10: "That’s the practical reason. The second one runs deeper, and I want you to find it yourself. Two questions — answer them in your head before reading on.<br/><br/><strong class='hl'>One: if something passes the Turing test, is it definitely intelligent?</strong> Not necessarily. To pass, a machine has to imitate the very human and not at all intelligent bits too — typos, taking ten seconds over 17×24.<br/><br/><strong class='hl'>Two: if something fails the test, does that mean it isn’t intelligent?</strong> Also no. Hand it a million-number sequence and ask for the pattern, and it finds one instantly — and it fails precisely because it can, giving itself away as not human.<br/><br/>Put the two answers together and the conclusion falls out: this ruler measures <strong class='hl'>human behavior</strong>, not intelligent behavior. Those two sets only partly overlap — so it is both too strict and too loose at once.",
    s11: "And while we’re on machines “seeing”: is this a sheep, or a dishcloth? 🐑",
  },
  ch4: {
    s1: "Two ways to measure <em class='hl-cyan'>thinking</em>",
    s2: "In 1961 Newell and Simon did something that sounds very odd: they sat real people down with puzzles and made them <strong class='hl'>say out loud everything going through their heads</strong>, then wrote down every sentence. Not to study psychology — to compare it against each step of the program they had just written.<br/><br/>That is one of the two ways to measure <em>thinking</em>. The other needs no humans at all: compare against the laws of logic. Same program, two rulers, two different scores.",
    s3: "THINK LIKE HUMANS · THINKING HUMANLY",
    s4: "General Problem Solver — Newell and Simon, 1961",
    s5: "What makes GPS interesting isn’t that it solved the puzzles. It’s that the two authors sat real people down with the same puzzles, recorded every step of their reasoning, and <strong class='hl'>compared it against every step of the program</strong>. Reaching the right answer earned no marks — the route through the head had to match too.",
    s6: "COGNITIVE SCIENCE",
    s7: "AI’s computational models <span style='color:var(--faint)'>+</span> psychology’s experiments <span style='color:var(--faint)'>→</span> a <strong class='hl-mid'>precise and testable</strong> theory of the human mind. The two have since moved into separate houses: they still share some of the old theories, but neither side can yet explain anything that really resembles human intelligence.",
    s8: "THINK RATIONALLY · THINKING RATIONALLY",
    s9: "The laws of thought — Aristotle (384–322 BC)",
    s10: "“Thinking correctly” here means reasoning so tight that nobody can argue with it. Aristotle left the syllogism forms ready-made: feed in true premises and the <strong class='hl'>conclusion is guaranteed true</strong> — a machine running those forms is thinking rationally.",
    s11: "All men are mortal.",
    s12: "Socrates is a man.",
    s13: "Therefore Socrates is mortal.",
    s14: "TWO PLACES THE LOGICIST ROAD TRIPS",
    s15: "<strong class='hl-red-soft'>1 ·</strong> Not every piece of intelligent behavior is willing to go through logic — you didn’t work a syllogism before dodging that car that cut in front of you.",
    s16: "<strong class='hl-red-soft'>2 ·</strong> “Solvable in principle” and “solved before the sun burns out” are two very different things.",
    s17: "Hold on to these two. In Sessions 7 and 8 you’ll build exactly that kind of reasoning system — and you’ll trip over these same two again.",
  },
  ch6: {
    s1: "What AI borrowed, and from whom",
    s2: "AI didn’t drop out of the sky. Eight other fields had already asked the best questions and left a full toolkit behind; AI borrowed the lot, then added exactly one question of its own: <em>so could we build a machine that does that?</em>",
    s3: "FIELD",
    s4: "IN VIETNAMESE",
    s5: "WHAT IT GAVE AI",
    s6: "These three names get used interchangeably everywhere, newspapers included. They actually nest inside one another like Russian dolls: deep learning is one way of doing machine learning, and machine learning is one way of doing AI. The large language models you use daily sit in the innermost layer — and the eight middle sessions of this course, from search through logic, never touch that layer once.",
    s7: "UPSIDE · DOWNSIDE",
    s8: "UPSIDE",
    s9: "More capable, more useful computers",
    s10: "New and better interfaces",
    s11: "Problems we couldn’t solve before",
    s12: "Better information processing",
    s13: "Less drowning in information",
    s14: "Turning information into knowledge",
    s15: "DOWNSIDE",
    s16: "Rising costs",
    s17: "Software development is hard — slow and expensive",
    s18: "Few experienced developers",
  },
  ch7: {
    s1: "Eight decades, two winters",
    s2: "In 1970 Marvin Minsky told Life magazine that in three to eight years we would have a machine as intelligent as an average person. Four years later, funding agencies in Britain and then the US cut their budgets one after another. Labs closed, PhD students switched fields.<br/><br/>The question worth asking isn’t “why did Minsky get it wrong” — everyone gets things wrong sometimes. The question worth asking is: <strong class='hl'>was that a one-off accident?</strong> No. It’s a loop, and you’re about to watch it run twice across eight decades.<br/><br/>Scan the timeline once, paying particular attention to the two red bands. Then read the names of the four eras: they are four different answers to the very question from section 02.",
    s3: "Timeline 1940 → 2022",
    s4: "the playhead sweeps left to right; the red bands are the AI winters",
    s5: "1940–70 · LOGIC LEADS",
    s6: "Boolean circuits of the brain (1943), Turing’s paper (1950), Samuel’s checkers, Logic Theorist, Geometry Engine, the Dartmouth conference in 1956, Robinson’s complete reasoning algorithm in 1965.",
    s7: "1970–90 · KNOWLEDGE, THEN COLLAPSE",
    s8: "Knowledge-based systems grew from 1969–79, the expert-systems industry boomed 1980–88, then collapsed 1988–93 — the stretch that earned the name <strong class=\"hl-red-soft\">AI Winter</strong>.",
    s9: "1990–2010 · STATISTICS AND AGENTS",
    s10: "Probability came back, uncertainty took center stage, technical depth grew, and agents and learning systems arrived — the “AI Spring”. TD-Gammon 1992, Deep Blue 1997, Roomba 2002.",
    s11: "2010– · BIG DATA, THEN SCALE",
    s12: "SIRI 2011, AlexNet 2012, Atari 2015, AlphaGo 2016, Transformer 2017, AlphaFold 2018–20, image generation 2021–22, ChatGPT 2022.",
    s13: "The famous winter is 1988–93, when the expert-systems industry fell over. The 1974–80 band gets mentioned less but follows the same recipe: promise big → fail to deliver → funders pull out. The recipe has repeated often enough to be worth remembering — does it feel at all familiar right now? 👀",
  },
  quiz: {
    s1: "Quiz — how much did you <em class='hl-cyan'>actually</em> take in?",
    s2: "eight questions · the four approaches, Turing, history, rational agents",
    s3: "Reading straight through and feeling like you got all of it is the most familiar sensation there is — and the easiest one to fool yourself with. The eight questions below aren’t here to grade you; they’re here to expose where you only <em>recognize</em> something rather than understand it. Get one wrong and read the explanation right underneath, don’t save it for later. Finish these before the homework.",
  },
  ch5: {
    qCount: (i: number, n: number) => `QUESTION ${i}/${n}`,
    score: (c: number, n: number) => `CORRECT ${c}/${n}`,
    s1: "Acting rationally — the box this course picks",
    s2: "This is the box the whole course lives in, so I want one answer from you first.<br/><br/><strong class='hl'>You look both ways, cross an empty street, and an aircraft door falls on you. Was the decision to cross rational?</strong><br/><br/>Yes. Rationality grades the <em>decision</em>, not the <em>outcome</em> — and that is the whole difficulty of the word. Rational = <strong class='hl'>doing the right thing</strong>, where “the right thing” has a narrow, measurable meaning: the thing that is <em>expected</em> to get you closest to your goal, given exactly the information in your hands. And <strong class='hl-green'>agent</strong> is almost disappointingly simple: anything that perceives and then acts, that’s it.",
    s3: "WHAT AN AGENT IS",
    s4: "A function: percepts in, actions out. It looks trivial, but the whole of Session 2 goes into taking it apart — PEAS, the seven environment dimensions, the five kinds of agent.",
    s5: "WIDER THAN “THE LAWS OF THOUGHT”",
    s6: "<strong class='hl-green'>It includes</strong> thinking and inference — those are just tools for acting correctly.",
    s7: "<strong class='hl-green'>It also includes</strong> actions with no time to think at all — reflexes, for one.",
    s8: "<strong class='hl-green'>And</strong> correct inference isn’t the whole story: sometimes no action can be proven right, and you still have to do something rather than stand there.",
    s9: "EASIER TO DO SCIENCE ON",
    s10: "The reason is thoroughly practical: “rational” is a mathematical notion, clear and general, so you can still do science on top of it. Whereas <em>human behavior</em> and <em>human thought</em> are things we can’t even describe yet — hard to use as a standard. So that’s the box I pick as the spine of this course 🎯",
    s11: "SORT IT YOURSELF — PUT EACH SYSTEM IN ITS BOX",
    s12: "↺ try again",
    s13: "✓ Right. ",
    s14: "✗ Not quite — the answer is: ",
    s15: "↺ Back to question 1",
    s16: "Next question →",
    s17: "OPEN QUESTION — REFLEX, INTELLIGENT, OR RATIONAL?",
    s18: "There’s no answer key here, and I’m not certain either. Four situations below: which is a reflex, which needs thinking, and which involves no thinking at all yet is perfectly rational?",
    s19: "A man pulls his finger back from a hot stove.",
    s20: "A newborn grips their mother’s finger.",
    s21: "Two people cross the road at a pedestrian crossing.",
    s22: "A woman wears a mask so she doesn’t pass her flu on to anyone.",
  },
  ch8: {
    s1: "What it can do, and what it can’t yet",
    s2: "On 8 October 2024 the Nobel Prize in Physics went to Hopfield and Hinton for the foundational discoveries behind artificial neural networks. Exactly one day later, the Nobel Prize in Chemistry named AlphaFold. Two natural-science Nobels on consecutive days, for the same family of tools — the family that thirty years earlier was written off as a dead end.<br/><br/>Below are the places AI genuinely delivers. When you’ve read them, save some skepticism for the end of the section: the list of things it <em>can’t</em> do yet is longer than you’d guess.",
    s3: "AUTOMATED PLANNING AND SCHEDULING",
    s4: "Scheduling telescope observations",
    s5: "Autonomous exploration rovers",
    s6: "Data analysis",
    s7: "MEDICINE",
    s8: "Classification on medical images",
    s9: "Diagnostic systems — MYCIN, for instance",
    s10: "Do you have a positive culture result yet?",
    s11: "DOCTOR:",
    s12: "Yes.",
    s13: "What type of infection?",
    s14: "DOCTOR:",
    s15: "Primary bacteremia.",
    s16: "→ I recommend gentamycin at a dose of…",
    s17: "GAMES AND ENTERTAINMENT",
    s18: "Deep Blue beat Kasparov (1997)",
    s19: "AlphaGo beat Lee Sedol (2016)",
    s20: "Poker: DeepStack and Libratus (2017)",
    s21: "Games are the cleanest laboratory AI has: rules are explicit and nobody argues about who won. In Session 5 I’ll open these up with you — minimax and α-β pruning.",
    s22: "QUICK QUIZ — WHICH OF THESE CAN MACHINES DO TODAY?",
    s23: "tap the ones you think machines can do — no answer key, this is a place to argue with yourself",
    s24: "This list was written years ago. A game worth playing: guess how people would have answered in 2015, then compare it with your answer today. Wherever the two diverge, that’s where the field genuinely moved.",
    s25: "LIMITS AND ETHICS",
    s26: "That was all good news. Now the part I like less but have to say anyway: those same capabilities, pointed the wrong way, become real risks. Four things to keep in mind while you work on your project, and while you argue about AI:",
    s27: "<strong class=\"hl-red-soft\">Lethal autonomous weapons</strong> — machines choosing their own targets.",
    s28: "<strong class=\"hl-red-soft\">Surveillance and persuasion</strong> — the scale of monitoring, and the pull on public opinion. Ever since synthetic voices and faces got close to indistinguishable, the cost of a convincing lie has fallen to roughly nothing.",
    s29: "<strong class=\"hl-red-soft\">Bias in decisions</strong> — a system learns from old data and so reproduces old prejudice. The more data a model swallows off the open Internet, the harder it gets to know whose prejudice it is learning.",
    s30: "<strong class=\"hl-red-soft\">Jobs and safety</strong> — automation, and the places where one mistake kills someone. Plus a very new failure mode: a system stating something false in a rock-solid tone, sounding more convincing than when it’s right.",
  },
  ch9: {
    s1: "Wrap-up — and where this course goes next",
    s2: "🧭 One sentence for the whole session, if you only keep one: AI tries to build intelligent entities, there are four ways to define “intelligent”, and I pick the <strong class='hl-green'>acting rationally</strong> box to follow for all 11 sessions. Here is the map of the road ahead.",
    s3: "Four boxes, no peeking at the table",
    s4: "Name the four approaches to AI and say exactly what each one uses as its standard. Stuck on one? Go back to <a href=\"#ch2\">section 02</a> — but try to recall it first, because reaching for it and missing is what makes the lookup stick.",
    s5: "Where the Turing test goes wrong",
    s6: "Not “because it’s too hard”. Be able to say why passing it doesn’t mean intelligent, <em>and</em> why failing it doesn’t mean unintelligent (<a href=\"#ch3\">section 03</a>).",
    s7: "Where AI winters come from",
    s8: "Describe the mechanism, not the dates: what was it about the way this field made promises that led to the money running out (<a href=\"#ch7\">section 07</a>)?",
  },
  hw: {
    lead: (base: string) =>
      `This session has no homework set of its own — the course’s problem sets start from Session 2 material, and I’ve put the four PEAS questions you may have heard about exactly where they belong: <a href='${base}courses/csc14003/lessons/b2#hw'>section 10 of Session 2</a>, where you’ll have the tools to do them properly. The three below you can answer right now, from what you’ve just read.`,
    s1: "Before you move on to <em class='hl-purple'>Session 2</em>",
    s2: "three questions to ask yourself · no paper needed",
    s3: "Next up: <strong class='hl'>Session 2 — Intelligent Agents</strong>, where I cut the function f: 𝓟 → 𝓐 open and you look inside — PEAS, the seven environment dimensions, the five kinds of agent. Exactly the toolkit those four homework questions are asking for 😉",
    s4: "← Back to the roadmap",
  },
  scenes: {
    s1: "HUMANS — THE STANDARD IS PEOPLE",
    s2: "RATIONALITY — THE STANDARD IS DOING THE RIGHT THING",
    s3: "thinking",
    s4: "acting",
    s5: "Interrogator",
    s6: "A person",
    s7: "A machine",
    s8: "SCREEN — WRITTEN EXCHANGE ONLY",
    s9: "written questions →",
    s10: "← written answers",
    s11: "which is the person, which is the machine?",
    s12: "CAN’T TELL THEM APART → THE MACHINE PASSES",
    s13: "eight decades of AI — the main milestones and four eras",
  },
} satisfies typeof VI;
