import type { VI } from './lab.text.vi';

export const EN = {
  fn: {
    stepOf: (t: number, n: number) => `STEP ${t} / ${n}`,
    explored: (n: number) => `EXPLORED — EXPANDED (${n})`,
    goalPath: (path: string, cost: number | null, opened: number) =>
      `Path: ${path} · cost ${cost} · ${opened} nodes expanded`,
  },
  lab: {
    s1: "Manim Lab — watch 7 algorithms step by step",
    s2: "Watching one run beats reading ten times. Pick an algorithm and press <strong class='hl'>Run</strong>, or use <strong class='hl'>Next / Back</strong> to inspect each step. Colors follow the convention used throughout the page: <span class='hl-cyan'>blue — frontier</span> · <span class='hl-yellow'>yellow — expanding</span> · <span style='color:var(--muted-2)'>gray — explored</span> · <span class='hl-green'>green — path</span> · <span class='hl-purple'>purple — a cheaper route just found</span>.",
    s3: "Here are three experiments I want you to try now: (1) on Romania, run GBFS and then A* — greedy gives 450 km, A* gives 418 km; work out where those 32 km went; (2) run HC on the same preset and watch it get stuck in Timișoara; (3) switch to the Lab graph and compare BFS (cost 9) with UCS (cost 8) to see “shallowest ≠ cheapest” for yourself.",
  },
  codelab: {
    s1: "Code Lab — implement all 7 algorithms",
    s2: "⌨️ The fun part: writing code. The assignment asks for Python and <em>your own search implementations</em>. Helper libraries are fine; a library that solves the search for you isn’t. Read <span class='code-inline'>input.txt</span>, write <span class='code-inline'>output.txt</span>, and measure runtime and peak memory for each algorithm. This is an <strong class='hl'>individual</strong> assignment over about 3 weeks. Marks: 7 algorithms × 10% · ≥ 5 test cases 10% · report 20%. I’ve put the code framework below; you fill in the core.",
    s3: "THREE CONVENTIONS — GET THESE WRONG AND YOUR OUTPUT IS WRONG. PLEASE READ",
    s4: "BFS · DFS · GBFS stop when the goal is <strong class='hl-cyan'>GENERATED</strong>",
    s5: "UCS · A* stop when the goal is <strong class='hl-yellow'>REMOVED</strong>",
    s6: "HC stuck → no path → print <strong class='hl-red'>-1</strong>",
    s7: "INPUT.TXT — the graph may be DIRECTED or undirected",
    s8: "line 1: node count · line 2: start goal · next: adjacency matrix (weights, 0 = no edge) · last line: heuristic for each node",
    s9: "OUTPUT.TXT — path or -1, with time and memory",
    s10: "this is the “Lab 1 · 6 nodes” preset from Manim Lab above — compare your code’s output step by step",
    s11: "SHARED BY ALL 7 — TRACE PARENT POINTERS BACK",
    s12: "MAIN.PY — READ INPUT, RUN 7 ALGORITHMS, MEASURE TIME + MEMORY",
    s13: "time.perf_counter() + tracemalloc — exactly the two requirements: “high-resolution timer” and “peak memory”",
    s14: "5 TEST CASE IDEAS WITH DIFFERENT PROPERTIES — MARKS WORTH PICKING UP",
    s15: "<strong class='hl-mid'>1 ·</strong> The sample 6-node graph above: Manim Lab provides reference results to catch your first bugs.",
    s16: "<strong class='hl-mid'>2 ·</strong> No solution: isolate the goal. All 7 must print -1 and exit cleanly. Any that hang have a loop bug.",
    s17: "<strong class='hl-mid'>3 ·</strong> A DIRECTED graph (asymmetric matrix): exposes neighbor-traversal bugs immediately, especially scanning a column instead of a row.",
    s18: "<strong class='hl-mid'>4 ·</strong> Deliberately supply a NON-admissible heuristic so A* returns a suboptimal path. That isn’t a bug; it matches the theory. Explaining it in your report earns useful marks.",
    s19: "<strong class='hl-mid'>5 ·</strong> A large random graph (n ≥ 500). Every algorithm finishes a 6-node graph in 0.0001 seconds; increase the size until time and memory differences show up.",
  },
  searchlab: {
    s1: "hill climbing",
    s2: "FRONTIER — FIFO queue (left = next out)",
    s3: "FRONTIER — stack (right = top, next out)",
    s4: "FRONTIER — priority queue by g (sorted)",
    s5: "CURRENT PATH (DLS backtracking)",
    s6: "FRONTIER — priority queue by h",
    s7: "FRONTIER — priority queue by f = g + h",
    s8: "FRONTIER — none (one current node only)",
    s9: "Lab 1 · 6 nodes",
    s10: "Romania · 10 nodes",
    s11: "Stuck at a local optimum → output: -1",
    s12: "No solution → output: -1",
    s13: "⟲ Reset",
    s14: "◀ Back",
    s15: "❚❚ Pause",
    s16: "▶ Run",
    s17: "Next ▶",
    s18: "STUCK",
  },
  f_codelab: {
    s1: "WORKBENCH — PICK AN ALGORITHM, READ THE PSEUDOCODE, THEN INSPECT PYTHON",
    pythonHeading: "PYTHON — LAB 1 FRAMEWORK",
  },
  scenes: {
    s1: " nodes",
    s2: "b = 10, d = 12 → 10¹² nodes",
    s3: "≈ 13 days at 1 million nodes/second · ≈ 1 petabyte of memory",
    s4: "state space →",
    s5: "↑ objective value (−h)",
    s6: "global optimum",
    s7: "STUCK — local optimum",
    s8: "reaching the higher peak means accepting a DOWNHILL step",
  },
} satisfies typeof VI;
