import type { VI } from './narrate.vi';

/* Lời kể của lab tìm kiếm — bản tiếng Anh. `satisfies typeof VI` ép đủ 42 câu và đúng chữ ký. */
export const EN = {
  n1: `Lab 1 graph (6 nodes)`,
  n2: `hill climbing`,
  n3: (a0: string | number) => `Initialize: put ${a0} in the QUEUE (FIFO). BFS tests for the goal the moment a node is GENERATED.`,
  n4: (a0: string | number) => `Take ${a0} off the FRONT of the queue — the SHALLOWEST node — and expand it.`,
  n5: (a0: string | number) => `Generate ${a0} (not seen before) → append to the BACK of the queue.`,
  n6: `Queue empty — every reachable node has been visited → NO SOLUTION.`,
  n7: (a0: string | number) => `Initialize: put ${a0} on the STACK (LIFO). DFS dives as deep as it can before backtracking.`,
  n8: (a0: string | number) => `Take ${a0} off the TOP of the stack — the DEEPEST node — and expand it.`,
  n9: (a0: string | number) => `Generate ${a0} → push onto the TOP of the stack (it will be expanded BEFORE the nodes already waiting).`,
  n10: `Stack empty → NO SOLUTION.`,
  n11: (a0: string | number, a1: string | number, a2: string | number) => `A CHEAPER route to ${a0}: g = ${a1} via ${a2} — update its parent and its key.`,
  n12: `Queue empty → NO SOLUTION.`,
  n13: (a0: string | number, a1: string | number) => `ROUND ${a0} — run DLS with depth limit ℓ = ${a1}. Everything starts again FROM SCRATCH (trading time for memory).`,
  n14: (a0: string | number, a1: string | number) => `${a0} hits the limit ℓ = ${a1} → CUTOFF, backtrack.`,
  n15: `Raised ℓ to the size of the graph without finding the goal → NO SOLUTION.`,
  n16: `Priority queue on h(n) — the node that LOOKS closest to the goal is expanded first. The past (g) is ignored entirely.`,
  n17: (a0: string | number, a1: string | number) => `Take ${a0} — smallest h (= ${a1}): it LOOKS closest to the goal.`,
  n18: `Queue empty → NO SOLUTION.`,
  n19: (a0: string | number, a1: string | number) => `Start at ${a0} (h = ${a1}). NO frontier — it remembers exactly ONE current node.`,
  n20: (a0: string | number, a1: string | number) => `No neighbor has a smaller h than ${a0} → STUCK at ${a1} (a local optimum). Lab convention: treat it as no path → print -1.`,
  n21: (a0: string | number, a1: string | number, a2: string | number) => `First-choice: found ${a0} with h = ${a1}, smaller than ${a2} → climb IMMEDIATELY, no further checking, no looking back.`,
  n22: (a0: string | number, a1: string | number, a2: string | number) => `h drops ${a0} → ${a1}: climb to ${a2} — GOAL! (Pure luck: hill climbing guarantees nothing of the sort.) `,
  n23: `The start is already the goal. `,
  n24: (a0: string | number) => `Generated ${a0} — GOAL! Stop on generation (Lab convention). Fast — but is it optimal? `,
  n25: `The start node is the goal. `,
  n26: (a0: string | number, a1: string | number, a2: string | number) => `Dive down to ${a0} (depth ${a1}/${a2}).`,
  n27: (a0: string | number, a1: string | number) => `Start again from ${a0} with ℓ = ${a1}.`,
  n28: (a0: string | number, a1: string | number, a2: string | number) => `${a0} is the GOAL at depth ${a1} — round ℓ=${a2} succeeds, and this is the SHALLOWEST solution. `,
  n29: (a0: string | number, a1: string | number) => `Generate ${a0} with g = ${a1}.`,
  n30: (a0: string | number, a1: string | number) => `Take ${a0} — smallest g (= ${a1}).`,
  n31: (a0: string | number, a1: string | number, a2: string | number, a3: string | number) => `Take ${a0} — smallest f: f = ${a1} + ${a2} = ${a3}.`,
  n32: (a0: string | number, a1: string | number, a2: string | number) => `Take ${a0} off with g = ${a1} — GOAL, and guaranteed optimal: every node still waiting has g ≥ ${a2}. `,
  n33: (a0: string | number, a1: string | number) => `Take ${a0} off with f = g = ${a1} — GOAL. With a consistent h, the first removal is always along an optimal path. `,
  n34: `Priority queue on g(n) — the REAL cost from the start. It only stops when the goal is REMOVED.`,
  n35: `Priority queue on f(n) = g(n) + h(n): cost ALREADY TRAVELED plus the estimate of what REMAINS. It only stops when the goal is REMOVED.`,
  n36: (a0: string | number) => `Generated ${a0} — GOAL! `,
  n37: `The start node is the goal. `,
  n38: (a0: string | number) => `Generated ${a0} — GOAL! Stop right there, no need to wait for removal. `,
  n39: `The start node is the goal. `,
  n40: (a0: string | number, a1: string | number) => `Trace the parent pointers back: ${a0} — cost ${a1}.`,
  n41: (a0: string | number, a1: string | number) => `Generate ${a0} (h = ${a1}).`,
  n42: (a0: string | number, a1: string | number, a2: string | number, a3: string | number) => `Generate ${a0}: f = ${a1} + ${a2} = ${a3}.`,
} satisfies typeof VI;
